### ISSUE TITLE
Pretrained fetching little upgrade

### ISSUE THREAD

**Issue by gandroz** [speechbrain/speechbrain#1000]
When using a pretrained model, we call method `from_hparams` which has a parameter `save_dir`. It is said that this parameter has a default value. However, if the default value is used or if a path different than the `source` is provided, the `pretrained.fetching.fetch` method tries to make a symbolic link to the source file. I do not have the right to make symbolic links on my machine :( After looking at the source code, I noticed that if the `source` and `save_dir` were the same, no symlink is created and the library uses the path I gave to the `from_hparams` method. It could be a good idea to get ride of the default value of the `save_dir` so that by default, the behaviour would be to use the `source` as a local path just like when `source` and `save_dir` are the same ?

**Comment by Gastron** [comment]
Changing the default would break backwards compatibility unfortunately. But it's good to hear that passing a particular save_dir value bypasses your original issue. Are you on Windows, is the original issue the same as #893 ?

**Comment by gandroz** [comment]
Yes, it is on Windows, and I had not seen the #893 before posting this issue, sorry. But I think that what I propose can be a good workaround when working locally. You could also add another method for this kind of usecase so that Windows is better supported, or just simply adding a parameters to the `from_hparams` would do the job

**Comment by Gastron** [comment]
I still feel the same way as discussed in #893, in brief: since this can actually work on Windows, the permissions just need to be set right, we should probably keep it as it is for now. Thank you for the suggestions, they'll be really helpful for future reference! 

I'll close this issue, as it seems to handled.
