### ISSUE TITLE
wav_len and src mismatch under multiple GPU

### ISSUE THREAD

**Issue by kaiyikang** [speechbrain/speechbrain#1002]
Hi,

I want to train the default LibriSpeech Transformer model on Tedlium dataset. 
Only the pipeline of audio processing and the size of Transformer are changed, other configurations remain the same.

## Issue
I run the `train.py` under `--data_parallel_backend`, which means two GPUs.

I got this error:
~~~python
  File "/home/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/sb/lib/python3.8/site-packages/speechbrain/nnet/attention.py", line 416, in forward
    output, attention = self.att(
  File "/home/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 978, in forward
    return F.multi_head_attention_forward(
  File "/home/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/functional.py", line 4283, in multi_head_attention_forward
    assert key_padding_mask.size(1) == src_len
AssertionError
~~~

It seems like the length of mask is unmatched, so I checked this.
~~~python
    def compute_forward(self, batch, stage):
        """Forward computations from the waveform batches to the output probabilities."""
        batch = batch.to(self.device)
        wavs, wav_lens = batch.sig
        tokens_bos, _ = batch.tokens_bos
        # Add augmentation if specified
        ......
        # compute features
        ......
        # forward modules
        src = self.modules.CNN(feats) 
        enc_out, pred = self.modules.Transformer(
            src, tokens_bos, wav_lens, pad_idx=self.hparams.pad_index
        )
~~~

Before the `wav_lens` is fed into `self.modules.Transformer`, the print of `wav_lens` is `tensor([0.3970, 0.2246, 1.0000, 0.1892], device='cuda:0')`  (the max length of src is `508`)

When I checked the `wav_lens` again in `TransformerASR.forward()`:
~~~python
        (src_key_padding_mask,
         tgt_key_padding_mask,
         src_mask,
         tgt_mask,
        ) = self.make_masks(src, tgt, wav_len, pad_idx=pad_idx)
~~~

`wav_len` is separated into two parts:
- `tensor([0.3970, 0.2246], device='cuda:0')`
- `tensor([1.0000, 0.1892], device='cuda:1')`

Therefore, the shape of `src_key_padding_mask` under `cuda:0` is `[2, 202]`.

I know the problems of multiple GPUs are always complicated. 

If you have any idea, could you tell me why the error occurs?

## Possible solution
1. If I run the `train.py` only on one GPU or CPU, no error occurs.
2. I added `wav_len = wav_len/wav_len.max()` before `self.make_masks()`, no error occurs.

Is the second solution reasonable? Because I only know the `wav_len` is using a relative length, but don't know the effect of the second solution on Transformer.

Thanks so much.

**Comment by TParcollet** [comment]
Hi, this should not occur. Also, please consider not using DP but DDP when playing with transformer, you'll notive a huge speed up (we don't know why and it kinda is inherent to Torch). @popcornell, it seems to be related to the masking again .. any idea ? @kaiyikang could you confirm that your batch_size > 1 ?

**Comment by kaiyikang** [comment]
@TParcollet Thanks for your reply! The batch_size of training is 5. I have switched DP to DDP mode and this is no problem currently.

**Comment by TParcollet** [comment]
5 cannot be divided in 2, hence the error I think.

**Comment by kaiyikang** [comment]
> 5 cannot be divided in 2, hence the error I think.

yes, it makes sense. thx

**Comment by Gastron** [comment]
Great! Closing as this was solved.
