### ISSUE TITLE
Add RNNLM to huggingface wav2vec2-large-xlsr

### ISSUE THREAD

**Issue by 73minerva** [speechbrain/speechbrain#1005]
Hi,
If I understand correctly, it is possible to load huggingface pretrained wav2vec2-large-xlsr models such as [wav2vec2-large-xlsr-53-german](https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-german). I wanna fine-tune the mentioned model as a freezed acoustic model beside of a RNNLM. First of all, I decided to train a RNNLM with a large text corpora. 
As mentioned in the [tutorial](https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing#scrollTo=9To_-2fej2SA), the RNNLM needs a SPM tokenizer object, But wav2vec2-large-xlsr models use a HF tokenizer, not SPM. Also converting HF tokenizer into SPM tokenizer is not easy!
So, should these tokenizers be the same and have a unique index mapping? Or I will get a good result if I train and use a different tokenizer.

**Comment by TParcollet** [comment]
Hi there, so what is necessary is that both models are **trained** with the same tokenizer, whatever it is. So, if your HF models is ASR pretrained, you should extract the tokenizer and give it to the RNNLM training (you can simply extract the vocabulary). If it isn't pretrained on ASR, you can simply create an AM with the tokenizer of the RNNLM as demonstrated in the tutorial and templates and other recipes. If, however, both of them have been trained with different tokenizers, well it is sub-optimal. What can be done, maybe, is to finetune for few epochs the AM with the RNNLM tokenizer (by adding a dense layer at the top of the AM for instance).

**Comment by 73minerva** [comment]
The HF model is ASR pretrained and extract the vocabulary form HF tokenizer is easy. But, Sentencepiece's dictionary is basically immutable and I cant modify it after training. So How should I have a SPM tokenizer with the same index mapping ?!
It is possible for you to support HF tokenizers like SPM tokenizers ?!

**Comment by TParcollet** [comment]
You can extract the HF tokens and force your SPM to use this vocabulary. This is totally feasible.

**Comment by 73minerva** [comment]
I cant find anything, Can you describe more or share a link to how force SPM to use a specific vocab ?!

**Comment by TParcollet** [comment]
[here](https://github.com/speechbrain/speechbrain/blob/3a26f15512da2247a2860f171774747668bd409f/speechbrain/tokenizers/SentencePiece.py#L55) Note: You need to set the number of tokens equal to the number of elements you give of course. And you will have to retrain the RNNLM with this new set of tokens. To avoid having issues with the tokenization, verify that the AM tokenizer contains at least the alphabet letters, so unknown words for the RNN can at least be splitted by characters :)

**Comment by 73minerva** [comment]
Thanks, it worked.
I also make sure that both of tokenizers encoding works same by :
`
with open(valid_data_path, 'r') as file_reader :
        for line in file_reader:
            spm_input_ids = model.EncodeAsIds(line)
            hf_input_ids = hf_tokenizer.pad(hf_tokenizer.encode_plus(line))["input_ids"]
            if not spm_input_ids == hf_input_ids:
                print(line, hf_input_ids, spm_input_ids
`
and nothing printed!
