### ISSUE TITLE
How to use self-trained models for transcription

### ISSUE THREAD

**Issue by Jeremiah0425** [speechbrain/speechbrain#1008]
hi，I trained my own model and transcribed it inwindows, but found that I still use the huggingface model.How to use your own model offline？

**Comment by TParcollet** [comment]
Hi, you need to clone the HF repo first with git lfs. Then you specify the local path instead of the hub name

**Comment by Jeremiah0425** [comment]
> 嗨，您需要先使用 git lfs 克隆 HF 存储库。然后指定本地路径而不是集线器名称

I don't quite understand your explanation， specify the path here? It doesn't seem to be feasibl
![1632620795(1)](https://user-images.githubusercontent.com/51948524/134790442-e66b036b-ad28-400b-a61b-ed23a2896911.jpg)
e。

**Comment by TParcollet** [comment]
speechbrain/asr-transformer-aishell is a HuggingFace repository. It means that it is a git repository. If you `git clone https://huggingface.co/speechbrain/asr-transformer-aishell` it will be cloned locally. Then you can simply give to `source="" ` the local path where you cloned the repository.

**Comment by anautsch** [comment]
Hi @Jeremiah0425 I'm closing this issue as there was no further activity, please feel free to re-open it.
