### ISSUE TITLE
how to train ECAPA-TDNN embeddings model for Speaker Diarization

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1019]
hello:
I encountered a problem: how to train and call a model parameter of ecapa TDNN for speaker dialogue (AMI)
Please tell me some steps.
thank you !

**Comment by Gastron** [comment]
Here's the recipe: [https://github.com/speechbrain/speechbrain/tree/develop/recipes/AMI/Diarization](https://github.com/speechbrain/speechbrain/tree/develop/recipes/AMI/Diarization)
