### ISSUE TITLE
very weird prediction with STT seq2seq (wav2vec2 encoder) when decoding

### ISSUE THREAD

**Issue by mrtunguyen** [speechbrain/speechbrain#1021]
Hello, 

I trained a STT seq2seq with wav2vec2 encoder on a private dataset (unluckly, I can't share it) and got a really good WER compared to CTC only approach. 
However, when I try to predict on new dataset with beam search + LM, I found that the prediction on some audios (not all, just a few) produce very weird result. 
For example, the prediction on one audio with start at 87.2s and end at 95s is ééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééé""""""""""""""""éééééééé                  
The prediction on the same audio but with start at 87s and end at 95 gives a correct result. 

And this error doesn't occur with CTC only approach. So probably it comes from the attention part in seq2seq. 

I know that it is difficult to give an answer without exactly reproducing the error, but it is impossible for me to release the dataset. Just want to ask if anybody here encounters the same error or your intuition of possible explanation?

**Comment by mrtunguyen** [comment]
It turns out the problem comes from `using_max_attn_shift` parameter. I should put it as False so that the problem doesn't occur.

**Comment by Gastron** [comment]
Thanks for sharing the solution!
