### ISSUE TITLE
Tokenizer_file does not seem to work when training LM

### ISSUE THREAD

**Issue by Jeremiah0425** [speechbrain/speechbrain#1031]
When I used my dataset to train RNNLM, I specified the wrong Tokenizer_file path in RNNLM.yaml, and I could still run and get the result. what is the reason?

**Comment by mravanelli** [comment]
Not sure to understand this issue. On my side, it looks like everything is working. Could you please provide some code snippet to replicate this issue?

**Comment by Adel-Moumen** [comment]
Hi, 

As requested by mravanelli, further information is needed such as a replicable code snippet. I will therefore close this issue and I'll ask the author to open a new one with the required information asked in the issue template.

Thanks!
