### ISSUE TITLE
[Discussion] Usage in production with custom speaker-identification service

### ISSUE THREAD

**Issue by ilirosmanaj** [speechbrain/speechbrain#1032]
Hello everyone,

I am planning to use speechbrain for custom speaker-identification service in a production environment.
What I do not know yet and didn't manage to find in the documentation or other discussions, is the following:

- How good is speechbrain for usage in production environment? e.g. latency during prediction, how computation heavy it is?
- Has anyone else used the tool with custom data speaker-identification? How does it work overall and what amount of effective speech would be good to have for each speaker? (i know the more the better, but is there any benchmarking in terms of number of seconds vs EER)
- Is there any notebook, other than the one in tutorials, where it shows how to use it with custom data?

I know my questions are a bit broad, but just want to know before jumping deeper into it

**Comment by mravanelli** [comment]
Hi, I think you can take a look at the ECAPA-TDNN recipe for speaker identification [here](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py). It uses cyclic LR without issues ([see this](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml#L158)). Note that the cyclic LR schedule uses parameters different from the linear one.
