### ISSUE TITLE
SpeedPerturb induces pitch change

### ISSUE THREAD

**Issue by Alva-2020** [speechbrain/speechbrain#1037]
Hi, thanks for giving so great work.  I found 'speedperturb' to augment the train set with speed change in the speaker verification recipe. The algorithm is sinc-based interpolation to resample. But this resample method will change the pitch of the speech.  Does this need to expand the number of speakers to three times the original number at the same time like this paper [https://www.isca-speech.org/archive/pdfs/interspeech_2019/yamamoto19_interspeech.pdf?](URL) ?   Or maybe I loss some info?

**Comment by mravanelli** [comment]
There are also computational issues to consider here. According to my knowledge,  the methods that attempts to preserve the pitch are much slower and thus not suitable for our "on-the-fly" data augmentation pipeline.
