### ISSUE TITLE
GPU-based multi-mic processing

### ISSUE THREAD

**Issue by gleb-shnshn** [speechbrain/speechbrain#1046]
Is it possible to run https://colab.research.google.com/drive/1UVoYDUiIrwMpBTghQPbA6rC1mc9IBzi6?usp=sharing with GPU?
I tried to move data to cuda via `.to(cuda:0)` but received 
```
File "/senv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
 File "/senv/lib/python3.8/site-packages/speechbrain/processing/multi_mic.py", line 1130, in forward
    doas = Music._music(
 File "/senv/lib/python3.8/site-packages/speechbrain/processing/multi_mic.py", line 1168, in _music
    Us, _ = eig.svdl(XXs_val)
 File "/senv/lib/python3.8/site-packages/speechbrain/processing/decomposition.py", line 169, in svdl
    es, ush = torch.linalg.eigh(ash_mm_ash_T, UPLO="U")
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnSsyevd(handle, jobz, uplo, n, A, lda, W, work, lwork, info)`
```

As far as i found in https://github.com/pytorch/pytorch/issues/60892 this issue is because of problems with device setting. What is the right way to do it?

**Comment by mravanelli** [comment]
Do you still see the issue? @FrancoisGrondin recently fixed some issues in the multi-mic tutorial

**Comment by gleb-shnshn** [comment]
As far as i noticed, Francois fixed MVDR formulas with replacing XX with NN. But this issue is about GPU processing, there is no example in tutorial related to it. So, I still need the example of performing beamforming with cuda

**Comment by mravanelli** [comment]
Thank you for reporting that. I indeed found some device mismatch issues that I already fixed in the current development branch (@FrancoisGrondin). Now, everything should work. Do you confirm it? Note that the fix is in the dev branch only for now (until we will release the new version of speechbrain). You have to use the "git clone" version and not the "pip install speechbrain" to see the fix.

**Comment by mravanelli** [comment]
Basically, you have to install speechbrain in this way:
```
!git clone https://github.com/speechbrain/speechbrain/
%cd /content/speechbrain
!pip install -r requirements.txt
!pip install -e .
```
Make sure you put the tensors back on cpu before doing the plots in the tutorial.

**Comment by gleb-shnshn** [comment]
I still catch same error
```  
File "/raid/shanshin/senv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/shanshin/vqe_experiments/speechbrain/speechbrain/processing/multi_mic.py", line 1146, in forward
    doas = Music._music(
  File "/raid/shanshin/vqe_experiments/speechbrain/speechbrain/processing/multi_mic.py", line 1189, in _music
    Us, _ = eig.svdl(XXs_val)
  File "/raid/shanshin/vqe_experiments/speechbrain/speechbrain/processing/decomposition.py", line 169, in svdl
    es, ush = torch.linalg.eigh(ash_mm_ash_T, UPLO="U")
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnSsyevd(handle, jobz, uplo, n, A, lda, W, work, lwork, info)`
```

To debug I add prints before this line `eig.svdl(XXs_val)` 

`print(XXs.device, As.device, doas.device, XXs_val.device, XXs_idx.device)`

shows `cuda:8 cuda:8 cuda:8 cuda:8 cuda:8`. That means it is all on the same device, do you have any other ideas why this happens?

**Comment by gleb-shnshn** [comment]
Looks like https://github.com/pytorch/pytorch/issues/60892 fixed it only in torch=1.10+, and torchaudio=0.10 respectively, so I think `requirements.txt` should have such versions

**Comment by mravanelli** [comment]
I see. Do you confirm it is working with torch >= 1.10 and torchaudio >=
0.10?

**Comment by gleb-shnshn** [comment]
Also, we need to move doas to device, otherwise `doas2taus` will produce this error 
```  
File "/raid/shanshin/vqe_experiments/speechbrain/speechbrain/processing/multi_mic.py", line 1115, in __init__
    self.taus = doas2taus(
  File "/raid/shanshin/vqe_experiments/speechbrain/speechbrain/processing/multi_mic.py", line 1267, in doas2taus
    taus = (fs / c) * torch.matmul(doas, mics.transpose(0, 1))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:8! (when checking argument for argument mat2 in method wrapper_mm)
```

So, it looks like you should add `self.doas = self.doas.to(mics.device)` before these lines on 1099 and 922
```
        # Generate associated taus with the doas
        self.taus = doas2taus(
            self.doas, mics=mics, fs=sample_rate, c=speed_sound
        )
```

**Comment by gleb-shnshn** [comment]
And, yes, then it is working

**Comment by mravanelli** [comment]
This is something I fixed in the latest version of the development branch.
On my side it is working with that. Are you using the latest version of the
development branch?

**Comment by gleb-shnshn** [comment]
I do not see this fix, check if you have done `mics.to("cuda")` while you are testing because there is no error if mics on cpu

**Comment by mravanelli** [comment]
I added the fixes here in this commit:
https://github.com/speechbrain/speechbrain/commit/25635ebade3a24091d36c3502aa0c95bd37e2569
After that, everything was working on my side. Could you please share the
exact code snippet that you are running? Note that the fix is in the dev
branch (not in the main version that you get with pip install speechbrain)

**Comment by gleb-shnshn** [comment]
Yeah, I have last version and I see these fixes, but you see the wrong part of code - you fixed on 978 and 1173 lines, whilst I am saying about needs of fixes in 922 and 1099 lines in class initalization instead of forward functions

**Comment by mravanelli** [comment]
I see, if you share the code snippet that gives you the problem I can try
to replicate and do the final fix

**Comment by gleb-shnshn** [comment]
I am running
```
            device = "cuda:8"
            mics = mics.to(device)
            xs = read_audio(str(temp_name)).unsqueeze(0).to(device)
            stft = STFT(sample_rate=fs)
            cov = Covariance()
            music = Music(mics, sample_rate=fs)
            delaysum = DelaySum()
            istft = ISTFT(sample_rate=fs)
            Xs = stft(xs)
            XXs = cov(Xs)
            doas = music(XXs)
            Ys = delaysum(Xs, doas, doa_mode=True, mics=mics, fs=fs)
            ys_ds = istft(Ys)
            write_audio(str(out_path), ys_ds.squeeze().to("cpu"), fs)
```

**Comment by mravanelli** [comment]
Ok, got it. I'm now able to replicate. I just fixed that in the latest development branch. Could you please double check?
I'm now able to run the following code snippet without device mismatch issues:

```
import torch
from speechbrain.processing.features import STFT, ISTFT
from speechbrain.processing.multi_mic import Covariance, GccPhat, Music, DelaySum
from speechbrain.dataio.dataio import read_audio

device = "cuda:0"
mics = torch.zeros((4,3), dtype=torch.float)
mics[0,:] = torch.FloatTensor([-0.05, -0.05, +0.00])
mics[1,:] = torch.FloatTensor([-0.05, +0.05, +0.00])
mics[2,:] = torch.FloatTensor([+0.05, +0.05, +0.00])
mics[3,:] = torch.FloatTensor([+0.05, +0.05, +0.00])

mics = mics.to(device)
xs = read_audio('samples/audio_samples/multi_mic/speech_-0.82918_0.55279_-0.082918.flac').unsqueeze(0).to(device)

fs = 16000
stft = STFT(sample_rate=fs)
cov = Covariance()
music = Music(mics, sample_rate=fs)
delaysum = DelaySum()
istft = ISTFT(sample_rate=fs)
Xs = stft(xs)
XXs = cov(Xs)
doas = music(XXs)
Ys = delaysum(Xs, doas, doa_mode=True, mics=mics, fs=fs)
ys_ds = istft(Ys)
```
Note that I'm able to run it on pytorch 1.9 as well. Are you on a windows machine?

**Comment by gleb-shnshn** [comment]
No, the linux-like one. Well, it works on 1.10, not on 1.9 in my case
