### ISSUE TITLE
AMI diarization

### ISSUE THREAD

**Issue by sch0ngut** [speechbrain/speechbrain#1056]
I'm trying to follow the recipe for speaker diarization on the AMI dataset (https://github.com/speechbrain/speechbrain/tree/develop/recipes/AMI/Diarization) but unfortunately without success. Here's the output:
```
...
speechbrain.utils.parameter_transfer - Loading pretrained files for: embedding_model, mean_var_norm_emb
__main__ - Tuning for p-value for SC (Multiple iterations over AMI Dev set)
__main__ - Diarizing dev set
__main__ - No recording IDs found! Please check if meta_data json file is properly generated.
```

I have downloaded the data and set the variables in the config files accordingly, i.e.:
```
data_folder: .../AMI/amicorpus/
manual_annot_folder: .../AMI/ami_public_manual_1.6.2 
```
where amicorpus looks as follows:
`amicorpus/EN2009d/audio/EN2009d.Mix-Headset.wav`

I'm running this using `device: 'cpu'`

I checked the results/.../metadata folder and I see that `ami_dev.Mix-Headset.subsegs.json` and `eval.Mix-Headset.subsegs.json` are empty, while `ami_train.Mix-Headset.subsegs.json` contains a dict of elemts like
```
"EN2009d_0.0_2.99": {
    "wav": {
      "file": "/Users/jonas/Desktop/Translated/ASR/datasets/AMI/amicorpus//EN2009d/audio/EN2009d.Mix-Headset.wav",
      "duration": 2.99,
      "start": 0,
      "stop": 47840
    }
  }
```

I would really appreciate some help! Am I missing anything?

**Comment by nauman-daw** [comment]
This looks like a small problem, but it's important to mention this somwhere. Actually no one got this error. Are you using some different OS ? I was wondering if its related to OS specific paths?
 
I am not sure if should state this point in the README or something... 
@mravanelli what do you think?

**Comment by sch0ngut** [comment]
That's interesting. I'm using Mac OS 11.6, so not so specific

**Comment by nauman-daw** [comment]
Closing this path issue for now.
