### ISSUE TITLE
The question about the 'Array1' and 'BeamformIt'of the  AMI dataset 

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1064]
Hello:
I'm glad you can provide code in the field of speaker log, but I have a doubt about the dataset:
This is ecapa_ The tdnn.yaml file gives the selection #options for mic about the dataset_ type: 'Mix-Lapel', 'Mix-Headset', 'Array1', 'Array1-01', 'BeamformIt'
This is the audio classification given by AMI dataset: 1. Realmedia audio mix 2, headset mix 3, lapel mix 4, individual lapels 5, individual headsets 6 and microphone array
I want to know which data sets' array1 'and' beamform it 'refer to respectively? Especially the data of 'beamform it', can you provide this explanation
The question is childish. I hope to get a reply. Thank you!

**Comment by MQQ1996** [comment]
i really want to know that you only use the 'Array1'， in your experiment(beamform array)? if not, how to use the  2 microphone arrays? 'separately beamform using BeamformIt', which means that i can simply use 'Array1' option or  'Array2 ' option to use SpeechBrain's inbuilt beamformer? i really don‘t know how to beamform on the two Array, hoping for your guidance.

**Comment by mravanelli** [comment]
@nauman-daw any idea?

**Comment by nauman-daw** [comment]
Hi @MQQ1996 ,
Yes, you can separately beamform 'n' microphones using BeamformIt which is a famous tool. 
You can also use the SpeechBrain in-built beamformer.  You can check this tutorial by @FrancoisGrondin  on how to achieve that.

**Comment by MQQ1996** [comment]
One more question. In your paper《ECAPA-TDNN Embeddings for Speaker Diarization》，the results of beamformed array signal is different from your Array1 results of speechbrain. Did the speechrbain use the data of beamformed array1 signal, and paper use Array1+Array2? @nauman-daw

**Comment by MQQ1996** [comment]
mic_type: 'BeamformIt' in the speechbrain, which corresponds to the  beamformed array signal of paper《ECAPA-TDNN Embeddings for Speaker Diarization》? Is it right?

**Comment by nauman-daw** [comment]
yes. right. mic_type: 'BeamformIt' in the speechbrain, corresponds to the beamformed array 1 signal.
