### ISSUE TITLE
error message ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by 200987299** [speechbrain/speechbrain#1079]
dear developers:
I am trying to install speechbrain on docker image pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime. But I got this error message after installing speech brain. How could I solve this problem?

Bests

**Comment by xiongjun19** [comment]
I have encountered the same problem, and the bug is caused by the old version of ruamel.yaml preinstalled in the docker container, and my solution is:
     add the following command to your docker file:
     `RUN pip3 install --ignore-installed ruamel.yaml==0.17.8`

**Comment by miguelmartin75** [comment]
I also ran into this problem @xiongjun19's suggestion worked. Thanks.
