### ISSUE TITLE
CTCTextEncoder - special_label inconsistent

### ISSUE THREAD

**Issue by gebauertnt** [speechbrain/speechbrain#1090]
I noticed an inconsistency in the naming of the special_labels for the CTCTextEncoder. While "blank_label", "bos_label" and "eos_label" set the desired index for the specific label, it is not possible to actually set the label itself. On the other side defines the "unk_label" the actual label of the unknown token and it is not possible to set the index manually. I am passing all labels within the constructor. If this is not intended please let me know.

**Comment by mravanelli** [comment]
Thank you for reporting that. This sounds a topic for @Gastron and @popcornell.

**Comment by aheba** [comment]
Hey @gebauertnt,

The idea is that the CTCTextEncoder handle the mapping (idx, label) for you. even if you wanna update your label_encoding, the good way is to use your CTCTextEncoder to do.
You have the function `enforce_label` where you can specify the index of your label.. and the current label at the same index will be moved to size(labels)+1.

The `add_unk()` is used when for example in my case for French Language, I have a specific symbols when using different corpus like `ô`. In this case, you can use `add_unk` function to add the mapping of `ô` to `<unk>`. or even use `ensure_label` function if you would like to add it. but consider that your model will never predict it... so this is probably a bad Idea



NB: Just to mention `BOS_label` and `Eos_label` are not used for CTC, so you can remove it in your `data_prep` like:
```
    lab_enc_file = os.path.join(hparams["save_folder"], "label_encoder.txt")
    special_labels = {
        "blank_label": hparams["blank_index"],
    }
```

**Comment by aheba** [comment]
@gebauertnt , is that ok for you ? feel free to close the discussion if so.

**Comment by gebauertnt** [comment]
Hey @aheba,

sorry for the late response and thank you for the clarification. Using enforce_label does definitely circumvent the problems we have been facing. I will close the Issue for now.
However, for me it still seems counterintuitive to have an entry special_labels  in the constructor that will handle all four labels but uses the input in different fashion, i.e., as index or as label depending on its type.
