### ISSUE TITLE
Incompatible versions between torch and torch audio

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#1092]
Hi all and thanks first of all for this amazing toolkit!

I just finished a quick installation via `requirements.txt`. However, when installing under conda environment (miniconda3), as specified in the file:
```
torch>=1.8.0,<=1.10.1
torchaudio>=0.7.2,<=0.10.1
```
by default pip installs minimal version of the requirements. However, torchaudio 0.7.2 is not compatible with torch 1.8.0 (1.7.1 instead). Of course I know we would not use torch <=1.8.0 so I suggest to change the minimal torch audio version to 0.8.0. If needed I can make a very small PR for it.

Also I suggest to drop support for torch <=1.9.0 since for multiple GPUs 1.9.0 provides much better support I think (by checking the [update note](https://pytorch.org/blog/pytorch-1.9-released/)).

**Comment by mravanelli** [comment]
Sure, feel free to ask a PR with the new version of torchaudio. As for torch, many people are still using pytorch 1.8, but we will probably drop support for pytorch 1.8 when the pytorch 1.11 will come out.

**Comment by mravanelli** [comment]
fixed
