### ISSUE TITLE
Training model with DDP couldn't accelerate

### ISSUE THREAD

**Issue by lhanzl** [speechbrain/speechbrain#1096]
I used DDP to run Common and Vox recipes with 4-8 Gpus, but instead of speeding up, it took longer to train one epoch.
My training environment is not NFS. Here is the script I ran
```
CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=40 python -m torch.distributed.launch --nproc_per_node=4 \
  train.py hparams/train_ecapa_tdnn.yaml \
  --data_folder=data/common_voice_kpd \
  --batch_size=4 --seed=2000 \
  --num_workers=20 \
  --distributed_launch \
  --distributed_backend='nccl'
```
Enlarging num_works mentioned in this issue In issue https://github.com/speechbrain/speechbrain/issues/784#issuecomment-847720463 does not solve my problem.

Is there something wrong? Thanks in advance!

**Comment by TParcollet** [comment]
Hi, quick verification: batch_size = 4 means that the effective batch_size will be 16. We agree that when you compare to solo GPU your batch size isn't already 12 or 16, correct? It is also 4?

**Comment by lhanzl** [comment]
@TParcollet Yes, solo GPU my batch size is 4.

**Comment by TParcollet** [comment]
Ok, this is ultra weird. Could you verify that all GPUs are running with nvidia-smi ? Could you also verify that the number of steps is 4 times smaller (the one on the progress bar).

**Comment by Gastron** [comment]
The number of workers 20 is quite large. This is multiplied by the number training processes - you end up with 80 data loading workers. Does that number make sense for you? I would suggest something an order of magnitude smaller, e.g. num_workers=2

**Comment by lhanzl** [comment]
Commit-id: 72447d55
Without DDP at beginning(same as recipe setup)
![image](https://user-images.githubusercontent.com/24434459/140543781-ede5abde-4bcc-43f1-bb18-76a87c3c52e3.png)

DDP node=2 at beginning
![image](https://user-images.githubusercontent.com/24434459/140543839-4ac36cd6-fa15-444c-b49c-f6768c0da13b.png)

DDP node=2 finish training(first epoch cost 23:41)
![image](https://user-images.githubusercontent.com/24434459/140543879-292076be-6cae-4fbd-8c9f-43479f2b4c0c.png)

**Comment by lhanzl** [comment]
> The number of workers 20 is quite large. This is multiplied by the number training processes - you end up with 80 data loading workers. Does that number make sense for you? I would suggest something an order of magnitude smaller, e.g. num_workers=2

I tried it and it was still as slow. The parameters I set do not exceed the maximum load of the machine. In fact, I found that the CPU usage was much smaller than the number of works I had set up. Is it stuck in the data preparation phase?

**Comment by mravanelli** [comment]
In the past we noticed that the ECAPA-TDNN model is slow when using
multiple GPUs with DDP. As far as I remember, one user found out that this
was related to the residual block used in the recipe (there was a
discussion about that). There might be the need for a fix there. If someone
from the community would like to help with that is welcome! The team has
currently issues in supporting the speaker verification part because the
students working on that left.

**Comment by TParcollet** [comment]
What is the time for one epoch with one gpu ?

**Comment by mravanelli** [comment]
On my side, with a single 48 GB GPU it took something like 20-24 hours with
voxceleb 1 + voxceleb2.

**Comment by lhanzl** [comment]
> What is the time for one epoch with one gpu ?

About 12 minutes.

**Comment by TParcollet** [comment]
We have to investigate this. Never suffered from that before.

**Comment by TParcollet** [comment]
@lhanzl I confirm that I can reproduce your issue. Not that using DP instead of DDP will fix it (--data_parallel_backend). I am investigating this as this is the first time I see DDP slower than DP and monogpu.

**Comment by lhanzl** [comment]
@TParcollet In CommonLanguage Recipe, I'm running DP and I don't have an advantage in speed either.
Single GPU, batch_size= 4, one epoch takes about 12 minutes and 15 seconds
Two Gpus, batch_size=4, and one epoch took about 12 minutes and 41 seconds
What is your configuration?

**Comment by TParcollet** [comment]
Oh sorry, this is normal DP split the batch_size (DDP multiply). so you need to set the BS to nb_gpu*batch_size.

**Comment by TParcollet** [comment]
We found the issue, a PR may follow to solve it. In the meantime, please consider using DP instead.

**Comment by mravanelli** [comment]
That should be solved in the current development branch. Do you confirm?

**Comment by EmreOzkose** [comment]
Hi, I have similar issue now. I am training [speaker recognition - ecapa-tdnn](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py). 

When I run `python -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr server1 --master_port 55553 train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --distributed_launch --distributed_backend='gloo'` , training elapsed approximately 21 hours. 

When I run `python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr server1 --master_port 55553 train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --distributed_launch --distributed_backend='gloo'` in both server1 and server2, elapsed time for training in progress bar does not change. 

However, when I run `CUDA_VISIBLE_DEVICES=0,1 python train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --data_parallel_backend`,  elapsed time for training in progress is approximately 14 hours. 

Is the issue solved? Do I need a trick when running scripts such as changing a config parameter?

**Comment by TParcollet** [comment]
DDP should be faster as well. Make sure that your GPUS are properly used. Can you try with a singles server and two GPUs  ?

**Comment by EmreOzkose** [comment]
When I try to observe GPU utilization with nvitop, GPUs are seem to be used. 

When I run the following command in the same machine and change `nproc_per_node` from 1 to 4, times (1 epoch) in progress bar decrease from approximately 21 hours to 9 hours.
 `python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr server1 --master_port 55553 train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --distributed_launch --distributed_backend='gloo'`

In the same server, paralleling works fine for me. However when I add 2 extra GPU from a different machine like:

 `python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr server1 --master_port 55553 train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --distributed_launch --distributed_backend='gloo'`
and
 `python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr server1 --master_port 55553 train_speaker_embeddings.py hparams/train_ecapa_tdnn_dist.yaml --distributed_launch --distributed_backend='gloo'`

Time increases from approximately 9 hours to 22 hours.

**Comment by EmreOzkose** [comment]
In addition to these tests, I should share my network test, it might be the problem. When I test connection between 2 server with `iperf`, I got 625 Mbits/sec bandwidth. 

Test commands:
`iperf -s` in server 1
`iperf -c server1` in server2

As a baseline, [Horovod benchmarks](https://github.com/horovod/horovod#why-horovod) are done with 25 Gbit/s network.
