### ISSUE TITLE
Is there a tutorial on GAN

### ISSUE THREAD

**Issue by dugudongfangshuo** [speechbrain/speechbrain#1098]
hello  Is this framework relevant for GAN

**Comment by TParcollet** [comment]
Hi, not a tutorial per say, but we have a PR ongoing on HifiGAN (that uses a GAN).

**Comment by mravanelli** [comment]
Note that we are using GANs for speech enhancement as well. See for
instance SE-GAN (
https://github.com/speechbrain/speechbrain/tree/develop/recipes/Voicebank/enhance/SEGAN)
or MetriGAN+ (
https://github.com/speechbrain/speechbrain/tree/develop/recipes/Voicebank/enhance/MetricGAN
).
