### ISSUE TITLE
Error replacing SE-net  training ECAPA-TDNN

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1099]
Hello:
Hello, I have a problem:
I want to train Python train under speechtrain / recipes / voxceleb / speakerrec /_ speaker_ embeddings.py hparams/train_ ecapa_ When tdnn.yaml code, you want to replace a module. See the effect:
Here is the previous seblock:
![image](https://user-images.githubusercontent.com/86965285/140678088-3b826b97-dba1-451d-ba18-a1c269600147.png)
This is the replaced module:
![image](https://user-images.githubusercontent.com/86965285/140678198-30f031a2-28f6-481e-ae6e-b05ecad31cf0.png)
However, I would like to ask the reasons for such problems and how to solve them?
![image](https://user-images.githubusercontent.com/86965285/140678315-a3a19acd-e618-45ce-8e11-b164cb4df15a.png)
Error replacing se net training ecapa-tdnn

**Comment by TParcollet** [comment]
Hi, if you look at the logs, you'll see that these recipes are loading a pretrained model. Hence, if you change the architecture the pretrained model won't correspond anymore. Simply comment the two lines of the pretrainer call in the train.py.
