### ISSUE TITLE
TypeError: Invalid file: WindowsPath('example_mandarin.wav')

### ISSUE THREAD

**Issue by liuqi6777** [speechbrain/speechbrain#1101]
When I tried to run code in WINDOWS
```python
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-transformer-aishell",
                                               savedir="pretrained_models/asr-wav2vec2-transformer-aishell")
res = asr_model.transcribe_file('speechbrain/asr-wav2vec2-transformer-aishell/example_mandarin.wav')
```
I got the error:
![image](https://user-images.githubusercontent.com/72511133/140745987-dcacd316-8273-4d00-a5e7-88f67e875dd6.png)

I looked at some of the code located in the file "\speechbrain\pretrained\interfaces.py":
![image](https://user-images.githubusercontent.com/72511133/140747347-7f143dd8-d9ce-4ecc-891b-ca654c93c86c.png)

and I found that the function `torchaudio.load(path, channels_first=False)` requires a `str`. However, the function `fetch`  in 
 this file return an object with the type  `pathlib.WindowsPath` , so actually I use it instead of an `str`. And this raised the error.

I wonder if this is an incompatibility issue on Windows? I have avoided this problem in some other way, but I sincerely hope it can be resolved.

**Comment by ghackk** [comment]
from speechbrain.inference.separation import SepformerSeparation as separator
import torchaudio

model = separator.from_hparams(source="speechbrain/sepformer-whamr-enhancement", savedir='pretrained_models/sepformer-whamr-enhancement4')
enhanced_speech = model.separate_file(path='1min.mp3')


can you tell me how you corrected it
