### ISSUE TITLE
Run EER evaluation for ECAPA-TDNN

### ISSUE THREAD

**Issue by ARKEYTECT** [speechbrain/speechbrain#1103]
I am trying to run EER evaluations on a self-trained ECAPA model. I keep running in to the following error: "FileNotFoundError: [Errno 2] No such file or directory: '/network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1/meta' "

Since this line is pre-defined in the verification_ecapa.yaml, I am wondering how to fix this issue. Thanks!

**Comment by mravanelli** [comment]
It looks like you didn't change the variable `voxceleb_source` in the yaml file with your own path.

**Comment by ARKEYTECT** [comment]
Thanks Mirco! As it turned out, If one were to run EER the first time, he only needs to leave voxceleb_source blank.
