### ISSUE TITLE
Train the model obtained by speakerrec to solve the problem of Speaker Diarization on AMI corpus

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1104]
Hello:
I have a problem in training speechtrain / recipes / voxceleb / speakerrec/_ speaker_  embeddings.py hparams/train_  ecapa_  I found that the configuration of each training is the same, but different results will be obtained during Speaker Diarization on AMI corpus. I want to ask how to solve this problem and analyze the reasons, as shown in the following figure:

<img width="471" alt="734669adc551df7d94d8f2850a7b861" src="https://user-images.githubusercontent.com/86965285/140841027-303d1a11-198f-4d31-8856-a5632e0df8e8.png">

**Comment by mravanelli** [comment]
As far as I recall, in the past I was able to achieve the same performance when running the code multiple times. @nauman-daw any idea about what is going on here?

**Comment by LONG520520** [comment]
Hello:
Maybe I didn't make it clear that I just ran the speechtrain / recipes / voxceleb / speakerrec/_ speaker_  embeddings.py hparams/train_  ecapa_ TDNN, but behind the python speaker_ verification_ cosine.py hparams/verification_ The code of ecapa.yaml didn't run, so we directly took the obtained model for Speaker Diarization on AMI corpus experiment. I want to ask whether this needs to be completed, and then use the final model?

**Comment by LONG520520** [comment]
Hello:
I discussed with my senior sister in our laboratory whether this result is calculated by taking the average value of all experiments? If this can be used for comparative experiments, but I wonder if it is reasonable?

**Comment by nauman-daw** [comment]
Hi,
Sorry, I am super busy these days so couldn't reply. 
You can directly take the pre-trained model from HuggingFace and it should work with the diarization recipe. You don't need to train model again.
I am not sure what exactly might be happening here as you are getting different results for the same model. Earlier we ran multiple times and got the same results (as also @mravanelli mentioned) Even the error rates are very high... might be the case that your model isn't loading properly or there is some randomness (not sure).

**Comment by nauman-daw** [comment]
I hope you were able to regenerate the results. I am closing this for now. Feel free to re-open if it is not resolved.

**Comment by LONG520520** [comment]
thanks you !
