### ISSUE TITLE
CTC/Attention decoding: BOS token role and CTC loss computing

### ISSUE THREAD

**Issue by baptistepouthier** [speechbrain/speechbrain#1105]
Hello,

I am a bit confused by the recipes that use joint CTC/Attention decoding (e.g, [recipes/LibriSpeech/ASR/transformer](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/transformer) or [recipes/CommonVoice/ASR/transformer](https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/transformer)).

In such recipes, the CTC and decoder final linear layers are as large as the vocabulary (e.g, output_neurons = 5000 in the LibriSpeech example) **that comprises BOS and EOS tokens.**

The CTC must be able to output the EOS token in order to align with the Attention decoder during the joint decoding, but:

(1) why is there a neuron dedicated to the BOS token in both final layers?

(2) why is the CTC loss computed using "tokens" rather than "tokens_eos" ("tokens" + EOS)?
https://github.com/speechbrain/speechbrain/blob/da5701ad81bfc6f56b62fa34835b93c9373c44e3/recipes/LibriSpeech/ASR/transformer/train.py#L123

Thanks

**Comment by 30stomercury** [comment]
Hi, 
(1) We include bos, eos and blank in output neurons for joint att/ctc training, decoding. The BOS token won't contribute. You can exclude the BOS from output neurons but it makes indexing easier.
(2) We don't need eos to compute ctc alignment in CTC loss.
