### ISSUE TITLE
How to link language with output index

### ISSUE THREAD

**Issue by jcn199729** [speechbrain/speechbrain#1106]
Would be greatly helpful if getting the mapping list. For example, 12 refers to Japanese
![image](https://user-images.githubusercontent.com/58527362/141055191-0b612b8b-8733-443b-a698-445188526623.png)

**Comment by Gastron** [comment]
Sounds like you want to encode text labels as indices - this is what the categorical encoder does: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.dataio.encoder.html#speechbrain.dataio.encoder.CategoricalEncoder

**Comment by mravanelli** [comment]
Not sure which recipes you are referring to. However, in the ouput folder
you should find a file called label_encoder.txt that contains this mapping
information. Do you see it?
