### ISSUE TITLE
Appropriate masks are needed for TransformerASR.decode()

### ISSUE THREAD

**Issue by dave-rtzr** [speechbrain/speechbrain#1107]
Hi, 

S2STransformerBeamSearch uses TransformerASR.decode() to get posterior probabilities.
However, in contrast to TransformerASR.forward(), TransformerASR.decode() does not use encoder-decoder attention masks.
This may result in incorrect values when S2STransformerBeamSearch is run with batch size bigger than 2 and at least one of the elements has a smaller length, since padded positions may be attended in the encoder-decoder cross attention block.
Is there any intention regarding not passing cross-attention masks in TransformerASR.decode() method?
On our dataset, using appropriate cross attention masks in TransformerASR.decode() method results in better performance.
I would like to PR a fix if needed.

**Comment by 30stomercury** [comment]
Hi,
The attention decode step should take `memory_key_padding_mask` into account to exclude paddings. I solved it [here](https://github.com/speechbrain/speechbrain/pull/933/commits/db4a46d58e8551c002d1c3c89c069c52a4183b72) in #933.

**Comment by mravanelli** [comment]
Could you please add this fix in another PR that we can merge sooner than
#933? This way, this can be part of the next version of speechbrain that we
are going to release soon.
