### ISSUE TITLE
How to override `!include` in YAML file via command line args?

### ISSUE THREAD

**Issue by weiwei-ww** [speechbrain/speechbrain#1109]
Suppose that I have two YAML files:

**f1.yaml:**
```
seed: 123456
config: !include:f2.yaml
```

**f2.yaml:**
```
batch_size: 32
lr: 0.01
```

How should I pass the command line arguments if I wish to override the `batch_size` in **f2.yaml**?

I have tried the following, but it is not working:

`python train.py f1.yaml --config {batch_size: 64}`

**Comment by TParcollet** [comment]
This is a question for the YAML master @pplantinga

**Comment by mravanelli** [comment]
This looks related to the issue that @weiwei-ww raised in the hyperpyyaml repository. Maybe @Gastron has something to say here as well.

**Comment by Gastron** [comment]
It is hard for me to offer advice, I think some of the HyperPyYAML features at this point have don't have clearly defined behaviour, particularly when used together.

**Comment by weiwei-ww** [comment]
> It is hard for me to offer advice, I think some of the HyperPyYAML features at this point have don't have clearly defined behaviour, particularly when used together.

I understand and thanks for your reply. Nevertheless, I made some modifications directly to the hyperpyyaml package and made it work for now. :-)

**Comment by Gastron** [comment]
Nice, @weiwei-ww, and actually, if the modifications are not just hacks for your particular script, would you consider a PR in the HyperPyYAML repo?

**Comment by mravanelli** [comment]
Yes please, feel free to share it!

**Comment by pplantinga** [comment]
Perhaps this is a bit late, but overriding in included files should be possible. In order to do this, the overridden element must be added as a sub-element of the include statement:

```
seed: 123456
batch_size: !PLACEHOLDER
config: !include:f2.yaml
        batch_size: !ref <batch_size>
```
```
batch_size: 32
lr: 0.001
```

**Comment by pplantinga** [comment]
Of course you can get around this in a slightly less safe way by just calling `load_hyperpyyaml` with the argument `overrides_must_match=False`

**Comment by weiwei-ww** [comment]
> Perhaps this is a bit late, but overriding in included files should be possible. In order to do this, the overridden element must be added as a sub-element of the include statement.

Yes, that is exactly what I am trying to implement. However, in the current implementation, if the !include tag comes with no extra override keys, e.g.:

```
config: !include:f2.yaml
```

it will be interpreted as a `TaggedScalar` class. Then if an override is given via command line args, it will throw an exception.

**Comment by weiwei-ww** [comment]
> Nice, @weiwei-ww, and actually, if the modifications are not just hacks for your particular script, would you consider a PR in the HyperPyYAML repo?

Sure, I am happy to contribute. Btw, I also fix the bug that I reported in [this issue](https://github.com/speechbrain/HyperPyYAML/issues/9) as well. I need some time to test if my codes do not bring any unexpected errors. If everything works, I will submit a PR to the HyperPyYAML repo.
