### ISSUE TITLE
Adaptive SpecAugment

### ISSUE THREAD

**Issue by dave-rtzr** [speechbrain/speechbrain#1112]
It seems like many papers are using adaptive SpecAugment algorithm from [SpecAugment on Large Scale Datasets](https://arxiv.org/abs/1912.05533).
Its main difference is that the number of time masks and their widths differ depending on the lengths of the samples.
This algorithm may be suitable for those who are training a model on a large dataset with diverse sample lengths.
Is there any plan to officially support above algorithm in this library?

**Comment by Gastron** [comment]
I don't think anyone is working on this, but we'd be happy accept contributions!

**Comment by mravanelli** [comment]
Yes, any contribution is welcome! Since we are going to revise the
augmentation part in the next major release of SpeechBrain, we can take
this opportunity to implement that as well.

>
