### ISSUE TITLE
ValueError: 'rir_path' is a !PLACEHOLDER and must be replaced.

### ISSUE THREAD

**Issue by oneway234** [speechbrain/speechbrain#1113]
I follow [speechbrain/sepformer-whamr](https://huggingface.co/speechbrain/sepformer-whamr) to run train.py with
 `python train.py hparams/sepformer-whamr.yaml --data_folder=your_data_folder`

But got this issue:

> Traceback (most recent call last):
>   File "train.py", line 532, in <module>
>     hparams = load_hyperpyyaml(fin, overrides)
>   File "/home/cbav/anaconda3/envs/sb/lib/python3.8/site-packages/hyperpyyaml/core.py", line 152, in load_hyperpyyaml
>     yaml_stream = resolve_references(
>   File "/home/cbav/anaconda3/envs/sb/lib/python3.8/site-packages/hyperpyyaml/core.py", line 306, in resolve_references
>     _walk_tree_and_resolve("root", preview, preview, overrides, file_path)
>   File "/home/cbav/anaconda3/envs/sb/lib/python3.8/site-packages/hyperpyyaml/core.py", line 353, in _walk_tree_and_resolve
>     current_node[k] = _walk_tree_and_resolve(
>   File "/home/cbav/anaconda3/envs/sb/lib/python3.8/site-packages/hyperpyyaml/core.py", line 363, in _walk_tree_and_resolve
>     raise ValueError(f"'{key}' is a !PLACEHOLDER and must be replaced.")
> ValueError: 'rir_path' is a !PLACEHOLDER and must be replaced.

Is there a missing argument?

**Comment by Gastron** [comment]
Yes looks like the model card is missing the `rir_path` arg. You should provide a path where the RIRs are saved, just add`--rir_path <your-desired-path>` to the command.

**Comment by Gastron** [comment]
I've modified the model card, thanks for noting this!
