### ISSUE TITLE
Unable to assign sample rate to `speechbrain.dataio.dataio.read_audio`

### ISSUE THREAD

**Issue by weiwei-ww** [speechbrain/speechbrain#1117]
When calling `speechbrain.dataio.dataio.read_audio(wav_path)`, the wave data is loaded with its original sample rate, and it is not possible to assign a sample rate. The original sample rate is not returned either, which should be used for resampling.

**Comment by Gastron** [comment]
We should probably return the sample rate. Unfortunately, adding this breaks backwards compatibility in a often used function. We have to think about how to implement the change, probably in a major revision. @mravanelli, do you agree about this breaking change?

**Comment by mravanelli** [comment]
Yes, it makes sense. This is something to add in SpeechBrain 0.6 (i.e, the
next major version)

**Comment by pplantinga** [comment]
If you want to load the audio with a sample rate, wouldn't torchaudio.load() do the trick? My understanding of `speechbrain.dataio.dataio.read_audio(wav_path)` is that it was intended as a convenience function.

**Comment by Adel-Moumen** [comment]
Hello, 

Please have a look at Peter's [comment](https://github.com/speechbrain/speechbrain/issues/1117#issuecomment-1385603168). I think we can close this issue. Feel free to reopen it if you think there's more on this issue please.

Thanks! 
Adel
