### ISSUE TITLE
Broken docs for `speechbrain.alignment.ctc_segmentation`

### ISSUE THREAD

**Issue by seungwonpark** [speechbrain/speechbrain#1119]
Hi, thanks for maintaining such a wonderful library.

Looks like the documentation for `speechbrain.alignment.ctc_segmentation` is broken:
https://speechbrain.readthedocs.io/en/latest/API/speechbrain.alignment.ctc_segmentation.html

I guess this is caused by unneeded shebang, as shown in the following:
https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/alignment/ctc_segmentation.py#L1-L2

Perhaps this could be related to #819 ?

**Comment by amrit110** [comment]
Hi @seungwonpark, seems like the issue might be that the ctc-segmentation package (https://github.com/lumaku/ctc-segmentation) needs to be installed before compiling the docs. So, perhaps a solution could be to add `ctc-segmentation` to `docs/docs-requirements.txt` file before compiling the html docs using `make html`. I could add a PR if you agree.

**Comment by mravanelli** [comment]
Sure, feel free to do a PR!

**Comment by Gastron** [comment]
I think this could be a case where mocking the import in the docs compilation process would be best. Adding the library here, basically:
https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/docs/conf.py#L72

I'd be happy to look at the PR!

**Comment by Gastron** [comment]
@amrit110 Did you test the output, does this fix the issue?

**Comment by amrit110** [comment]
@Gastron, yes i tested locally, and the speechbrain.alignment.ctc_segmentation page is rendered now. However, the autosummary doesn't get generated for this page, but maybe this is expected, i'm not sure. It seems like just adding to the autodoc_mock_imports should have also mocked the module for autosummary generation according to (https://github.com/sphinx-doc/sphinx/issues/5635), but doesn't seem to be the case.  

On a related note, `numba` is also mocked according to `docs/conf.py`, but the package is also mentioned in `docs/docs-requirements.txt`. So, why not add `ctc_segmentation` to the `docs/docs-requirements.txt`? I would imagine we care most about the build generated by readthedocs with least warnings and maximum documentation features. What would you recommend? 

I also noticed lots of warnings generated in the doc build process, I can create a separate issue to track and clean those up if that would be worthwhile.

**Comment by Gastron** [comment]
I guess adding ctc_segmentation to `docs-requirements.txt` makes sense too. I suppose we should actually opt for either mock or adding to the requirements. Solving the warnings would be nice, but might require a lot of formatting changes in the docstrings.

**Comment by amrit110** [comment]
yes exactly @Gastron, so ill update the PR to add `ctc_segmentation` to `docs-requirements.txt` and remove `numba` from the mock setting. 

As for other warnings, and formatting to docstrings, ill look at it and post on a separate issue.

**Comment by amrit110** [comment]
@Gastron please check updated PR
