### ISSUE TITLE
ConvolutionFrontEnd with residuals skips residual branches

### ISSUE THREAD

**Issue by aviadb** [speechbrain/speechbrain#1124]
The `ConvBlock` forward method is broken when residual is set to True.

/speechbrain/lobes/models/convolution.py, lines 158-164
```           
if self.reduce_conv:
    out = out + self.reduce_conv(x)
    out = self.drop(x)
```
The last line of code should be 
`out = self.drop(out)`

**Comment by Gastron** [comment]
We'd be happy see a PR fix! Or we'll try to get to it when we have time.

**Comment by mravanelli** [comment]
It actually should be:

```
out = out + self.reduce_conv(x)
out = self.drop(x)
```

**Comment by mravanelli** [comment]
Thank you for spotting this issue. I fixed it in the current development branch. Fortunately, this has no effect of the existing recipes because we don't use residual connections. After this fix, it makes sense to try it again.
