### ISSUE TITLE
Unable to use Multi-GPU training using Data Parallel with asr-transformer-transformerlm-librispeech

### ISSUE THREAD

**Issue by matiuste** [speechbrain/speechbrain#1128]
Hi, 
I am trying to replicate the results from asr-transformer-transformerlm-librispeech, unfortunately the multi-GPU for running data in parallel does not work.

I am running the following command:
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 train.py hparams/transformer.yaml --data_parallel_backend --data_folder=/.../librispeech/LibriSpeech/

When I remove the --data_parallel_backend option the program runs, but it only uses one GPU. Do you know what could be causing this? 

I get the following error when transitioning from epoch 1 to 2:

speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/transformer/8886
librispeech_prepare - Skipping preparation, completed in previous run.
speechbrain.pretrained.fetching - Fetch lm.ckpt: Using existing file/symlink in results/transformer/8886/save/lm.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in results/transformer/8886/save/tokenizer.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 161.6M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from results/transformer/8886/save/CKPT+2021-11-16+01-14-50+00
speechbrain.utils.epoch_loop - Going into epoch 1
100%|████████████████████████████████████████████████████████████████████████████████████████████████▉| 35155/35156 [14:36<00:00,  1.53it/s, train_loss=229]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 445, in <module>
    asr_brain.fit(
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/speechbrain/core.py", line 1033, in fit
    loss = self.fit_batch(batch)
  File "train.py", line 152, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "train.py", line 75, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'src' and 'tgt'

Thanks in advance for your help.

**Comment by TParcollet** [comment]
Do you see the same issue with DDP ?

**Comment by matiuste** [comment]
Yes, I am not very familiar with DDP, but I tried the following command:

python3 -m torch.distributed.launch --nproc_per_node=4 train.py hparams/transformer.yaml --distributed_launch=True --distributed_backend='nccl' --data_folder=/.../librispeech/LibriSpeech/

However, I get also an error:

/.local/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: train.py [-h] [--debug] [--debug_batches DEBUG_BATCHES] [--debug_epochs DEBUG_EPOCHS] [--log_config LOG_CONFIG] [--local_rank LOCAL_RANK] [--device DEVICE]
                [--data_parallel_backend] [--distributed_launch] [--distributed_backend DISTRIBUTED_BACKEND] [--find_unused_parameters]
                [--jit_module_keys [JIT_MODULE_KEYS [JIT_MODULE_KEYS ...]]] [--auto_mix_prec] [--max_grad_norm MAX_GRAD_NORM] [--nonfinite_patience NONFINITE_PATIENCE]
                [--noprogressbar] [--ckpt_interval_minutes CKPT_INTERVAL_MINUTES]
                param_file
train.py: error: argument --distributed_launch: ignored explicit argument 'True'
usage: train.py [-h] [--debug] [--debug_batches DEBUG_BATCHES] [--debug_epochs DEBUG_EPOCHS] [--log_config LOG_CONFIG] [--local_rank LOCAL_RANK] [--device DEVICE]
                [--data_parallel_backend] [--distributed_launch] [--distributed_backend DISTRIBUTED_BACKEND] [--find_unused_parameters]
                [--jit_module_keys [JIT_MODULE_KEYS [JIT_MODULE_KEYS ...]]] [--auto_mix_prec] [--max_grad_norm MAX_GRAD_NORM] [--nonfinite_patience NONFINITE_PATIENCE]
                [--noprogressbar] [--ckpt_interval_minutes CKPT_INTERVAL_MINUTES]
                param_file
train.py: error: argument --distributed_launch: ignored explicit argument 'True'
usage: train.py [-h] [--debug] [--debug_batches DEBUG_BATCHES] [--debug_epochs DEBUG_EPOCHS] [--log_config LOG_CONFIG] [--local_rank LOCAL_RANK] [--device DEVICE]
                [--data_parallel_backend] [--distributed_launch] [--distributed_backend DISTRIBUTED_BACKEND] [--find_unused_parameters]
                [--jit_module_keys [JIT_MODULE_KEYS [JIT_MODULE_KEYS ...]]] [--auto_mix_prec] [--max_grad_norm MAX_GRAD_NORM] [--nonfinite_patience NONFINITE_PATIENCE]
                [--noprogressbar] [--ckpt_interval_minutes CKPT_INTERVAL_MINUTES]
                param_file
train.py: error: argument --distributed_launch: ignored explicit argument 'True'
usage: train.py [-h] [--debug] [--debug_batches DEBUG_BATCHES] [--debug_epochs DEBUG_EPOCHS] [--log_config LOG_CONFIG] [--local_rank LOCAL_RANK] [--device DEVICE]
                [--data_parallel_backend] [--distributed_launch] [--distributed_backend DISTRIBUTED_BACKEND] [--find_unused_parameters]
                [--jit_module_keys [JIT_MODULE_KEYS [JIT_MODULE_KEYS ...]]] [--auto_mix_prec] [--max_grad_norm MAX_GRAD_NORM] [--nonfinite_patience NONFINITE_PATIENCE]
                [--noprogressbar] [--ckpt_interval_minutes CKPT_INTERVAL_MINUTES]
                param_file
train.py: error: argument --distributed_launch: ignored explicit argument 'True'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1517460) of binary: /bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/pizarm5k/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2021-11-15_17:32:25
  host      : 
  rank      : 1 (local_rank: 1)
  exitcode  : 2 ()
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2021-11-15_17:32:25
  host      : 
  rank      : 2 (local_rank: 2)
  exitcode  : 2 ()
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2021-11-15_17:32:25
  host      : 
  rank      : 3 (local_rank: 3)
  exitcode  : 2 ()
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-15_17:32:25
  host      : 
  rank      : 0 (local_rank: 0)
  exitcode  : 2 ()
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by anish9208** [comment]
I'm also having the same issue as @matiuste ...  any progress so far ?

**Comment by padmalcom** [comment]
I ran into the same problem training tacotron2 on LJSpeech with 7 GPUs. I restarted the training with a batch size of 70 instead of 64. Will report if the TypeError disappears.

**Comment by Adel-Moumen** [comment]
Hello, 

`data_parallel_backend` is officially deprecated by PyTorch and SpeechBrain. Please use instead `DDP` see: https://speechbrain.readthedocs.io/en/latest/multigpu.html. It would solve your issue. 

Best, 
Adel
