### ISSUE TITLE
Can't import speechbrain in "Introduction to SpeechBrain" colab

### ISSUE THREAD

**Issue by jemisjoky** [speechbrain/speechbrain#1130]
I am trying to learn the basics of SpeechBrain, starting with the "Introduction to SpeechBrain" tutorial. I'm using the [version on Google Colab](https://colab.research.google.com/drive/12bg3aUdr9mTfOGqcB5pSMABoIKPgiwcM?usp=sharing), but unfortunately I keep running into the same CUDA library error when running the second code cell (`import speechbrain as sb`), namely `OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory` (full stack trace at bottom of post).

It looks like this could be more of a torchaudio issue, but since this affects the speechbrain import, it makes it difficult to explore the use of this library. I've also tried running the same Colab with a GPU environment (same error), and using a local installation via cloning the repo and using `pip install -e .` (same error).

Any insight into how to proceed here? I'm going to try doing an installation on my local machine and playing with the tutorial script there, but it would be really convenient to have the Colab version working.

```console
/usr/local/lib/python3.7/dist-packages/speechbrain/dataio/sampler.py in <module>()
     19 import numpy as np
     20 from typing import List
---> 21 from speechbrain.dataio.dataset import DynamicItemDataset
     22 
     23 logger = logging.getLogger(__name__)

/usr/local/lib/python3.7/dist-packages/speechbrain/dataio/dataset.py in <module>()
     11 from torch.utils.data import Dataset
     12 from speechbrain.utils.data_pipeline import DataPipeline
---> 13 from speechbrain.dataio.dataio import load_data_json, load_data_csv
     14 import logging
     15 

/usr/local/lib/python3.7/dist-packages/speechbrain/dataio/dataio.py in <module>()
     18 import csv
     19 import time
---> 20 import torchaudio
     21 import json
     22 import re

/usr/local/lib/python3.7/dist-packages/torchaudio/__init__.py in <module>()
----> 1 from torchaudio import _extension  # noqa: F401
      2 from torchaudio import (
      3     compliance,
      4     datasets,
      5     functional,

/usr/local/lib/python3.7/dist-packages/torchaudio/_extension.py in <module>()
     25 
     26 
---> 27 _init_extension()

/usr/local/lib/python3.7/dist-packages/torchaudio/_extension.py in _init_extension()
     19     # which depends on `libtorchaudio` and dynamic loader will handle it for us.
     20     if path.exists():
---> 21         torch.ops.load_library(path)
     22         torch.classes.load_library(path)
     23     # This import is for initializing the methods registered via PyBind11

/usr/local/lib/python3.7/dist-packages/torch/_ops.py in load_library(self, path)
    108             # static (global) initialization code in order to register custom
    109             # operators with the JIT.
--> 110             ctypes.CDLL(path)
    111         self.loaded_libraries.add(path)
    112 

/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Comment by jemisjoky** [comment]
UPDATE: This same issue is affecting the ["What can I do with SpeechBrain?" colab](https://colab.research.google.com/drive/1mhvu5eyEzNBBhNC6sknG-kgD2ZQ6NEyI?usp=sharing), and most likely all other colabs as well.

**Comment by mravanelli** [comment]
Yes, we are aware of it. The issue is that the latest version of torchaudio doesn't work with colab. See https://github.com/speechbrain/speechbrain/issues/1131. The colab team is going to fix that.

**Comment by TParcollet** [comment]
Note: we will add a hot fix to all tutorials asap.

**Comment by jemisjoky** [comment]
Great, thanks you both! I'll close this, since it's covered by Mirco's new issue

**Comment by mravanelli** [comment]
This is fixed now
