### ISSUE TITLE
A temporary issue on tutorials

### ISSUE THREAD

**Issue by mravanelli** [speechbrain/speechbrain#1131]
It looks like the latest version of torchaudio (v.1.10) cannot be imported correctly within colab. The colab and torchaudio team are aware of it:
https://github.com/googlecolab/colabtools/issues/2417

The temporary solution consists of adding 
`pip install torchaudio -f https://download.pytorch.org/whl/cu113/torch_stable.html`

before installing speechbrain.

**Comment by Aksh97** [comment]
@mravanelli , This solves the problem:

%pip install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

**Comment by mravanelli** [comment]
right, also simply this:
`pip install torchaudio -f https://download.pytorch.org/whl/cu113/torch_stable.html`
I really hope the Colab team will fix this issue soon. It is quite annoying.

**Comment by fosimoes** [comment]
Fyi, I faced the same problem outside Colab, when trying to use Speechbrain on a machine without GPU.
The workaround suggested above solved the problem for me.

**Comment by mravanelli** [comment]
I temporarily modified all the tutorials with the fix posted above. Everything seems to work. I will remove that once Colab will fix the incompatibility issue.

**Comment by mravanelli** [comment]
The colab team just fixed this issue. I removed all the temporary patches from the tutorial. We can now close this issue!
