### ISSUE TITLE
[Speech Separation] Reconstruct the custom wav dataset for training

### ISSUE THREAD

**Issue by windspirit95** [speechbrain/speechbrain#1136]
Thank you for your open-source toolkit for speech processing. I have a question related to the dataset preparation for Sepformer training.
The tutorial is for training on WSJ0-Mix2 and WSJ0-Mix3 dataset, and inside the sepformer-customdataset.yaml I saw we need three csv files for train/valid/test set.
Suppose I am having the wav dataset for 3 speakers mixed with wham noise with structure as below:

dataset
--mix_00001
-----mixture.wav
-----s1.wav
-----s2.wav
-----s3.wav

So could you give me some hints on how to reconstruct the dataset and prepare the content for 3 above CSV files for training? 
Thank you very much.

**Comment by mravanelli** [comment]
@ycemsubakan, could you please share a snippet of how the csv files files should look like?
It should just be `mixture_path, target1_path, target2_path, target3_path`.
@windspirit95, my suggestion is to run a recipes and take a look at it. It is probably the best way to start.

**Comment by ycemsubakan** [comment]
@windspirit95 , thanks for your interest. I will give some examples for this.

**Comment by ycemsubakan** [comment]
@windspirit95 , Sorry for the delay in my reply. 

The code for custom dataset csv generation is here: 
https://github.com/speechbrain/speechbrain/blob/2e78d2cc9aca596a68ee54308534b572e702b13a/recipes/WSJ0Mix/prepare_data.py#L55

The current code follows the following structure:

datasetpath
   train / test / valid
         source1/ source2/ mixture

Maybe to start you can try to make it work with 2 sources. 
Then you can simply modify this function to add the noise and the third source.

**Comment by windspirit95** [comment]
@ycemsubakan Wow thank you so much ^^

**Comment by SutirthaChakraborty** [comment]
Can you share a sample? code or repo, I want to do the same
