### ISSUE TITLE
Problem on introductory Colab tutorial

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#1137]
Hi all! So I happened to want to run some [introductory things](https://colab.research.google.com/drive/12bg3aUdr9mTfOGqcB5pSMABoIKPgiwcM?usp=sharing#scrollTo=F8jUAb9mAhTc) but then I found myself not being able to import with Colab default environment with following error:

```
import speechbrain as sb
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-005055459bd2> in <module>()
----> 1 import speechbrain as sb

12 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

Is it the problem from Colab itself or we may have to debug for back-compatibility? Because torch 1.10.0 with latest ver. of torchaudio may need different version of CUDA (colab currently runs 11.1 while 10.2/11.3 is needed).

If necessary I can make small change on colab to make it work in one-shot.

**Comment by Gastron** [comment]
See issue #1131
