### ISSUE TITLE
Problem while trying to import package

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1138]
Hi, I am using google colab to run this project, last week I ran my project smoothly but today this error comes, could anyone help me how to solve this error? The day before, it tells that I dont have utils module, but today it tells I dont have dataio module

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-9fc59e5b1095> in <module>()
      8 import speechbrain as sb
      9 from speechbrain.utils.data_utils import get_all_files, download_file
---> 10 from speechbrain.dataio.dataio import read_audio

ModuleNotFoundError: No module named 'speechbrain.dataio'

**Comment by Gastron** [comment]
Could you try starting from a clean kernel? Then, you may also have to follow the instructions on issue #1131 at the moment.

**Comment by mravanelli** [comment]
Right, periodically that happens due to some unknown issue in the colab.
Usually a clean start fixes that.

**Comment by mravanelli** [comment]
Could you please try it now?

**Comment by aheba** [comment]
@fadlanhidayat , is it working for you ?

**Comment by fadlanhidayat** [comment]
Hi! Yes, it's working right now. Thank you very much!

**Comment by fadlanhidayat** [comment]
Hello! Just now, it happens again, I couldn't import the package. I have started my project from the beginning then it happened again. Could you please tell me what to do? thank you

**Comment by fadlanhidayat** [comment]
Hi! if I changed my runtime to GPU, then the error appears again. Could you help me with what should I do?

**Comment by Gastron** [comment]
Again, this seems like an issue of the notebook state. Probably just restarting the notebook kernel is the solution again, but if you need some temporary solution (e.g. don't want to lose current state) then you can try explicitly importing the missing package, here e.g. `import speechbrain.dataio.dataio`.
