### ISSUE TITLE
Speech separation from distributed microphones

### ISSUE THREAD

**Issue by jeffshee** [speechbrain/speechbrain#1148]
Hi, thanks for providing this framework! =)

I'm a little bit lost and I'm not sure what to do for my task (or what kind of problem my task belongs to).
I want to perform speech separation on multiple recordings recorded using distributed microphones. For example, 5 people participate in a group discussion in the same room. So here I assign one microphone for each participant and start all recordings at the same time. Ideally, only the speech of the assigned participant should be recorded into that specific microphone. That way I can perform speech recognition for each participant without having to do speaker diarization. However, in real-world situations, participants are in the same room, so speeches from other participants are also recorded as noise. What can I do to obtain the clean recording for each participant in this case?

In brief, my inputs are N recordings from distributed microphones. I want the outputs as N recordings, without the speech (noise) from other participants. Any idea?

**Comment by mravanelli** [comment]
I worked on a similar project years ago in the context of my master thesis. In this context, I think it is reasonable to assume that the voice of the speaker that is closer to the microphone is louder than the others. What you can do is to perform an analysis with some sliding windows and compare energies (or other metrics) for all the microphones simultaneously. Note that this requires that all the microphones are synchronous and have the same gain. The microphone with the highest energy is kept, the others are set to zero. Of course, you can think about more sophisticated approaches (e.g., training a neural network that classifies speech vs cross-talk), but I would suggest starting with very simple approaches. Maybe  @nauman-daw has other suggestions.

**Comment by ycemsubakan** [comment]
It's been while since the question's been asked, so maybe you have already tried this but, 

I suppose one easy baseline to try would be to process each microphone with one of our pre-trained models in Huggingface. You can try both the separators and the speech enhancement models for this. 

A more advanced thing to try would be to simulate this setup in training, and train a separator this way. Basically another way of doing dynamic mixing.

**Comment by nauman-daw** [comment]
I think both the approaches @mravanelli and @ycemsubakan suggested are good enough. 
You may also look at beamforming all streams. This may generate a single enhanced signal. You can then perform diarization and then ASR on specific chunks. But this is just a more involved option.
