### ISSUE TITLE
Training Speaker recognition experiments python train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml "voxceleb_source"

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1149]
Hello:
I'd like to ask a question about Python train in the experiment of training Speaker recognition experiments with VoxCeleb ,python train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml is a parameter voxceleb_source in this instruction. doesn't know how to set it, as shown in the following figure. I want to know what this parameter means and how to set it?
Thank you.
![image](https://user-images.githubusercontent.com/86965285/142838438-ee059c43-d610-4ef4-8122-75a55d3c7ea6.png)

**Comment by mravanelli** [comment]
Hi, 
actually there isn't the `voxceleb_source` parameter in `hparams/train_ecapa_tdnn.yaml`. As you can see for [here](https://github.com/speechbrain/speechbrain/blob/2e78d2cc9aca596a68ee54308534b572e702b13a/recipes/VoxCeleb/voxceleb_prepare.py#L72) it is an optional parameter that by default is set to `None`.  I don't remember why @nauman-daw introduced it, but in my case, everything works even without specifying it. 

@nauman-daw any idea about the role of it? If it is not strictly needed we can even remove it, right?

**Comment by nauman-daw** [comment]
Yes, I don't think it is needed anymore. I might have forgotten to remove it.  Maybe it's safe to remove that.
