### ISSUE TITLE
Code inconsistency between github repo and pip package, under same version

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#1151]
Hi all! I am now trying to configure some speaker recognition experiments using ECAPA-TDNN. However, when I was trying to load the model via yaml file, I got following error:
```
TypeError: ('Invalid argument to class speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN', "__init__() got an unexpected keyword argument 'groups'")
```
I then checked the pip package, the initialization arguments for ECAPA-TDNN are different from the current github one.

In the pip package, can be checked at `$conda_directory/.local/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py`:
```class ECAPA_TDNN(torch.nn.Module):
    """An implementation of the speaker embedding model in a paper.
    "ECAPA-TDNN: Emphasized Channel Attention, Propagation and Aggregation in
    TDNN Based Speaker Verification" (https://arxiv.org/abs/2005.07143).

    Arguments
    ---------
    device : str
        Device used, e.g., "cpu" or "cuda".
    activation : torch class
        A class for constructing the activation layers.
    channels : list of ints
        Output channels for TDNN/SERes2Net layer.
    kernel_sizes : list of ints
        List of kernel sizes for each layer.
    dilations : list of ints
        List of dilations for kernels in each layer.
    lin_neurons : int
        Number of neurons in linear layers.

    Example
    -------
    >>> input_feats = torch.rand([5, 120, 80])
    >>> compute_embedding = ECAPA_TDNN(80, lin_neurons=192)
    >>> outputs = compute_embedding(input_feats)
    >>> outputs.shape
    torch.Size([5, 1, 192])
    """

    def __init__(
        self,
        input_size,
        device="cpu",
        lin_neurons=192,
        activation=torch.nn.ReLU,
        channels=[512, 512, 512, 512, 1536],
        kernel_sizes=[5, 3, 3, 3, 1],
        dilations=[1, 2, 3, 4, 1],
        attention_channels=128,
        res2net_scale=8,
        se_channels=128,
        global_context=True,
    ):
```
Meanwhile on [Github](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/lobes/models/ECAPA_TDNN.py), also the one I have in my sync-ed repo:
```class ECAPA_TDNN(torch.nn.Module):
    """An implementation of the speaker embedding model in a paper.
    "ECAPA-TDNN: Emphasized Channel Attention, Propagation and Aggregation in
    TDNN Based Speaker Verification" (https://arxiv.org/abs/2005.07143).
    Arguments
    ---------
    device : str
        Device used, e.g., "cpu" or "cuda".
    activation : torch class
        A class for constructing the activation layers.
    channels : list of ints
        Output channels for TDNN/SERes2Net layer.
    kernel_sizes : list of ints
        List of kernel sizes for each layer.
    dilations : list of ints
        List of dilations for kernels in each layer.
    lin_neurons : int
        Number of neurons in linear layers.
    groups : list of ints
        List of groups for kernels in each layer.
    Example
    -------
    >>> input_feats = torch.rand([5, 120, 80])
    >>> compute_embedding = ECAPA_TDNN(80, lin_neurons=192)
    >>> outputs = compute_embedding(input_feats)
    >>> outputs.shape
    torch.Size([5, 1, 192])
    """

    def __init__(
        self,
        input_size,
        device="cpu",
        lin_neurons=192,
        activation=torch.nn.ReLU,
        channels=[512, 512, 512, 512, 1536],
        kernel_sizes=[5, 3, 3, 3, 1],
        dilations=[1, 2, 3, 4, 1],
        attention_channels=128,
        res2net_scale=8,
        se_channels=128,
        global_context=True,
        groups=[1, 1, 1, 1, 1],
    ):
```
The latter is obviously the compatible one with the YAML file. I am on a public cluster so `python setup.py install` is not an option. The version I have for both sides is 0.5.10 (latest).

Am I missing anything or this is an issue shall be fixed? I know group setting is trivial for ECAPA-TDNN but this issue can be hard to be spotted if people does not give much attention to pip (and they install via pip). And this may not be the only issue as I suspect.

**Comment by Gastron** [comment]
Note that the PyPI package follows the `main` branch. Looks like the groups parameter still hasn't made its way to main:
https://github.com/speechbrain/speechbrain/blob/main/speechbrain/lobes/models/ECAPA_TDNN.py

This does however remind us of the issue of keeping the recipes in sync with the library code. Since they share the same repository, it would be natural to expect that the recipes at any given commit work with the library code at that commit. Here, that does hold. The recipes can only trail the library code - but the library code might at some point be changed so that recipes no longer work. We've discussed the possibility of breaking the recipes into their own repositories, but for now we felt that keeping everything in the same repository is overall better. Maybe we could start adding SpeechBrain repo commit hashes to recipes (in the README for example), to mark at least one version where the recipe works.

**Comment by underdogliu** [comment]
@Gastron Thanks a lot for the reply! But I wonder what is the exact roles of the branch `develop`? Is it supposed to be a "nightly" branch where most likely we shall expect something breaking down? Or is should be stable as well for existed features, but with some new functions which may break down?

**Comment by Gastron** [comment]
Good question! In this toolkit, I think the line between "nightly" and "new but stable" is very blurry, but I guess I'd say it's good to have "nightly"-type expectations :D. But in practice a lot of people are doing their research work on the `develop` branch.

**Comment by Gastron** [comment]
Also, you mention that you might not be able to install via setup.py because of working on a public cluster - to this end, both conda (which you seem to be using) and venv/virtualenv environments should solve the issue, is [this](https://speechbrain.readthedocs.io/en/latest/installation.html#install-locally) of any help?

**Comment by underdogliu** [comment]
Yeah we will see later because after some debugging I made a "modified" ver. working on my side lol. But in terms of speaker recognition experiments, I think the repo has multiple problems. Will address them in another issue or something.

Also, would it be helpful if we somehow have some connections with kaldi in terms of I/O? I mean, torchaudio by default supports it and as far as I learned, lots of people, although being a bit frustrated with kaldi's steep learning curve, do find their file management have been awesome.

**Comment by Gastron** [comment]
Ok, good to hear this was cleared - I'll close the issue. 

We'd be happy to consider any ideas and contributions you have!

SpeechBrain works with any PyTorch-style data loading, so if torchaudio has e.g. an appropriate Dataset implementation, that should work, and you could also consider [Lhotse](https://lhotse.readthedocs.io/en/latest/kaldi.html). I'm also planning to contribute a script that converts Kaldi data to WebDataset shards - before it's ready for SpeechBrain, here it is as a gist, if that's of any help:
[https://gist.github.com/Gastron/a641526a9716e1aef022b4f8ec05dcc9](https://gist.github.com/Gastron/a641526a9716e1aef022b4f8ec05dcc9)**
