### ISSUE TITLE
How to do inference after training a MetricGAN+ ?

### ISSUE THREAD

**Issue by vincentwu0730** [speechbrain/speechbrain#1153]
Hi,

I've reproduced the result from the recipe of MetricGAN+. Great work!

And the easy-inference function on HuggingFace also works perfectly when source=speechbrain/metricgan-plus-voicebank.

So the question is how do I load the trained model from disk? There seems to be a problem when I try to use the SpectralMaskEnhancement.from_hparams() function  by the ckpt file and the hyperparams.yaml saved by train.py.

Can you provide a snippet to do inference from custom training MetricGAN+?

Really appreciate your help with this situation.

**Comment by mravanelli** [comment]
Hi,
the inference hyperparameters are different from the training one. We wrote a [tutorial](https://colab.research.google.com/drive/1137MD-gAERblRAVhxDnwNXV3YyAiwtxV?usp=sharing) to describe how to use the inference interfaces with your models.  The [hparam file](https://huggingface.co/speechbrain/metricgan-plus-voicebank/blob/main/hyperparams.yaml) in the metricgan+ HF repo could be a good starting point to check for you.
