### ISSUE TITLE
Pretrained.from_hparams() failing on windows when non admin

### ISSUE THREAD

**Issue by gfournier** [speechbrain/speechbrain#1155]
The following code is failing on windows with non-admin rights (not a big issue but sadly a "standard" case in lots of "big" companies) due to symlinks.

```python
EncoderClassifier.from_hparams(
  source=r"C:\path\to\pretrained\model",
  savedir="./tmp",
  overrides={"pretrained_path": r"C:\path\to\pretrained\model"})
```

I fixed it locally by copying models to `savedir` instead of making a symlink (`fetching.py:L102`), BUT I will not submit it as a fix.
```python
try:
  destination.symlink_to(sourcepath)
except:
  import shutil
  shutil.copyfile(sourcepath, destination)
```

I can start working on local loading feature in a PR if you're interested. When loading from local, we could even avoid copying or symlinking directories and loading directly from the local folder for example.

**Comment by gfournier** [comment]
EDIT: it works well for following configuration as a workround, I let you decide if you need a better solution :)

```python
EncoderClassifier.from_hparams(
  source=r"C:\path\to\pretrained\model",
  savedir=r"C:\path\to\pretrained\model",
  overrides={"pretrained_path": r"C:\path\to\pretrained\model"})
```

**Comment by Gastron** [comment]
Yes, this is a known issue, see for instance #893. Thanks for a new workaround idea! At the moment we don't plan to change this implementation just for Windows users who cannot run with the right permissions. However, this might get fixed for Windows users if we decide to move away from symlinks to real copies - which seems to be behaviour that multiple users expect.

**Comment by gfournier** [comment]
I found a new one with latest version 0.5.11:
https://github.com/speechbrain/speechbrain/blame/9d56d50809d8745cc7dafa930aec554145be4028/speechbrain/pretrained/interfaces.py#L281

A fetch of a `custom.py` file has been introduced and a symlink is created if the file is missing.
This customization cannot be bypassed by passing `None` for example.

**Comment by Gastron** [comment]
Ooh that is just a bug in how local `source`s are handled!

**Comment by padmalcom** [comment]
FYI this issue still exists for Tacotron2.from_hparams on Windows.

**Comment by Adel-Moumen** [comment]
Hello, 

Any news on this issue please? 

Thanks.

**Comment by tomwagstaff-opml** [comment]
I'd also be interested in an update. There are quite a few of us Windows users out there without admin rights 😅 

Even some further explanation / documentation of the workarounds would be useful, although in my case I'm using a package that depends on speechbrain so I can't implement any workarounds directly.

**Comment by erklem** [comment]
Can we re-open this, please? During the review of the linked PR (#2476), it seems disabling symlinks by default was backtracked. 

In speechbrain 1.0.2, [Pretrained.from_hparams](https://github.com/speechbrain/speechbrain/blob/31e007e9a5de7a2d36d586d970deec95ff949514/speechbrain/inference/interfaces.py#L402) still defaults to using symlinks.

```python
    def from_hparams(
        cls,
        source,
        hparams_file="hyperparams.yaml",
        pymodule_file="custom.py",
        overrides={},
        savedir=None,
        use_auth_token=False,
        revision=None,
        download_only=False,
        huggingface_cache_dir=None,
        overrides_must_match=True,
        local_strategy: LocalStrategy = LocalStrategy.SYMLINK,
        **kwargs,
    ):
```
