### ISSUE TITLE
Show training utterances in the training log

### ISSUE THREAD

**Issue by csetanmayjain** [speechbrain/speechbrain#1157]
Hi,
Some of my utterances are creating issues while training. Following is the error, it's throwing:
`RuntimeError: The size of tensor a (17243) must match the size of tensor b (2500) at non-singleton dimension 1`

I want to troubleshoot, exactly which utterance is creating the problem. 
How can I modify the script, so, while training, it will also print utterances in the terminal, which batches are currently selected for training, or there is any other efficient way to troubleshoot the error?

Thanks

**Comment by Gastron** [comment]
You can just add a `print` statement inside `compute_forward()` for instance. You can also directly iterate the dataset.

My hunch is that the 2500 size tensor is your max size for positional encoding (I think we have that as default) and this utterance is way longer. Either you can modify the maximum positional encoding size, or perhaps filter out this very long utterance.

**Comment by csetanmayjain** [comment]
hi @Gastron 
Thanks for the help.
I get the institution, & tried to print the batch, waves, etc in `compute_forward()`, but the issue is, it's printing the features. I want to print the wav file name, which is currently selected for processing. 

Also, how can I modify the maximum positional encoding size? Can't able to find out any variable related to this in YAML file. I'm using Librispeech based transformer recipe.

Thanks

**Comment by Gastron** [comment]
Try printing `batch.id`.

The maximum positional encoding size is determined by the max_length param, see this: https://speechbrain.readthedocs.io/en/latest/_modules/speechbrain/lobes/models/transformer/TransformerASR.html#TransformerASR

**Comment by csetanmayjain** [comment]
Thanks @Gastron 
The issue was resolved.
I use batch.id, to print the utt.
There was an utt of more than 10 minutes, which is creating the issue.

Thanks a lot :)

**Comment by FusionLi** [comment]
Is it possible to increase max_length param for pretrained EncoderDecoderASR for processing very long sequence?
