### ISSUE TITLE
mean and var in normalizer get updated during inference?

### ISSUE THREAD

**Issue by jjjjohnson** [speechbrain/speechbrain#1159]
Hi,
I am looking at the `speechbrain/asr-transformer-aishell` and see after load the initial ckpt of normalizer `speechbrain.processing.features.InputNormalization`, the statistics will still get updated during inference since the default value for  InputNormalization is `update_until_epoch=3`  and `epoch=0` in forward. This behavior looks weird to me.

Thanks for any clarification!
Junjie

**Comment by jjjjohnson** [comment]
Look like you need to set update_until_epoch to 0 to disable update during inference:
```
normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    update_until_epoch: 0
```

**Comment by TParcollet** [comment]
The reason for that is that the mean and var are computed per batch. You should avoid having this parameter bellow 1.

**Comment by jjjjohnson** [comment]
Thanks @TParcollet 
I am still confused since using the setting below:  
```
normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
```
self.glob_mean and self.glob_std will change during inference:
https://github.com/speechbrain/speechbrain/blob/2e78d2cc9aca596a68ee54308534b572e702b13a/speechbrain/processing/features.py#L1089

**Comment by TParcollet** [comment]
Again, this is expected, even at inference time. If you don't update these values between batches, it would mean that you normalize all the data w.r.t the first batch statistics only.

**Comment by jjjjohnson** [comment]
Based on https://github.com/speechbrain/speechbrain/blob/2e78d2cc9aca596a68ee54308534b572e702b13a/recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer.yaml#L203
My understanding is self.glob_mean and self.glob_std only updated during first 4 epochs during training. Why do we need to update self.glob_mean and self.glob_std during inference? Sorry I am kinda newbie in this tool...

**Comment by TParcollet** [comment]
Well it depends on what you would like to do as there isn't a single way of doing normalization. We decided to continue updating the statistics even at inference to adapt to the new dataset :-)

**Comment by jjjjohnson** [comment]
Cool ! Thanks for the clarification! Really appreciate it!
