### ISSUE TITLE
Finetune wav2vec2 models on speechbrain

### ISSUE THREAD

**Issue by csetanmayjain** [speechbrain/speechbrain#1161]
Hi,
I would like to use the pre-trained model of wav2vec2 from facebook [like this](https://huggingface.co/facebook/s2t-wav2vec2-large-en-ar) 

How can I use these models to fine-tune my data using librispeech transformer-based recipe?
Do I also need to take care of the tokenizer, layers, etc. ? Also, the model is in .bin, extension how can I further fine-tune it?

Thanks

**Comment by TParcollet** [comment]
Hi! Everything is managed within SpeechBrain (apart from the tokenizer), see [this tutorial](https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing). If this isn't enough I'll help you. But note: if the model already is finetuned with a specific tokenizer, I don't know (empirically speaking) how it will react with a new one. I guess it should work just fine.

**Comment by TParcollet** [comment]
Hi! Everything is managed within SpeechBrain (apart from the tokenizer), please see the different recipes we have with wav2vec 2.0 (CommonVOice or LibriSpeech: https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/CTC). If this isn't enough I'll help you. But note: if the model already is finetuned with a specific tokenizer, I don't know (empirically speaking) how it will react with a new one. I guess it should work just fine.

**Comment by csetanmayjain** [comment]
Thanks @TParcollet 
If I'm not wrong, it's not based on the transformer? I want to fine-tune on transformer-based architecture

**Comment by TParcollet** [comment]
Write, simply change the model to a transformer then :-P SpeechBrain is done so everything is extremely simple. However, we did not use a transformer in top of wav2vec 2.0 due to the crazy VRAM consumption of the fine-tuning (especially if you fine-tune the wav2vec encoder as well).

**Comment by csetanmayjain** [comment]
Thanks a lot, @TParcollet :)
I will give it a try with tranformer
