### ISSUE TITLE
AttributeError: 'VAD' object has no attribute 'merge_close_segments'

### ISSUE THREAD

**Issue by kaen2891** [speechbrain/speechbrain#1165]
Hello, I found one error from the `VAD` pre-trained model which is described in [https://huggingface.co/speechbrain/vad-crdnn-libriparty](url).

In that URL, the VAD pipeline's descriptions are as follows:

```
from speechbrain.pretrained import VAD
VAD = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")

# 1- Let's compute frame-level posteriors first
audio_file = 'pretrained_model_checkpoints/example_vad.wav'
prob_chunks = VAD.get_speech_prob_file(audio_file)

# 2- Let's apply a threshold on top of the posteriors
prob_th = VAD.apply_threshold(prob_chunks).float()

# 3- Let's now derive the candidate speech segments
boundaries = VAD.get_boundaries(prob_th)

# 4- Apply energy VAD within each candidate speech segment (optional)

boundaries = VAD.energy_VAD(audio_file,boundaries)

# 5- Merge segments that are too close
boundaries = VAD.merge_close_segments(boundaries, close_th=0.250)

# 6- Remove segments that are too short
boundaries = VAD.remove_short_segments(boundaries, len_th=0.250)

# 7- Double-check speech segments (optional).
boundaries = VAD.double_check_speech_segments(boundaries, audio_file,  speech_th=0.5)
```

Here, the 5th function seems to not work.
```
# 5- Merge segments that are too close
boundaries = VAD.merge_close_segments(boundaries, close_th=0.250)
```

As I follow those guidelines, I got error as follow:

![image](https://user-images.githubusercontent.com/46586785/143470600-21652ed4-6f77-4d89-a1a6-5acf0ac2975f.png)

Could you give pieces of information about this and if this function has already gone, would you change the description written in [https://huggingface.co/speechbrain/vad-crdnn-libriparty](url).

Thanks.

**Comment by mravanelli** [comment]
Hi, that function was renamed for consistency. If you are using the `pip install` version of speechbrain, you should use `merge_short_segments` instead of `merge_close_segments`. If you are using the latest development branch (the one you get with git clone), you can use the `merge_close_segments`. This issue will disappear when we will release the new version of speechbrain (which should be issued quite soon). My suggestion, for now, is to use the "clone version" of speechbrain that uses the development branch:
```
git clone https://github.com/speechbrain/speechbrain/
cd speechbrain
pip install -e .
```

**Comment by kaen2891** [comment]
Thanks for fast response. Your mentions are very helpful for me. Thanks a lot.
