### ISSUE TITLE
Too many levels of symlinks error when loading model in AWS Lambda function

### ISSUE THREAD

**Issue by suneelmatham** [speechbrain/speechbrain#1177]
Hi, I have been trying to containerize Speaker Recognition model in an AWS lambda function which has a read-only Linux file system with just '/tmp' folder available for write. Following issues #1001 and #1155, I have downloaded the model files and copied them into '/tmp' during build and loaded as below
`diarizer = SpeakerRecognition.from_hparams(source='/tmp', savedir='/tmp', overrides={"pretrained_path": '/tmp'})`

Getting a too many levels of symlinks error
![sb-lambda-err](https://user-images.githubusercontent.com/54971275/144649078-757c33f6-60ca-4c00-8976-940565a50b26.png)

Please let me know how I can fix it. Thanks

**Comment by mravanelli** [comment]
@Gastron, any idea?

**Comment by Gastron** [comment]
Too many levels of symlinks results from some kind of broken, probably circular symlink. If you do the same thing on your own machine, do you get the same error. Also double check whether you're actually copying the model files and not just the symlinks (HuggingFace Hub downloads to its cache and SpeechBrain creates a symlink in savedir) during your build.

**Comment by Gastron** [comment]
It could be that - and also, are you using the `paths` argument to Pretrainer? Perhaps you could simplify, name the checkpoint files appropriately in `/tmp` - maybe that is causing additional symlinks like for instance this label encoder file.

Other than that, if it works on the local side, but not on AWS Lambda, I suggest going over the loading process on the local side once more - perhaps it needs some other location (outside `/tmp`) after all? Or is there some other difference between the Lambda instance and your local? Can you replicate the environment where only `/tmp` is writeable?

**Comment by Adel-Moumen** [comment]
Hello, 

Any news with this issue please? 

Thanks. 
Adel

**Comment by asumagic** [comment]
I noticed this issue before but the reason didn't occur to me until now: `source` and `savedir` cannot be the same, which likely causes a symlink into itself. We should add a check of some sort to prevent this, and reduce the use of symlinks in general (#2476).
