### ISSUE TITLE
Fine tune LID with less langs

### ISSUE THREAD

**Issue by supreet21** [speechbrain/speechbrain#1184]
Hi, 
I was trying to finetune the voxlingua model for only 10 langs.
can anyone tell me how can I use the pretrained model and fine-tune it for some particular languages?

Thanks

**Comment by Gastron** [comment]
Have you looked at [this tutorial](https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing)? It does not directly implement what you are looking for but hopefully it could help you understand how to go about this.

**Comment by mravanelli** [comment]
Yes, you can follow the tutorial. I think the simplest way here is to pretrain the [encoder](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxLingua107/lang_id/hparams/train_ecapa.yaml#L62) with our pretraner class (see an example [here](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml#L77)). Then you can change the number of outputs in the classifier [here](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxLingua107/lang_id/hparams/train_ecapa.yaml#L45]) and fine-tune with your data.
