### ISSUE TITLE
Multilingual Text to Speech Support like this project?

### ISSUE THREAD

**Issue by krigeta** [speechbrain/speechbrain#1185]
Hello, does it support the Multilingual process, like mentioned below?

Japanese speakers can able to speak in English.

This project is doing something like this but the results are not that good.

Link: [https://github.com/Tomiinek/Multilingual_Text_to_Speech]

**Comment by mravanelli** [comment]
Some systems work pretty well with accented/non-native speech. You might
want to take a look, for instance, at our commonvoice-en system (
https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-en). If it
doesn't work well for you, you can still give it a try to the standard
LibriSpeech one
https://huggingface.co/speechbrain/asr-transformer-transformerlm-librispeech
.

**Comment by TParcollet** [comment]
Hey Mirco, I think the comment was on TTS and not STT. We do not support multilingual TTS. And To be honest, this remains a completely open line of research so you may not be able to find a really convincing system around.

**Comment by krigeta** [comment]
@TParcollet 
yes, you are right, and have you checked the link in the post?

@mravanelli it is not related to what I asked but I appreciate it if there is a google collab notebook for this. Like I want to analyze Japanese voices and convert them into Text. Japanese Voice = Japanese Text

**Comment by TParcollet** [comment]
We have an ongoing PR for integrating TTS with tacotron 2 + HiFiGAN but it still is under training ...
