### ISSUE TITLE
Unable to use the REAL-M dataset; malformed WAV files?

### ISSUE THREAD

**Issue by actuallyaswin** [speechbrain/speechbrain#1188]
Hello, I'm trying to experiment with the newly released [REAL-M dataset](https://huggingface.co/speechbrain/REAL-M-sisnr-estimator), but I can't seem to open the original audio files for some reason. Using `sox`:
```
user@host:/data/REAL-M-v0.1.0$ soxi audio_files_converted_8000Hz/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav 

Input File     : 'audio_files_converted_8000Hz/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 25-bit
Duration       : 00:00:04.26 = 34080 samples ~ 319.5 CDDA sectors
File Size      : 136k
Bit Rate       : 256k
Sample Encoding: 32-bit Floating Point PCM

user@host:/data/REAL-M-v0.1.0$ soxi audio_files/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav 
soxi FAIL formats: can't open input file `audio_files/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav': WAVE: RIFF header not found
```

Similarly when trying to open the file in Python:

```python
# Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
# [GCC 9.3.0] on linux
# Type "help", "copyright", "credits" or "license" for more information.
>>> import soundfile as sf
>>> y = sf.read('audio_files/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav')
'''Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/soundfile.py", line 256, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home//.local/lib/python3.8/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/user/.local/lib/python3.8/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/home/user/.local/lib/python3.8/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'audio_files/aCuPKFNALlIVbOl/mixture_111_aCuPKFNALlIVbOl.wav': File contains data in an unknown format.'''
```

What's going on here? Any insights @ycemsubakan?

**Comment by mravanelli** [comment]
@ycemsubakan, I guess we should provide a dataset that can be easily read by the users. Do you think we should share a normalized version of the dataset rather than the original raw recordings?

**Comment by ycemsubakan** [comment]
Yes, the processed versions are available in 8k in the version that is up.
I can provide the 16k versions as well.

**Comment by actuallyaswin** [comment]
That would be great! A lot of algorithms are working with 16k audio these days, and my goal for opening the files with `sox` was specifically to batch convert sampling rates. 🙌 Until you guys release a version though, I'll do what @ycemsubakan said and convert using `librosa`, although I imagine that will be much slower than `ffmpeg` or `sox`.

**Comment by ycemsubakan** [comment]
I have just uploaded the 16k files here: http://sourceseparationresearch.com/static/REALM_audio_files_converted_16000Hz.tar.gz

Please let us know if something is wrong!

**Comment by mravanelli** [comment]
Thank you for sharing your feedback. I think we can definitely proceed with
the release of the 16khz dataset. What do you think @ycemsubakan
<https://github.com/ycemsubakan>?

**Comment by ycemsubakan** [comment]
Yes, I mean the original dataset is at 48kHz. It's up to the users to subsample as they wish. The thing that I overlooked is the need for resaving.. The other thing we should do would be to release the performance estimator at 16kHz..

**Comment by ycemsubakan** [comment]
I am closing the issue, as I think it's solved. Feel free to reopen if you have other questions.
