### ISSUE TITLE
[AMI] What flags for AMI-IHM dataset? 

### ISSUE THREAD

**Issue by patrickvonplaten** [speechbrain/speechbrain#1189]
Thanks a lot for writing a script to prepare the AMI dataset - this is super useful! 
One question: In most papers, results are reported on the AMI-IHM dataset, *e.g.*:
- https://www.researchgate.net/profile/Pawel-Swietojanski/publication/258075865_Hybrid_acoustic_models_for_distant_and_multichannel_large_vocabulary_speech_recognition/links/54b98ea50cf24e50e93dc808/Hybrid-acoustic-models-for-distant-and-multichannel-large-vocabulary-speech-recognition.pdf

It should correspond to the single speaker close distance microphone, but I'm unsure which settings need to be set exactly. 
Would the default flags: 

```
    split_type="full_corpus_asr",
    skip_TNO=True,
    mic_type="Lapel",
    vad_type="oracle",
    max_subseg_dur=3.0,
    overlap=1.5,
```

be correct for this? 

Gently pinging @nauman-daw here

**Comment by mravanelli** [comment]
@nauman-daw

**Comment by patrickvonplaten** [comment]
Thanks a lot @nauman-daw

**Comment by nauman-daw** [comment]
You're welcome! I will close this issue.

**Comment by nauman-daw** [comment]
You're welcome!
