### ISSUE TITLE
Running on AWS Sagemaker

### ISSUE THREAD

**Issue by rudsamn** [speechbrain/speechbrain#1191]
Related to #833 

I'm trying to run speechbrain in Sagemaker using an endpoint. How do I convert the speechbrain enhancement model into a format that can be called through an endpoint?

**Comment by Gastron** [comment]
SpeechBrain is used to build PyTorch models - hopefully the AWS SageMaker documentation for PyTorch can help you: [https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#deploy-pytorch-models](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#deploy-pytorch-models).

**Comment by rudsamn** [comment]
Thank you, will try this out!

**Comment by rudsamn** [comment]
Hello, all the examples given are for text / NLP applications. 
Is there any support for audio files ?

**Comment by Gastron** [comment]
That question is purely related to the commercial AWS SageMaker product - in general I advice to refer to its documentation and help resources. That said, perhaps this can help: [https://github.com/aws-samples/amazon-sagemaker-audio-classification-pytorch](https://github.com/aws-samples/amazon-sagemaker-audio-classification-pytorch)

**Comment by Gastron** [comment]
Closing, but it'd be nice to hear if you got it to work
