### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1196]
Hi,

I was running the Transducer model with French CommonVoice data (https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/transducer). I stopped the model training after 1st epoch and then run it again, however, now I am getting `RuntimeError: generator raised StopIteration` when it starts the 2nd epoch. Do you perhaps know why I receive the error?

It was trained with data-parallel-backend option

``` bash
 Available devices: 3
 CUDA Available: True
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/cv_transducer/2140
common_voice_prepare - results/cv_transducer/2140/save/train.csv already exists, skipping data preparation!
common_voice_prepare - results/cv_transducer/2140/save/dev.csv already exists, skipping data preparation!
common_voice_prepare - results/cv_transducer/2140/save/test.csv already exists, skipping data preparation!
speechbrain.tokenizers.SentencePiece - Tokenizer is already trained.
speechbrain.tokenizers.SentencePiece - ==== Loading Tokenizer ===
speechbrain.tokenizers.SentencePiece - Tokenizer path: results/cv_transducer/2140/save/1000_unigram.model
speechbrain.tokenizers.SentencePiece - Tokenizer vocab_size: 1000
speechbrain.tokenizers.SentencePiece - Tokenizer type: unigram
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 142.4M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from results/cv_transducer/2140/save/CKPT+2021-12-09+04-58-56+00
speechbrain.utils.epoch_loop - Going into epoch 2

44178it [00:00, ?it/s]
44178it [00:00, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/sw/arch/Debian10/EB_production/2021/software/Anaconda3/2021.05/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/kubara/repos/speechbrain/speechbrain/dataio/dataloader.py", line 206, in __iter__
    iterator = super().__iter__()
  File "/home/kubara/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/kubara/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 302, in _get_iterator
    return _SingleProcessDataLoaderIter(self)
  File "/home/kubara/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 552, in __init__
    super(_SingleProcessDataLoaderIter, self).__init__(loader)
  File "/home/kubara/repos/speechbrain/speechbrain/dataio/dataloader.py", line 151, in __new_init
    next(self._sampler_iter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kubara/repos/speechbrain/recipes/CommonVoice/ASR/transducer/train.py", line 416, in <module>
    asr_brain.fit(
  File "/home/kubara/repos/speechbrain/speechbrain/core.py", line 1032, in fit
    for batch in t:
RuntimeError: generator raised StopIteration
srun: error: r34n7: task 0: Exited with exit code 1
```

**Comment by Gastron** [comment]
Looks like it's loading an intra-epoch checkpoint, and that the dataloader is trying to fast forward the Sampler, but the Sampler runs out of indices. I think this case is actually not handled correctly; since Python 3.7 we should actually catch the StopIteration explicitly - I'll create a fix quick. 

However, this case is also very unlikely, so let's verify it really happened the way I described. Can you paste the contents from a a couple of files in your checkpoint directory `results/cv_transducer/2140/save/CKPT+2021-12-09+04-58-56+00`: `CKPT.yaml` and `dataloader-TRAIN.ckpt` (or something similar)?

**Comment by KacperKubara** [comment]
Ok great thanks. File content below.

`CKPT.yaml`
``` yaml
# yamllint disable
brain_intra_epoch_ckpt: true
end-of-epoch: false
unixtime: 1639022336.4647799
```

`dataloader-TRAIN.ckpt`
``` txt
44178
```

**Comment by Gastron** [comment]
Okay. Looks like it really happened the way I described, an intra-epoch checkpoint. Did you change something between the runs? Or are you using something like dynamic batching or other method that could make the number of batches per epoch different across runs?

**Comment by Gastron** [comment]
And if you try to run it with this change applied: https://github.com/speechbrain/speechbrain/pull/1197 does it work?

**Comment by KacperKubara** [comment]
From what I remember, I did change the batch size manually after epoch one because I didn't use the full capacity of GPUs. I got this error afterwards so I swapped back to the old batch size but I got this error once again.

**Comment by Gastron** [comment]
Closing, but I'd be happy to hear how the fix PR affected this.
