### ISSUE TITLE
Error Loading French model asr-wav2vec2-commonvoice-fr 

### ISSUE THREAD

**Issue by cveaux** [speechbrain/speechbrain#1206]
Hi, I'm getting an error while trying to load this CTC/Attention model: asr-wav2vec2-commonvoice-fr (to be used with ctc_segmentation).

```
from speechbrain.pretrained import EncoderASR
sr_model = EncoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-fr", savedir="pretrained_models/asr-wav2vec2-commonvoice-fr")

ImportError: cannot import name 'model_info' from 'huggingface_hub' (/home/fsuser/miniconda3/envs/py37/lib/python3.7/site-packages/huggingface_hub/__init__.py)
```

Is this a version compatibility issue? I'm using speechbrain 0.5.11

**Comment by TParcollet** [comment]
Hi, I don't really understand. I tried again and it worked ... could you please try with a fresh install? like in a clean env, pip install speechbrain and then try again. 
<img width="1777" alt="Capture d’écran 2021-12-22 à 23 22 43" src="https://user-images.githubusercontent.com/11910731/147161865-f8246217-ea98-45b0-961d-32f6fbd1be94.png">

**Comment by cveaux** [comment]
yes, I actually just updated `huggingface-hub` to 0.2.1 and it worked, I had a too old version of this module.
