### ISSUE TITLE
Old version of interfaces.py when installing using pip

### ISSUE THREAD

**Issue by asher-bs** [speechbrain/speechbrain#1207]
This issue makes it impossible to use the Emotion recognition model 
can't import 
from speechbrain.pretrained.interfaces import foreign_class

**Comment by TParcollet** [comment]
@aheba any idea?

**Comment by aheba** [comment]
Mmm, let me take a look

**Comment by mravanelli** [comment]
@aheba are you able to replicate this issue?

**Comment by anautsch** [comment]
Closing here. Please feel free to re-open.
