### ISSUE TITLE
weights loading error

### ISSUE THREAD

**Issue by curlneuron** [speechbrain/speechbrain#1211]
When run the IEMOCAP task, the codes need to get wav2vev2-model-weight. 
Probably it's because of the Net Connection at my machine.  How can I solve this by using an offline loading way(put the model in a dirpath by myself) to replace the original code(online way)?
I cannot find it. 
Thanks for your help.

/home/test/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py:348: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Downloading:   0%|                                                          | 510k/363M [05:00<328:10:23, 321B/s]("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
OSError: Can't load weights for 'facebook/wav2vec2-base'. Make sure that:

- 'facebook/wav2vec2-base' is a correct model identifier listed on 'https://huggingface.co/models'

**Comment by TParcollet** [comment]
Hi, you can use git lsf to clone the HuggingFace repository locally.

**Comment by curlneuron** [comment]
> 

thank for your advice. But my GPU is without internet connection. Now I have downloaded the files byhand. But still a new problem, like that:
#######
hparams = yaml.load(yaml_stream, Loader=yaml.Loader)
(Pdb) n
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/facebook/wav2vec2-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f174cd31f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> /home/test/anaconda3/lib/python3.8/site-packages/hyperpyyaml/core.py(182)load_hyperpyyaml()
########

Could you help to figure out how to revise the code ? 
If I change the path in hparams/train_with_wav2vec2.yaml of "wav2vec2_hub:"facebook/wav2vec2-base". thx.

**Comment by TParcollet** [comment]
Right, this is most likely because the folder is not found. SpeechBrain tests like this: test the folder given as a model_hub, if it exists just proceed, if it doesn't, it will try to download from HF (hence triggering an error as you don't have itnernet).

**Comment by TParcollet** [comment]
In particular, it will 1. test if the folder exists; 2. test if the folder contains a .bin (which is the original HuggingFace saving format for checkpoints). If one of these test fails, it will try to download it

**Comment by Adel-Moumen** [comment]
Hello, 

Is there any news about this issue, please? Thanks.

**Comment by Adel-Moumen** [comment]
Hello, 

There is no more activity on this issue, so I am closing it. 

If necessary, you can reopen this issue. Thanks :-)
