### ISSUE TITLE
ModuleDict Normalize Error

### ISSUE THREAD

**Issue by Dabuk** [speechbrain/speechbrain#1215]
I followed the speechbrain installation instructions as given in the documentation. I then downloaded the librispeech data.

Command used within speechbrain/recipes/LibriSpeech/ASR/transformer/- 
python train.py hparams/conformer_small.yaml

The data preparation proceeds normally. Then I see this error.

speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/transformer/7775
librispeech_prepare - Skipping preparation, completed in previous run.
speechbrain.pretrained.fetching - Fetch lm.ckpt: Using existing file/symlink in results/transformer/7775/save/lm.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in results/transformer/7775/save/tokenizer.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - 13.3M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                               | 0/17578 [00:00<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 445, in <module>
    asr_brain.fit(
  File "/home/ec2-user/efs/users/dkannang/software/speechbrain/speechbrain/core.py", line 1034, in fit
    loss = self.fit_batch(batch)
  File "train.py", line 152, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "train.py", line 67, in compute_forward
    feats = self.modules.normalize(feats, wav_lens, epoch=current_epoch)
  File "/home/ec2-user/anaconda3/envs/speechbrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleDict' object has no attribute 'normalize

pytorch version - 1.10.1+cu102

Is there something I'm missing ? or miss adding something in the config ?

**Comment by TParcollet** [comment]
This is an error, thanks, I'll fix it. The normalise must be given to the modules in yaml.

**Comment by Dabuk** [comment]
is the yaml file updated ?

**Comment by besacier** [comment]
hello @Dabuk actually you can modify the yaml file yourself this way:
modules:
    CNN: !ref <CNN>
    Transformer: !ref <Transformer>
    seq_lin: !ref <seq_lin>
    ctc_lin: !ref <ctc_lin>
    **normalize: !ref <normalize>   ####add this to fix error**
