### ISSUE TITLE
The use of the speechbrain for windows

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1216]
Hello:
I want to ask a question, can speechbrain be configured and run in the window environment?

**Comment by Gastron** [comment]
Most things should work, but some special care may be needed in the installation. Some users have also had issues with the symlinks in the [fetch](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.pretrained.fetching.html?highlight=fetch#speechbrain.pretrained.fetching.fetch) function, which requires running as administrator on Windows. Windows compatibility is not actively tested for.

https://speechbrain.readthedocs.io/en/latest/installation.html?highlight=windows#operating-systems
