### ISSUE TITLE
lm_corpus_path - unexpected keyword argument

### ISSUE THREAD

**Issue by vsokolov00** [speechbrain/speechbrain#1219]
Hello, I'm trying to start training LibriSpeech language model (transformer).
I manually downloaded the corpus and when I'm trying to run `train.py` on two GPUs:

```
CUDA_VISIBLE_DEVICES=0,1
python train.py hparams/transformer.yaml --data_parallel_backend
```
I'm getting the argument error:
https://paste-bin.xyz/29180
`TypeError: __init__() got an unexpected keyword argument 'lm_corpus_path'`

Is something wrong with the dataset loading script? I tried to find some info about how you should name the argument providing the corpus path but it was unsuccessful.

**Comment by jamfly** [comment]
Hi @vsokolov00,

I've opened a PR #1223, you can follow my modification to run this recipe.

**Comment by vsokolov00** [comment]
Thank you! @jamfly
