### ISSUE TITLE
VAD Speech boundaries fails using basic .wav file.

### ISSUE THREAD

**Issue by stobias123** [speechbrain/speechbrain#1220]
Following the examples, I am getting errors with just three lines :( 

The below yields a shape error.
```python
from speechbrain.pretrained import VAD
VAD = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")
audio_file = "20211229030727-000-vocals-split006.wav"
```
returns this error.
```
RuntimeError: Given normalized_shape=[40], expected input with shape [*, 40], but got input of size[160000, 1, 40, 2]
```

**Comment by stobias123** [comment]
Just had to reshape/resample 😬 
Found some helpful code [here](https://github.com/speechbrain/speechbrain/blob/a60c88461368beb86f642746e8465c7dd3459de5/recipes/LibriParty/VAD/commonlanguage_prepare.py#L59)

Working code looks like this... would be nice if I didn't have to resave, but i didn't see how that was immediately possible through the VAD api.
```python 
waveform, sample_rate = torchaudio.load(audio_file, normalize=True)
transform = transforms.Resample(sample_rate, VAD.sample_rate)
waveform = transform(waveform)
waveform = waveform[0].unsqueeze(0)
output_file = "foo.wav"
torchaudio.save("foo.wav", waveform, VAD.sample_rate)

boundaries = VAD.get_speech_segments(output_file)
```

**Comment by mravanelli** [comment]
Hi! It looks like your input audio has two channels, right? As far as I
remember the model expects just one. You can just read it and save it as
single channel audio.
