### ISSUE TITLE
How to use audios with multiple segments ?

### ISSUE THREAD

**Issue by Dabuk** [speechbrain/speechbrain#1225]
Is there a way to use audios with multiple segments similar to how kaldi uses a segments file with start and end timestamps  and a corresponding scp file ?

The json examples provided in the tutorials don't mention this.

Apologies for asking here, is there a google group for such questions ?

**Comment by Gastron** [comment]
If you use [speechbrain.dataio.dataio.read_audio](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.dataio.dataio.html#speechbrain.dataio.dataio.read_audio) for reading the audio files, that function already has this richer input style, where you can specify start and end (in samples).

So in the data manifest, this would look something like:
```json
{
    "utt1": {
        "wave": {
            "file": "{DATAROOT}/spk1.wav",
            "start": 0,
            "stop": 32000
        }
    "utt2: {
        "wave": {
            "file": "{DATAROOT}/spk1.wav",
            "start": 34000,
            "stop": 68000
        }
}
```

**Comment by Dabuk** [comment]
would the groundtruths file look the same ?

**Comment by Gastron** [comment]
Soryy, what do you mean by ground truth file?

**Comment by Dabuk** [comment]
like the asr groundtruth for each segment

**Comment by Gastron** [comment]
Yes.

Extended from above:
```json
{
    "utt1": {
        "wave": {
            "file": "{DATAROOT}/spk1.wav",
            "start": 0,
            "stop": 32000
        },
        "text": "More people have been to Moscow than I have",
    },
    "utt2": {
        "wave": {
            "file": "{DATAROOT}/spk1.wav",
            "start": 34000,
            "stop": 68000
        },
        "text": "I am speaking the second utterance here",
    },
}
```

**Comment by Dabuk** [comment]
got it. Thanks!

**Comment by Gastron** [comment]
There is no function that kind of integrates all of this, that might be nice actually. For now, you could quite easily write one for yourself following the read_audio implementation (which gets the sampling rate from reading the audio in - then just multiply the time in seconds by the sampling rate). In the medium term we've decided that read_audio should return the sampling rate, but that would break backwards compatibility, so we haven't immediately changed it.
