### ISSUE TITLE
How to use your pretrained aishell model in my local path?

### ISSUE THREAD

**Issue by JaheimLee** [speechbrain/speechbrain#1226]
Hi, I'm new to your speechbrain. I have downloaded your huggingface model to my local system path "/data/pretrained_models/asr-wav2vec2-transformer-aishell". But when I run:
```python
asr_model = EncoderDecoderASR.from_hparams(source="/data/pretrained_models/asr-wav2vec2-transformer-aishell")
```
The wav2vec2 model will be downloaded from facebook automatically. But it has already in 'asr-wav2vec2-transformer-aishell'. I noticed in your hyperparams.yaml file, the wav2vec2_hub is set as:
```python
wav2vec2_hub: facebook/wav2vec2-large-100k-voxpopuli
```
If I change it to my local path, it will raise:
```python
OSError: Can't load feature extractor for '/data/pretrained_models/asr-wav2vec2-transformer-aishell'. Make sure that:

- '/data/pretrained_models/asr-wav2vec2-transformer-aishell' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure '/data/pretrained_models/asr-wav2vec2-transformer-aishell' is not a path to a local directory with something else, in that case)

- or '/data/pretrained_models/asr-wav2vec2-transformer-aishell' is the correct path to a directory containing a preprocessor_config.json file
```
So, how can I totally use your pretrained model locally?

**Comment by TParcollet** [comment]
Hi, I did it and it worked what is your speechbrain version ?
<img width="1792" alt="Capture d’écran 2022-01-06 à 23 49 26" src="https://user-images.githubusercontent.com/11910731/148463285-e2152458-235b-461f-b644-32f0d5644d33.png">

**Comment by JaheimLee** [comment]
I use 'speechbrain==0.5.11', 'python==3.9.9' and 'pytorch==1.10.1'. 
Here are my local files: 
![8FF6FDA2-0418-46D7-BD8B-B69A145BEAB2](https://user-images.githubusercontent.com/18062264/148506966-adba36cc-52c3-4d7c-ac36-57436e18fdf9.png)
And here is my running result:
![07D84B09-C0F6-4B64-B702-C8354EBE0683](https://user-images.githubusercontent.com/18062264/148507178-94837363-aa15-4759-ab19-e33149a6daec.png)

**Comment by TParcollet** [comment]
Oops indeed I did not say that it was depending on another model from the yaml. You can modify the yaml (wav2vec2_hub) that you downloaded and give it the path  of the facebook model you downloaded somewhere :-) If you don't want to modify it you can pass overrides to the from_hparams function to dynamically change this parameter in the yaml :-)
