### ISSUE TITLE
Possible bug code utils/metric_stats.py

### ISSUE THREAD

**Issue by aluminumbox** [speechbrain/speechbrain#1233]
I am using BinaryMetricStats to calcuate eer/threshold, and got following error

```
  RuntimeError: Tensors must have same number of dimensions: got 1 and 2
```

It maybe caused by code https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/utils/metric_stats.py#L384
Here, self.labels == 0 gives all the index with 0 elements, but self.labels[self.labels == 0] only gives all the 0 elements
The correct code would be 
```
  positive_scores = self.scores[self.labels.nonzero(as_tuple=True)]
  negative_scores = self.scores[(self.labels == 0).nonzero(as_tuple=True)]
```
or a more simplified writing should be 
```
  positive_scores = self.scores[(self.labels==1).nonzero(as_tuple=True)]
  negative_scores = self.scores[(self.labels==0).nonzero(as_tuple=True)]
```

If this is indeed a mistake or a typo, hope you may find this issue helpful and fix it.
Many thanks!

**Comment by aluminumbox** [comment]
If this is need a bug, I have already created a PR for your approval

**Comment by mravanelli** [comment]
Hi @aluminumbox,
thank you for reporting. Fortunately, we are not using it in the EER computation for the voxceleb example (because use directly the [eer function](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/speaker_verification_cosine.py#L286)). I don't remember where we use the BinaryMetricStats  stats. @popcornell, it looks like you work on it. Could you please take a look?

**Comment by aluminumbox** [comment]
> Hi @aluminumbox, thank you for reporting. Fortunately, we are not using it in the EER computation for the voxceleb example (because use directly the [eer function](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/speaker_verification_cosine.py#L286)). I don't remember where we use the BinaryMetricStats stats. @popcornell, it looks like you work on it. Could you please take a look?

The bug occurs when using recipe/LibriParty/VAD. In train.py, you used threshold=0.5. So, BinaryMetricStats do not calculate threshold. But if you do not pass threshold, BinaryMetricStats would calculate threshold from postive_scores/negative_scores, then the bug would occur.

**Comment by popcornell** [comment]
Sorry for my late response been busy the last week. 
I am not familiar with the EER computation here but this definitely looks like a bug.

**Comment by aluminumbox** [comment]
Close this issue, for we are already working on it in a PR
