### ISSUE TITLE
VAD exporting model to onnx

### ISSUE THREAD

**Issue by seekingdeep** [speechbrain/speechbrain#1235]
Hi there, @mravanelli
In the case of cpu-only devices,

- How to export the VAD model to onnx.
- Why is the VAD model and the Voice_Activity_Detection.ipynb not included in the speechbrain repository, instead in an outside link
- Will speechbrain add auto-hyperparameter tuning and auto-postprocessing pipeline for VAD to generate the final speech timestamps.

waiting for your reply

**Comment by Franck-Dernoncourt** [comment]
Did you find a solution?
