### ISSUE TITLE
VAD documentation on training, inferencing, finetuning and hyperparameter tuning

### ISSUE THREAD

**Issue by seekingdeep** [speechbrain/speechbrain#1237]
Hi there, @mravanelli 

The `Voice_Activity_Detection.ipynb` doesn't go further into the technical matters,
such as:
- Training from scratch
- Finetuning an existing model
- Exporting to onnx
- Inferencing using onnx

**Comment by mravanelli** [comment]
Thank you  @seekingdeep, we can consider your request for the future!
