### ISSUE TITLE
How to explicitly clear gradients for pretrained model?

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1239]
Hi!

I am working with one of the pretrained models, [CRDD-RNNLM](https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech), while partially following one of your tutorials on pretrained models and fine-tuning: https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing

My current research work explores gradients properties to estimate the uncertainty of predictions. For that, I need to how a good control over gradients in the ASR models. The main thing that I struggle with right now is to clear gradients.

In this tutorial, you define `class EncDecFineTune(sb.Brain):` that is used for fine-tuning.
``` Python
from speechbrain.lobes.features import Fbank
import torch 

# Define fine-tuning procedure 
class EncDecFineTune(sb.Brain):

    def on_stage_start(self, stage, epoch):
        # enable grad for all modules we want to fine-tune
        if stage == sb.Stage.TRAIN:
            for module in [self.modules.enc, self.modules.emb, self.modules.dec, self.modules.seq_lin]:
                for p in module.parameters():
                    p.requires_grad = True
     
    def compute_forward(self, batch, stage):
        """Forward computations from the waveform batches to the output probabilities."""
        batch = batch.to(self.device)
        wavs, wav_lens = batch.signal
        tokens_bos, _ = batch.tokens_bos
        wavs, wav_lens = wavs.to(self.device), wav_lens.to(self.device)

        # Forward pass
        feats = self.modules.compute_features(wavs)
        feats = self.modules.normalize(feats, wav_lens)
        #feats.requires_grad = True
        x = self.modules.enc(feats)
        
        e_in = self.modules.emb(tokens_bos)  # y_in bos + tokens
        h, _ = self.modules.dec(e_in, x, wav_lens)

        # Output layer for seq2seq log-probabilities
        logits = self.modules.seq_lin(h)
        p_seq = self.hparams.log_softmax(logits)

        return p_seq, wav_lens

    def compute_objectives(self, predictions, batch, stage):
        """Computes the loss (CTC+NLL) given predictions and targets."""

        
        p_seq, wav_lens = predictions

        ids = batch.id
        tokens_eos, tokens_eos_lens = batch.tokens_eos
        tokens, tokens_lens = batch.tokens

        loss = self.hparams.seq_cost(
            p_seq, tokens_eos, tokens_eos_lens)
        

        return loss

    def fit_batch(self, batch):
        """Train the parameters given a single batch in input"""
        predictions = self.compute_forward(batch, sb.Stage.TRAIN)
        loss = self.compute_objectives(predictions, batch, sb.Stage.TRAIN)
        loss.backward()
        if self.check_gradients(loss):
            self.optimizer.step()
        self.optimizer.zero_grad()
        return loss.detach()
```
You can define brain class as per tutorial:
``` Python
brain = EncDecFineTune(modules, hparams=hparams, opt_class=lambda x: torch.optim.SGD(x, 1e-5))
brain.tokenizer = asr_model.tokenizer
```

And so my approach would be to just reverse engineer `fit_batch()` function and use: 
`brain.optimizer.zero_gradients()`

But it gives me `AttributeError: 'EncDecFineTune' object has no attribute 'optimizer'`

Any ideas how can I easily clear the gradients for this Brain class?

**Comment by Gastron** [comment]
Sounds like you're maybe not calling `fit()`, but rather just running a model. But `brain.optimizer` is created in the setup code in `fit()`: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.core.html?highlight=init_optimizer#speechbrain.core.Brain.init_optimizers

I'd suggest thinking if perhaps the Brain class is not a helpful abstraction here, and similarly, perhaps an optimizer is not a helpful abstraction either. Maybe you could clear the gradients manually, zero_grad() doesn't do all that much: https://pytorch.org/docs/stable/_modules/torch/optim/optimizer.html#Optimizer.zero_grad? But you can probably hack around and get this to work in many ways.

**Comment by KacperKubara** [comment]
Yes indeed I didn't use the fit() before running the model. Custom function for clearing the gradients sounds more promising thanks.
