### ISSUE TITLE
AMI speaker diarization dataset which to download

### ISSUE THREAD

**Issue by TianlongKong** [speechbrain/speechbrain#1246]
Hello, when i want to download at https://groups.inf.ed.ac.uk/ami/download/, I don't know how to download those as data, can you give some introduction?
![e704e506-a0ef-48cb-a1a8-b64f1d8dc6eb](https://user-images.githubusercontent.com/65606373/149096962-c2439d2b-a2aa-4cfd-be99-cc42d32e9a66.jpg)
![c0a69b43-4d5c-4479-8104-ba2a18a8a8f6](https://user-images.githubusercontent.com/65606373/149096982-2fb013d6-cc5d-4909-b057-e290b631298c.jpg)

Thanks a lot!

Which should I choose to download?

**Comment by mravanelli** [comment]
@nauman-daw could you please help @TianlongKong with that?

**Comment by nauman-daw** [comment]
Hi @TianlongKong ,

Downloading data is very simple. Detailed information about the dataset can be found in the `Documentation` section (https://groups.inf.ed.ac.uk/ami/corpus/).
 
You can download the `AMI_manual_annotations` and select the media streams you would like to download. 
**You can download all the meetings.** 

I think your confusion is on how to select the meetings ID (Signal)?? 
So basically, you can select one meeting and then hold shift key and then select another (and all) meeting ID.   In this way, you can select all the meetings.  After clicking on the "Get data size estimation..." button you will get a link to download. 
 
![Screenshot 2022-01-16 at 7 35 07 PM](https://user-images.githubusercontent.com/8971210/149684718-80c7ea7a-96ec-4dfe-a124-3b191eb11a27.png)


I have selected only 2 meeting IDs just for illustration purposes. Please select all of them.

**Comment by TianlongKong** [comment]
> Hi @TianlongKong ,
> 
> Downloading data is very simple. Detailed information about the dataset can be found in the `Documentation` section (https://groups.inf.ed.ac.uk/ami/corpus/).
> 
> You can download the `AMI_manual_annotations` and select the media streams you would like to download. **You can download all the meetings.**
> 
> I think your confusion is on how to select the meetings ID (Signal)?? So basically, you can select one meeting and then hold shift key and then select another (and all) meeting ID. In this way, you can select all the meetings. After clicking on the "Get data size estimation..." button you will get a link to download.
> 
> ![Screenshot 2022-01-16 at 7 35 07 PM](https://user-images.githubusercontent.com/8971210/149684718-80c7ea7a-96ec-4dfe-a124-3b191eb11a27.png)
> 
> I have selected only 2 meeting IDs just for illustration purposes. Please select all of them.

OK，fine，thanks, I got it.

**Comment by nauman-daw** [comment]
You're welcome!

**Comment by AMITKESARI2000** [comment]
I was somehow not able to download [AMI manual annotations v1.6.2](http://groups.inf.ed.ac.uk/ami/AMICorpusAnnotations/ami_public_manual_1.6.2.zip) by clicking on the link, but doing `wget http://groups.inf.ed.ac.uk/ami/AMICorpusAnnotations/ami_public_manual_1.6.2.zip` gave me the zip file i needed. 


![image](https://user-images.githubusercontent.com/66141447/177595588-a517cb6a-1bab-4f79-8f72-bccbc8cca546.png)

Hope this helps someone.
