### ISSUE TITLE
Distributed Data Parallel Error

### ISSUE THREAD

**Issue by Dabuk** [speechbrain/speechbrain#1250]
Does Distributed Data Parallel work only for certain combinations of  --nproc_per_node and batch size ?

on a 8 gpu server, it worked for setting --nproc_per_node=4 and batch_size=8.

Setting any higher batchsize or increasing  --nproc_per_node throws this error

Traceback (most recent call last):
  File "train_conf.py", line 413, in <module>
    asr_brain.fit(
  File "/home/dabuk/software/speechbrain/speechbrain/core.py", line 1075, in fit
    loss = self.evaluate_batch(batch, stage=Stage.VALID)
  File "train_conf.py", line 200, in evaluate_batch
    loss = self.compute_objectives(predictions, batch, stage=stage)
  File "train_conf.py", line 180, in compute_objectives
    target_words = [wrd.split(" ") for wrd in batch.wrd]

**Comment by TParcollet** [comment]
It should work for everything. What is the recipe here ? what is the actual error ? Cause we can't see it here

**Comment by Dabuk** [comment]
it was a minor bug on my end with a param name
