### ISSUE TITLE
Inference OOM for separation

### ISSUE THREAD

**Issue by vcuculo** [speechbrain/speechbrain#1255]
When doing speech separation with the WHAMR!16K model I always receive the following error when calling `separate_file` method:

`RuntimeError: CUDA out of memory. Tried to allocate 35.54 GiB (GPU 0; 23.88 GiB total capacity; 4.55 GiB already allocated; 15.00 GiB free; 8.11 GiB reserved in total by PyTorch)
`

the code used is very simple

```python
from speechbrain.pretrained import SepformerSeparation as separator
import torchaudio

model = separator.from_hparams(source="speechbrain/sepformer-whamr16k", savedir='pretrained_models/sepformer-whamr16k', run_opts={"device":"cuda"})

est_sources = model.separate_file(path='audio.wav') 
```

the audio is 16K single channel, 2 minutes and 16 seconds long,  the speechbrain version is 0.5.11.

**Comment by vcuculo** [comment]
Solved by adopting a shorter audio track (around 1 minute). Could be helpful to specify this in the documentation.

**Comment by Gastron** [comment]
With most models, the hardware (essentially VRAM) dictates how much audio can be processed at once.

These sorts of issues in general could be eased by some kind of chunked/streaming processing, but many models do not support that in any trivial way. That sort of processing is a topic of interest for SpeechBrain development for sure.

**Comment by vcuculo** [comment]
Cool, thank you for your answer. Audio stream or chunk processing will certainly make a difference.
