### ISSUE TITLE
Inference error: when set lm_weight: 0.50 in train.yaml

### ISSUE THREAD

**Issue by Yuanyuan-888** [speechbrain/speechbrain#1256]
Hi, 

I am training a Dutch ASR model using your code in speechbarin/templates/speech_recognition. I trained a Language model using the LM codes in templates, and also a Tokenizer.

When I test with my checkpoint, if I set lm_weight:0.50 in train.yaml, then there is a error: ValueError: too many values to unpack (expected 2)
![image](https://user-images.githubusercontent.com/67212823/149748718-f27a78e3-b386-4fcd-9d5b-448065621bf3.png)

But when I set lm_weight:0.00 in train.yaml, then it can work:
![image](https://user-images.githubusercontent.com/67212823/149749536-84c4619d-3c5b-437f-b931-d82940c16977.png)

Could you tell me what to do with this error?

Thanks in advance!

**Comment by TParcollet** [comment]
Hi does it happen as well with other values for this param ?

**Comment by Yuanyuan-888** [comment]
Thanks for your reply! Yes, other values like 0.1 and 0.2 does not work either. But now I am using the recipes of LibriSpeech, and I do not use language model. So there is no problem now.

**Comment by Adel-Moumen** [comment]
Hello @Yuanyuan-888, 

Is the issue still up? It doesn't seems to be related to your `lm_weight` value. Setting `lm_weight` to be `0.0` will remove the LM part from the beam search. So what it means is that there's an issue with the LM that you trained. Which model did you trained? What is your YAML config file for the training of your model?

**Comment by Adel-Moumen** [comment]
In the meantime, I'm closing this issue as it is a very old one (over 1 year). Please reopen a new issue and fill all the required informations (e.g., working example). 

Thanks and have a nice weekend. 
Adel
