### ISSUE TITLE
Is there any way for ASR recipes to calculate CER when doing testing?

### ISSUE THREAD

**Issue by MingjieChen** [speechbrain/speechbrain#1262]
Hello,

I am using LibriSpeech/ASR/transformer/train.py recipe. I just notice it only calculates WER when doing testing.
Is there any way to calculate character error rate (CER) as well?

Thanks

**Comment by TParcollet** [comment]
Hi yes, have a look at the CommonVoice recipes, they report CER. You must add a ErrorRateStats to your yaml and then call it at the evaluation :-)
