### ISSUE TITLE
[Question] What is the approximate training time for CommonVoice pretrained French models?

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1265]
Hi!

Question as above, I couldn't find information about it. Do you perhaps know approximate times for Transducer/Transformer/Wav2vec2.0+CTC given the listed GPUs?

https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR

**Comment by TParcollet** [comment]
Hi ! It highly depends on the version of CV. But all of them, with the listed GPUs are below 5 days of training. The longer being wav2vec models

**Comment by KacperKubara** [comment]
Ok great thanks!
