### ISSUE TITLE
# Convenience functions for querying the stat results  OSError: [WinError 1] Incorrect function

### ISSUE THREAD

**Issue by miglanianuragensai** [speechbrain/speechbrain#1266]
# Code

from speechbrain.pretrained import EncoderClassifier
from pathlib import Path
classifier = EncoderClassifier.from_hparams(source="speechbrain/lang-id-commonlanguage_ecapa", savedir="pretrained_models/lang-id-commonlanguage_ecapa")
out_prob, score, index, text_lab = classifier.classify_file('speechbrain/lang-id-commonlanguage_ecapa/example-it.wav')
print(text_lab)
# Error Could you throw some light into it 
I have the admin privileges.
i am running it on windows
\Anaconda3\lib\pathlib.py in symlink_to(self, target, target_is_directory)
   1389         if self._closed:
   1390             self._raise_closed()
-> 1391         self._accessor.symlink(target, self, target_is_directory)
   1392 
   1393     # Convenience functions for querying the stat results

OSError: [WinError 1] Incorrect function: 'C:\\Users\\amiglan\\.cache\\huggingface\\hub\\f1cb07494c3cf72d67202c925b11c8745b0cf964f3c0f1c969dd7f15fe3a69e5.6a5b020bdb255f49924cb6bf2d6be48181713f684c54ed6e64b01f203ca5292b' -> 'pretrained_models\\lang-id-commonlanguage_ecapa\\hyperparams.yaml'

**Comment by Gastron** [comment]
A quick google lead me here: https://github.com/flutter/flutter/issues/66795

I think this could be the issue: Windows does not support symlinking from a local drive to a network drive. Your HuggingFace cache seems to be on the local C: drive, is the destination (where you are working) on a network drive? You could maybe move HuggingFace cache to the same network drive, I guess that should fix it. It can be set with the HUGGINGFACE_HUB_CACHE environment variable.

**Comment by Adel-Moumen** [comment]
Hello @miglanianuragensai,

Any news about this issue, please? Thanks. :-)

**Comment by Adel-Moumen** [comment]
This issue seems to be inactive. Please re-open it if you are still facing the issue... thanks!
