### ISSUE TITLE
Shouldn't EncoderClassifier.classify_batch() operates on embeddings?

### ISSUE THREAD

**Issue by stachu86** [speechbrain/speechbrain#1273]
Shouldn't `classify_batch(self, wavs, wav_lens=None)` instead be `classify_batch(self, embeddings)`  in `EncoderClassifier`?

That would allow to use it together with `EncoderClassifier.encode_batch()`. It seems to makes more sense to me, also there is nothing to do with precomputed embeddings at the moment (because only waves are expected for classification).

**Comment by Gastron** [comment]
That could work as well, but changing this doesn't really provide anything new and would break backwards compatibility. I think these methods are meant as full self-contained pipelines. In some cases the embeddings themselves are the desired end product, in some cases the classification result is.
