### ISSUE TITLE
fix:  Speechbrain.core - Loss in nan.  <CommonLanguage recipe>

### ISSUE THREAD

**Issue by Thayabaran** [speechbrain/speechbrain#1276]
https://github.com/speechbrain/speechbrain/blob/9d56d50809d8745cc7dafa930aec554145be4028/speechbrain/nnet/losses.py#L925

A numerical error occurs if the Cosine value slightly crosses 1.0 and results in "nan" in further calculations.

Error:
```
ValueError: Loss is not finite and patience is exhausted. To debug, wrap 'fit()' with autograd's detect_anomaly()', e.g.
with torch.autograd.detec_anomaly():
     brain.fit(...)
```
Related issues reported: https://github.com/speechbrain/speechbrain/issues/1020#issue-1011886114

This can be prevented by adding a line of code:

line: 926  `cosine = torch.clamp(cosine, -1+1e-7, 1-1e-7) #You can modify the eps value according to your preference`

**Comment by mravanelli** [comment]
Hi,
thank you for noticing. Could you please ask for a PR with the fix?

Thank you!

Best,

Mirco

**Comment by Thayabaran** [comment]
Hi Micro,

I just created a PR with the fix. Please validate and accept.

1c824e96647babc206d8abdb0bdb13c4792d8d3e

Best,
Thaya
