### ISSUE TITLE
TIMIT Recipe Missing uppercase option

### ISSUE THREAD

**Issue by picheny-nyu** [speechbrain/speechbrain#1277]
in the seq2seq recipe for timit in train.py the keyword uppercase is missing so if the data is uppercase directory format it can't read it if uppercase is in the yaml file (which is where I assume it should be). It's a trivial change to add it....

**Comment by mravanelli** [comment]
Sure, we can add it (I took a note on that). Meanwhile, you can add this
option in train.py when calling timit prepare:

    run_on_main(
        prepare_timit,
        kwargs={
            "data_folder": hparams["data_folder"],
            "save_json_train": hparams["train_annotation"],
            "save_json_valid": hparams["valid_annotation"],
            "save_json_test": hparams["test_annotation"],
            "skip_prep": hparams["skip_prep"],
            *"uppercase": True*
        },
    )

**Comment by Adel-Moumen** [comment]
Hello, 

The issue has been solved with #1564, I'm closing this issue as a consequence.
