### ISSUE TITLE
Would it be possible to add inference from trained model to ASRfromScratch.ipynb?

### ISSUE THREAD

**Issue by catskillsresearch** [speechbrain/speechbrain#1282]
This Colab: 

https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing

has training from scratch but it doesn't supply a completely concrete example of inference from scratch using the just-trained model.   In Section 5 it shows concretely how to use a presupplied pretrained model.  It gives concepts on how to do the same with the just-trained model but it doesn't actually do it.  There is this discussion:

https://giters.com/speechbrain/speechbrain/issues/1017

and this CoLab:

https://colab.research.google.com/drive/1137MD-gAERblRAVhxDnwNXV3YyAiwtxV?usp=sharing

which give prescriptions on ways of doing inference but neither concretely applies the just-trained model to do inference by

* loading the newly trained from scratch model from .ckpt files (not using the trained model still in memory)
* applying the loaded model to do transcription

It would be really nice if you could update the first GitHub so it finishes up on the training and eval steps provided to provide an inference step using the stored just-trained model that operates on a .WAV file name to produce text.

It would also be great if the CoLabs were stored as .ipynb's in the GitHub in a tutorial section.

**Comment by TParcollet** [comment]
Hi, 

we might want to consider doing this, but we might not decide to go for it in the end. Why ? Simply because this would force us to have different tutorials to maintain on the same subject i.e. if the inference process changes one day, we will have to keep track of all the tutorials that must be changed. I took a look again at the inference tutorial. If you apply it like this to the template or ASR from scratch tutorial, it will work. You can either create a function that transcribes a dataset (dirty but good for prototyping) or simply use our EncoderDecoderASR interface. If your model is too custom, you can also develop your own interface.

Please try, and if you do not succeed, we can help with that.

**Comment by rachidio** [comment]
Hello
After training the ASRFromScratch I wanted also use the trained model for inference, at first I used the EncoderDecoderASR interface with a modified hyperparams.yaml (inspired by [HuggingFace](https://huggingface.co/speechbrain/asr-crdnn-commonvoice-fr/blob/main/hyperparams.yaml). Unfortunately, it didn't succeeded and the transcribe_file method always returns "TTTTTTT", when I debugged the code I found that the encoded_output is all "nan"s, then I dug deeper to find that the InputNormalization module returns tensor[0], the cause I found is that it only returns the expected values when self.training == True. If someone is interested and can help on this I can share more insights.

**Comment by catskillsresearch** [comment]
I stopped looking into SpeechBrain because the tutorials are on CoLab and code is on GitHub and models are on HuggingFace and the tutorials do not show how to train a model on a local PC with local GPU from scratch and do inference with the models on a single input.  A complete set of tutorials in Jupyter Notebooks in GitHub that run on a local PC GPU out of the box and are fully explicit about how to train and do inference using a local model trained from scratch are necessary to make SpeechBrain accessible.  By local I mean every step, VAD, LM, ASR and so on without reference to pretrained models.  Absent that I think SpeechBrain will not gain traction with anybody but the 3 or 4 people that wrote it.

**Comment by rachidio** [comment]
FYI, you can find more info on this tutorial about how to do inference with trained SpeechBrain model
[Inferring on your trained SpeechBrain model](https://colab.research.google.com/drive/1137MD-gAERblRAVhxDnwNXV3YyAiwtxV?usp=sharing)

Regards

**Comment by TParcollet** [comment]
Dear @catskillsresearch, thank you for this point of view. We would like to let you know that SpeechBrain already is widely used within the community and peoples are entirely satisfied with it, at least with respect to their needs. Now, if it is not your case, then I truly hope that you'll find what you need with all the other excellent existing toolkits such as ESPnet, NeMo, Fairseq, or now Coqui. SpeechBrain has already been used to teach DL + Speech to Master's students that successfully trained various models from scratch, locally. 

Your remarks will be discussed during our next meeting, however, personal considerations such as _I think SpeechBrain will not gain traction with anybody but the 3 or 4 people that wrote it._ aren't really useful to this discussion and almost insulting to the 79 current contributors.
