### ISSUE TITLE
Training Speformer WHAMR! Enhancement with Librispeech

### ISSUE THREAD

**Issue by ARKEYTECT** [speechbrain/speechbrain#1287]
Hi there:
    Is there a way to train Sepformer Enhancement recipe with LibriSpeech dataset? I appreciate the help.

**Comment by ycemsubakan** [comment]
Yes.. we do not currently have the enhancement recipe for Librispeech, but it should be easy to adapt the enhancement recipe on WHAMR to Librispeech.
