### ISSUE TITLE
The influence of "sorting" method. Could I use "random" sorting when training?

### ISSUE THREAD

**Issue by Yuanyuan-888** [speechbrain/speechbrain#1289]
Hi,

I have trained a seq2seq Dutch ASR model and I use recipes/LibriSpeech/ASR/seq2seq/train_BPE_1000.yaml

But I change the number of tokens from 1000 to 5000, and I also use ctc decode (0.40) when test.

The dataset I use contains about 530000 sentences (about 360hours), the smallest one is about 0.157s, the longest one is 20s. 

The problem is when I set sorting: ascending
![image](https://user-images.githubusercontent.com/67212823/152504235-52085b77-2a70-4696-826f-3af9fb6814e0.png)
it works.

But the same model and other settings, when I set sorting: random
![image](https://user-images.githubusercontent.com/67212823/152504440-43914220-9695-46e0-b684-e90c372407ab.png)

it failed.

Now I am training another ASR model for improving the performance, using  recipes/LibriSpeech/ASR/transfomer/transformer.yaml

The default setting in transformer.yaml : sorting : random

Does the way of sorting matter for this model(transfomer.yaml)? Should I change the sorting: random to sorting: ascending?

Thanks in advance!

**Comment by Yuanyuan-888** [comment]
I did not use any data augmentation and language model

**Comment by TParcollet** [comment]
Hey Hi, the effect of sorting is a bit mysterious. In practice, we initially avoided using it with transformers because attention was sensible to this increasing length issue ... The best solution, imho, to benefit both from a fast training and good performance, is to use dynamic batching instead.

**Comment by Yuanyuan-888** [comment]
Thanks! I got it. Now I will not use ascending sorting.
