### ISSUE TITLE
recipes/LibriSpeech/seq2seq/hparams/train_BPE_1000.yaml Why number_of_ctc_epochs is only 5?

### ISSUE THREAD

**Issue by Yuanyuan-888** [speechbrain/speechbrain#1297]
Hi, I have a question about the number_of_ctc_epochs.

In recipes/LibriSpeech/seq2seq/hparams/train_BPE_5000.yaml. number_of_ctc_epochs is set to 25.

But in recipes/LibriSpeech/seq2seq/hparams/train_BPE_1000.yaml. number of ctc_epochs is only 5.

If I use train_BPE_1000.yaml, but I also use ctc_decode, Could I increase the number of ctc epochs to improve the ASR performance?

**Comment by TParcollet** [comment]
Hi,

Honestly, there isn't any explanation outside of: This is what gave us the best results ... If you use CTC decode, I would indeed encourage you to have the same number of training steps for the CTC decoder and the attentional decoder.
