### ISSUE TITLE
[Question] Why use Adadelta in wav2vec 2.0 optimizer?

### ISSUE THREAD

**Issue by upskyy** [speechbrain/speechbrain#1299]
Thank you so much for sharing a good repo!

I have a question about wav2vec 2.0 optimizer.
[recipes/LibriSpeech/ASR/CTC/hparams/train_with_wav2vec.yaml#L124-L142](https://github.com/speechbrain/speechbrain/blob/9ebd14b57241f0a0dacbd680d34e0ba3fcd1c4d8/recipes/LibriSpeech/ASR/CTC/hparams/train_with_wav2vec.yaml#L124-L142)

As far as I know, this part seems different from the [paper](https://arxiv.org/pdf/2006.11477.pdf).  Is there a reason for using Adadelta?

Thanks in advance.

**Comment by TParcollet** [comment]
Hi! Well, the paper does not investigate optimizers as well, and we decided not to follow the paper and instead go for the best performing solution. We tried a couple of alternatives with SGD /Adam but this one was the best. Of course, you can just change it if you prefer using Adam or SGD :_)

**Comment by upskyy** [comment]
I was just curious 😄  Thank you for answer.
