### ISSUE TITLE
The meaning of the “nn” about speaker differentiation on AMI corpus in hparams/ecapa_tdnn.yaml

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1301]
Hello:
When I was doing the speaker differentiation on AMI corpus experiment, one parameter was unclear. cosis used to calculate the matrix similarity. What does nn mean here? Please elaborate. Thank you very much!
![image](https://user-images.githubusercontent.com/86965285/153391673-1c043045-2f74-445a-8658-901079fb91cc.png)

**Comment by mattnappo** [comment]
"nn" = nearest neighbors

**Comment by Adel-Moumen** [comment]
Hello, 

I will close this issue as It seems that @mattnappo answered your question. Feel free to reopen if needed. Thanks!
