### ISSUE TITLE
emotion detection...training loss not going below 0.69

### ISSUE THREAD

**Issue by muhammad-imaz** [speechbrain/speechbrain#1306]
I am am using speechbrain speaker-id model for emotion detection but my training loss is not going below 0.694. I am attaching train.yaml file. what can be done to improve the training loss. Is there any way i can add more layers to the model?
[train.yaml.txt](https://github.com/speechbrain/speechbrain/files/8097801/train.yaml.txt)

**Comment by TParcollet** [comment]
Hi, yes, you can simply modify the yaml corresponding to the embedding :-)

**Comment by muhammad-imaz** [comment]
Thanks for your response. How can i add more layers to it in the yaml?

**Comment by TParcollet** [comment]
Have a look at the embedding_model :-) It specifies the parameters. If you don't understand the paramters, please refer to custom_model.Xvector and see what they are.

**Comment by muhammad-imaz** [comment]
Alright thanks.
