### ISSUE TITLE
[Question] How to reproduce announced results ?

### ISSUE THREAD

**Issue by juliendespres** [speechbrain/speechbrain#1321]
Hi, 
I am a new SpeechBrain user, and I a try to understand how it works.

I have read all the documentation and tutorials, but I did not managed to find a recipe or some script lines to reproduce the speech transcription results claimed with the pre-trained models.
Is there for example a simple recipe to obtain the 9.96% announced with this French model https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr ?

This seems fundamental to me and it should be the first thing you want to do when you learn to use a new tool.

Thanks in advance.

**Comment by TParcollet** [comment]
Hi,

The recipes correspond to the numbers. So for this one: https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/CTC

**Comment by juliendespres** [comment]
Thank you for coming back to me.
Sorry, my  question was not clear.
What I would like to have is all the necessary elements to decode the test set to get a score of 9.96%. 
This implies having:
- the test set itself, with the exact list of audio segments 
- the script that automatically transcribes the test audio files
- the script that calculates the error rates.
I can't find the exact references of the test set, nor the tool to calculate the error rate, neither in https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/CTC, nor in https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr.

**Comment by TParcollet** [comment]
Alright I see.

Here: https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/CTC On the table, you'll see a model link to google drive. This link contains the experimental folder corresponding to this run. It contains all the files you are looking for. If you want to replicate the results, you just need to download this folder and call the train script with the save_folder pointing toward the downloaded folder. This will automatically jump to the test. You'll also need to download the corresponding CommonVoice dataset (the date of the release is given in the Table as new releases of CommonVoice are often created).

**Comment by juliendespres** [comment]
Thank you very much, this is exactly what I was looking for.

If I may suggest, you should add these explanations on the HuggingFace page of the pretrained models for future users who will ask the same question as me.

**Comment by juliendespres** [comment]
Sorry to bother you again.
Once I uploaded the folder you mentioned and configured everything correctly (I hope), I get an error that I have trouble interpreting and correcting:
`
> python train_with_wav2vec_pretrained.py pretrained_models/hyperparams.yaml
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: pretrained_models/results/cv_fr_seq2seq_ctc
common_voice_prepare - pretrained_models/results/cv_fr_seq2seq_ctc/save/train.csv already exists, skipping data preparation!
common_voice_prepare - pretrained_models/results/cv_fr_seq2seq_ctc/save/dev.csv already exists, skipping data preparation!
common_voice_prepare - pretrained_models/results/cv_fr_seq2seq_ctc/save/test.csv already exists, skipping data preparation!
speechbrain.tokenizers.SentencePiece - Tokenizer is already trained.
speechbrain.tokenizers.SentencePiece - ==== Loading Tokenizer ===
speechbrain.tokenizers.SentencePiece - Tokenizer path: pretrained_models/results/cv_fr_seq2seq_ctc/save/76_char.model
speechbrain.tokenizers.SentencePiece - Tokenizer vocab_size: 76
speechbrain.tokenizers.SentencePiece - Tokenizer type: char
speechbrain.core - Info: auto_mix_prec arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 318.7M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from pretrained_models/results/cv_fr_seq2seq_ctc/save/CKPT+2021-08-22+19-35-57+00
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/home/despres/source/speechbrain/recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec_pretrained.py", line 348, in <module>
    asr_brain.fit(
  File "/home/despres/source/speechbrain/speechbrain/core.py", line 1019, in fit
    self.on_fit_start()
  File "/home/despres/source/speechbrain/speechbrain/core.py", line 789, in on_fit_start
    self.checkpointer.recover_if_possible(
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 836, in recover_if_possible
    self.load_checkpoint(chosen_ckpt, device)
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 849, in load_checkpoint
    self._call_load_hooks(checkpoint, device)
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 984, in _call_load_hooks
    default_hook(obj, loadpath, end_of_epoch, device)
  File "/home/despres/source/speechbrain/speechbrain/core.py", line 1276, in _recover
    self.optimizer_step = save_dict["optimizer_step"]
KeyError: 'optimizer_step'
`

I tried to use the trainer provided in speechbrain/recipes/CommonVoice/ASR/seq2seq or the trainer provided in the google drive folder of the pretrained model, but the error is the same in both cases.

Have you a suggestion ?

**Comment by TParcollet** [comment]
Hi,

We identified the issue, thanks for pointing out this error. We will try to issue a clean fix asap.

**Comment by TParcollet** [comment]
A short-term solution for you is to downgrade the version of speechbrain to the exact version that was used at this time (it should also ensure perfect replication of the results).

**Comment by TParcollet** [comment]
Bug has been solved in the referenced PR. It is now on the develop branch. Please let us know if it solves your issue :-) 
``

**Comment by juliendespres** [comment]
I switched to the develop branch.
The bug is not the same, but it still bugs :
`speechbrain.tokenizers.SentencePiece - Tokenizer is already trained.
speechbrain.tokenizers.SentencePiece - ==== Loading Tokenizer ===
speechbrain.tokenizers.SentencePiece - Tokenizer path: pretrained_models/results/cv_fr_seq2seq_ctc/save/76_char.model
speechbrain.tokenizers.SentencePiece - Tokenizer vocab_size: 76
speechbrain.tokenizers.SentencePiece - Tokenizer type: char
speechbrain.core - Info: auto_mix_prec arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 318.7M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from pretrained_models/results/cv_fr_seq2seq_ctc/save/CKPT+2021-08-22+19-35-57+00
/home/despres/source/speechbrain/speechbrain/core.py:1282: UserWarning: 'optimizer_step' not found in ASR checkpoint. Using the saved 'step' value (BACKWARDS COMPATIBILITY)
  warnings.warn(MSG)
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 961, in _call_load_hooks
    loadpath = checkpoint.paramfiles[name]
KeyError: 'wav2vec_opt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/despres/source/speechbrain/recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec_pretrained.py", line 348, in <module>
    asr_brain.fit(
  File "/home/despres/source/speechbrain/speechbrain/core.py", line 1020, in fit
    self.on_fit_start()
  File "/home/despres/source/speechbrain/speechbrain/core.py", line 790, in on_fit_start
    self.checkpointer.recover_if_possible(
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 836, in recover_if_possible
    self.load_checkpoint(chosen_ckpt, device)
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 849, in load_checkpoint
    self._call_load_hooks(checkpoint, device)
  File "/home/despres/source/speechbrain/speechbrain/utils/checkpoints.py", line 973, in _call_load_hooks
    raise RuntimeError(MSG)
RuntimeError: Loading checkpoint from pretrained_models/results/cv_fr_seq2seq_ctc/save/CKPT+2021-08-22+19-35-57+00,                             but missing a load path for wav2vec_opt
`
Maybe it is a configuration problem ?

**Comment by TParcollet** [comment]
Hehe, no, I think that this is a google drive problem :-P (we will move from google drive soon, it sucks). Can you tell me if you can see a file named wav2vec_opt.ckpt in CKPT+2021-08-22+19-35-57+00/ ? If not, have a look at the folder on Google Drive, and you will see that this file exist. For some reasons, it is not included when you download the folder .........

**Comment by juliendespres** [comment]
Indeed, I was missing this file, it seems that it is a problem due to the fact that Google cannot run its antivirus on files that are too big.
The decoding works now perfectly and I was able to reproduce the result.
Thanks a lot.
