### ISSUE TITLE
The related reference of the transformer.yaml in /recipes/LibriSpeech/hparams/transformer.yaml

### ISSUE THREAD

**Issue by Yuanyuan-888** [speechbrain/speechbrain#1327]
Hi,

Could you please tell me the related reference paper of this transformer-based ASR model ( /recipes/LibriSpeech/hparams/transformer.yaml) ? 

Thanks in advance!

Yuanyuan

**Comment by Yuanyuan-888** [comment]
Is this paper : https://arxiv.org/abs/2001.02674?

**Comment by TParcollet** [comment]
There isn't really a reference paper I believe, It's inspired from ESPnet, but we changed few things. It's a vanilla transformer for ASR.

**Comment by Yuanyuan-888** [comment]
Got it! Thanks for you fast reply!
