### ISSUE TITLE
Adding external Language Model 

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1328]
Hi,
Is it possible to use an external language model with Speechbrain? I.e. there is an option to add LM to [beam search models](https://speechbrain.readthedocs.io/en/0.5.7/_modules/speechbrain/decoders/seq2seq.html#S2SRNNBeamSearchLM) but I was wondering if I could add any LM models here provided that they are based on PyTorch ModuleList?

If it is possible, are there any additional steps for implementation that I should keep in mind?

**Comment by TParcollet** [comment]
Hi, I guess that this is indeed feasible as long as it is a PyTorch ModuleList. You should have a look at the class available in speechbrain/decoders/seq2seq.py In practice, you will have to create a class to manage you custom module inheriting from one of the searcher.

**Comment by KacperKubara** [comment]
Ok thanks, also the tokens used for ASR and external LM have to be the same, right?
