### ISSUE TITLE
Problem While Running ASR/Transformers

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1350]
![image](https://user-images.githubusercontent.com/44331921/161213940-3f21d5e7-0001-4676-8c21-b008de1eab5b.png)

Hi, I am running the code from recipes/librispeech/ASR/transformers. And I dont understand what is the meaning of this code? this code I get from file train.py line 344. They trying to get the file from hparams["test_csv"] but hparams["test_csv"]  is only string to the file not contained any name of file, so what is the used of for loop function in that code? could someone explain it to me? Thank you

**Comment by TParcollet** [comment]
In the transformer.yaml, for instance, we can see the following code: 
`test_csv:
    - !ref <data_folder>/test-clean.csv
    - !ref <data_folder>/test-other.csv`

Hence, we are iterating over the different officiel test sets of Librispeech.

**Comment by fadlanhidayat** [comment]
owh, I think I didn't read it carefully. Thank you so much
