### ISSUE TITLE
How to undo generation of softlinks of wav files when using Speaker Verification model?

### ISSUE THREAD

**Issue by xiaofu2730** [speechbrain/speechbrain#1352]
Things just like this 
![image](https://user-images.githubusercontent.com/86200651/161357227-cf5693ff-ed2b-43f6-8406-a0d0e97fa189.png)

**Comment by anautsch** [comment]
Hi @Opsamcxf, please clarify what happened, so we know where to help (it must be obvious but we want to be on the right track). Which speaker verification model is used how, to result in which wav files, and which softlinks are created - and why do they need to be undone?

**Comment by Opsamcxf** [comment]
Thank you for your reply! The problem I mentioned is that speechbrain generates softlinks of relevant audio files when using ECAPA_TDNN model. I want to undo this function for its messing up my working directory. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andreas ***@***.***&gt;; 
发送时间: 2022年4月1日(星期五) 晚上9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [speechbrain/speechbrain] How to undo generation of softlinks of wav files when using Speaker Verification model? (Issue #1352)





 
Hi @Opsamcxf, please clarify what happened, so we know where to help (it must be obvious but we want to be on the right track). Which speaker verification model is used how, to result in which wav files, and which softlinks are created - and why do they need to be undone?

**Comment by Spectra456** [comment]
I also have this problem, it's annoying and load audio always using softlink which is linked to first version of the file.

**Comment by TParcollet** [comment]
Hi, we took note of this issue and are starting to discuss it internally :-) Thanks !
