### ISSUE TITLE
Error loading audio file

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1355]
Hi, I am running recipes/Librispeech/Transformer, I got error loading audio file. while loading train-clean dataset it works fine, but when loaded dev-clean datasets, the error happened, I think this was because the path of the file, but I already cek at the hparams transformers.yaml file the datafolder is : data/Librispeech, and the dev_splits : dev-clean, so I think the path to dev-clean dataset will refer to data/Librispeech/dev-clean, right? but it couldn't load the data like in that picture, do you know what I supposed to do? thank you

![image](https://user-images.githubusercontent.com/44331921/161469722-69a816f2-359c-4fd9-af08-0f5c4baa4dd5.png)

**Comment by suhasiniselvam** [comment]
Hi!

How did you corrected this error?

**Comment by TParcollet** [comment]
Hi, try not using a relative path ;) depending on where your script starts, it will fail.
