### ISSUE TITLE
Key Error Dynamic Batching

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1360]
I am running recipes/Librispeech/ASR/seq2seq using 5000.yaml file as the hparams. I got this key error like in this image below. Could somebody tell me what should I do to solve this error? I try to take a look at the hparams file there is no dynamic_batching hparams. 

![image](https://user-images.githubusercontent.com/44331921/162118709-3f57fab0-5c57-4c04-8414-97b09e73d289.png)

**Comment by TParcollet** [comment]
Then this is the error. This is due to a recent change in the recipe. If you simply add dynamic_batching: False in the hparams, it will work :-)
