### ISSUE TITLE
Training files missing for hugginface models

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1372]
Hi,

I've been using the CRDNN-based model from Huggingface: https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech/blob/main/hyperparams.yaml

I wanted to find a train.py in the LibriSpeech recipe, however it's not there: https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR. In the transducer folder, the hparams are not the same!

Where can I find it?

**Comment by TParcollet** [comment]
Hi, I am not sure to understand. What is the problem exactly ? The hparams of the seq2seq is available on ASR/seq2seq/hparams.

**Comment by KacperKubara** [comment]
Is https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech/blob/main/hyperparams.yaml equivalent to https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/seq2seq/hparams/train_BPE_1000.yaml?

They seem to have a lot of differences thus I am not sure if the training file in the Librispeech folder matches the Huggingface model.

**Comment by KacperKubara** [comment]
Issue related to the #1383 and will be tracked there. Closing but feel free to reopen if needed
