### ISSUE TITLE
Can not repeat WHAMandWHAMR/enhancement/sepformer-whamr-DM.yaml

### ISSUE THREAD

**Issue by poor1017** [speechbrain/speechbrain#1377]
Hi
After 200 epoches training, I can get only 2.20 PESQ, not 2.84 PESQ as README mentioned. Has any one can repeat this result?

**Comment by ycemsubakan** [comment]
Hi @poor1017 , sorry for my very late reply. Did you train with 16k, or 8k? The given results in the README are with 8k.

**Comment by ycemsubakan** [comment]
Ok, I am closing this issue since you are saying that you are able to get close to the one we obtained, when trying with 8k.
