### ISSUE TITLE
There is no such class as speechbrain.lobes.features.Fbanku

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1378]
Hi, I am trying to run recipes/LibriSpeech/ASR/Transducer. But I got this error:
ImportError: There is no such class as speechbrain.lobes.features.Fbanku

![image](https://user-images.githubusercontent.com/44331921/163750947-31384ad4-234b-469c-a7ec-3d3e867ef90b.png)
Do you have any idea hwo to solve this problem? thank you

**Comment by TParcollet** [comment]
Hi, just remove the u from Fbanku.
