### ISSUE TITLE
How to load exact pretrained model for the ready-to-use recipe?

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1383]
Hi!

I've been trying for a while to load the pretrained CRDNN model trained on the librispeech (https://huggingface.co/speechbrain/asr-crdnn-transformerlm-librispeech) to the exact training recipe (https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/seq2seq) with which it was trained upon.

The reason I want to load it to the recipe is to have a **full** control over the forward loop as I need to change it a bit for my research.

So I made some tweaks to train.py to make it work, mainly:
1) Inherit from pretrained interface, i.e
``` Python
class  ASR(Pretrained):
```

Instead of 
``` Python
class  ASR(sb.Brain):
```
2) Load the pretrained model:
``` Python
 brain = ASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech",
                                        savedir=hparams["model_dir"])
```

However, the module names seem to not match. When I print with  `brain.mods.keys()` I get:
``` Python
odict_keys(['normalizer', 'encoder', 'decoder', 'lm_model'])
```

If I try to run the model, I start getting AttributeErrors, because in forward() function of the model I cannot access directly layer names. You can see that layer names don't match those above odic_keys at all.
``` Python
    def compute_forward(self, batch, stage):
        """Forward computations from the waveform batches to the output probabilities."""
        batch = batch.to(self.device)
        wavs, wav_lens = batch.signal
        tokens_bos, _ = batch.tokens_bos
        wavs, wav_lens = wavs.to(self.device), wav_lens.to(self.device)

        # Add augmentation if specified
        if stage == sb.Stage.TRAIN:
            if hasattr(self.modules, "env_corrupt"):
                wavs_noise = self.modules.env_corrupt(wavs, wav_lens)
                wavs = torch.cat([wavs, wavs_noise], dim=0)
                wav_lens = torch.cat([wav_lens, wav_lens])
                tokens_bos = torch.cat([tokens_bos, tokens_bos], dim=0)

            if hasattr(self.hparams, "augmentation"):
                wavs = self.hparams.augmentation(wavs, wav_lens)

        # Forward pass
        feats = self.hparams.compute_features(wavs)
        feats = self.modules.normalize(feats, wav_lens)
        x = self.modules.enc(feats.detach())
        e_in = self.modules.emb(tokens_bos)  # y_in bos + tokens
        h, _ = self.modules.dec(e_in, x, wav_lens)

        # Output layer for seq2seq log-probabilities
        logits = self.modules.seq_lin(h)
        p_seq = self.hparams.log_softmax(logits)

        # Compute outputs
        if stage == sb.Stage.TRAIN:
            current_epoch = self.hparams.epoch_counter.current
            if current_epoch <= self.hparams.number_of_ctc_epochs:
                # Output layer for ctc log-probabilities
                logits = self.modules.ctc_lin(x)
                p_ctc = self.hparams.log_softmax(logits)
                return p_ctc, p_seq, wav_lens
            else:
                return p_seq, wav_lens
        else:
            if stage == sb.Stage.VALID:
                p_tokens, scores = self.hparams.valid_search(x, wav_lens)
            else:
                p_tokens, scores = self.hparams.test_search(x, wav_lens)
            return p_seq, wav_lens, p_tokens
```

For example: 
``` Python
AttributeError: 'function' object has no attribute 'normalize'
```

Is https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech/blob/main/hyperparams.yaml equivalent to https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/seq2seq/hparams/train_BPE_1000.yaml?They seem to have a lot of differences thus I am not sure if the training file in the Librispeech folder matches the Huggingface model.

It seems however that Hugginface and Librispeech recipes don't match??? Was the model on Hugginface trained with different architecture or hparams file? How can I make the above work?

**Comment by torphix** [comment]
If you find a solution please post a comment here as am looking for a solution too

**Comment by KacperKubara** [comment]
@TParcollet @mravanelli-mila  do you have any ideas perhaps?

**Comment by TParcollet** [comment]
Hi, so, models hosted on HF are cleaned version of the output dir of an experiment. This mean that we renamed the checkpoints and modified the yaml so it matches across all recipes of the same task and model (e.g. ASR with encoder-decoder). If you want to load this model, please go to the GDRIVE instead: https://drive.google.com/drive/folders/15uUZ21HYnw4KyOPW3tx8bLrS9RoBZfS7?usp=sharing . These models are a bit old, I hope they are still compatible with the SB version. If not, I will re-upload the models.

**Comment by KacperKubara** [comment]
Alright, thanks for the answer. I will try it out and let you know this week.

**Comment by torphix** [comment]
How would you load and fine tune a model that's hosted on hugging face, ie: the updated model

**Comment by TParcollet** [comment]
It depends what you mean by load. Is it to re-run the recipe but starting from this checkpoint or is it to use it as a pretrained model for something else ?

**Comment by KacperKubara** [comment]
@torphix there is a finetuning tutorial here: https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing

This, however, uses a pretrained interface that hides some of the model's functionality. 

With EncoderDecoderASR class which is an interface for pretrained models, you can transcribe, encode and decode audio. But if you need more control over the model, then from my understanding you need to download the model from Gdrive

**Comment by KacperKubara** [comment]
Hi @TParcollet , so I've tried loading the pretrained model using the code from the LibriSpeech recipe.

However, I am not sure if everything gets loaded correctly. As a sample test I wanted to do a single forward pass using compute_forward()  and then compute the predicted tokens and words using compute_objectives(). However, the `p_tokens, scores = self.hparams.valid_search(x, wav_lens)` seems to return empty tensor?

``` Python 
            if stage == sb.Stage.VALID:
                print(x)
                print(x.shape)
                print(wav_lens)

                p_tokens, scores = self.hparams.valid_search(x, wav_lens)
                
                print("VALID SEARCH")
                print(p_tokens)
                print(scores)
            else:
                print("TEST SEARCH")
                p_tokens, scores = self.hparams.test_search(x, wav_lens)
            return p_seq, wav_lens, p_tokens
```

And what I get in return is:
``` bash
tensor([[[ 0.0000e+00,  5.9659e-01,  0.0000e+00,  ...,  0.0000e+00,
          -1.6345e-02,  2.0907e+00],
         [ 2.4825e+00,  1.2240e+00, -1.2080e-03,  ...,  1.6541e-01,
          -7.9528e-03,  1.9069e+00],
         [ 8.8044e-01,  0.0000e+00,  1.1017e+00,  ..., -0.0000e+00,
          -7.2927e-03,  0.0000e+00],
         ...,
         [ 1.8690e+00, -2.1625e-02, -8.8127e-03,  ..., -6.2974e-03,
           0.0000e+00,  6.0728e-01],
         [ 1.6732e+00, -1.7115e-02, -1.5545e-02,  ..., -4.4341e-03,
           7.4131e-01, -2.0538e-03],
         [ 2.1198e+00, -2.4103e-02, -1.5082e-02,  ..., -2.0006e-03,
          -2.1062e-02,  1.2150e+00]]], grad_fn=<MulBackward0>)
torch.Size([1, 342, 512])
tensor([1.])
VALID SEARCH
[[]]
tensor([[-6.8312]])
```

**Comment by TParcollet** [comment]
That is weird, let me try. Note: you can do a recipe from the HF models as well, it's just a matter of loading the checkpoint on HF with a Pretrainer (Yaml) and making sure that the structure of the YAML code is the same than the checkpoint you want to load (i.e. same PyTorch class or composition of classes).

**Comment by KacperKubara** [comment]
Ok thanks, I just tried to verify if the checkpoint is loaded:
``` Python
    ckpt = asr_brain.checkpointer.recover_if_possible(
            device='cpu'
        )
    print("CHECKPOINT")
    print(ckpt)
    data = audio_pipeline(hparams)
```

I got this
``` bash
CHECKPOINT
None

```

**Comment by TParcollet** [comment]
the checkpoint should log you something somewhere about what he his trying to load (and potentially failing)

**Comment by KacperKubara** [comment]
Alright, it works now. I was running it from the wrong folder...

I will recreate this checkpoint loading in my experiments and will let you know if everything works! Thanks.

**Comment by TParcollet** [comment]
We really have to switch from GDrive to something else though ...

**Comment by TParcollet** [comment]
Ask no more: https://github.com/speechbrain/speechbrain/blob/cec3bc7f21361ad1123ee08dbca0129f60940dc6/recipes/VoxCeleb/SpeakerRec/hparams/verification_plda_xvector.yaml#L77

We have a Pretrainer that can load any arbitrary .ckpt as long as the YAML definition corresponding to this model is given :_)
