### ISSUE TITLE
speechbrain.nnet.losses.get_si_snr_with_pitwrapper parameter order is wrong when calling PitWrapper.forward

### ISSUE THREAD

**Issue by bookong22** [speechbrain/speechbrain#1388]
source, estimate_source == target, pred
Let us have a see: speechbrain/nnet/losses.py
Function get_si_snr_with_pitwrapper() line 710 calling: **pit_si_snr(source, estimate_source)**
But PitWrapper.**forward(self, preds, targets)**
So this is the first time the order is reversed about source, estimate_source/preds, targets
And then PitWrapper._opt_perm_loss() line 180 calling: loss_mat = self.**base_loss(pred, target)**
But def **cal_si_snr(source, estimate_source)**
So this is the second time the order is reversed about source, estimate_source/preds, targets
I think it's better to fix this two params order although this problem is like "negative * negative = positive"
In fact **cal_si_snr** get the right order after two times reversing("negative * negative = positive")

**Comment by anautsch** [comment]
Hi @bookong22, please provide a minimal example, so we can follow better along the lines of your problem. I get that your argument is on a general level yet an example would help to see where you are at. Is your remark concerning an algorithmic error or a design choice?

**Comment by Adel-Moumen** [comment]
Hello @bookong22,

Any news on this issue, please?
