### ISSUE TITLE
MetricGAN+ target metric

### ISSUE THREAD

**Issue by wooseok-shin** [speechbrain/speechbrain#1393]
The MetricGAN and MetricGAN+ papers used PESQ or STOI as the target metric for training.
In addition to PESQ and STOI, is it possible to use metrics such as CSIG, CBAK, and COVL be used as target metrics? (Possibility)

**Comment by wooseok-shin** [comment]
Yes, it may take some time, but I will PR when the work is done.

**Comment by Adel-Moumen** [comment]
Hello, 

It seems that the issue has been settled. Therefore, I am closing this issue. Feel free to reopen if needed.

Many thanks!
