### ISSUE TITLE
Very high WER on test-other for CRDNN librispeech model

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1395]
Hi,
So I was experimenting with the pretrained CRDNN model on the English librispeech data. While the performance is quite good on test-clean set, the performance on the noisy test-other set is very bad.

Looking at WER stats from the [pretrained model on gdrive](https://drive.google.com/drive/folders/1_WmSVYK4u9DHGoq7ukETLbS5H0wamwdH):

test-clean
``` txt
%WER 3.09 [ 1622 / 52576, 167 ins, 171 del, 1284 sub ]
%SER 33.66 [ 882 / 2620 ]
Scored 2620 sentences, 0 not present in hyp.
================================================================================
ALIGNMENTS

Format:
<utterance-id>, WER DETAILS
<eps> ; reference  ; on ; the ; first ;  line
  I   ;     S      ; =  ;  =  ;   S   ;   D  
 and  ; hypothesis ; on ; the ; third ; <eps>
================================================================================
672-122797-0033, %WER 0.00 [ 0 / 2, 0 ins, 0 del, 0 sub ]
A ; STORY
= ;   =  
A ; STORY
================================================================================
2094-142345-0041, %WER 0.00 [ 0 / 1, 0 ins, 0 del, 0 sub ]
DIRECTION
    =    
DIRECTION
================================================================================
2830-3980-0026, %WER 50.00 [ 1 / 2, 0 ins, 0 del, 1 sub ]
VERSE ; TWO
  S   ;  = 
FIRST ; TWO
================================================================================
237-134500-0025, %WER 50.00 [ 1 / 2, 0 ins, 0 del, 1 sub ]
OH ;  EMIL
=  ;   S  
OH ; AMIEL

(cut for brevity)
```

test-other
``` txt
%WER 219.23 [ 114 / 52, 64 ins, 0 del, 50 sub ]
%SER 100.00 [ 16 / 16 ]
Scored 16 sentences, 0 not present in hyp.

2414-128291-0020, %WER 700.00 [ 7 / 1, 6 ins, 0 del, 1 sub ]
WELL ; <eps> ; <eps> ; <eps> ; <eps>  ;  <eps>  ; <eps>
 S   ;   I   ;   I   ;   I   ;   I    ;    I    ;   I  
 I   ; DON'T ;  KNOW ;  WHAT ; YOU'RE ; TALKING ; ABOUT
================================================================================
7902-96592-0020, %WER 700.00 [ 7 / 1, 6 ins, 0 del, 1 sub ]
NONSENSE ; <eps> ; <eps> ; <eps> ; <eps>  ;  <eps>  ; <eps>
   S     ;   I   ;   I   ;   I   ;   I    ;    I    ;   I  
   I     ; DON'T ;  KNOW ;  WHAT ; YOU'RE ; TALKING ; ABOUT
================================================================================
8188-269290-0057, %WER 125.00 [ 5 / 4, 2 ins, 0 del, 3 sub ]
<eps> ; <eps>  ; I ;  WILL ;  TELL  ; HER
  I   ;   I    ; = ;   S   ;   S    ;  S 
 I'M  ; AFRAID ; I ; CAN'T ; AFFORD ;  IT
================================================================================
3538-142836-0023, %WER 600.00 [ 6 / 1, 5 ins, 0 del, 1 sub ]
ICES ; <eps>  ; <eps> ; <eps> ; <eps>  ; <eps>
 S   ;   I    ;   I   ;   I   ;   I    ;   I  
I'M  ; AFRAID ;   I   ; CAN'T ; AFFORD ;   IT 

(cut for brevity)
```

Why the performance is so bad on `test-other` set? What I also noticed is that for any other audio sets outside of `test-clean` performance is also really bad. For example, I've tried it for [SLR70](https://openslr.org/70/) and the average WER is also way above 100.

**Comment by TParcollet** [comment]
Hi, very interesting. We should maybe re-train a model from scratch. Maybe something weird happened during the training. We learned so many of them that I don't remember .. .

**Comment by KacperKubara** [comment]
Yeah, it seems something went wrong somewhere with training. It seems like it's quite heavily overfitting on the `clean` part of Librispeech

**Comment by KacperKubara** [comment]
But this model, on the other hand, seems to be okay: https://drive.google.com/drive/folders/1O_OfqnGc_ZoUyP4sDncKuIC9WOEJWajt

Which is the same architecture but with larger vocabulary. That is quite weird. Do you have any suspicions what could go wrong, @TParcollet? It is hard for me to figure it out since I didn't design this training procedure.

**Comment by TParcollet** [comment]
I trained the recipe again, I don't have this issue. I'll try to upload the model asap (now).

**Comment by KacperKubara** [comment]
Ok that's great, thanks!

**Comment by TParcollet** [comment]
Ok, I can't today because a problem occurred on our lab cluster ahah

**Comment by KacperKubara** [comment]
In the meantime, I am trying to run the CRDNN with 5000 characters: https://drive.google.com/drive/folders/1O_OfqnGc_ZoUyP4sDncKuIC9WOEJWajt

I changed all parameters so they match the new vocab size and added a correct path to tokenizer. However, I am getting an error: 
``` bash
Traceback (most recent call last):
  File "pipeline_correlation_scores.py", line 169, in <module>
    pipeline_uncertainty(hparams, test=hparams["test_mode"])
  File "pipeline_correlation_scores.py", line 62, in pipeline_uncertainty
    tokens_pred, words_pred = brain.compute_objectives(predictions, data, Stage.VALID, return_tokens=True)
  File "/home/kacper/Desktop/repos/uncertainty_baselines/uncertainty_baselines/model/crdnn_new.py", line 149, in compute_objectives
    predicted_words = [
  File "/home/kacper/Desktop/repos/uncertainty_baselines/uncertainty_baselines/model/crdnn_new.py", line 150, in <listcomp>
    self.tokenizer.decode_ids(utt_seq).split(" ")
  File "/home/kacper/miniconda3/envs/uncertain/lib/python3.8/site-packages/sentencepiece/__init__.py", line 174, in DecodeIdsWithCheck
    return _sentencepiece.SentencePieceProcessor_DecodeIdsWithCheck(self, ids)
IndexError: Out of range: piece id is out of range.
```

I printed out the vocab size and its 1000 instead of 5000. Do you know what might be an issue?

My tokenizer setup is more or less:
``` yaml
pretrained_lm_tokenizer_path: speechbrain/asr-crdnn-transformerlm-librispeech

...
tokenizer: !new:sentencepiece.SentencePieceProcessor
  model_file: !ref <save_folder>/5000_unigram.model
...
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <save_folder>
   loadables:
      lm: !ref <lm_model>
      tokenizer: !ref <tokenizer>
   paths:
      lm: !ref <save_folder>/lm.ckpt
      tokenizer: !ref <save_folder>/tokenizer.ckpt

```

**Comment by KacperKubara** [comment]
Alright I think that the Gdrive splits the folder into multiple zipfiles when downloading - I will check if that's the issue

**Comment by TParcollet** [comment]
GDrive is a freakin nightmare ... looking forward to switching from it (this summer).

**Comment by KacperKubara** [comment]
Thanks for adding the new model! Just saw that it has been updated (https://drive.google.com/drive/folders/19mAyMR1ITSb83Anhds4n694PLwKD47yf?usp=sharing). It looks good now. I will test it and if there will be some problems I will reopen the issue.
