### ISSUE TITLE
Is the KsponSpeech recipe sample Colab notebook working now?

### ISSUE THREAD

**Issue by jinyoungSeol** [speechbrain/speechbrain#1402]
I am trying to run this Collab notebook for using the pre-training model, but I get a size mismatch error.

=> Please, [see this Colab notebook](https://colab.research.google.com/drive/10N98aGoeLGfh6Hu6xOCH5BbjVTVYgCyB?usp=sharing) on using the pretrained model

![image](https://user-images.githubusercontent.com/58845926/169478738-ef8f4c51-ed87-462e-9573-21163709e7b8.png)

**Comment by jinyoungSeol** [comment]
I checked that it will be executed if I change the branch and install it, but I don't think the result is coming out properly.

before : !pip install git+https://github.com/speechbrain/speechbrain.git@develop
to : !pip install git+https://github.com/speechbrain/speechbrain.git

![image](https://user-images.githubusercontent.com/58845926/169483057-a8bf8c7a-0685-4e28-8734-dba9b5956f35.png)

**Comment by anautsch** [comment]
Hi @jinyoungSeol the pretrained model is provided by @ddwkim and @kimdwkimdw - the error is reproducible from:
https://huggingface.co/ddwkim/asr-conformer-transformerlm-ksponspeech

```python
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="ddwkim/asr-conformer-transformerlm-ksponspeech", savedir="pretrained_models/asr-conformer-transformerlm-ksponspeech")
```

**Comment by dave-rtzr** [comment]
Hi,

We will take a look at this issue and get back to this as soon as possible.

**Comment by dave-rtzr** [comment]
Hi, 

We were able to replicate the issue and current are tracking the cause.
It seems like there was a change in the model architecture following our contribution.
For the time being, please use
` !pip install git+https://github.com/speechbrain/speechbrain@c762107`

**Comment by jinyoungSeol** [comment]
Hi @dave-rtzr 

I solved the problem using
!pip install git+https://github.com/speechbrain/speechbrain@c762107
Thank you!
