### ISSUE TITLE
Problem of inference after training a wav2vec model: "pretrainer" key missing

### ISSUE THREAD

**Issue by Craya** [speechbrain/speechbrain#1407]
Dear Speechbrain community,

First of all, than for your tremedous job for the ASR community!

We are facing an issue of inference using a model we trained based on [French wav2vec HuggingFace model](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr). We basically followed the training process described [here](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr#training), and detailed here below:
- For the training:
```
cd speechbrain/recipes/CommonVoice/ASR/CTC/
python train_with_wav2vec.py hparams/train_fr_with_wav2vec.yaml --skip_prep=True --batch_size=12 --number_of_epochs=30 --data_folder="XXXX"  --output_folder="YYYY/" --data_parallel_backend
```
- Training ends successfully with amazing WER! Then for inference, we are using the classic code:
```
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="YYYY/", savedir="ZZZZ/",run_opts={"device":"cuda"})
print(asr_model.transcribe_file("test.wav"))
```
But EncoderDecoderASR.from_hparams fails and returns the following error:

```
  File "/usr/local/lib/python3.8/dist-packages/speechbrain/pretrained/interfaces.py", line 238, in from_hparams
    pretrainer = hparams["pretrainer"]
KeyError: 'pretrainer'
```

It is correct that there is no pretrainer attribute in the generated YYYY/hyperparams.yaml, which is consistent with the example given in the tutorial as [training results (models, logs, etc)](https://drive.google.com/drive/folders/1T9DfdZwcNI9CURxhLCi8GA5JVz8adiY8?usp=sharing).

We expected our fine-tuned model to be directly usable for inference, but it seems not (and we didn't succeed yet to implement pretrainer in YAML file, and thus benefit of our model!).

Many thanks for your support.

Fabien.

**Comment by anautsch** [comment]
Hi @Craya, Fabien, good to see the training recipe works out fine!
For using the pretrained model, another, related hparams file is needed that specifies what needs to be loaded.
Regarding wav2vec2, please take a look at this [training recipe for CommonVoice](https://raw.githubusercontent.com/speechbrain/speechbrain/develop/recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml) - in comparison to the [pretrained model yaml on HuggingFace](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr/blob/main/hyperparams.yaml). It might be sufficient to use an EncoderASR as pretrained interface.

**Comment by Craya** [comment]
Dear @anautsch , many thanks for your support,

Your proposal works fine for [French wav2vec HuggingFace model](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr)! For the community, here is what we did to move from training to inference: adapt the hparams.yaml from the [pretrained model yaml on HuggingFace](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr/blob/main/hyperparams.yaml) as such:
- change the token_type to char (as set by default in the recipe)
- change the wav2vec2/save_path to "save" (well, the folder you want)
- Create symbolic links for the pretrainer to find the ckeckpoints:
> - wav2vec2.ckpt -> save/CKPT+2022-06-01+02-06-58+00/wav2vec2.ckpt
> - asr.ckpt -> save/CKPT+2022-06-01+02-06-58+00/model.ckpt
> - tokenizer.ckpt -> save/76_char.model
- Use EncoderASR instead of EncoderDecoderASR

And inference works very well then!

However, this method seems not applicable for every recipes. Indeed, we are going to test and compare several recipes, in french and english, in order to determine the most adequate/performant for our specific noisy environment. Note that if you already have some ideas about that, feel free to help us in identifying the most suitable recipes by replying [our request for help  here](https://speechbrain.discourse.group/t/which-recipe-s-for-fine-tuning-with-noisy-dataset/619) ;-) .

Our next attempt was obviously to train an english ASR based on [English wav2vec HuggingFace model](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-en). Training ends once again with amazing WER, but we couldn't manage to perform inference applying the same procedure as here below.

During `EncoderDecoderASR.from_hparams` for the default model `speechbrain/asr-wav2vec2-commonvoice-en` and also for our fine-tuned model, we have first of all the following warning:
```
warnings.warn(
Some weights of the model checkpoint at facebook/wav2vec2-large-lv60 were not used when initializing Wav2Vec2Model: ['project_q.weight', 'quantizer.codevectors', 'quantizer.weight_proj.weight', 'quantizer.weight_proj.bias', 'project_hid.bias', 'project_q.bias', 'project_hid.weight']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

Then, hparams loading fails for our fine-tuned with 21 occurrence of the error:
```
loading from /zzz/asr.ckpt, the object could not use the parameters loaded with the key: XXX.bias (or XXX.weight)
```

When comparing hparams from training and from the huggingFace model, we identified several differences, but we can't either explain them, nor make them converge.

Any help would be appreciated to solve this new issue.

Hope to read you soon.

Thanks!

Fabien.

**Comment by TParcollet** [comment]
Hi @Craya, thank you for appreciating SpeechBrain, it's quite a lot of job and we are happy to see that the community enjoys it. We won't answer on Discourse, because we will soon close it ... (we will announce).

For the english: the warning is normal. Some parameters are not used because they are only useful for the pretraining. Could you please give the structure of the folder that you are using for inference (we all the checkpoint) as well as the yaml that you give to EncoderDecoderASR ? (note: for english, it's better to also use only EncoderASR and use CTC only, the WER is slightly worse, but the model is infinitely faster to infer).

**Comment by Craya** [comment]
Salut @TParcollet,

We are working on ASR for almost one year and a half and yes I confirm, your framework is the most powerful we ever trier so far! And cherry on the cake: the community is very active (except on Discourse but now I understand why :wink: ).

Based on your answer to use only EncoderASR, we have adapted the hparam file of the [French wav2vec HuggingFace model](https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr/blob/main/hyperparams.yaml) by comparing it with the [hparam file of the english training recipe](https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml), and it worked!

This is definitely one point to improve according to us: to easily build/reuse an hparam file for inference after training a model based on existing recipe.

As I said previously, we expect to test several recipes to find the most suitable for our noisy environment. Any advice to ease the inference for our next attempts? 

Bon week-end.

Fabien.

**Comment by TParcollet** [comment]
Hi and thanks!

If you already followed the tutorial on inference, you already know everything. Inference is definitely something we will improve, but at the same time, it is absolutely impossible to provide a tutorial for all case, because remember that our interfaces provide generic code that encapsulate an entire pipeline to be called with only one line. Hence, it's nearly impossible to have something that is generic enough without going full black-box. This means that the process of going from yaml training to yaml infer will always differ from one pipeline to an other if the models / LM / data prep / anything change. The best way is to look at the code of the interface, see what are the HPARAMS_NEEDED elements, then see in a HF repository how they look like in the yaml and finally transpose to your recipe.

**Comment by Craya** [comment]
Thanks @TParcollet for this complete feedback,

I understand and a agree the rationale that it is the drawback of the flexibility of your interface (that makes this framework so good!).  Maybe only one inference yaml per recipe you provide, adapated to the training yaml parameters, could help? Then if one change the recipe, the inference yaml is to be adapted of course.

Anyway, Thanks for your support, it works well now in our case, I thus close the ticket very satisfied!

Read you soon.

Fabien.
