### ISSUE TITLE
ValueError: length requested, but no length specified for ShardIterator

### ISSUE THREAD

**Issue by 980202006** [speechbrain/speechbrain#1409]
For bugs encountered in the test of vox107 training, you may need to add this line.   
hparams["val_dataloader_options"]["looped_nominal_epoch"] = (
            num_train_samples // hparams["val_dataloader_options"]["batch_size"]

**Comment by Adel-Moumen** [comment]
Hello @980202006,

If you found a bug please open a new issue following the issue template so that we have more information on the issue. 

Thanks!
