### ISSUE TITLE
Speaker Indentification from Scratch

### ISSUE THREAD

**Issue by EddyGiusepe** [speechbrain/speechbrain#1411]
Hello people!
First of  all, congratulations for this wonderful work.
I need your help, please.

Contextualizing here:
I'm studying the speakerIDfromScratch script (research work). I'm working with  audios of 15 seconds in duration (aprox.), railway environment, 48 speakers (number of classes),  etc. I'm, also, using ECAPA_TDNN, custom_model.classifier (I tried to used: ECAPA_TDNN.Classifier, but it gave me an error), etc.

So I have the following questions:

*  I thought of adding the following settings (add_rev; add_noise; add_rev_noise; etc.), would it be the correct way? 

![image](https://user-images.githubusercontent.com/69597971/170890505-14130781-e580-495b-83fc-afb86c0b07c5.png)

My current configuration is: [train.yaml](https://drive.google.com/file/d/1KYD6lXKlpoBcKlgypJnL_SB4gyewqDgo/view?usp=sharing).

*Nota:* I'm wanting to add the maximum number of parameters settings, in such a way that I can get a "real" road environment. It is important to say that I am training with audios (48 speakers, approx. 800 audios in total) that were recorded in a noise-free environment. What other parameters can I modify or add in train.yaml?

* How can I make the inference, to be able to identify the speaker who is speaking? with "real" audio? in which the AUDIO has 4 or more parts and in which there are different speakers in these parts (usually there are two speakers). 

Would I have to calculate the embeddings for each piece of audio?

Thank you very much!

**Comment by anautsch** [comment]
Hi @EddyGiusepe hope you are doing well. There are a lot of questions ;-)

> I thought of adding the following settings (add_rev; add_noise; add_rev_noise; etc.), would it be the correct way?

What is defined in the yaml files also needs to be picked up by your training recipe. Just declaring it in the yaml file might instantiate the objects `add_ref`, `add_noise`, and `add_rev_noise` - but that's not guaranteeing that they are used at all during training or in the way one intends for it. @mravanelli  wrote a [consistency testing PR](https://github.com/speechbrain/speechbrain/pull/1404), please take a look. It might help you in developing your recipe further. You'll see there in the [noise corruptions for the VAD recipe](https://github.com/speechbrain/speechbrain/pull/1404/files#diff-f95ef35a5c70ae9ba9017935680d953d8bc0831b8e88232970cf0c6b61503482), which are similar to yours, that we needed to take some definitions out of the yaml file since the training recipe did not pick up on them (the PR will be merged soon).

> I'm wanting to add the maximum number of parameters settings, in such a way that I can get a "real" road environment.

I don't have expertise for that maybe - @pplantinga ?

> How can I make the inference, to be able to identify the speaker who is speaking? with "real" audio? in which the AUDIO has 4 or more parts and in which there are different speakers in these parts (usually there are two speakers).

Sounds like a PR you could contribute ;-)
* What is a "part" for you?
* For multiple speakers in one audio, please look into "speaker diarization" - usually people fix the number of speakers, which is a way to adapt to their datasets - depends on the use case scenaria
* "Real audio" as in non-lab audio?

> Would I have to calculate the embeddings for each piece of audio?

By rewriting your script in a way that does so. The questions you raise have been part of ongoing research discussions - there are some fully online research archives like this [one](https://www.isca-speech.org/archive/) - Interspeech proceedings are a good entry point for study.

@underdogliu what's your take?

**Comment by EddyGiusepe** [comment]
Thank you very much @anautsch for starting this discussion, I hope to continue discussing with you and others researchers. 

Then:
* When you speak of "training recipe" you are referring to the "train.py" (meu [train.py](https://drive.google.com/file/d/1F0z3uLWp1yCMxnhAPl38kwldkTP0x2jE/view?usp=sharing)) file, right? 

* Thanks for these links (Thanks, also, @mravanelli): [consistency testing PR](https://github.com/speechbrain/speechbrain/pull/1404) and [noise corruptions for the VAD recipe](https://github.com/speechbrain/speechbrain/pull/1404/files#diff-f95ef35a5c70ae9ba9017935680d953d8bc0831b8e88232970cf0c6b61503482). I've already started reading these links and I'm looking at how I can use this for my task.  

* If I evolve, develop, in this challenge I would like to contribute (it's an honor).

* "part" --> mean, that in each audio I always have excerpts (or I called: "parts") of speeches which correspond to different speakers (usually in these audios I have two speakers), did you understand?   

I commented this because when I go to pass the audio to detect the speaker... I will pass a raw audio (that is, an audio where there will be two speakers, with noise, etc. Remembering here: I trained until only with audios where there is only one speaker with their respective identities, did you understand?

*  I thought about DIARIZATION, to separate the audio excerpts (or calculate the embeddings of each audio excerpt or excerpt that will contain only one speaker)... I'm still not quite sure how to do that :( .


* Real áudio --> it is the same audio that is used in the work field (in the highway field). With noise, speakers speaking fast, slow, with echo ( reverberation), etc.

* I will see and study, too, this [link](https://www.isca-speech.org/archive/).

*I'll be back soon with some improvements, etc.*


Thank you very much!!

**Comment by EddyGiusepe** [comment]
Thank you, @anautsch, yes yes ... I'm very happy to be learning this line of research.

Then:
* With respect to those recipe files, it was clear yes. Thank you!

* I know where these files are located for consistency. But unfortunately, I'm not able to run the consistency test (I'm working on Google Colab: [consistency_test_file](https://colab.research.google.com/drive/1CVfoy5ihFrz3acGOOaExlZ5bj8DJsG_l?usp=sharing)) ... could you give me a suggestion here?, please!

* Yes.  So, I'm training with 48 speakers, of each speaker I have 20 audios, each audio is 13 seconds aprox. (Also, I know their identities).  You can send these books to me ... I will try to study in parallel. Thank you!

*  Good questions! ... I still have doubts about it. In principle I know that for a raw audio I should have the separate parts (or the embeddings) to later compare each "part" with the Database that I have already "trained" (maybe I can apply COSINE SIMILARITY ) . I need to study more about this part. For starters I'm focussing on this [script](https://colab.research.google.com/drive/1UwisnAjr8nQF3UnrkIJ4abBMAWzVwBMh?usp=sharing). Since this script has an INFERENCE part ("Use the EncoderClassifier interface on your model").   In this part, also, is possible to calculate the EMBEDDINGS ... so I thought of comparing the embeddings of the new audios with my Database, already trained.

* So, I have a Database yes. But they are very few (I will try to collect more Data). There is no Data related to my task (railway environment is very complex). Due to this difficulty (few Data, noisy environment, distorted speech, etc) I am trying use AUGMENTATION (I'm using the model pre-treined with VoxCeleb). 

Aqui a minha configuração: [train.yaml](https://drive.google.com/file/d/12TXXA1fhIsXB34jdYYU3A-kkk_NjiSm4/view?usp=sharing) . If you can give me some suggestions, I would appreciate it! 


** In that train.yaml file, I am still thinking how to use the ECAPA_TDNN classifier. 

I'm making little progress little by little :)



Thank you very much!!!

**Comment by EddyGiusepe** [comment]
*I closed unintentionally* :(

Hello @underdogliu!!!
Quiet.

* I would like to be able to discuss more how you make the inference. I will look for this author *Kaldi* to know more about this part. So, in this first part I'm using the SpeechBrain script to make some inferences. I'm still training the script with my Data. Obviously, this inference I make is only with an audio that has one speaker (I'm still studying how to make the inference for a real audio). I would like to discuss this part with you to see how you make this inference. Thank you!


*  Yes yes ... this issue of Embeddings is, also, on my mind. 



Thank you so much, @underdogliu !

**Comment by EddyGiusepe** [comment]
Hello @anautsch!
* I will do this consistency test.

* I'll look for those books yes, thank you!

*  I have little data. But, I'm already trying to get more Data for my training. I'm applying Augmentation and I'm also adding noise, velocity, revorbation, etc. I'm currently training the Network and my test_erro~5%, but when making the inference... the network makes a lot of mistakes.
My train.yaml (I think there is another way to do these settings):
![image](https://user-images.githubusercontent.com/69597971/171750298-36175cff-602f-4e59-9d89-51f4c888855a.png)

Yes, the numbers of speakers is two in each piece of áudio, I know the identities at the time of Training (each one has an ID) ... Yes, I thought of using a Pre-trained model. If you have a study link, please send it to me. I will be careful with the question of: "Data sharing".

* Alright, let's go on this challenge.

* Are you on our slack? --> No, not yet.


Thank you so much!

**Comment by anautsch** [comment]
Make sure to use the `env_corrupt` in the train.py file. Check for a set of audios which are the noise effects you'd desire to have. Look at the training data of a pretrained model. Which data augmentation would be necessary to transform them into your environment? Maybe it is enough to retrain a pretrained model based on in-domain data augmentation. You won't need to corrupt audios that are already in-domain (unless to see if there's some performance gain because of a nature of the data your model is not encompassing by its design).

**Comment by EddyGiusepe** [comment]
Hello @anautsch !
Sorry for answer now. I'm still focused on training SpeakerIDfromScratch.

* Yes, I'm taking your observations into account. I'm using a pre-training model since I have little Data.

![image](https://user-images.githubusercontent.com/69597971/172956105-81ac6e26-c9b3-4d33-9ac2-424058dcb793.png)
![image](https://user-images.githubusercontent.com/69597971/172958115-412fa553-e189-4aaa-9504-6044bfc2d8fa.png)

* I have a question:  How can I calculate the ROC-AUC Curve ou the Confusion Matrix?  I think the ROC curve is not possible, right? ... because I have 48 classes (speakers), right?  Is there any script where I can add or modify the code to get this? 


Thank you very much!
