### ISSUE TITLE
IEMOCAP emotion recognition results

### ISSUE THREAD

**Issue by WillQuCD** [speechbrain/speechbrain#1415]
Hi Guys,

thank you very much for the contribution and the great project! 

I have one question regarding the speech emotion recognition (SER) results in table 1 of paper
https://arxiv.org/pdf/2111.02735.pdf

![image](https://user-images.githubusercontent.com/28244700/170935124-646cca07-49fe-40d9-af69-13c27ce63b70.png)

Frozen-w2v-base[15] reports their results in the speaker-independent settings (no speaker overlap between training and test sets) with 5-fold cross validation;
(see the dataset preparation codes: https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/emotion/IEMOCAP_preprocess.py)

Attention Pooling[32] reports their results in a 10-fold cross-validation using a leave-one-out strategy in a speaker-independent setting as well. (see the paper https://kar.kent.ac.uk/67453/1/Atten_pooling_v4.pdf)

However, in the train.json and test.json in the following link, I found maybe your results are performed with speaker-dependent (speaker overlap between training and test sets) cases?
https://drive.google.com/drive/folders/1TslAr9NQ_nAjLeyoJ-f6xabk7n8C-HO8

Please feel free to correct me if I am wrong.

Thank you again for the great project!

**Comment by WillQuCD** [comment]
Hi @BenoitWang , 
thank you very much for the quick reply. 

Yes, IEMOCAP is a very small dataset. The leave-two-session-out strategy will loss a lot of data. 

That would be great to build a standard benmark for the community by this excellent project.

thank you again for your contribution!

**Comment by Adel-Moumen** [comment]
Hello,

It seems that everything is settled now. Therefore, I am closing this issue. Feel free to reopen if needed! Thanks.
