### ISSUE TITLE
Building ssl models in speechbrain

### ISSUE THREAD

**Issue by pratikkumar018** [speechbrain/speechbrain#1424]
HI Team,
I am trying to build ssl models like wav2vec2, wavlm, hubert in speechbrain from scratch for a different langauge. I tried looking for but couldnt find any leads. Can anyone point out how to build these models.

**Comment by pratikkumar018** [comment]
Thanks for the info.

**Comment by fedecosta** [comment]
Hi team!

Do you have a recipe to pre-train wavLM?
I found a wav2vec2 recipe [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/self-supervised-learning/wav2vec2) but not a wavLM one.

Thanks in advance!!!

**Comment by asumagic** [comment]
> Hi team!
> 
> Do you have a recipe to pre-train wavLM? I found a wav2vec2 recipe [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/self-supervised-learning/wav2vec2) but not a wavLM one.
> 
> Thanks in advance!!!

Not that I can find, but I am not entirely sure.
