### ISSUE TITLE
Data keys are static by default and it can't be changed with `dynamic_items`

### ISSUE THREAD

**Issue by grazder** [speechbrain/speechbrain#1427]
Hi! I noticed strange behavior of `DynamicItemDataset`.

# Problem 👩‍⚕️

My dataset looks like this:

```
{
    "my_audio.wav": {
        "audio_path": "my_audio.wav",
        "ref": "example of speech",
        "length": 5
    }
}
```

I put it into `DynamicItemDataset` using some both audio and text pipelines which I put into `dynamic_items`. 

But in text pipeline I'm doing text preprocessing and it looks like this:

```
@sb.utils.data_pipeline.takes("ref")
@sb.utils.data_pipeline.provides("ref")
def text_pipeline(ref):
    ref = hparams["preprocessor"].process(ref)
    yield ref
```

Main thing here that my input and output keys are the same. So I want my dataset to have `ref` key both in input and in ouput.

So the problem that I found that if key is in data then it will be considered as static item even if it will be in dynamic items.

Here is all data keys are considered as static keys. So this code don't check if this key is in dynamic_items.

https://github.com/speechbrain/speechbrain/blob/d9c37f4274a383107f972329a8cbe1b2d77a163a/speechbrain/dataio/dataset.py#L151

And after that here. All data keys are considered static by default and no preprocessing occurs.

https://github.com/speechbrain/speechbrain/blob/d9c37f4274a383107f972329a8cbe1b2d77a163a/speechbrain/utils/data_pipeline.py#L496

# Workaround

Because of this issue I have to do some weirds workarounds like changing output key or doing preprocessing somewhere else. And I think that it's not ok.

**Comment by Gastron** [comment]
The items' keys are meant to be unique. You should not both take and provide the same key. It might be cleanest to just change the key of your DynamicItem "ref". If you absolutely need the output to be called "ref", you can use a mapping in the output, see:
https://github.com/speechbrain/speechbrain/blob/d9c37f4274a383107f972329a8cbe1b2d77a163a/speechbrain/dataio/dataset.py#L195-L210

So for example, you can do something like:
```python
@sb.utils.data_pipeline.takes("ref")
@sb.utils.data_pipeline.provides("ref_processed")
def text_pipeline(ref):
    ref = hparams["preprocessor"].process(ref)
    yield ref

dataset.add_dynamic_item(text_pipeline)
dataset.set_output_keys(
    {"id": "id",
     "audio": "audio", 
     "ref": "ref_processed"}  # <- remap to "ref"
)

```




Perhaps we should implement some checks for duplicate keys, with appropriate error messages.

**Comment by grazder** [comment]
Yeah thanks, it wasn't clean until i started to dig deeper. So I think warnings or errors are super necessary here

**Comment by anautsch** [comment]
@grazder noted your poke on warnings & errors -> agreeing there.
_Hope we can get to work more on comfort-tools after the next 2+ major changes (or earlier)._

Closing this issue as it seems "solved". Please feel free to reopen :)

If you like to contribute a PR on adequate warnings based on this issues, please go for it (we can continue discussing there).
