### ISSUE TITLE
InputNormalization is not cuda compatible?

### ISSUE THREAD

**Issue by BuxianChen** [speechbrain/speechbrain#1434]
The code below will enter into `speechbrain.processing.features.py:InputNormalization`
```
from speechbrain.pretrained import SpeakerRecognition
import librosa
path = "source1hat.wav"
encoder = SpeakerRecognition.from_hparams(source="spkrec-ecapa-voxceleb")
device="cuda:0"
encoder.to(device)
signal, fs = librosa.load(path, sr=16000)
inp = torch.tensor(signal).to(device).unsqueeze(0)
emb = encoder.encode_batch(inp, normalize=True)
```
and get the following error
```
*** RuntimeError: Expected all tensors to be on same device, but found at least two devices, cuda:0 and cpu!
```

Then, I find the code in `InputNormalization` has the following, which is not cuda compatible
```python
self.glob_mean = torch.tensor([0])
self.glob_std = torch.tensor([0])
```

**Comment by anautsch** [comment]
Hi @BuxianChen 
it might be because of librosa to load audios.
I created a pretrained model from `encoder = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb")` 

then `signal = encoder.load_audio("tests/samples/ASR/spk1_snt1.wav")`  

returns the signal as a tensor that is on the same device as the model.

Does this help with this part of your error message?
> but found at least two devices, cuda:0 and cpu

**Comment by BuxianChen** [comment]
Maybe the snippet code is not clean enough, but the key point here is `encoder.encode_batch(inp, normalize=True)`, the `normalize` set to `True` will cause the problem. The cleaner code as following, which get the same error
> but found at least two devices, cuda:0 and cpu
```
from speechbrain.pretrained import SpeakerRecognition
path = "source1hat.wav"
encoder = SpeakerRecognition.from_hparams(source="spkrec-ecapa-voxceleb")
device="cuda:0"
encoder.to(device)
inp = encoder.load(path)
emb = encoder.encode_batch(inp, normalize=True)
```

**Comment by Adel-Moumen** [comment]
Hello @BuxianChen,

You should have passed in argument of `SpeakerRecognition.from_hparams(source="spkrec-ecapa-voxceleb")` the device like that:
```
device="cuda:0"
encoder = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", run_opts={"device": device})
```

Now everything works as expected!

The full working example bellow:
```
from speechbrain.pretrained import SpeakerRecognition
path = "source1hat.wav"
device="cuda:0"
encoder = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", run_opts={"device": device})

inp = encoder.load_audio(path)
emb = encoder.encode_batch(inp, normalize=True)
```

Best.
