### ISSUE TITLE
Accuracy Issue with DDP Training

### ISSUE THREAD

**Issue by poor1017** [speechbrain/speechbrain#1436]
Hi

I trained `recipes/VoxLingua107/lang_id` with DDP, the train_log.txt is pretty good:
```
epoch: 6, lr: 8.85e-04 - train loss: 7.24e-02 - valid loss: 8.24e-02, valid ErrorRate: 2.50e-02
epoch: 7, lr: 8.62e-04 - train loss: 6.72e-02 - valid loss: 1.13e-01, valid ErrorRate: 6.25e-02
epoch: 8, lr: 8.38e-04 - train loss: 6.38e-02 - valid loss: 8.89e-02, valid ErrorRate: 3.75e-02
epoch: 9, lr: 8.15e-04 - train loss: 6.24e-02 - valid loss: 1.47e-01, valid ErrorRate: 3.75e-02
epoch: 10, lr: 7.92e-04 - train loss: 6.09e-02 - valid loss: 1.60e-01, valid ErrorRate: 6.25e-02
epoch: 11, lr: 7.69e-04 - train loss: 5.76e-02 - valid loss: 1.53e-01, valid ErrorRate: 3.75e-02
epoch: 12, lr: 7.46e-04 - train loss: 5.63e-02 - valid loss: 1.38e-01, valid ErrorRate: 3.75e-02
epoch: 13, lr: 7.23e-04 - train loss: 5.51e-02 - valid loss: 1.97e-01, valid ErrorRate: 6.25e-02
```
But, I got a totally wrong model, I used the model do a test, errRate is 80%.

I trained the same recipe without DDP (Single GPU), and did the same test, I got errRate 4%.

Do I miss some key steps?

Thank you!

**Comment by TParcollet** [comment]
Are the training logs equivalent from DDP to not DDP ?

**Comment by poor1017** [comment]
@TParcollet Thank you for your reply.
A little different, DDP has a lower loss totally. I train my model with DDP (4 GPUs).

Errr.... I have found the reason: When I save the model, I forgot to add .module, it seems that DDP will encapsulate the model with .module.
