### ISSUE TITLE
Error while enhancing MetricGAN+ Using Pretrained Model

### ISSUE THREAD

**Issue by ChandanaJonna** [speechbrain/speechbrain#1440]
Hi,

I am trying to evaluate my samples with MetricGAN+ using the Pretrained Model(model.ckpt) available in "https://drive.google.com/drive/folders/1IV3ohFracK0zLH-ZGb3LTas-l3ZDFDPW?usp=sharing".

And, I used the easy-inference function on HuggingFace from this link "https://huggingface.co/speechbrain/metricgan-plus-voicebank". While evaluation "enhanced = enhance_model.enhance_file(noisy)" I got below error.

![image](https://user-images.githubusercontent.com/101628409/173776070-39c96a72-1c02-4f2a-92f1-5b24f7ecc536.png)

If anyone tried evaluation using a pre-trained model or come across this error. please provide your comments. Thanks in advance.

**Comment by TParcollet** [comment]
@mravanelli @pplantinga any idea ? This is not the first time I come across this error.

**Comment by ChandanaJonna** [comment]
this is how I am using the code.
![image](https://user-images.githubusercontent.com/101628409/173784573-ecd8431e-e238-4592-ba56-7d76082b910f.png)

Got error in enhance_batch function interface.py file
![image](https://user-images.githubusercontent.com/101628409/173784991-8316c7a9-0b67-44ac-9013-041dec82528a.png)
