### ISSUE TITLE
Fusion of LM and ASR score in decoders

### ISSUE THREAD

**Issue by Pupiera** [speechbrain/speechbrain#1441]
Hello speechbrain community,
Currently, the fusion of the LM and ASR in the S2SBeamSearcher class is handled through a weighted sum of the log_prob from the ASR and the log_prob from the LM (i.e. : shallow fusion). Meaning that the LM and the ASR module must use the same vocabulary (same tokenizer).
Do you have any plan to handle other type of fusion such as Deep fusion or Cold fusion ? (https://arxiv.org/pdf/1807.10857.pdf)
These would allow for flexible LM swapping, which could be a very useful feature.
Thanks in advance for your answers !

**Comment by anautsch** [comment]
Hi @Pupiera - we are currently getting back to this PR #751 to refactor scoring. Take a look!

It will take a while and we can't make promises here before mid fall.
Of course, you are welcome to contribute.

**Comment by Pupiera** [comment]
Thanks for the answer, I'll check this PR.
