### ISSUE TITLE
Code Style Fixing

### ISSUE THREAD

**Issue by xin-w8023** [speechbrain/speechbrain#1451]
https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/utils/metric_stats.py#:~:text=(self.-,labels,-%3D%3D%201).
<img width="500" alt="image" src="https://user-images.githubusercontent.com/43900898/174516502-6876ad49-f48b-480c-82de-b9b2964c317a.png">
It's better to use `self.labels == self.positive_label` than hardcode to `self.labels == 1`.

**Comment by Adel-Moumen** [comment]
Hello, 

Could you please open a PR with your modification?

Many thanks :)
