### ISSUE TITLE
 Output of this Dual_Path_Model  has different shape under multi-gpu and single-gpu； why？

### ISSUE THREAD

**Issue by mochakong-chen** [speechbrain/speechbrain#1452]
I did a small experiment based on my code, my experimental code is as follows:

os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"

bi_rnn1 = speechbrain.lobes.models.dual_path.SBRNNBlock(input_size = 64,
                                                                                                hidden_channels = 128,
                                                                                                num_layers = 1,
                                                                                                bidirectional = True).cuda()

bi_rnn2 = speechbrain.lobes.models.dual_path.SBRNNBlock(hidden_channels = 128,
                                                                                                 input_size = 64,
                                                                                                 num_layers = 1,
                                                                                                 bidirectional = True).cuda()

model = speechbrain.lobes.models.dual_path.Dual_Path_Model(in_channels = 1,      #Number of channels at the output of the encoder.
                                                                                                       out_channels = 64,     #Number of channels that would be inputted to the intra and inter blocks.
                                                                                                        intra_model = bi_rnn1,#Model to process within the chunks.
                                                                                                        inter_model = bi_rnn2,#model to process across the chunks,
                                                                                                        num_layers = 1,       #Number of layers of Dual Computation Block.
                                                                                                        K = 283,              #Chunk length.
                                                                                                        num_spks = 1,         #Number of sources (speakers).
                                                                                                        max_length = 40000).cuda()   

sig = torch.ones((2,1,4000)).cuda()
out = model(sig)
print(out.shape)

model = nn.DataParallel(model)
sig = torch.ones((2,1,4000)).cuda()
out = model(sig)
print(out.shape)

This code output：
torch.Size([1, 2, 1, 4000])   
torch.Size([2, 1, 1, 4000])

I wonder why this is? how do i fix it？Thanks

**Comment by Adel-Moumen** [comment]
Hello, 

`DataParallel` is deprecated in PyTorch and SpeechBrain. Instead please use [DDP](https://speechbrain.readthedocs.io/en/latest/multigpu.html). 

Best, 
Adel
