### ISSUE TITLE
Exporting the operator stft to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by tungedng2710** [speechbrain/speechbrain#1455]
Hi, I have exported your MetricGAN+ model to ONNX (I called ```SpectralMaskEnhancement``` class from speechbrain.pretrained). However, I received the error message: 
```bat
Exporting the operator stft to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
In addition, I have modified the forward function of the ```SpectralMaskEnhancement``` a bit
```
def forward(self, noisy):
    """Runs enhancement on the noisy input"""
    print("Hello line 2128")
    return self.enhance_batch(noisy, lengths=torch.tensor([1.]))
```
Many thanks!

**Comment by mravanelli** [comment]
Unfortunately torch.stft (used in many places, such a feature computation) is not ONNX exportable.  I'm running into the same problem, but I don't have a solution. It could be great to have this operation supported in ONNX, as many people are asking it.
