### ISSUE TITLE
3rd party arpa LM to asr-crdnn-rnnlm-librispeech

### ISSUE THREAD

**Issue by Andrey-847-2** [speechbrain/speechbrain#1467]
Hi,

Is there any example of attaching 3rd party arpa LM to existing model asr-crdnn-rnnlm-librispeech?

I see speechbrain.lm.arpa module, but there is no any examples of BackoffNgramLM usage.

**Comment by TParcollet** [comment]
Hi, 

In the current version n-gram can easily be integrated with ctc_decode or pyctcdecode (external libraries). By the beginning of Fall, we will also release our own n-gram restorer :-)

**Comment by Andrey-847-2** [comment]
Great!

is there any example of such integration?

**Comment by mravanelli** [comment]
I think Aku ***@***.***) can provide some examples. In general I think LMs
and integration of ARPA LMs can be the object of a tutorial. What do you
think about Aku?

**Comment by TParcollet** [comment]
I think @Moumeneb1 can give an example as well. Please provide a short piece of code showing how to connect the CTC output to a n-gram rescoring if you can :-)

**Comment by Andrey-847-2** [comment]
@Moumeneb1 , did you have a chance to look at this? (see above)

**Comment by Moumeneb1** [comment]
Hi ! 
It's made simple to utilize pyctcdecode with a speechbrain trained EndoderASR model; all you have to do is encode the batch and import the right labels from the tokenizer that has already been exported. Following that, you must use pyctcdecide to load the arpa/bin file and do the decoding; batching is another option (multiprocessing not gpu parallelism). This as an easy example.

```python 
import torchaudio
import torch
from pyctcdecode import build_ctcdecoder
from speechbrain.pretrained import EncoderASR

#load the model 
asr_model = EncoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-fr", savedir="pretrained_models/asr-wav2vec2-commonvoice-fr")
#load audio
audio, sr  = torchaudio.load('/content/speechbrain/example1.wav')
#load wav length 
rel_length = torch.tensor([1.0])

#encode the wav with wav2vec2+vanilla_enc+ctc head 
encoder_out  = asr_model.encode_batch(audio,rel_length)

#get the labels from the used tokenizer
labels  = [asr_model.tokenizer.id_to_piece(id).lower() for id in range(asr_model.tokenizer.get_piece_size())]

labels[1]=' '
labels[0] = '<pad>'


decoder = build_ctcdecoder(labels,
    "model.arpa",
    alpha=0.6)

#decode the batch 
decoder.decode(encoder_out[0].cpu().numpy())
```

**Comment by VitoPepe** [comment]
@TParcollet @Moumeneb1 Hello, I'm trying to implement pyctcdecode too but I have an issue with the logits and vocab size even if I'm implementing pyctcdecode the same way as you : ValueError: Input logits shape is (179, 1000), but vocabulary is size 1001. Need logits of shape: (time, vocabulary)

Have you ever met that issue?

**Comment by Moumeneb1** [comment]
Hi @VitoPepe you please share your **labels** list ? Did you correctly change the **unk** Token to **pad** ? maybe it's that ?

**Comment by VitoPepe** [comment]
@Moumeneb1 Oh thanks a lot, that was my problem !

**Comment by Moumeneb1** [comment]
Great that it worked ! You're welcome ✌️

**Comment by Adel-Moumen** [comment]
Hello, 

It seems that the question has been solved. Therefore, I am closing this issue. Please, feel free to reopen it if necessary! Thank you very much. 😃
