### ISSUE TITLE
`torch.arange` doesn't implemented for `float16`

### ISSUE THREAD

**Issue by grazder** [speechbrain/speechbrain#1470]
# Problem 👩‍⚕️

I found that when `x` is in `float16` this line doesn't work:

https://github.com/speechbrain/speechbrain/blob/c7219b5b2b5c1b8a68da23e81eae0046b6769556/speechbrain/nnet/attention.py#L345

It is important because when I train the model in `fp16` (with `autocast` for ex) it throws an exception. 

# Repro 📔

```
 import torch

 seq_len = 10
 x = torch.randn(8, 50, 128).to(torch.float16)

 torch.arange(0, seq_len, dtype=x.dtype)
 ```
 
 Return:
 ```
 ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-28-1c012662a902>](https://localhost:8080/#) in <module>()
      6 print(x.dtype)
      7 
----> 8 torch.arange(0, seq_len, dtype=x.dtype)

RuntimeError: "arange_cpu" not implemented for 'Half'
 ```
 
 It is reproducible in colab too
 
 # Workaround 👀
 
I found that in Nemo `arange` is `float32` by default in dtype

```
# one of examples
positions = torch.arange(length - 1, -length, -1, dtype=torch.float32, device=device).unsqueeze(1)
```
 https://github.com/NVIDIA/NeMo/blob/41f27a5e68934761b05dd373e7b288aa798858e5/nemo/collections/asr/parts/submodules/multi_head_attention.py#L288

**Comment by vadimkantorov** [comment]
Also, float16 has max value of 65536 and quite inaccurate in the higher range, so using it for length calculation (if at all) should be done with extreme caution

**Comment by TParcollet** [comment]
That is interesting, @popcornell ?

**Comment by popcornell** [comment]
I also encountered this error. I tried to fix it, and it is quite easy to do so. 
However I got much worse performance for vanilla transformer. 
In my understanding half precision is broken right now. Didn't investigate further. 

> Also, float16 has max value of 65536 and quite inaccurate in the higher range, so using it for length calculation (if at all) should be done with extreme caution

Probably for ASR or NLP will be fine as you will not end up with such long sequences. 
But frankly nemo solution or using int64 is better.

**Comment by vadimkantorov** [comment]
@grazder which version of PyTorch are you running? @ngimel suggests in https://github.com/pytorch/pytorch/issues/80483#issuecomment-1169381845 that torch.arange for float16 should be supported in recent versions

(not implying that speechbrain should use fp16, i argue for the use of int64 or float32)

**Comment by vadimkantorov** [comment]
Also for float16 is badly supported on CPU (https://github.com/pytorch/pytorch/issues/80483#issuecomment-1169404072), it should probably be changed to default int64 or float32 that are supported on most devices

**Comment by vadimkantorov** [comment]
@popcornell Do you mean model accuracy was much worse? or computation speed?

**Comment by Adel-Moumen** [comment]
Hello,

any news on this issue, please? 😃

**Comment by Adel-Moumen** [comment]
OK. Thanks.

Have you run some tests between float16 and int64 on our transformers recipes?

**Comment by vadimkantorov** [comment]
No, @grazder just fixed it to be int64 to be safe of overflow/underflow of fp16

**Comment by Adel-Moumen** [comment]
OK. 

I will need to train some transformer recipes to test it. But I agree that it would be better to have int64 or fp32.

**Comment by asumagic** [comment]
I've looked into this again and I think there is no reason _not_ to use fp32 in the `arange`:

1. Checking out the `dtype` of the input tensor might not be a good idea (here or elsewhere). Even if you are using fp16 AMP, by design, not all tensors will be fp16, depending on the previous operation. The end result may be unnecessary extra casting or lost precision in certain cases.
2. Using `int64` does not seem meaningful as the result will get ultimately converted to floating-point and fp32 is enough precision and range anyway.
3. Since `positions` is immediately multiplied by `self.inv_freq`, which itself is , it is promoted to fp32 anyway

Extra note: the vanilla positional encodings are not affected and unconditionally use fp32.
