### ISSUE TITLE
Installing scikit-learn in diarization script

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#1484]
Hi all! I am now checking the diarization recipe via `recipe/AMI`. However, I found in the README and `extra_requirements.txt`, the library installed is `sklearn`, not `scikit-learn`. The latter, I believe, is the right library if one wants to use scikit-learn functions. So I think we may want to fix it? Or `sklearn` (whose version is always 0.0) is what we want here?

**Comment by Adel-Moumen** [comment]
Fixed in #1485
