### ISSUE TITLE
Device error when setting `deltas=True` in `speechbrain.lobes.features.Fbank`.

### ISSUE THREAD

**Issue by sangeet2020** [speechbrain/speechbrain#1489]
While extracting features of a wave tensor, I tried to use delta coefficients along with 40 filter-bank coefficients by setting `deltas=True` in `speechbrain.lobes.features.Fbank`. However, this runs into 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper___conv_depthwise2d)
```
The error lies in the [this line](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/processing/features.py#L838).
Changing it to (just for debug shake)
```
torch.nn.functional.conv1d(x.to(device='cpu'), self.kernel, groups=x.shape[1])
```
fixes the error.
i.e. the input and kernel tensor must be put into the same device. 

Thanks

**Comment by TParcollet** [comment]
Hi thanks! Any chance you could propose a quick fix for that? I guess we would have to retrieve the correct device though as they can be extracted from GPUs as well.

**Comment by sangeet2020** [comment]
@TParcollet sure, I will initiate a pull request that
- proposes a quick fix for this.
- adds epoch train time as discussed in [here](https://github.com/speechbrain/speechbrain/issues/122) (already discussed with @mravanelli )

Thank You
