### ISSUE TITLE
ECAPA TDNN length_to_mask

### ISSUE THREAD

**Issue by helloworld02202** [speechbrain/speechbrain#1494]
I am confused with the using of length_to_mask here, where `lengths * L`
Any idea of doing so? Because for simple case like lengths with size (B,) = (2,) and values [10,100], it will become [1000,10000]

https://github.com/speechbrain/speechbrain/blob/7897537fe929affa8e809b0229f464acbca7632d/speechbrain/lobes/models/ECAPA_TDNN.py#L254

**Comment by TParcollet** [comment]
Hi, this is a question for @mravanelli and @anautsch

**Comment by TParcollet** [comment]
Hi @helloworld02202, sorry for the late reply, I only found time to look into the code again. This function must return the mask i.e. will need to retrieve the max sentence length. This is why lengths is multiplied by L. L corresponds to the time dimension, hence, it is multiplied with the length vector that contains the relative lengths of the current sequences with the SpeechBrain style.

**Comment by Adel-Moumen** [comment]
Hello, 

It seems that @TParcollet has answered your question. Therefore, I am closing this issue. Please feel free to reopen it if necessary. Thank you very much 😃
