### ISSUE TITLE
`make_dataloader` always sets shuffle=False when DistributedSampler is employed.

### ISSUE THREAD

**Issue by lawlict** [speechbrain/speechbrain#1495]
In speechbrain.core.Brain class, when DistributedSampler is employed, it sets shuffle to False. Is there any reason to do so?
![image](https://user-images.githubusercontent.com/35951198/177245522-fe1ebcab-351b-476f-b235-4e36af12efe5.png)

**Comment by TParcollet** [comment]
Hi, yes there is a reason for that @Gastron and @popcornell might remember why, actually even @RuABraun as well might know.

**Comment by RuABraun** [comment]
Was kind of hoping someone else would take care of this, I will open a PR to fix this by tomorrow.

**Comment by TParcollet** [comment]
Hey @RuABraun I guess everyone is in vacation right now :p
