### ISSUE TITLE
Brain's check_gradients seems to not do what name implies?

### ISSUE THREAD

**Issue by RuABraun** [speechbrain/speechbrain#1496]
Was trying to debug something of mine and noticed two things:

1. [check_gradients](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/core.py#L888) does not actually check the gradients, it checks the loss [which does not have to be NaN if the gradients will be](https://discuss.pytorch.org/t/loss-is-not-nan-but-the-gradients-are/21224)

2. the [GradScaler's step will use unscale (which checks for nonfinite gradients) to skip an optimization step if any of the gradients are null](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler.step), so the faulty behaviour of `check_gradients` works out because it's actually already done by GradScaler

So it seems to me that at minimum `check_gradients` should be renamed to check loss or something like that, because it's confusing to read the code and see it doesn't match the function name and docstring, and then one wonders if there's a bug.

**Comment by pplantinga** [comment]
I agree that a different name could be more informative. Something like `check_loss_isfinite` or similar.

**Comment by Adel-Moumen** [comment]
Hi guys, 

What should we do about this? Should we create a PR to change the naming of `check_gradients`?

**Comment by Adel-Moumen** [comment]
Closing this issue as #2010 is merged in develop.
