### ISSUE TITLE
Preferred Bit Rate

### ISSUE THREAD

**Issue by msj121** [speechbrain/speechbrain#1497]
Do models have there preferred bit rates (and other settings) for wav files? Currently I am using the following model with not great accuracy: ([speechbrain/spkrec-ecapa-voxceleb](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb)).

But I assume I am missing something in my wav file setup. Thanks.

**Comment by TParcollet** [comment]
Hi,

Indeed, models are usually trained with fixed bit rates that are connected to the training dataset. I am not sure about VoxCeleb but you will certainly find this information in the YAML or the corpus description

**Comment by msj121** [comment]
Thanks 16kHz single channel in case anyone is interested.
