### ISSUE TITLE
AMI Diarization recipe databse folder structure

### ISSUE THREAD

**Issue by AMITKESARI2000** [speechbrain/speechbrain#1499]
Hi,
I am trying to run the diarization recipe but  `No recording IDs found! Please check if meta_data json file is properly generated.` is being shown. I came to know that this is due due to incorrect folder structure of the AMI data folder (manual annotations folder is the same from website).
Could you please add the directory structure in the documentation as well.

Current system:
![image](https://user-images.githubusercontent.com/66141447/177709303-307ab5a6-1fab-4c66-9b1a-b398ec845fc8.png)

![image](https://user-images.githubusercontent.com/66141447/177721097-71607de5-395b-4962-bd26-86de845706f2.png)

```
/home/datasets/AMI_Array01/
├── EN2001a
│   └── audio
│       └── EN2001a.Array1-01.wav
├── EN2001b
│   └── audio
│       └── EN2001b.Array1-01.wav
├── EN2001d
│   └── audio
│       └── EN2001d.Array1-01.wav
├── EN2001e
│   └── audio
│       └── EN2001e.Array1-01.wav
```

Also where can i see the diarized results?

**Comment by mattnappo** [comment]
Did you end up finding a solution to this? I am having the same issue

**Comment by mravanelli** [comment]
Any idea Nauman?

**Comment by nauman-daw** [comment]
Sorry for the late reply.  Thanks, @anautsch, for letting me know.

The audio path looks fine to me. Can you please paste a few lines of your generated json file here? 

In general, when you extract the files downloaded from the AMI webpage, it, by default creates a directory structure `amicorpus/EN2001a/audio/EN2001a.Array1-01.wav` . You just need to provide the root directory path, i.e., path to `amicorpus/ `  
As commented sample example mentioned in the yaml file: https://github.com/speechbrain/speechbrain/blob/a139a9a30dbc7a63827642442ed040d2307e81de/recipes/AMI/Diarization/hparams/ecapa_tdnn.yaml#L13

Diarized results can be found in your sub-folder inside the output folder as provided in the yaml file:  https://github.com/speechbrain/speechbrain/blob/a139a9a30dbc7a63827642442ed040d2307e81de/recipes/AMI/Diarization/hparams/ecapa_tdnn.yaml#L18
Search for `.rttm` files

**Comment by Adel-Moumen** [comment]
Hello @AMITKESARI2000,

Is the issue still up? Thanks! :-)

**Comment by anautsch** [comment]
Closing here. Please feel free to re-open.
