### ISSUE TITLE
CoreML conversion issue

### ISSUE THREAD

**Issue by justinklchan** [speechbrain/speechbrain#1500]
I am trying to convert the Resepformer model to CoreML

```
import coremltools as ct
from speechbrain.pretrained import SepformerSeparation as separator
import torchaudio
import speechbrain as sb
import torch

model = separator.from_hparams(source="speechbrain/resepformer-wsj02mix", savedir='pretrained_models/resepformer-wsj02mix')

ml_input1 = ct.TensorType(name='mixture', shape=(1, 1, 15625 * 3))
model = ct.convert(
    traced_model,
    inputs=[ct.TensorType(shape=dummy_input.shape)]
 )
```

This yields the error 
```
Converting Frontend ==> MIL Ops:   2%|▏         | 49/1969 [00:00<00:01, 1520.66 ops/s]
/usr/local/lib/python3.7/dist-packages/coremltools/converters/mil/frontend/torch/ops.py in convert_nodes(context, graph)
     85         if add_op is None:
     86             raise RuntimeError(
---> 87                 "PyTorch convert function for op '{}' not implemented.".format(node.kind)
     88             )
     89         add_op(context, node)

RuntimeError: PyTorch convert function for op 'remainder' not implemented.
```

Does anyone know what the issue is here?

**Comment by pplantinga** [comment]
@ycemsubakan ? What is this "remainder" op?

**Comment by ycemsubakan** [comment]
@justinklchan @pplantinga I am not sure what's happening here. I just tried the inference with RE-Sepformer using the latest version of the develop branch of speechbrain, and it is working fine. I guess this might be due to something about coreml?

**Comment by Adel-Moumen** [comment]
Hello @justinklchan,

Any news about this issue, please? Thanks :-)

**Comment by Adel-Moumen** [comment]
Hello @justinklchan,

I'm closing this issue as it has been inactive for a significant amount of time. If this is still an ongoing concern, I would encourage you to open a new issue with the updated issue template so that we have all the necessary information to investigate further.

Let me know if you have any questions or concerns.
