### ISSUE TITLE
Use specific version of a model hosted on Hugginface 

### ISSUE THREAD

**Issue by hbredin** [speechbrain/speechbrain#1509]
`huggingface_hub.hf_hub_download` supports passing a `revision` parameter to `hf_hub_{url|download}` to load a specific version (understand: commit, tag, or branch head) of models hosted on Huggingface Hub:

```python
from huggingface_hub import hf_hub_download
hf_hub_url(repo_id, filename, revision=..., ...)
```

It would be nice to expose this `revision` parameter in `speechbrain` so that one can pin a model to a specific version (and ensure that a given code will still behave the same even if the model is updated upstream).

The API could look like this:

```python
from speechbrain.pretrained import EncoderClassifier
encoder = EncoderClassifier.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb",
    revision="5c0be3875fda05e81f3c004ed8c7c06be308de1e",
)
```

or maybe like this that @julien-c [implemented](https://github.com/pyannote/pyannote-audio/blob/2decda1d0482578ae1f64aa98cbb6b5fbe32b6be/pyannote/audio/core/model.py#L773-L782) for `pyannote.audio`:

```python
from speechbrain.pretrained import EncoderClassifier
encoder = EncoderClassifier.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb@5c0be3875fda05e81f3c004ed8c7c06be308de1e")
```

**Comment by TParcollet** [comment]
Done https://github.com/speechbrain/speechbrain/pull/1510.
