### ISSUE TITLE
topk argument should also return top k hypothesis

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1514]
For all classes inheriting S2SBeamSearcher, if I set the **topk** argument only top k scores are returned. Snippet from the last part of the forward() function of this class

``` Python
        ) = self._get_top_score_prediction(hyps_and_scores, topk=self.topk,)
        # pick the best hyp
        predictions = topk_hyps[:, 0, :]
        predictions = batch_filter_seq2seq_output(
            predictions, eos_id=self.eos_index
        )

        if self.return_log_probs:
            return predictions, topk_scores, log_probs
        else:
            return predictions, topk_scores
```
As you can see, only topk scores are returned, not top k hypothesis. 

That it is incorrect, as according to the documentation: `topk  – The number of hypothesis to return. (default: 1)`.

**Comment by KacperKubara** [comment]
Hi @TParcollet, do you know if there is any way to return the hypothesis without forking a Speechbrain repo and changing the source code?

**Comment by TParcollet** [comment]
Hi, I am unsure, as the expected behavior would be to really return the predictions in "predictions", maybe we did something wrong. If so, we would be glad to see someone opening a PR for that. HR ressources are currently drained by the next version ...

**Comment by KacperKubara** [comment]
Ok no worries, I have created a fix on my fork so I can propose the PR, maybe even today.

**Comment by KacperKubara** [comment]
PR in https://github.com/speechbrain/speechbrain/pull/1550

**Comment by 30stomercury** [comment]
Related to #1550:

I actually have addressed the issue at
https://github.com/speechbrain/speechbrain/blob/102f9f785f13f96110de02cae7a00df217d4e247/speechbrain/decoders/seq2seq.py#L733-L741
It's not been merged yet as it involves several major changes.
I also remember similar issue was raised before, I think the changes will be done in the future (refactored) version.

**Comment by Adel-Moumen** [comment]
Hello, 

As mentioned by @30stomercury, a PR is already addressing this issue. 

We have some major steps to finish before merging the latter PR but It will solve your issue!
