### ISSUE TITLE
Speaker diarization not working

### ISSUE THREAD

**Issue by heunggyulee** [speechbrain/speechbrain#1529]
Hi. I started below code and not working also delayed too much time.
Until yesterday it works well but today may there is some problem.
Check Plz Thank you

diarization_pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2022.07")
# apply pretrained pipeline
diarization = diarization_pipeline(DEMO_FILE)

File ~/anaconda3/envs/speech_to_text_yip/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py:452, in SpeakerDiarization.apply(self, file, num_speakers, min_speakers, max_speakers, hook) 449 embeddings = None 450 else: --> 452 embeddings = self.get_embeddings( 453 file, 454 binarized_segmentations, 455 exclude_overlap=self.embedding_exclude_overlap, 456 ) 457 hook("embeddings", embeddings) 458 # shape: (num_chunks, local_num_speakers, dimension) 
...
297 _single(0), self.dilation, self.groups) --> 298 return F.conv1d(input, weight, bias, self.stride, 299 self.padding, self.dilation, self.groups) KeyboardInterrupt:

**Comment by anautsch** [comment]
Hi @heunggyulee [pyannote](https://huggingface.co/pyannote) while also being on HuggingFace is not SpeechBrain. Please contact them directly. 

Their github repo is right over here: https://github.com/pyannote/pyannote-audio
