### ISSUE TITLE
Wrong verification list in the Readme at speechbrain/recipes/VoxCeleb/SpeakerRec/

### ISSUE THREAD

**Issue by egruttadauria98** [speechbrain/speechbrain#1533]
The README specifies multiple times that the verification list is veri_split.txt, but in the hparams the one that is actually downloaded is veri_split2.txt

**Comment by underdogliu** [comment]
Hi, our statistics are fetched from the cleaned VoxCeleb1-O set, which is available in:
[https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt)

Therefore the hparams our results is "correct". The veri_test.txt is un-cleaned files from voxceleb1. It has some noticeable annotation errors. 

I am now working on updating the statistics. Will update the README at some point. But for now, please use the one provided by default in the hparams file.

**Comment by sharmadhiraj86** [comment]
Hii @underdogliu @egruttadauria98, please tell what should be modified in the Readme file. I want to contribute to solve this issue as soon as possible and raise a PR as this is a part of my academic curriculum.
