### ISSUE TITLE
Plugging in a custom model

### ISSUE THREAD

**Issue by buddhicw** [speechbrain/speechbrain#1538]
Hi,

Seems like an obvious question. But I could not find a solution anywhere. 

I am trying to train an ASR model containing a custom neural network with CTC using TIMIT database. I tried to add _myCRDNN_ to lobes/models and defined this in train.yaml. But I get the following error.

Is this expected? Is it not possible to plugin our own models to Speechbrain?

![image](https://user-images.githubusercontent.com/102768522/184454172-b71e1904-0ba3-4b3b-abd7-125965731472.png)

Thank you.

**Comment by mravanelli** [comment]
I think it is expected. Likely, you can fix it by refreshing the
installation with pip -e . from the main speechbrain folder.

**Comment by buddhicw** [comment]
Refreshing the installation fixed the problem. Thank you.
