### ISSUE TITLE
Multi-label classification

### ISSUE THREAD

**Issue by kirillkoncha** [speechbrain/speechbrain#1541]
Hi!

Is there any example of multi-label classification with SpeechBrain? What should I do if I want to predict two classes with one model (for example, language and mood)?

**Comment by lzl1456** [comment]
you can use twice  
sb.dataio.encoder.CategoricalEncoder()

**Comment by lzl1456** [comment]
I don't know how you imported the tag, I imported it like this    

_   

    @sb.utils.data_pipeline.takes('age')
    @sb.utils.data_pipeline.provides('age', 'age_id_encoded')
    def label_pipeline(age):
        yield age
        age_id_encoded = label_encoder_age.encode_sequence_torch([age])
        yield age_id_encoded

    sb.dataio.dataset.add_dynamic_item(datasets, label_pipeline)

    @sb.utils.data_pipeline.takes('gender')
    @sb.utils.data_pipeline.provides('gender', 'gender_id_encoded')
    def label_pipeline_2(gender):
        yield gender
        gender_id_encoded = label_encoder_gender.encode_sequence_torch([gender])
        yield gender_id_encoded

    sb.dataio.dataset.add_dynamic_item(datasets, label_pipeline_2)
_

and  


      sb.dataio.dataset.set_output_keys(
        datasets,
        ['id', 'sig', 'age_id_encoded', 'gender_id_encoded'])



in Brain ,  you  only like this
     age_ids, _ = batch.age_id_encoded
     gender_ids, _ = batch.gender_id_encoded

**Comment by anautsch** [comment]
@kirillkoncha  @lzl1456 
> > you can use twice
> > sb.dataio.encoder.CategoricalEncoder()
> 
> Yeah, that will encode different labels. However, what changes in the code of Brain class are need to be done? How to make model predict and output both labels?

Have two thoughts here that I'd like to share:
* naive classifiers are not made for this; they rely on the total probability theorem and by splitting up a world model of exhaustive and mutually classes into their boxes; then, each box is assigned with a probability—the job of the naive classifier. Here, you ask for two probabilities to one box. The game changes a bit (i.e. more coding is required).
* yet I sense you are asking for a different but related concern, I'd usually phrase this as:
  > Information depends on the question asked.
  
  In your case, when you want to have multi-label, what you are interested in is: how many lots of questions can I ask to a single utterance (audio/video/text/...) to annotate it the most richest? Each of the annotation question will get an answer of different information reliability level. Every underlying task is at another sufficiency level for its training data and the sample data given. It's more multi-task/inquiry than multi-class.

Here's a multi-task recipe (different tasks though to which you mentioned).
https://github.com/speechbrain/speechbrain/tree/develop/recipes/Voicebank/MTL/ASR_enhance
