### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given 

### ISSUE THREAD

**Issue by Asma-droid** [speechbrain/speechbrain#1543]
Hello,

I followed the tutorial "Speech Recognition From Scratch" and i have built the full model. When i would like to make inference in an audio file i got the error "TypeError: forward() takes 2 positional arguments but 3 were given "

Below is my code for inference:

from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="/srv/nas_data/atrabelsi/speechbrain/templates/speech_recognition/ASR/results/CRDNN_BPE_960h_LM/2602"
                                           ,savedir="pretrained_models/new_new")

audio_file = '/srv/nas_data/atrabelsi/speechbrain/templates/speech_recognition/ASR/example.wav'

asr_model.transcribe_file(audio_file)

the problem is not clear!

**Comment by anautsch** [comment]
Hi @Asma-droid this sounds like #1528 - but the interface shuoldn't have had changed.

Can you reproduce the example from data that is online available?
(e.g. via HuggingFace repos of SpeechBrain)

I ran this doctest locally which corresponds to your code snippet
https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/speechbrain/pretrained/interfaces.py#L499
```python
from speechbrain.pretrained import EncoderDecoderASR
tmpdir = "/tmp/tmpdir"
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir=tmpdir,)
# it's downloading/symlinking now; takes time
asr_model.transcribe_file("tests/samples/single-mic/example2.flac")
# takes time again - I pressed return a couple of times
```
> "MY FATHER HAS REVEALED THE CULPRIT'S NAME"

which works.

Are the properties of the audio files different?
When you compare `"tests/samples/single-mic/example2.flac"` with `'/srv/nas_data/atrabelsi/speechbrain/templates/speech_recognition/ASR/example.wav'` ?

**Comment by Adel-Moumen** [comment]
This issue seems to be inactive. Please re-open it if you are still facing the issue... thanks!
