### ISSUE TITLE
how to use torchrun instead of python -m torch.distributed.launch?

### ISSUE THREAD

**Issue by aluminumbox** [speechbrain/speechbrain#1551]
Hi, 

I am using Voxceleb recepie to train speaker embedding. I tried to use torchrun to replace python -m torch.distributed.launch, and changed my command from
`python -m torch.distributed.launch --nproc_per_node=4 train_cnceleb.py hparams/cnceleb.yaml --distributed_launch --distributed_backend=nccl`
to
`torchrun --nproc_per_node=4 train_cnceleb.py hparams/cnceleb.yaml --distributed_launch --distributed_backend=nccl`. 
And it failed.

Then I use `torchrun --nproc_per_node=4 train_cnceleb.py hparams/cnceleb.yaml`. But the training steps is 4 time largger. It seems that each process runs the whole data, rather than runs 1/4 of the whole data.

What is the correct way of using torchrun for speechbrain?

**Comment by Adel-Moumen** [comment]
Hello, 

Thanks for asking. 

First, I was wondering why are you using `torchrun` instead of `python -m torch.distributed.launch ...` ? Are there any reasons for that? (e.g, performances?)

For the moment, SpeechBrain is only supporting `torch.distributed.launch` (see: https://speechbrain.readthedocs.io/en/latest/multigpu.html). There are no plans yet to change to `torchrun` (as far as I know). :smiley:

**Comment by aluminumbox** [comment]
> Hello,
> 
> Thanks for asking.
> 
> First, I was wondering why are you using `torchrun` instead of `python -m torch.distributed.launch ...` ? Are there any reasons for that? (e.g, performances?)
> 
> For the moment, SpeechBrain is only supporting `torch.distributed.launch` (see: https://speechbrain.readthedocs.io/en/latest/multigpu.html). There are no plans yet to change to `torchrun` (as far as I know).

Ehh No particular reason. I just notice that pytorch recommend using torchrun and some other projects are using torchrun, so I want to try if it is faster. 
https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L10
Its okay that we use torch.distributed.launch.
