### ISSUE TITLE
segmentation fault on using tensorboard for IEMOCAP recipe

### ISSUE THREAD

**Issue by Neil-Shah** [speechbrain/speechbrain#1553]
I am facing this weird issue of segmentation fault (core dumped) on using train_with_wav2vec2.py recipe of IEMOCAP. As soon as I load "speechbrain.utils.train_logger.TensorboardLogger" in the yaml file, it says segmentation fault. Though if I comment those lines, the code successfully runs

I checked this by loading python on terminal:

Segmentation error if I import speechbrain initially
>>> import speechbrain
>>> import torch
>>> from torch.utils.tensorboard import SummaryWriter
Segmentation fault (core dumped)

No error, if I import speechbrain after 
>>> import torch
>>> from torch.utils.tensorboard import SummaryWriter
>>> import speechbrain

**Comment by BenoitWang** [comment]
Hi @Neil-Shah , this seems a known issue https://github.com/pytorch/pytorch/issues/30651, hope these links may help:
https://github.com/lanpa/tensorboardX/issues/178
https://stackoverflow.com/questions/16731115/how-to-debug-a-python-segmentation-fault?rq=1

**Comment by groadabike** [comment]
I had to add `from torch.utils.tensorboard import SummaryWriter` as the first import in train.py and the error disappear
