### ISSUE TITLE
Symbolik link issue

### ISSUE THREAD

**Issue by varsenyantitan** [speechbrain/speechbrain#1556]
OS: Ubuntu 20 LTS
Python: 3.8.13
Speechbrain: 0.5.12
-----------------------------------------
Code:
```
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="./pretrained_ASR")
```
-------------------------------------------
Error: 
/anaconda/envs/trans/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
torchvision is not available - cannot save figures
Downloading: 100%|██████████| 4.49k/4.49k [00:00<00:00, 3.50MB/s]

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 from speechbrain.pretrained import EncoderDecoderASR
----> 2 asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="./pretrained_ASR")

File /anaconda/envs/trans/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py:339, in Pretrained.from_hparams(cls, source, hparams_file, pymodule_file, overrides, savedir, use_auth_token, **kwargs)
    337     clsname = cls.__name__
    338     savedir = f"./pretrained_models/{clsname}-{hashlib.md5(source.encode('UTF-8', errors='replace')).hexdigest()}"
--> 339 hparams_local_path = fetch(
    340     hparams_file, source, savedir, use_auth_token
    341 )
    342 try:
    343     pymodule_local_path = fetch(
    344         pymodule_file, source, savedir, use_auth_token
    345     )

File /anaconda/envs/trans/lib/python3.8/site-packages/speechbrain/pretrained/fetching.py:127, in fetch(filename, source, savedir, overwrite, save_filename, use_auth_token)
    125     sourcepath = pathlib.Path(fetched_file).absolute()
    126     _missing_ok_unlink(destination)
--> 127     destination.symlink_to(sourcepath)
    128 return destination

File /anaconda/envs/trans/lib/python3.8/pathlib.py:1384, in Path.symlink_to(self, target, target_is_directory)
   1382 if self._closed:
   1383     self._raise_closed()
-> 1384 self._accessor.symlink(target, self, target_is_directory)

File /anaconda/envs/trans/lib/python3.8/pathlib.py:446, in _NormalAccessor.symlink(a, b, target_is_directory)
    444 @staticmethod
    445 def symlink(a, b, target_is_directory):
--> 446     return os.symlink(a, b)

OSError: [Errno 95] Operation not supported: '****/hyperparams.yaml' -> 'pretrained_ASR/hyperparams.yaml'

**Comment by anautsch** [comment]
Hi @varsenyantitan this might be a stupid question, but is are your jupyter and ipywidgets priviliged to have 'sylink rights' i.e. are you using this code within jupyter and is your jupyter allowed to create sylinks?

The only helpful thing I could find through online search is this one:
https://stackoverflow.com/questions/46097302/jupyter-does-not-show-symlink-folder

While it is good, you provide OS; Python & SpeechBrain versions, these two lines are tested always in SpeechBrain (and they work). The problem - especially for the error code - hint at a config issue on your machine/virtual environmeny/notebook.

Which steps did you take before & in which environment were you carrying out the two-liner code snippet?

**Comment by varsenyantitan** [comment]
Hi @anautsch. I have resolved this issue. It is not a permission issue but rather a drive issue. I am working in AzureML so each instance has an Azure File Share mounted. Apparently, creating a symlink from mounted cloud storage is not a supported operation. I have switched to the local storage of an instance (which is smaller) to be able to create a symlink.
Thank you for your replay.
