### ISSUE TITLE
couldn't find speechbrain.tokenizers.SentencePiece

### ISSUE THREAD

**Issue by gelimcgill** [speechbrain/speechbrain#1568]
>>> speechbrain.tokenizers.SentencePiece
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'speechbrain.tokenizers' has no attribute 'SentencePiece'

**Comment by Adel-Moumen** [comment]
Hello, 

Could you please provide a minimal example that reproduces the error that you are facing? Thanks!

**Comment by Adel-Moumen** [comment]
Hello, any news please?

**Comment by Adel-Moumen** [comment]
Hello @gelimcgill,

Please use `from` instead of `import` when fetching a specific class:
```python
from speechbrain.tokenizers.SentencePiece import SentencePiece

if __name__ == "__main__":
  print(SentencePiece)
```

Best.
