### ISSUE TITLE
Missing bos and eos id's in tokenizer hparams file

### ISSUE THREAD

**Issue by gozdii** [speechbrain/speechbrain#1581]
Hi 
In speechbrain/recipes/LibriSpeech/Tokenizer/hparams/1K_unigram_subword_bpe.yaml bos and eos tokens are not specified as 1 and 2 and it results in incorrect tokenization later

**Comment by Adel-Moumen** [comment]
Hello,

Could you provide a reproducible example, please?

**Comment by TParcollet** [comment]
I think that this is an error. However, it will not affect the results that much ... at least on LibriSpeech ... @gozdii could you please do a PR to change this, especially if you have trained the model afterward? We will need to update the Gdrive and the readme :-)

**Comment by Adel-Moumen** [comment]
And the Language Model...

**Comment by anautsch** [comment]
@TParcollet @Adel-Moumen what's the status on this issue?
