### ISSUE TITLE
Batch size and testing WER

### ISSUE THREAD

**Issue by kexinzhengn** [speechbrain/speechbrain#1582]
Hi,

I have trained a model using the pretrained CDRNN on LibriSpeech. When I was testing the model with same dataset but different batch size, the WER of batch size 2 is much larger than that of batch size 1. I want to ask why is the batch size setting also affecting the evaluation? There is no training involved for testing so I am a bit confused.

Thanks in advance!

**Comment by anautsch** [comment]
Hi @kexinzhengn without trying to reproduce it - you might want to take a looks at `undo_padding` (here as it is used in another branch than `develop`):
https://github.com/speechbrain/speechbrain/blob/80816c76c65f0c4656c54712428cf217ebb89d76/recipes/LibriSpeech/ASR/seq2seq/train.py#L99

The function is available on `develop` too - please check it out if this function helps your case:
https://github.com/speechbrain/speechbrain/blob/51f60fcab6d1155cec1fe098bcd2de012c9adbd0/speechbrain/utils/data_utils.py#L21

**Comment by kexinzhengn** [comment]
> Hi @kexinzhengn without trying to reproduce it - you might want to take a looks at `undo_padding` (here as it is used in another branch than `develop`):
> 
> https://github.com/speechbrain/speechbrain/blob/80816c76c65f0c4656c54712428cf217ebb89d76/recipes/LibriSpeech/ASR/seq2seq/train.py#L99
> 
> The function is available on `develop` too - please check it out if this function helps your case:
> 
> https://github.com/speechbrain/speechbrain/blob/51f60fcab6d1155cec1fe098bcd2de012c9adbd0/speechbrain/utils/data_utils.py#L21

Hi @anautsch , Thank you for the information. I sort of understand how it works now.
