### ISSUE TITLE
Impossible to transcribe audio file with the same name

### ISSUE THREAD

**Issue by qanastek** [speechbrain/speechbrain#1586]
Due to the implementation of the [transcribe_file](https://github.com/speechbrain/speechbrain/blob/aef146861cc89482102f7ce63cda1e8d3366a229/speechbrain/pretrained/interfaces.py#L716) method and specially of the sub method [load_audio](https://github.com/mravanelli/speechbrain-1/blob/033d8cda7f237109636849ef34c0b0e83e9c4897/speechbrain/pretrained/interfaces.py#L229), it is impossible to transcribe audio file with the same name despite being located in different directories since the method copy the audio file locally at `savedir`. The new file with the same name doesn't overwrite the file, since it already exist and make the transcription impossible.

Example of file paths :

- /users/<user_name>/datasets/MyDataset/recordings/ZOWxbXGuoU/**recording_1.wav**
- /users/<user_name>/datasets/MyDataset/recordings/2h4v5o49Hj/**recording_1.wav**

It will be cool to get rid of this local file to fix this issue and improve overall performances of the transcription method.

One easy but dirty way of fixing it is to remove the file at the end of the transcription to allow further ones.

**Comment by anautsch** [comment]
Hi @qanastek yep.

This relates to #1303 - this topic touches on data handling in general:
* for researchers, can a training recipe run through?
* for industry, are the right audios loaded through the pretrained interfaces?
* for curious users, does the demo code provided on HuggingFace run?

Dropping a file does not help if there's DDP and multiple nodes are having fun with the same file name.

Hope we can get to it soon. As you mentioned, it's internal data handling and there's an expectation of this just running well (as it is also stated in the mentioned PR).
