### ISSUE TITLE
Conflicting documentation on supported Python versions

### ISSUE THREAD

**Issue by AsuMagic** [speechbrain/speechbrain#1593]
Both 3.7 and 3.8 are mentioned as minimal Python versions in different places, which could be confusing to users and contributors. So, which one is it?

Those are all the mentions to Python versions I've found after a quick lookup in the codebase:
- `README.md` mentions Python 3.8+
- `docs/contributing.md` mentions Python 3.8+
- Test actions are run for Python 3.7, 3.8, 3.9
- `setup.py` requires Python 3.7+
- `docs/installation.md` mentions Python 3.7+

FWIW, if you want, I can make a PR to solve the issue depending on your answer.

**Comment by anautsch** [comment]
Hi @AsuMagic thanks for pointing out - it's python 3.7.
Please go ahead with a PR :muscle:
