### ISSUE TITLE
[Bug]: Tensor Dimension Error on Speaker Separation

### ISSUE THREAD

**Issue by samecfrank** [speechbrain/speechbrain#1606]
### Describe the bug

I am getting a tensor dimension error when running speaker separation. 

### Expected behaviour

I expect the function to output an array of speaker separated audio files. 

### To Reproduce

model = separator.from_hparams(source="speechbrain/sepformer-wsj02mix", savedir='pretrained_models/sepformer-wsj02mix')
est_sources = model.separate_file(path='filename.wav')

### Relevant log output

```shell
Resampling the audio from 44100 Hz to 8000 Hz
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [14], in <cell line: 2>()
      1 model = separator.from_hparams(source="speechbrain/sepformer-wsj02mix", savedir='pretrained_models/sepformer-wsj02mix')
----> 2 est_sources = model.separate_file(path='/Users/franksae/Desktop/PCDT/microphone_test/audio/Lavalier_Mic_Test_10_5_22.wav')

File ~/opt/anaconda3/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py:2033, in SepformerSeparation.separate_file(self, path, savedir)
   2030     batch = batch.mean(dim=0, keepdim=True)
   2031     batch = tf(batch)
-> 2033 est_sources = self.separate_batch(batch)
   2034 est_sources = (
   2035     est_sources / est_sources.abs().max(dim=1, keepdim=True)[0]
   2036 )
   2037 return est_sources

File ~/opt/anaconda3/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py:1976, in SepformerSeparation.separate_batch(self, mix)
   1974 mix = mix.to(self.device)
   1975 mix_w = self.mods.encoder(mix)
-> 1976 est_mask = self.mods.masknet(mix_w)
   1977 mix_w = torch.stack([mix_w] * self.hparams.num_spks)
   1978 sep_h = mix_w * est_mask

File ~/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/opt/anaconda3/lib/python3.9/site-packages/speechbrain/lobes/models/dual_path.py:1021, in Dual_Path_Model.forward(self, x)
   1019 # [B, N, K, S]
   1020 for i in range(self.num_layers):
-> 1021     x = self.dual_mdl[i](x)
   1022 x = self.prelu(x)
   1024 # [B, N*spks, K, S]

File ~/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/opt/anaconda3/lib/python3.9/site-packages/speechbrain/lobes/models/dual_path.py:872, in Dual_Computation_Block.forward(self, x)
    870 inter = intra.permute(0, 2, 3, 1).contiguous().view(B * K, S, N)
    871 # [BK, S, H]
--> 872 inter = self.inter_mdl(inter)
    874 # [BK, S, N]
    875 if self.linear_layer_after_inter_intra:

File ~/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/opt/anaconda3/lib/python3.9/site-packages/speechbrain/lobes/models/dual_path.py:597, in SBTransformerBlock.forward(self, x)
    595 if self.use_positional_encoding:
    596     pos_enc = self.pos_enc(x)
--> 597     return self.mdl(x + pos_enc)[0]
    598 else:
    599     return self.mdl(x)[0]

RuntimeError: The size of tensor a (2526) must match the size of tensor b (2500) at non-singleton dimension 1
```

**Comment by TParcollet** [comment]
@mravanelli could you please look for this? It's pretty "urgent" thanks!

**Comment by mravanelli** [comment]
@ycemsubakan, could you please take a look?

**Comment by ycemsubakan** [comment]
@samecfrank , Are you on the develop or main branch? 

I have just tested on the `develop` branch (I fresh cloned the repo).

Can you try the following on a fresh clone, and let us know if you still get the same error? 

```
model = separator.from_hparams(source="speechbrain/sepformer-wsj02mix", savedir='pretrained_models/sepformer-wsj02mix' )
est_sources = model.separate_file(path='speechbrain/sepformer-wsj02mix/test_mixture.wav')
```

**Comment by samecfrank** [comment]
Thank you so much for your response! I did a fresh clone and that line ran. For reference the test lines you sent have always run correctly. My audio is a standard .wav file (never modified) that is ~5 minutes in length. Is there a reason model.separate_file() may be throwing an error for specific files?

**Comment by ycemsubakan** [comment]
I see.. 5 minutes seems to be too long, normally you should run out of memory, or the process should get killed. On a 32 gb gpu, ~2minutes is the max you can do without going OOM. However on CPU you might be able to do it, thought would be a bit  slower. Can you try cutting the file into a shorter segment (30 seconds maybe) and try?

**Comment by samecfrank** [comment]
Doing a cropped version of the file worked. Is there any way to use speechbrain on longer texts? Thank you so much for your help!

**Comment by ycemsubakan** [comment]
Do you mean longer files? You can use the 'Resepformer' model. It is less memory demanding: https://huggingface.co/speechbrain/resepformer-wsj02mix

**Comment by MartinKocour** [comment]
I think you @samecfrank encounter the same problem which I previously faced:
`SepFormerSeparation.separate_file()` is calling `fetch` function (take a look into [line 2014](https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/speechbrain/pretrained/interfaces.py#L2014)), which does multiple things... but the most important in this case is that it creates a symlink to provided file nad if the symlink already exists and `overwrite==False` then it does nothing.
This means that if your file was empty before, than the symlink will point to empty file.
More details are [here](https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/speechbrain/pretrained/fetching.py#L26)

In my case I solved the problem by deleting all symlinks created by fetch before. But you can also solve it, by calling fetch with `overwrite=True` or providing a differente `savedir`, e.g. some temporal directory.
