### ISSUE TITLE
[Bug]: templates.speech_recognition.LM.train doesn't call `hparams["pretrainer"].load_collected`

### ISSUE THREAD

**Issue by almson** [speechbrain/speechbrain#1609]
### Describe the bug

The LM template forgets to call `hparams["pretrainer"].load_collected`, the way that recipes such as `recipes/KsponSpeech/LM/train.py` do. This results in empty training data.

### Expected behaviour

That the code would contain this line and data would load.

### Versions

`develop` HEAD

**Comment by anautsch** [comment]
We merged the mentioned PR. Closing here. Please feel free to re-open.
