### ISSUE TITLE
[Feature Request]: A way to train the model based on number of batches instead of epochs

### ISSUE THREAD

**Issue by aviasd** [speechbrain/speechbrain#1612]
### 🚀The feature

Is there a simple way to run validation every X batches instead of every epoch? if not, it may be a good feature.

### Solution outline

Instead of the classical EpochCounter, we can create BatchEpochCounter that will signal "end of epoch" every X batches.
More changes might be needed to the "fit" function.

**Comment by TParcollet** [comment]
Hey Hi, we already used a step early-stopping on the SSL pretraining recipe, does this is equivalent to what you are looking for ?

**Comment by aviasd** [comment]
> Hey Hi, we already used a step early-stopping on the SSL pretraining recipe, does this is equivalent to what you are looking for ?

Do you mean [EpochCounterWithStopper](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/utils/epoch_loop.py#L71)?

**Comment by TParcollet** [comment]
This argument from the Brain class: --optimizer_step_limit does it helps?

**Comment by aviasd** [comment]
The [--optimizer_step_limit](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/core.py#L457) argument is used for early stopping. But the train-validation phases are still defined by epochs.  
When using [IterableDataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset), there are no epochs, but an infinite stream of batches.  
In this "online" train, we need to stop every X batches and run the validation step.
