### ISSUE TITLE
[Bug]: LJSpeech/TTS receipt does not run with current LJSpeech 1.1

### ISSUE THREAD

**Issue by padmalcom** [speechbrain/speechbrain#1614]
### Describe the bug

Running the receipt in LJSpeech/TTS has an issue decoding the bytes of the metadata.csv in the current LJSpeech dataset. It throws this decoding error:
```
(speechbrain) C:\Users\admin\speechbrain\recipes\LJSpeech\TTS\tacotron2>python train.py --device=cuda:0 --max_grad_norm=1.0 --data_folder="C:\Users\admin\Downloads\LJSpeech-1.1.tar\LJSpeech-1.1" hparams/train.yaml
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/tacotron2/1234
data folder C:\Users\admin\Downloads\LJSpeech-1.1.tar\LJSpeech-1.1 save_folder ./results/tacotron2/1234/save splits:  ['train', 'valid'] ratio:  [90, 10]
ljspeech_prepare -      Creating json file for ljspeech Dataset..
speechbrain.core - Exception:
Traceback (most recent call last):
  File "C:\Users\admin\speechbrain\recipes\LJSpeech\TTS\tacotron2\train.py", line 366, in <module>
    sb.utils.distributed.run_on_main(
  File "C:\Users\admin\Anaconda3\envs\speechbrain\lib\site-packages\speechbrain\utils\distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "C:\Users\admin\speechbrain\recipes\LJSpeech\TTS\tacotron2\..\ljspeech_prepare.py", line 102, in prepare_ljspeech
    data_split, meta_csv = split_sets(data_folder, splits, split_ratio)
  File "C:\Users\admin\speechbrain\recipes\LJSpeech\TTS\tacotron2\..\ljspeech_prepare.py", line 181, in split_sets
    meta_csv = list(csv_reader)
  File "C:\Users\admin\Anaconda3\envs\speechbrain\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1936: character maps to <undefined>
```

### Expected behaviour

I'm expecting the train.py to read the metadata.csv correctly.

### To Reproduce

Extract LJSpeech and run:

python train.py --device=cuda:0 --max_grad_norm=1.0 --data_folder="C:\Users\admin\Downloads\LJSpeech-1.1.tar\LJSpeech-1.1" hparams/train.yaml

**Comment by BenoitWang** [comment]
Hi @padmalcom, 

For the correct preparation, first you can download LJSpeech-1.1 with this link https://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2, then you unzip the file and give the unzipped path to `data_folder`.

Hope this may help.

**Comment by padmalcom** [comment]
@BenoitWang Thanks, Benoit. Doing what you proposed leads to the UnicodeDecodingError.

**Comment by BenoitWang** [comment]
Hi @padmalcom, I cannot reproduce the error and it seems a windows encoding issue, utf-8 should be used instead of CP1252, some links that may help:
https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
https://stackoverflow.com/questions/904041/reading-a-utf8-csv-file-with-python

**Comment by padmalcom** [comment]
Thanks for testing, I'll change the encoding to utf-8. Closing so far.
