### ISSUE TITLE
[Bug]: [Typo] 

### ISSUE THREAD

**Issue by starcell** [speechbrain/speechbrain#1615]
### Describe the bug

There are some typos in below sources,
recipes/LibriSpeech/Tokenizer/train.py
recipes/KsponSpeech/Tokenizer/train.py
.

In comment:
"""
~
coverts -> converts
bas  -> bad
~
"""

### Expected behaviour

To correct misspelled words.

**Comment by Adel-Moumen** [comment]
Hello @starcell,

Could you please open a PR to fix it? Thanks!

**Comment by sharmadhiraj86** [comment]
Hi @Adel-Moumen the typo on both the files has been fixed please let me know if there is any modifications required.

**Comment by Adel-Moumen** [comment]
Great! Many thanks.
