### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by GoldDRoge** [speechbrain/speechbrain#1618]
### 🚀The feature

hello im a new one. and i have some problem like this. Thanks for your help
I want to fine tuning this model on my dataset https://huggingface.co/dragonSwing/wav2vec2-base-vn-270h I follow all the code in the https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/CTC but it does not help because the file hparam look difference. And i really dont know what structure about train.csv is it link_path_to_wav trascript ??

### Solution outline

can u show me how to fine tuning step by step

**Comment by Adel-Moumen** [comment]
Hello,

This is a duplicate of #1617 therefore I am closing this "issue". :-)
