### ISSUE TITLE
[Bug]: The error of the DER for Spectral clustering with AMI

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1640]
### Describe the bug

![image](https://user-images.githubusercontent.com/86965285/198567765-01347324-962e-4689-b7fa-e33479c6280e.png)

### Expected behaviour

1

### To Reproduce

1

### Versions

1

### Relevant log output

```shell
1
```

### Additional context

1

**Comment by annedadaa** [comment]
Hello! I've got the same problem, did you managed to solve it?

**Comment by mravanelli** [comment]
@Adel-Moumen, could you please take a look at it?

**Comment by Adel-Moumen** [comment]
Hello, 

Thanks for pointing out this issue. 

It seems related to #600. 
Could you please try to install SpeechBrain locally?

The following steps will be mandatory:
```bash
  git clone https://github.com/speechbrain/speechbrain.git
  cd speechbrain
  pip install -r requirements.txt
  pip install --editable .
```

According to #600, during the pip install process, the SpeechBrain `tools` folder is not fetched so you will have to install SpeechBrain locally or copy the folder `tools` in the location of your SpeechBrain installed version.

Let me know if it fix your problem. Thanks! :-)

**Comment by LONG520520** [comment]
sorroy i kown how to deal with  this question thank you!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Adel ***@***.***> |
| Date | 11/02/2022 17:52 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [speechbrain/speechbrain] [Bug]: The error of the DER for Spectral clustering with AMI (Issue #1640) |

Hello,

Thanks for pointing out this issue.

It seems related to #600.
Could you please try to install SpeechBrain locally?

The following steps will be mandatory:

  git clone https://github.com/speechbrain/speechbrain.git
  cd speechbrain
  pip install -r requirements.txt
  pip install --editable .

According to #600, during the pip install process, the SpeechBrain tools folder is not fetched so you will have to install SpeechBrain locally or copy the folder tools in the location of your SpeechBrain installed version.

Let me know if it fix your problem. Thanks! :-)

**Comment by Adel-Moumen** [comment]
OK. Good. :-)

**Comment by annedadaa** [comment]
I solved the problem as well, thank you!
