### ISSUE TITLE
[Bug]: IEMOCAP wav2vec2 recipe

### ISSUE THREAD

**Issue by Janardhan2131** [speechbrain/speechbrain#1686]
### Describe the bug

I am trying to train the model IEMOCAP wav2vec2 model using the following command

%cd /content/speechbrain/recipes/IEMOCAP/emotion_recognition
!python train_with_wav2vec2.py hparams/train.yaml --data_folder = "/content/drive/MyDrive/IEMOCAP_full_release"

But It just running for 1 sec and not training at all and not running any epochs
![image](https://user-images.githubusercontent.com/84712492/200156585-2fad35f1-c5cf-4a66-8ff9-8e315743fe5c.png)

### Expected behaviour

I am expecting to train the model and run for all 30 epochs but its not happing

**Comment by Adel-Moumen** [comment]
Hello @BenoitWang, 

Could you please take a look? Thank you!

**Comment by Janardhan2131** [comment]
Can someone please look into this, I need to submit project report on this asap

**Comment by Janardhan2131** [comment]
@Adel-Moumen Please have a look on this issue, The IEMOCAP wav2vec2 recipe is not working and not able to training.

**Comment by Adel-Moumen** [comment]
Could you please provide more details? What is the output error? @Janardhan2131

**Comment by Janardhan2131** [comment]
while running the recipe it is expected to run 30 epochs but it is not
running at all

**Comment by Janardhan2131** [comment]
![image](https://user-images.githubusercontent.com/84712492/200266175-6a20f0cd-321a-4721-b5a8-6ee86bd8fac5.png)
It is just running for 1sec and giving output like this.

But I am expected like below image that all epochs running and making checkpoints but it is not happening

![image](https://user-images.githubusercontent.com/84712492/200266905-90fac192-a61a-440d-a025-c162695ed684.png)

**Comment by Janardhan2131** [comment]
@Adel-Moumen It is not training and no epoch is running as I specified above

**Comment by Adel-Moumen** [comment]
OK.

I have maybe an idea, when you are doing `!cd PATH`, actually it will not move you permanently to the PATH. You should add to your command the training also such that:
`! cd PATH; python train.py hparams/params.yaml --data_folder="PATH"`

Let me know if it solves it.

**Comment by Janardhan2131** [comment]
@Adel-Moumen It is not working , throwing segmentation fault

**Comment by mravanelli** [comment]
@BenoitWang, could you please take a look at it as well? I remember everytihng was working when I tested it as while ago.

**Comment by BenoitWang** [comment]
Hi @Janardhan2131 @Adel-Moumen @mravanelli sorry for the late response. For me this is not a problem of the recipe but something with google colab. Please check the environment and make sure to mount your drive.

**Comment by BenoitWang** [comment]
@Janardhan2131 for the wav2vec2 recipe a pretrained model is grabbed from huggingface, did you install the latest version of transformers?

**Comment by Janardhan2131** [comment]
Yes Every time I try to implement the recipe I installed transformers
latest version

**Comment by BenoitWang** [comment]
No idea... Can you download any model from huggingface? Try this ?
`from speechbrain.pretrained.interfaces import foreign_class`
`classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP", pymodule_file="custom_interface.py", classname="CustomEncoderWav2vec2Classifier")`
Or maybe it's the internet connection, can you make a wget to verify?

**Comment by Janardhan2131** [comment]
@BenoitWang But I want to train this recipe myself on IEMOCAP dataset and want to inference on the model that I can obtain.
Again tried on other desktops, still facing the same issue.

**Comment by Janardhan2131** [comment]
@BenoitWang I am sharing a small snapshot while running recipe , you can get clarity on the issue
https://drive.google.com/file/d/17dNrzu2mzpioyDL4K31Hbvf6KSYPNgvF/view?usp=share_link

**Comment by BenoitWang** [comment]
I reproduced the issue and finally got the answer. The default python version is 3.7, changing to 3.8 solved the problem. Here's my code https://colab.research.google.com/drive/1F0suhzTt1gHLYoCuFct-1w9pKpa4FLa9?usp=sharing, please tell me if this solves your problem.

**Comment by Janardhan2131** [comment]
Yes its working. @mravanelli @BenoitWang @Adel-Moumen Thank you for your help and solving this issue.

**Comment by Adel-Moumen** [comment]
OK. 

Good to know that everything is working now. 

I close this issue but feel free to open a new discussion if you have more questions on the training recipe. 😀
