### ISSUE TITLE
[Bug]: Can't access repository even with access token

### ISSUE THREAD

**Issue by abbatea** [speechbrain/speechbrain#1687]
### Describe the bug

Hello Everyone,

I accepted the user conditions for https://huggingface.co/pyannote/speaker-diarization
and created an access token.
When I tried to run my code
`from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
                                    use_auth_token='my_accesscode_which_i_obviously_dont_share')`
I get the error message:

RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin. If the repo is private, make sure you are authenticated. (Request ID: JB3M0GKc-lon466cv5Ca2)

After creating the accesstoken do I have to do something to activate /connect it with speaker-diarization or why do I keep getting the error?

### Expected behaviour

I expect to get access to the repository / load a model and run speaker diarization to my file

### To Reproduce

`from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
                                    use_auth_token='my_accesscode_which_i_obviously_dont_share')`

### Relevant log output

```shell
RepositoryNotFoundError                   Traceback (most recent call last)
Cell In [7], line 6
      2 from pyannote.audio import Pipeline
      3 #pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
      4 #                                    use_auth_token="my_accesscode_which_i_obviously_dont_share")
----> 6 pipeline = Pipeline.from_pretrained(use_auth_token='my_accesscode_which_i_obviously_dont_share', checkpoint_path="pyannote/speaker-diarization@2.1")
      8 print("it worked")

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyannote\audio\core\pipeline.py:98, in Pipeline.from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
     94 pipeline_name = config["pipeline"]["name"]
     95 Klass = get_class_by_name(
     96     pipeline_name, default_module_name="pyannote.pipeline.blocks"
     97 )
---> 98 pipeline = Klass(**config["pipeline"].get("params", {}))
    100 # freeze  parameters
    101 if "freeze" in config:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyannote\audio\pipelines\speaker_diarization.py:116, in SpeakerDiarization.__init__(self, segmentation, segmentation_step, embedding, embedding_exclude_overlap, clustering, embedding_batch_size, segmentation_batch_size)
    112 self.klustering = clustering
    114 seg_device, emb_device = get_devices(needs=2)
--> 116 model: Model = get_model(segmentation)
    117 model.to(seg_device)
    119 self._segmentation = Inference(
    120     model,
...
     81         f" {request_id})"
     82     )
     84 _raise_with_request_id(request)

RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin. If the repo is private, make sure you are authenticated. (Request ID: JB3M0GKc-lon466cv5Ca2)
```

**Comment by BenoitWang** [comment]
Hi @abbatea , I bumped into the same issue and [this](https://github.com/pyannote/pyannote-audio/issues/1128#issuecomment-1296000185) helped.

**Comment by abbatea** [comment]
hi @BenoitWang ty very much, it helped!
Have a nice day
(For anyone wondering: I accepted both terms (diarization and segmentation) then I uninstalled pyannote.audio and installed it again)
