### ISSUE TITLE
[Bug]: Audio examples for multi-mic processing tutorial are missing

### ISSUE THREAD

**Issue by rfalcon100** [speechbrain/speechbrain#1699]
### Describe the bug

The audio examples for the multi-mic processing tutorial are missing, or they have been deleted from dropbox. So running this cell returns nothing:
```python
%%capture
!wget https://www.dropbox.com/s/1bag9h3q588bjxx/speech_-0.82918_0.55279_-0.082918.flac
!wget https://www.dropbox.com/s/6vlnqgs076i846k/noise_diffuse.flac
!wget https://www.dropbox.com/s/esx4fetsvgjr3nt/noise_0.70225_-0.70225_0.11704.flac
```

### Expected behaviour

The files should be downloadable.

**Comment by TParcollet** [comment]
@FrancoisGrondin might help.

**Comment by mravanelli** [comment]
It looks like a problem with dropbox actually....

**Comment by Adel-Moumen** [comment]
Hello guys, 

Any news about this issue, please? Thanks :-)

**Comment by Adel-Moumen** [comment]
Hello, 

Please have a look at the updated tutorial : https://colab.research.google.com/drive/1UVoYDUiIrwMpBTghQPbA6rC1mc9IBzi6?usp=sharing . Everything works as intended. 

Best.
