### ISSUE TITLE
[Bug]:  FairseqWav2Vec2 Load example. 

### ISSUE THREAD

**Issue by germes96** [speechbrain/speechbrain#1703]
### Describe the bug

The section [FairseqWav2Vec2](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.lobes.models.fairseq_wav2vec.html#reference) in the documentation present and example to try Wav2Vec2. This example works with the 0.5.11 version of speechbrain but not work on last version 0.5.13.

### Expected behaviour

Produce the share of output

### To Reproduce

```
inputs = torch.rand([10, 600])
model_url = "https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt"
save_path = "models_checkpoints/wav2vec2.pt"
model = FairseqWav2Vec2(model_url, save_path)
outputs = model(inputs)
outputs.shape
```

### Versions

0.5.13

### Relevant log output

```shell
Traceback (most recent call last):
  File "test_wav2vec.py", line 9, in <module>
    outputs = model(inputs)
  File "~/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/venv/lib/python3.7/site-packages/speechbrain/lobes/models/fairseq_wav2vec.py", line 161, in forward
    return self.extract_features(wav).detach()
  File "~/venv/lib/python3.7/site-packages/speechbrain/lobes/models/fairseq_wav2vec.py", line 172, in extract_features
    out = self.model.extract_features(wav, padding_mask=None, mask=False)[0]
KeyError: 0
```

**Comment by germes96** [comment]
@anautsch @Adel-Moumen  After further investigation, I realized that the problem is not caused by speechbrain but rather by fairseq. Instead of the default version of fairseq (0.12.2) I installed a less recent version that I was already using in one of my projects (0.10.2). And everything works perfectly.

**Comment by Adel-Moumen** [comment]
OK! Glad to know that you solved the issue. 

Might be worth keeping this issue alive so that everyone is aware of this uncompatibility problem.

**Comment by TParcollet** [comment]
Closing. People can browse all issues to find answers :-)
