### ISSUE TITLE
[Bug]: Speechbrain speaker-diarization accuracy is really low

### ISSUE THREAD

**Issue by abbatea** [speechbrain/speechbrain#1720]
### Describe the bug

Hello everyone, I tried the speaker diarization
`from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
use_auth_token="ACCESS_TOKEN_GOES_HERE")
apply the pipeline to an audio file
diarization = pipeline("audio.wav")

dump the diarization output to disk using RTTM format
with open("audio.rttm", "w") as rttm:
diarization.write_rttm(rttm)`

And tried this code on multiple files but got really low accuracy for 2 people. For example identifying a speaker as speaker00, another one as speaker01 and it suddenly switches, that when speaker00 speaks the ouput says the other one speaks)

Is there a way to make the code more accurate, or is there like an "confident-percentage" as an output per line?

Best Regards

### Expected behaviour

differentiate between speakers

### To Reproduce

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
use_auth_token="ACCESS_TOKEN_GOES_HERE")
apply the pipeline to an audio file
diarization = pipeline("audio.wav")

dump the diarization output to disk using RTTM format
with open("audio.rttm", "w") as rttm:
diarization.write_rttm(rttm)`

**Comment by svecjan** [comment]
Hi @abbatea, I am looking at the description of your issue, but I have the feeling that you are reporting to the wrong toolkit. Your code uses `pyannote.audio` for diarization, and not SpeechBrain, try reporting it [there](https://github.com/pyannote/pyannote-audio).

**Comment by Adel-Moumen** [comment]
Hello,

Yes, indeed, it seems that this issue is related to pyannote and not SpeechBrain. 

Please open an issue on their side. Thanks!
(feel free to reopen this one if we have misunderstood something)
