### ISSUE TITLE
[Bug]: "InputType not supported" when training tacotron2 (LJSpeech) using tochaudio 0.13.0

### ISSUE THREAD

**Issue by padmalcom** [speechbrain/speechbrain#1745]
### Describe the bug

The train.py throws and error when training tacotron2 saying "InputType not supported." with torchaudio 0.13.0.
Downgrading to torchaudio 0.12.1 solves the issue.

### Expected behaviour

It should not throw the error.

**Comment by BenoitWang** [comment]
Hi @padmalcom, this was just solved in #1740.
