### ISSUE TITLE
[Bug]: ruamel.yaml versus ruamel_yaml

### ISSUE THREAD

**Issue by sjkoelle** [speechbrain/speechbrain#1748]
### Describe the bug

This is not an issue with the default installation instructions, but rather results from installing into an environment with a preexisting ruamel_yaml installation.
As discussed in https://github.com/fair-workflows/nanopub/issues/106, ruamel.yaml (the speechbrain dependency) and ruamel_yaml are different packages that are considered identical by pip's name parser.  ruamel.yaml is the 'correct' version, but also not the version we are using in most of our codebase, and pips attempts to uninstall ruamel_yaml to install ruamel.yaml were unsuccessful due to it being a disutils installed package. Conda works for installing both packages concurrently, but is not used in our build script, and we didn't want to introduce it. Ultimately, I forked https://github.com/sjkoelle/speechbrain and https://github.com/sjkoelle/HyperPyYAML in order to change ruamel.yaml to ruamel_yaml, and was able to obtain speaker encodings. 

### Expected behaviour

I would expect to be able to install both `ruamel.yaml` and `ruamel_yaml` as separate packages using pip.

**Comment by pplantinga** [comment]
Thanks for reporting this issue, I was not aware of `ruamel_yaml` and the potential for conflict. While we don't really have the resources to maintain support for both versions of this tool, I suppose a simple medium-term solution could be to add some code like the following:
```python
try:
    import ruamel.yaml as ruamelyaml
    from ruamel.yaml.representer import RepresenterError
except:
    import ruamel_yaml as ruamelyaml
    from ruamel_yaml.representer import RepresenterError
```
And use `ruamelyaml` everywhere that `ruamel.yaml` is currently used. If this supports your use case and you have some free time, feel free to submit a PR implementing it.

**Comment by sjkoelle** [comment]
I tried something like that in my branch but ran into issues when using the python:3.8 base image on docker.  In lieu of fixing the ruamel_yaml version I was able to get it to run with the speechbrain speechbrain (ie not my fork) and the --ignore-installed flag.  My understanding is that this lets both ruamel.yaml and ruamel_yaml be simultaneously installed.

**Comment by pplantinga** [comment]
Okay, sounds like there is a workaround that doesn't require code changes so I'll just go ahead and close this.
