### ISSUE TITLE
During speaker_id inference, running into an OSError: [WinError 1921] The name of the file cannot be resolved by the system: '\\content\\hparams_inference.yaml'

### ISSUE THREAD

**Issue by praveenmathew93** [speechbrain/speechbrain#1755]
### Describe the bug

I trained a model using partially LibriSpeech data and partially CommonVoice data.
Now I am doing the inference.

The code fails at EncoderClassifier.
classifier = EncoderClassifier.from_hparams(source="/content/best_model/", hparams_file='hparams_inference.yaml', savedir="/content/best_model/")

I have my best model placed at '/content/best_model/' along with the hparams_file='hparams_inference.yaml', yet I keep running into the error.

### Expected behaviour

The EncoderClassifier takes in the inputs and proceeds to accept the audio files for inference.

### To Reproduce

import os
import sys
import torch
import torchaudio
import speechbrain as sb
from hyperpyyaml import load_hyperpyyaml
from speechbrain.pretrained import EncoderClassifier

classifier = EncoderClassifier.from_hparams(source="/content/best_model/", hparams_file='hparams_inference.yaml', savedir="/content/best_model/")

# Perform classification
audio_file = 'data/LibriSpeech/train-clean-5/5789/70653/5789-70653-0036.flac'
signal, fs = torchaudio.load(audio_file) # test_speaker: 5789
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print('Target: 5789, Predicted: ' + text_lab[0])

# Another speaker
audio_file = 'data/LibriSpeech/train-clean-5/460/172359/460-172359-0012.flac'
signal, fs =torchaudio.load(audio_file) # test_speaker: 460
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print('Target: 460, Predicted: ' + text_lab[0])

### Relevant log output

```shell
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    classifier = EncoderClassifier.from_hparams(source="/content/best_model/", hparams_file='hparams_inference.yaml', savedir="/content/best_model/")
  File "E:\Study\Thesis\Voice print\speechbrain\speechbrain\pretrained\interfaces.py", line 343, in from_hparams
    hparams_file, source, savedir, use_auth_token, revision
  File "E:\Study\Thesis\Voice print\speechbrain\speechbrain\pretrained\fetching.py", line 89, in fetch
    if destination.exists() and not overwrite:
  File "C:\Python\Python37\lib\pathlib.py", line 1318, in exists
    self.stat()
  File "C:\Python\Python37\lib\pathlib.py", line 1140, in stat
    return self._accessor.stat(self)
OSError: [WinError 1921] The name of the file cannot be resolved by the system: '\\content\\best_model\\hparams_inference.yaml'
```

**Comment by AsuMagic** [comment]
Can you try `"./content/best_model/"` or `content/best_model/` (mind the dot)?

**Comment by praveenmathew93** [comment]
@AsuMagic with the dot, I get the same error.
When I do `content/best_model/` , I get this error:

`OSError: [WinError 1921] The name of the file cannot be resolved by the system: 'content\\best_model\\custom.py'`

looking for custom.py.
