### ISSUE TITLE
[Bug]: EER (or accuracy) in speaker verification is so bad

### ISSUE THREAD

**Issue by dungnguyen98** [speechbrain/speechbrain#1759]
### Describe the bug

I load pretrained model for speaker verification,  then I calculate accuracy and EER on list of file pairs of voxceleb;
I downloaded pretrained model from HuggingFace.
 But accuracy archive only ~50% and EER ~ 49%. I dont know why they are so bad.
The code that calculate accuracy as below.
Step 1: I load pretrained model.
Step 2: Loop through test file and read file pairs.
if the prediction == label, count += 1

step 3: calculate accuracy: count/ number_of_file_pairs

Please tell me if i did it wrong way

### Expected behaviour

I expect EER < 5%,  and accuracy > 96% on test file of Voxceleb.

### To Reproduce

from speechbrain.pretrained import SpeakerRecognition

from tqdm import tqdm
from random import shuffle

verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="pretrained_models/spkrec-ecapa-voxceleb", run_opts={"device":"cuda"})

# read pairs in test file
with open("/media/dover/4a7ee6a6-c86f-4987-9758-f2e533b38e1f/git/speechbrain2/pretrained_models/veri_test.txt", "r") as f:
    lines = f.readlines()
shuffle(lines)

i = 0

data = {}

count = 0
for line in tqdm(lines):
          data[i] = line.strip().split()
          score, prediction = verification.verify_files(
              "/media/dover/4a7ee6a6-c86f-4987-9758-f2e533b38e1f/git/voxceleb_trainer/data/vox1_test_wav/wav/" + data[i][1],
              "/media/dover/4a7ee6a6-c86f-4987-9758-f2e533b38e1f/git/voxceleb_trainer/data/vox1_test_wav/wav/" + data[i][2]
          )
          if int(prediction) == int(data[i][0]):
              count += 1
      
          i += 1

print("accuracy = ", m/len(lines))

### Relevant log output

```shell
accuracy =  0.49753446447507954 (* 100 %)
```

**Comment by dungnguyen98** [comment]
When I run "python speaker_verification_cosine.py hparams/verification_ecapa.yaml" as README.md in Voxceleb recipe. EER = 0.7%.
Is there anything special here?
In above code, I load model as the guidance of Huggingface and do verification.

**Comment by underdogliu** [comment]
Thanks, @dungnguyen98 for your question. The unsatisfying performance from your side is due to several reasons. 

But actually, I found some inconsistencies in your question post (variables, code indent). Could you please maybe share your complete script or colab notebook, if possible?

**Comment by dungnguyen98** [comment]
Sorry about that.
I rewrote the code [here](https://colab.research.google.com/drive/1IklyrO08IPa1MdjhIFYscV_26xbV_ado?authuser=1)
