### ISSUE TITLE
[Bug]: Voicebank/*/*MetricGAN* torch.multinomial error

### ISSUE THREAD

**Issue by anautsch** [speechbrain/speechbrain#1786]
### Describe the bug

While [testing recipes](https://github.com/speechbrain/speechbrain/pull/1600#issuecomment-1335378632), an error was thrown for all MetricGAN recipes. This report points to one log only, but it is alike for all three MetricGAN recipes.

RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement

### Expected behaviour

No error

### Relevant log output

```shell
File "speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 371, in train_discriminator
    self.fit(
...
  File "torch/utils/data/sampler.py", line 203, in __iter__
    rand_tensor = torch.multinomial(self.weights, self.num_samples, self.replacement, generator=self.generator)
RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement
```

**Comment by pplantinga** [comment]
This was fixed in f0535637f5c16d5f791708b3c3c15127ae40f247
