### ISSUE TITLE
[Bug]: CommonVoice/self-supervised-learning/wav2vec2 - not implemented for NumPy arrays

### ISSUE THREAD

**Issue by anautsch** [speechbrain/speechbrain#1787]
### Describe the bug

While [testing recipes](https://github.com/speechbrain/speechbrain/pull/1600#issuecomment-1335378632), an error occured.

TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.

### Expected behaviour

Either a clearer restriction of when this recipe can be used, or an adjustment of dependencies (so there is no error).

### Relevant log output

```shell
File "speechbrain/recipes/CommonVoice/self-supervised-learning/wav2vec2/train_hf_wav2vec2.py", line 111, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
...
  File "transformers/models/wav2vec2/modeling_wav2vec2.py", line 285, in _sample_negative_indices
    sampled_negative_indices[batch_idx] += batch_idx * sequence_length
TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.
```

**Comment by TParcollet** [comment]
This is a transformer issue. transformmers==4.15 should be added to the extra requirements (you cleaned it with the csv recipe PR)

**Comment by anautsch** [comment]
Yeiks, this is on us. Here's a patch file for the fix (will be uploaded with other PR 1600 edits).

```diff
diff --git a/speechbrain/lobes/models/huggingface_wav2vec.py b/speechbrain/lobes/models/huggingface_wav2vec.py
index d412430f..6775fcca 100644
--- a/speechbrain/lobes/models/huggingface_wav2vec.py
+++ b/speechbrain/lobes/models/huggingface_wav2vec.py
@@ -411,7 +411,7 @@ class HuggingFaceWav2Vec2Pretrain(nn.Module):
 
         sequence_length = self.model._get_feat_extract_output_lengths(
             raw_sequence_length
-        )
+        ).item()
 
         # 1. Compute the indices that will be masked
         mask_time_indices = _compute_mask_indices(
```

We were giving as input arguments for `(batch_size, sequence_length)` a `(2, tensor(157))` mix. It worked when using `.item()` on a previous variable, so the input argument is `(2, 157)` instead.
