### ISSUE TITLE
[Bug]: Missing EncoderDecoderASR.decoder in model "asr-wav2vec2-commonvoice-fr"

### ISSUE THREAD

**Issue by lumaku** [speechbrain/speechbrain#1796]
### Describe the bug

Using the Wav2vec2 `speechbrain/asr-wav2vec2-commonvoice-fr` model for the CTC aligner stops with the exception "The given asr_model has no CTC module!".

`speechbrain/asr-wav2vec2-commonvoice-fr` is of class `EncoderDecoderASR` but does not have a module `decoder`. The CTC segmentation throws an error as it would expect a `decoder` submodule for this class in it (the CTC layer is then part of the decoder module). The interface to the speechbrain CTC module is here:

https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/speechbrain/alignment/ctc_segmentation.py#L232-L259

The `EncoderDecoderASR` module is here:
https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/speechbrain/pretrained/interfaces.py#L528

The model configuration file of `speechbrain/asr-wav2vec2-commonvoice-fr` does not include a decoder:
https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr/blob/main/hyperparams.yaml

Other wav2vec2 models include a decoder, for example https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-en/blob/main/hyperparams.yaml

### Expected behaviour

This code tests for a `decoder` submodule:
```python
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-fr")
print( type(asr_model) )
print( has_attr(asr_model, "decoder") )
# <class 'speechbrain.pretrained.interfaces.EncoderDecoderASR'>
# False   ## <--- Expected: True
```

### To Reproduce

```python
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-fr" )
aligner = CTCSegmentation(asr_model, kaldi_style_text=False, gratis_blank=True)
# Exception:
# AttributeError: The given asr_model has no CTC module!
```

**Comment by anautsch** [comment]
Hi @lumaku you can use an `EncoderASR`.

Here's a config example which can be used in (upcoming) testing
https://github.com/speechbrain/speechbrain/blob/testing-refactoring/updates_pretrained_models/asr-wav2vec2-commonvoice-fr/test.yaml

Regarding the `aligner` - @Adel-Moumen this looks like sth you might be working on.

**Comment by lumaku** [comment]
@anautsch  I wrote this report for another user that encountered this issue in the Speechbrain CTC alignment tutorial:

https://gist.github.com/lumaku/75eca1c86d9467a54888d149dc7b84f1?permalink_comment_id=4418457#gistcomment-4418457

This may
* either be an issue with the pretrained model - It is `EncoderDecoderASR` but does not have a decoder module (this module has `decoder` in `MODULES_NEEDED` ).
* or an issue with the code that searches for the CTC layer in the module (`speechbrain.alignment.ctc_segmentation` above) - maybe this code should change? Has the default  interface to the CTC layer in Speechbrain changed?

**Comment by anautsch** [comment]
@Adel-Moumen this is yours ;)

**Comment by TParcollet** [comment]
This is an issue with the segmenter. The correct interface here is EncoderASR, hence, no decoder.

**Comment by lumaku** [comment]
OK, I see. That solves the issue. Thanks.

For the user, there was no information whether the model was initialized with the correct class (`EncoderDecoderASR` or `EncoderASR`). That test could be done in the parent module `class Pretrained`; it mentions the MODULES_NEEDED in a comment: https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/speechbrain/pretrained/interfaces.py#L210
