### ISSUE TITLE
[Bug]: Incorrect LR reloading when training is interrupted

### ISSUE THREAD

**Issue by mzboito** [speechbrain/speechbrain#1824]
### Describe the bug

Hello,

I need help! I am currently training speech translation models based on my recipe (https://github.com/speechbrain/speechbrain/blob/develop/recipes/IWSLT22_lowresource/hparams/train_w2v2_st.yaml). Although the dataset is not the same, all relevant model and checkpoint variables are kept the same from that yaml.

The problem I am currently having is that once training is interrupted (i.e. server timeout) and I have to relaunch the model, the adam learning rate recovers from an incredible different value, which ruins my model learning.

Here is an example from my train_log.txt:
```
epoch: 94, **lr_adam: 3.73e-13**, lr_wav2vec: 1.29e-09 - train loss: 41.66 - valid loss: 85.96, valid ACC: 6.38e-01, valid BLEU: 26.33,
epoch: 95, **lr_adam: 3.73e-13,** lr_wav2vec: 1.16e-09 - train loss: 41.67 - valid loss: 85.96, valid ACC: 6.38e-01, valid BLEU: 26.35
```
<Model is interrupted before the end of epoch 96 and recovers from an intermediate checkpoint CKPT+2023-01-22+16-41-09+00 (I save one every 15min)>

```
epoch: 96, **lr_adam: 1.86e-13**, lr_wav2vec: 1.04e-09 - train loss: 41.98 - valid loss: 98.48, valid ACC: 5.53e-01, valid BLEU: 11.66
```

However, "lr_adam" is saved at the yaml checkpointer:
```
lr_annealing_adam: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.5
    patient: 2

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        lr_annealing_adam: !ref <lr_annealing_adam>
        lr_annealing_wav2vec: !ref <lr_annealing_wav2vec>
        counter: !ref <epoch_counter>
```

This issue didn't happen before (six months in the past), and I was able to relaunch my models normally. The first time I noticed this "new" behavior was around one month ago. I installed the latest speech brain developer branch a couple of weeks ago, and the behavior persists.

Thanks a lot!!

### Expected behaviour

Learning rate is correctly retrieved by the train function.

### To Reproduce

You can use the recipe here:
https://github.com/speechbrain/speechbrain/tree/develop/recipes/IWSLT22_lowresource

I am not using the same dataset, but I only changed the data_prepare function, so  it shouldn't matter.

### Versions

Speechbrain develop version after padding fix for wav2vec 2.0 fine-tuning:
HEAD is now at 0423bda Merge pull request #1805 from Adel-Moumen/1794-bug-m1-gpu-mps-support

Running on NVIDIA A100 80GB, python 3.9.4, torch=1.9.0+cu111

### Relevant log output

```shell
Above.
```

**Comment by mzboito** [comment]
Now I'm wondering if this LR behavior is not simply the effect of the patient parameter. However, in this case, there might be something else that is not captured by the checkpoint and that is resulting in such a degradation (BLEU went from 26 to 11.......)?

**Comment by TParcollet** [comment]
@Adel-Moumen could you check this asap? This is worrying.

**Comment by Gastron** [comment]
To me it looks like `lr_adam==3.73e-13` for epochs 94 and 95, and then for epoch 96 it has changed to `1.86e-13`. Note that in the epoch end log, the printed LR is the one that was used during that epoch, the one that just ended, see: https://github.com/speechbrain/speechbrain/blob/0423bda83237070ad219d88b834d480f58cbe53e/recipes/IWSLT22_lowresource/train.py#L171

In the more verbose log.txt you could maybe find a line like "Changing LR from x to y".

The BLEU degradation is bad though, and I cannot immediately spot any simple mistake.

**Comment by anautsch** [comment]
@Gastron has a point. 
```
lr_adam has 0.5 annealing factor. 3.73e-13 * .5 ~ 1.86e-13
lr_wav2vec has 0.9 annealing factor: 1.29e-09 * .9 ~ 1.16e-09 & 1.16e-09 * .9 ~ 1.04e-09
```

also in the train script, as pointed out
```python
        if stage == sb.Stage.VALID and sb.utils.distributed.if_main_process():
            current_epoch = self.hparams.epoch_counter.current
            old_lr_adam, new_lr_adam = self.hparams.lr_annealing_adam(
                stage_stats["BLEU"]
            )
...
                (
                    old_lr_wav2vec,
                    new_lr_wav2vec,
                ) = self.hparams.lr_annealing_wav2vec(stage_stats["BLEU"])
                sb.nnet.schedulers.update_learning_rate(
                    self.wav2vec_optimizer, new_lr_wav2vec
                )
                self.hparams.train_logger.log_stats(
                    stats_meta={
                        "epoch": current_epoch,
                        "lr_adam": old_lr_adam,
                        "lr_wav2vec": old_lr_wav2vec,
                    },
                    train_stats={"loss": self.train_stats},
                    valid_stats=stage_stats,
                )
...
           self.checkpointer.save_and_keep_only(
                meta=meta, name=name, num_to_keep=10, max_keys=["BLEU"]
            )
```

Looks like expected behaviour. The logging reports on the old LRs that relate to the old/current performance reports & BLEU on valid is a result. Then, after reloading CKPT, the new learning rates are used.

Logging could include old/new learning rates.

As @mzboito reported, this did not happen this way before with other CKPTs. The reason might be as well as @Gastron pointed out indirectly, that in previous experiences there was no such change to be observable. In that regard, a change in BLEU is also what could happen when learning rates in need for a change. Yet, the `max_keys=["BLEU"]` mechanism should prevent that too low-BLEU CKPTs impact the overall result.

@mzboito please respond, if your recipe still works, and if this issue can be closed.

**Comment by Adel-Moumen** [comment]
Any news on this @mzboito please? thanks :-)

**Comment by mzboito** [comment]
Hi, thanks for answering my issue, and sorry for the wait, I was on vacations.
I'm a bit confused. I get it that fixing the variable changes and corrects the reported loss on the log file, but how does it fix my current problem on having horrible BLEU scores after relaunching? It consistently happens every single time I relaunch a model that is in the middle of training. BLEU scores drop sometimes over 10 BLEU and training is ruined.
Thanks a lot.

**Comment by mzboito** [comment]
oups, I closed by accident, this problem IS NOT solved :/

**Comment by anautsch** [comment]
Hi @mzboito maybe it's the recipe or a local point.

For the logging, please extend the above section in your local repo to
```python
                self.hparams.train_logger.log_stats(
                    stats_meta={
                        "epoch": current_epoch,
                        "lr_adam": old_lr_adam,
                        "new_lr_adam": new_lr_adam,
                        "lr_wav2vec": old_lr_wav2vec,
                        "new_lr_wav2vec": new_lr_wav2vec,
                    },
                    train_stats={"loss": self.train_stats},
                    valid_stats=stage_stats,
                )
```
just to see if you'd start from scratch & checkpoint loading comes if storing/reading checkpoints is the issue.

**Comment by mzboito** [comment]
Hi. Thanks for taking the time and trying to help me. What do you mean by local point?

I  added this information on the log. I would just like to highlight that I've been using this recipe for almost a year, and I didn't have this problem in the past. Checkpoint loading used to work, but it doesn't anymore (since at least December 2022).

Here is a couple of examples:

(before adding the information you asked)
* Restarting from intermediate epoch CKPT: (to see if intermediate checkpoints are somehow different from epoch ones)

Baseline (no interruption in training)

epoch: 49, lr_adam: 3.05e-09, lr_wav2vec: 8.73e-08 - train loss: 30.96 - valid loss: 49.81, valid ACC: 7.43e-01, valid BLEU: 27.67, valid BLEU_extensive: {'BLEU': 27.670990051672383, 'BP': 0.9281561751167434, 'ratio': 0.9306175583425941, 'hyp_len': 146549, 'ref_len': 157475, 'precisions': [62.763990201229625, 36.01306644636618, 23.121633599236382, 15.115600186828585], 'bleu_score': **27.670990051672383**}

epoch: 50, lr_adam: 3.05e-09, lr_wav2vec: 7.86e-08 - train loss: 30.96 - valid loss: 49.72, valid ACC: 7.44e-01, valid BLEU: 27.76, valid BLEU_extensive: {'BLEU': 27.760418692869752, 'BP': 0.9324216317917468, 'ratio': 0.9346054929353865, 'hyp_len': 147177, 'ref_len': 157475, 'precisions': [62.708167716423084, 35.97296502198855, 23.081422455813165, 15.090087911875356], 'bleu_score': **27.760418692869752**}


Restarting training after interruption (between 59 and 50). Retrieving from intermediate checkpoint (CKPT+2023-02-17+14-20-26+00)

epoch: 49, lr_adam: 3.05e-09, lr_wav2vec: 8.73e-08 - train loss: 30.96 - valid loss: 49.81, valid ACC: 7.43e-01, valid BLEU: 27.67, valid BLEU_extensive: {'BLEU': 27.670990051672383, 'BP': 0.9281561751167434, 'ratio': 0.9306175583425941, 'hyp_len': 146549, 'ref_len': 157475, 'precisions': [62.763990201229625, 36.01306644636618, 23.121633599236382, 15.115600186828585], 'bleu_score': **27.670990051672383**}

epoch: 50, lr_adam: 3.05e-09, lr_wav2vec: 7.86e-08 - train loss: 31.04 - valid loss: 54.73, valid ACC: 6.95e-01, valid BLEU: 20.84, valid BLEU_extensive: {'BLEU': 20.84049587248481, 'BP': 0.8066620026330502, 'ratio': 0.8231465311954278, 'hyp_len': 129625, 'ref_len': 157475, 'precisions': [60.93037608486017, 31.797315156152187, 19.346485942775193, 11.886100273685436], 'bleu_score': **20.84049587248481**}

* Restarting from epoch CKPT: (same issue)

Baseline (no interruption in training)

epoch: 41, lr_adam: 2.44e-08, lr_wav2vec: 2.03e-07 - train loss: 31.00 - valid loss: 50.55, valid ACC: 7.37e-01, valid BLEU: 26.45, valid BLEU_extensive: {'BLEU': 26.45315171507971, 'BP': 0.8917236856963873, 'ratio': 0.8971836799491982, 'hyp_len': 141284, 'ref_len': 157475, 'precisions': [63.178420769513885, 35.94237221235445, 22.937449808155616, 14.868523608319318], 'bleu_score': **26.45315171507971**}

epoch: 42, lr_adam: 2.44e-08, lr_wav2vec: 1.82e-07 - train loss: 30.99 - valid loss: 50.46, valid ACC: 7.38e-01, valid BLEU: 26.54, valid BLEU_extensive: {'BLEU': 26.538400350823217, 'BP': 0.8926167584707604, 'ratio': 0.8979901571678044, 'hyp_len': 141411, 'ref_len': 157475, 'precisions': [63.18744652113343, 35.97470091401623, 22.999313719373614, 14.94500092177226], 'bleu_score': **26.538400350823217**}

Restarting training using epoch CKPT (CKPT+checkpoint_epoch41)

epoch: 41, lr_adam: 2.44e-08, lr_wav2vec: 2.03e-07 - train loss: 31.00 - valid loss: 50.55, valid ACC: 7.37e-01, valid BLEU: 26.45, valid BLEU_extensive: {'BLEU': 26.45315171507971, 'BP': 0.8917236856963873, 'ratio': 0.8971836799491982, 'hyp_len': 141284, 'ref_len': 157475, 'precisions': [63.178420769513885, 35.94237221235445, 22.937449808155616, 14.868523608319318], 'bleu_score': **26.45315171507971}**

epoch: 42, lr_adam: 2.44e-08, lr_wav2vec: 1.82e-07 - train loss: 36.73 - valid loss: 62.92, valid ACC: 6.25e-01, valid BLEU: 12.54, valid BLEU_extensive: {'BLEU': 12.544718974555536, 'BP': 0.5660427911034264, 'ratio': 0.6373138593427529, 'hyp_len': 100361, 'ref_len': 157475, 'precisions': [60.999790755373105, 28.1684392200765, 15.85235578544923, 8.85649234896486], 'bleu_score': **12.544718974555536**}

* Finally, with the log modifications you asked:

Baseline (no interruption in training)
epoch: 20, lr_adam: 3.13e-06, new_lr_adam: 1.56e-06, lr_wav2vec: 1.67e-06, new_lr_wav2vec: 1.50e-06 - train loss: 32.25 - valid loss: 57.36, valid ACC: 6.84e-01, valid BLEU: 18.01, valid BLEU_extensive: {'BLEU': 18.01070080933908, 'BP': 0.6614921846822872, 'ratio': 0.7075853310049214, 'hyp_len': 111427, 'ref_len': 157475, 'precisions': [63.95218394105558, 33.23073427187374, 20.37489812550937, 12.69208037825059], 'bleu_score': **18.01070080933908**}

epoch: 21, lr_adam: 1.56e-06, new_lr_adam: 1.56e-06, lr_wav2vec: 1.50e-06, new_lr_wav2vec: 1.35e-06 - train loss: 32.13 - valid loss: 56.76, valid ACC: 6.88e-01, valid BLEU: 18.53, valid BLEU_extensive: {'BLEU': 18.52615494184228, 'BP': 0.6735193173374826, 'ratio': 0.7167232894110176, 'hyp_len': 112866, 'ref_len': 157475, 'precisions': [64.07952793578225, 33.57657547630679, 20.667312221305693, 12.873636389941838], 'bleu_score': **18.52615494184228**}

Restarting training using epoch CKPT 20

epoch: 20, lr_adam: 3.13e-06, new_lr_adam: 1.56e-06, lr_wav2vec: 1.67e-06, new_lr_wav2vec: 1.50e-06 - train loss: 32.25 - valid loss: 57.36, valid ACC: 6.84e-01, valid BLEU: 18.01, valid BLEU_extensive: {'BLEU': 18.01070080933908, 'BP': 0.6614921846822872, 'ratio': 0.7075853310049214, 'hyp_len': 111427, 'ref_len': 157475, 'precisions': [63.95218394105558, 33.23073427187374, 20.37489812550937, 12.69208037825059], 'bleu_score': **18.01070080933908**}

epoch: 21, lr_adam: 1.56e-06, new_lr_adam: 1.56e-06, lr_wav2vec: 1.50e-06, new_lr_wav2vec: 1.50e-06 - train loss: 37.59 - valid loss: 62.71, valid ACC: 6.24e-01, valid BLEU: 13.09, valid BLEU_extensive: {'BLEU': 13.09243827828041, 'BP': 0.5797489102689898, 'ratio': 0.6471820923956183, 'hyp_len': 101915, 'ref_len': 157475, 'precisions': [61.25889221409999, 28.502376725273468, 16.16000440177171, 9.217872296566059], 'bleu_score': **13.09243827828041**}

**Comment by anautsch** [comment]
> Thanks for taking the time and trying to help me.

@mzboito we need to find the issue; Aku's point has reasoning, so does yours. Your concern is valid, as data shows, let's dive into it and see what's going on. We can iterate faster through this.


> What do you mean by local point?

Does it also happen when you start from scratch?
i.e. rm -r results and start over.

It could be that the model got stuck somewhere ("could"; it's just one point to debug this).


> I would just like to highlight that I've been using this recipe for almost a year, and I didn't have this problem in the past. Checkpoint loading used to work, but it doesn't anymore (since at least December 2022).

You wrote this already above, I'm not ignoring your concern. One thing at a time. Both of us need to become better experts at this issue.


> Here is a couple of examples:
> 
> (before adding the information you asked)

I'll edit your message ... right now it's just log text but my eyes are human.

**Comment by mzboito** [comment]
Hi @anautsch ,

Yes, I tried restarting from different checkpoints, from different models (different data/wav2vec2 model), and retraining from scratch. 
To replicate the bug I usually kill the training at a given epoch, get the log, remove the last epoch and restart training. BLEU scores consistently go down compared to existing log.
I also tested training for many epochs after restarting to check if the network would quickly recover from this degradation, but it does not.

**Comment by TParcollet** [comment]
Are you 100% sure that all elements that must be saved are captured by the checkpointer? I often end up having this issue (last time was yesterday), because I am missing one element from the checkpoint (that will then be randomized again).

**Comment by mzboito** [comment]
Yes, I keep wondering if there is something I am failing to save, but if there is, it was something that before was saved by default and now it is not. And I have no idea what it is!

**Comment by anautsch** [comment]
fyi - in November we needed a quickfix for some torch update #1683

**Comment by anautsch** [comment]
Can you checkout by commit ID and retest one of the above?
(it's clear the impact is throughout)

```shell
# Commits on Oct 25, 2022
git checkout 15819a1

# Commits on Nov 3, 2022
git checkout 5270a75

# Commits on Nov 16, 2022
git checkout c7cbe77

# Commits on Nov 26, 2022
git checkout e772ebe

# Commits on Dec 1, 2022
git checkout d817d80

# Commits on Dec 7, 2022
git checkout 7125dc6

# Commits on Dec 13, 2022
git checkout 6a73603

# Commits on Dec 28, 2022
git checkout ff4366a
```

What's your pytorch etc environment like?

**Comment by Gastron** [comment]
Huh, I think in #1683 I may have introduced a bug. When loading a CyclicLRScheduler with a custom scale function, I think the scale function gets overwritten in the loading.

However, in this recipe, the LR scheduling is NewBob, so it is not the issue here.

**Comment by anautsch** [comment]
@Gastron trying to limit down the error scope. In the commit ID checkouts, I put intentionally one before & one after your PR. To be sure, that this one is not the reason why.

It might be to @mzboito environment and dependencies starting to run into conflict with one another.

@Gastron as you pointed out, the LR ckpt loading works just fine. As @TParcollet pointed to, it might be other things could be missing. Let's investigate this a bit. Narrowing down the error scope will help us better to gain focus for next steps.

**Comment by mzboito** [comment]
> @mzboito please checkout by commit ID and retest one of the above? (it's clear the impact is throughout all of your checkpoints)
> 
> ```shell
> # Commits on Oct 25, 2022
> git checkout 15819a1
> 
> # Commits on Nov 3, 2022
> git checkout 5270a75
> 
> # Commits on Nov 16, 2022
> git checkout c7cbe77
> 
> # Commits on Nov 26, 2022
> git checkout e772ebe
> 
> # Commits on Dec 1, 2022
> git checkout d817d80
> 
> # Commits on Dec 7, 2022
> git checkout 7125dc6
> 
> # Commits on Dec 13, 2022
> git checkout 6a73603
> 
> # Commits on Dec 28, 2022
> git checkout ff4366a
> ```
> 
> for some it should work, and for others break directly. (You have a testing set-up ready on your end.)

Ok! I will try it

> What's your pytorch etc environment like?
using venv with:
Python 3.9.4
torch '1.9.0+cu111'
speechbrain '0.5.13' (-e git+https://github.com/speechbrain/speechbrain.git@11c70de96b3cc33ccd31fad7e470297e5c0ca69f#egg=speechbrain)
transformers '4.24.0'

**Comment by mzboito** [comment]
Hi all,

I tried the oldest head (15819a1) first, and the problem already exist on that one. Is it worth it going over the other heads?

**Comment by anautsch** [comment]
Nope...
I also doubt it's of great benefit to continue with ealier commit IDs. 
(you can try; I've a feeling it's not that)

Last thing that I have in mind as a compatability issue:

Please create a new python environment and installt the latest develop branch version there, such that all needed requirements are also up to date (don't want to meddle with your setup).

**Comment by mzboito** [comment]
Hi,

I made a new environment and installed speechbrain on the latest requirements. However, I installed torch *before* installing the requirements, because otherwise you get torch cpu version installed. The problem is still there. :(

The differences between the environments are very minimal. For torch, the versions are the following:
old vs new environment
transformers 4.24.0 vs 4.26.1
torch 1.9.0+cu111 vs 1.11.0+cu113
torchaudio 0.9.0 vs 0.11.0+cu113
torchvision 0.10.0+cu111 vs 0.12.0+cu113
numpy 1.23.5 vs 1.24.2

**Comment by anautsch** [comment]
Hi @mzboito 
1. thank you for being that patient in hunting down the error options
2. wtf

Please note, that there were some changes we needed to implement with the latest pytorch versions, e.g. the aforementioned PR 1683.

With this new environment, does the same issue re-occur when re-loading after a few epochs? 
(maybe running 2-3 epochs is enough; and then loading the 1st epoch's checkpoint - I hope that's not too time/GPU-intensive)

I feel a bit sorry that I haven't run a check yet on my side - you gave all information so that we could - there's a PR on my desk since a few months which I just want to get done with - at least sync it with the latest develop version before the weekend.

**Comment by anautsch** [comment]
btw - with the PR 1600, I edited your recipe a bit, so we can test it automatically, I hope these changes were ok.

**Comment by mzboito** [comment]
Hi Andreas,

Sorry! My message was misleading. When I say it doesn't work, I mean that I started training from scratch for 11 epochs, stopped training, removed the checkpoint for epoch 11 (thus restarting from epoch 10) and relaunched the model. 
I noticed a BLEU degradation from 5.37 to 4.55 in this case. The difference is smaller (compared to the 14 BLEU I lose for some other setups), but i think this is mainly because the BLEU was not high in the first place.

**Comment by anautsch** [comment]
Marcely, recommendation for action?

**Comment by mzboito** [comment]
It would be great if you could try to reproduce the same behavior using the recipe.
It should be straightforward, and the corpus is only 17h, so it should also be pretty fast.
Just run it for ~10ish epochs (30min, 1h max on a v100), kill it, remove the last checkpoint, relaunch and check what happens.

If you reproduce the error, then it's something on SB's end, if not, then it's my mess to figure out.
It is true that the main difference between the time when I didn't have this issue and now is my place of employment. So it could still be an environment  issue, but I'm unable to check this.

**Comment by anautsch** [comment]
@mzboito maybe @Gastron had another point, please take a look at:
https://pypi.org/project/sacrebleu/#history

Which versions are in your environments?

Re-running your recipe now; will open a PR to add an extra_requirements file. I missed that this file was missing when reviewing your initial recipe PR.

**Comment by mzboito** [comment]
Hi again :)

I'm not sure I get the problem with sacrebleu, as it is just a scorer, but I checked and both environments (old one from original issue, torch 1.9, and new one, torch 1.11) use sacrebleu 2.3.1, which is the latest version.

Thanks for the help. Let me know!

**Comment by anautsch** [comment]
Hi @mzboito got back to this over the afternoon. My status is inconclusive. There are some differences between your recipe and e.g. LibriSpeech recipes. That in itself shouldn't be the issue bc hey it's a new view.

Your approach to cut-off layers from the wav2vec2 is reflected in the stored `wav2vec2.ckpt`. If the cut-off layers would be stored as well, it would be larger (tested it), and if the hparam layers would not be cut-off in the code, it would fail also (tested as well). These CKPT files also differ between epoch saves.

Other recipes use pretrainer, why did you drop it?
Example:
```yaml
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <save_folder>
   loadables:
      lm: !ref <lm_model>
      tokenizer: !ref <tokenizer>
   paths:
      lm: !ref <pretrained_lm_tokenizer_path>/lm.ckpt
      tokenizer: !ref <pretrained_lm_tokenizer_path>/tokenizer.ckpt
```
```python
run_on_main(hparams["pretrainer"].collect_files)
hparams["pretrainer"].load_collected(device=run_opts["device"])
```

Yet, this could be the reason - but shouldn't be ... checkpoints are recovered when fit starts...
https://github.com/speechbrain/speechbrain/blob/4f8e43ba2b87b07331c0ddf978ed4dc1bb6a9f6a/speechbrain/core.py#L837-L839

**Comment by mzboito** [comment]
Hi Andreas,

I am sorry, I forgot to let you know I am currently not using any cut-off for the wav2vec2 model (that line is commented), so that could not be the problem.
About the pretrainer: I removed those lines because I didn't have anything else to load (the tokenizer is created at dataio_prepare) other than the model that is recovered at .fit()

**Comment by anautsch** [comment]
Hi Marcely,

makes sense. I didn't get much further (it's prbly way simpler than I think it is). When the recipe starts, model parameters are as of the hparams file (w/o Brain class), and they seem to be always the same. Then, when instantiating the `st_brain`, these same values get transferred to device tensors so they remain as-is. Then, when fit() starts, `on_fit_start()` with the above checkpointer recovery is run. The st_brain parameters in model & wav2vec2 change. When the last checkpoint folder is moved, other values are loaded. Business as usual.

Looking at the recipe code's `compute_forward()` function, what is used: `self.modules.wav2vec2`; `self.modules.enc`; `self.modules.Transformer`; `self.modules.seq_lin` & `self.hparams.log_softmax` – the `valid_search` & `test_search` reference the Transformer & the seq_lin via hparams. The checkpointer as of hparams recovers all that.

Wondering if there's a random seed we missed to control which would have much more impact after a learning rate change (than just before that).

**Comment by anautsch** [comment]
@mzboito the above mentioned PR was merged and SB v0.5.14 released. Does the issue still occur with the latest version?

**Comment by mzboito** [comment]
Hello Andreas,

Thanks for the reminder, and sorry for the delay answering. I didn't have the time to test this yet, but I intend to do so in the following days!

**Comment by mzboito** [comment]
Indeed the issue still exists. :(

Without training interruption:
```
epoch: 23, lr_adam: 1.56e-06, new_lr_adam: 1.56e-06, lr_wav2vec: 1.35e-06, new_lr_wav2vec: 1.22e-06 - train loss: 31.58 - valid loss: 55.74, valid ACC: 6.96e-01, valid BLEU: 19.70, ...}
epoch: 24, lr_adam: 1.56e-06, new_lr_adam: 7.81e-07, lr_wav2vec: 1.22e-06, new_lr_wav2vec: 1.09e-06 - train loss: 31.53 - valid loss: 55.45, valid ACC: 6.99e-01, valid BLEU: 20.10, ...}
epoch: 25, lr_adam: 7.81e-07, new_lr_adam: 7.81e-07, lr_wav2vec: 1.09e-06, new_lr_wav2vec: 9.85e-07 - train loss: 31.45 - valid loss: 54.59, valid ACC: 7.05e-01, valid BLEU: 21.05, ...}
epoch: 26, lr_adam: 7.81e-07, new_lr_adam: 7.81e-07, lr_wav2vec: 9.85e-07, new_lr_wav2vec: 8.86e-07 - train loss: 31.39 - valid loss: 54.26, valid ACC: 7.07e-01, valid BLEU: 21.33, ...}
```

With training interruption:
```
epoch: 23, lr_adam: 1.56e-06, lr_wav2vec: 1.35e-06 - train loss: 31.58 - valid loss: 55.74, valid ACC: 6.96e-01, valid BLEU: 19.70, ...}
epoch: 24, lr_adam: 1.56e-06, lr_wav2vec: 1.22e-06 - train loss: 36.95 - valid loss: 63.37, valid ACC: 6.24e-01, valid BLEU: 12.80, ...}
epoch: 25, lr_adam: 1.56e-06, lr_wav2vec: 1.22e-06 - train loss: 37.82 - valid loss: 57.74, valid ACC: 6.69e-01, valid BLEU: 17.12, ...}
epoch: 26, lr_adam: 7.81e-07, lr_wav2vec: 1.09e-06 - train loss: 35.89 - valid loss: 56.21, valid ACC: 6.82e-01, valid BLEU: 18.54, ...}
```

**Comment by mzboito** [comment]
Hi,

I modified init_optimizers:

```
    def init_optimizers(self):
        # Initializes the wav2vec2 optimizer if the model is not wav2vec2_frozen
        if not self.hparams.wav2vec2_frozen:
            self.wav2vec_optimizer = self.hparams.wav2vec_opt_class(
                self.modules.wav2vec2.parameters()
            )
            if self.checkpointer is not None:
                self.checkpointer.add_recoverable(
                    "lr_annealing_wav2vec.ckpt", self.wav2vec_optimizer
                )
        self.adam_optimizer = self.hparams.adam_opt_class(
            self.hparams.model.parameters()
        )

        if self.checkpointer is not None:
            self.checkpointer.add_recoverable(
                "lr_annealing_adam.ckpt", self.adam_optimizer)
        
        def zero_grad(self, set_to_none=False):
            self.adam_optimizer.zero_grad(set_to_none)
            if not self.hparams.wav2vec2_frozen:
                self.wav2vec_optimizer.zero_grad(set_to_none)
```

Then run on mtedx for 7 epochs:
```
speechbrain.utils.train_logger - epoch: 6, lr_adam: 5.00e-05, lr_wav2vec: 6.56e-06 - train loss: 33.15 - valid loss: 47.50, valid ACC: 6.21e-01, valid BLEU: 14.99, valid BLEU_extensive: {'BLEU': 14.992658812087342, 'BP': 0.646426028826769, 'ratio': 0.6962350714961529, 'hyp_len': 39001, 'ref_len': 56017, 'precisions': [59.81385092689931, 28.433185404339252, 16.86230596957294, 10.09009009009009], 'bleu_score': 14.992658812087342}

speechbrain.utils.train_logger - epoch: 7, lr_adam: 5.00e-05, lr_wav2vec: 5.90e-06 - train loss: 31.82 - valid loss: 46.45, valid ACC: 6.32e-01, valid BLEU: 16.32, valid BLEU_extensive: {'BLEU': 16.319360300976673, 'BP': 0.6898240186652306, 'ratio': 0.7292250566792223, 'hyp_len': 40849, 'ref_len': 56017, 'precisions': [59.737080467086095, 29.166666666666668, 17.332852766264192, 10.371902769288637], 'bleu_score': 16.319360300976673}
```

Deleted epoch 7 and relaunched:
```
speechbrain.utils.train_logger - epoch: 7, lr_adam: 5.00e-05, lr_wav2vec: 5.90e-06 - train loss: 31.81 - valid loss: 46.95, valid ACC: 6.30e-01, valid BLEU: 15.72, valid BLEU_extensive: {'BLEU': 15.717292844420177, 'BP': 0.662133407756735, 'ratio': 0.7080707642322867, 'hyp_len': 39664, 'ref_len': 56017, 'precisions': [60.276321097216616, 29.238017577240193, 17.356927710843372, 10.3791422032043], 'bleu_score': 15.717292844420177}
```

BLEU difference: 0.6

**Comment by TParcollet** [comment]
Right but now the LR is loaded properly so the difference might simply be coming from the non-determinist aspect of the training?

**Comment by mzboito** [comment]
Yes, that's what I am thinking right now. 
Ha pointed out, however, that I am overwriting the LR annealing file with the optimizer now.
I'm gonna fix this and run a second sanity check and update the issue (hopefully close it as well ;) ).

Thank a lot for all the help.

**Comment by Adel-Moumen** [comment]
Hey @mhn226, we've already discussed this, but would it be possible for you to open a PR to fix this? It seems like the most straightforward solution since you already have the fix ready.

**Comment by Gastron** [comment]
Oh have a look at this:
https://github.com/speechbrain/speechbrain/blob/41583e09932baa314a92c30f62ed843c4b7b3049/recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec.py#L239-L240

Looks like in this recipe, the wav2vec 2.0 has its own optimizer. However, this optimizer is not checkpointed? That would explain the learning rate issue - the current learning rate (as well as other optimizer parameters) are saved as part of the optimizer state.

**Comment by mhn226** [comment]
Hi, like I said, IWSLT recipe lacks these two optimizers added in init_optimizers(). I tested and it worked fine if we have them there.

**Comment by mzboito** [comment]
Hi all.
Yes, Ha fix works! Thanks a lot for the sharp eye on this.
I'm gonna close this issue, and I'll be making a PR in the future to fix this on the IWSLT2022 recipe.
