### ISSUE TITLE
ARPAbet not supported?

### ISSUE THREAD

**Issue by burik193** [speechbrain/speechbrain#1862]
### Describe the bug

Tacotron2 doesn't produce usable spectrograms if the input is an ARPAbet string. 

### Expected behaviour

Hello,

I'm trying to get a good performance with other languages other than english and german. I'm using Tacotron2 class and found out, that it transforms the text sequence to vectors using **.utils.text_to_sequence** function. According to the documentation: 

_"Returns a list of integers corresponding to the symbols in the text.
    Converts a string of text to a sequence of IDs corresponding to the symbols in the text.
    The text can optionally have ARPAbet sequences enclosed in curly braces embedded
    in it. For example, "Turn left on {HH AW1 S S T AH0 N} Street."_

So my intital approach was just to turn my text into ARPAbet beforehand, put it in curly brackets (which works good) and then use **Tacotron2.encode_text** on them. While **.utils.text_to_sequence** works fine (but produces different vectors), the output I'm getting is not what it should be. Meaning: if one uses text input and its ARPAbet analogon for the same transformation, mel_spectrograms will be completely different.

So the question is if that's an expected behavior or rather a bug? And if it's possible to somehow use ARPAbet (or XSAMPA) instead of strings?

Thank you!

 

### To Reproduce
tacotron2 = Tacotron2_modifyed.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")
mel_output, mel_length, alignment = tacotron2.encode_text("{HH AH0 L OW1   W ER1 L D}")
mel_output1, mel_length1, alignment1 = tacotron2.encode_text(f"Hello world")

hifi_gan = HIFIGAN.from_hparams(source="speechbrain/tts-hifigan-ljspeech", savedir="tmpdir_vocoder")
waveforms = hifi_gan.decode_batch(mel_output[0])
display.display(display.Audio(waveforms.squeeze(1), rate=22050))

waveforms = hifi_gan.decode_batch(mel_output1[0])
display.display(display.Audio(waveforms.squeeze(1), rate=22050))

**Comment by Adel-Moumen** [comment]
Hi @BenoitWang, 

Could you please take a look? Thanks! :-)

**Comment by BenoitWang** [comment]
Hi @burik193, I think the docstring means that it is possible to train models with ARPAbet, but the model you fetched was only trained in characters. I would suggest training your own model if you have such data. 

@flexthink Hi Artem, do you think we have models that allow ARPAbet inputs please?

**Comment by burik193** [comment]
> Hi @burik193, I think the docstring means that it is possible to train models with ARPAbet, but the model you fetched was only trained in characters. I would suggest training your own model if you have such data.
> 
> @flexthink Hi Artem, do you think we have models that allow ARPAbet inputs please?

Hi @BenoitWang, many thanks for your quick response!

I had a feeling, that the model was only trained on ascii characters, but wondered, why the functionality allowed ARPAbet :)
I guess in my case I'll have to train my own model then!
