### ISSUE TITLE
[Bug]: AttributeError: 'ASR_TRAIN' object has no attribute 'zero_grad'

### ISSUE THREAD

**Issue by eric-debug666** [speechbrain/speechbrain#1879]
### Describe the bug

I encountered the AttributeError when training on the  conformer_small.yaml(../recipes/LibriSpeech/ASR/transformer/hparams).
I have replaced .zero_grad() into .zerograds() or .cleargrads(), but it didn't help at all. 
Can anybody help me? 
Thanks a loooooot.
![image](https://user-images.githubusercontent.com/62170105/224652911-8db57909-8707-4979-80de-4c2e9258c81e.png)

### Expected behaviour

help ne solve the problem I encountered.

### To Reproduce

![image](https://user-images.githubusercontent.com/62170105/224653402-7c5cf6b8-f9f2-4f59-abae-7def95fa28f3.png)

**Comment by AsuMagic** [comment]
`Brain.zero_grad()` appears to be relatively new (introduced 3 months ago). It's likely you copied a version of the recipe that depends on it, but that your SpeechBrain installation is older.

Two options:

- Check your SpeechBrain version using `pip show speechbrain`, and copy the recipe you're trying to use that matches that version, e.g. for `v0.5.13`: https://github.com/speechbrain/speechbrain/tree/v0.5.13
- Install/update SpeechBrain from git: https://github.com/speechbrain/speechbrain#install-with-github but do note that latest versions are less tested than actual releases.

**Comment by eric-debug666** [comment]
@AsuMagic 
Thanks for replying.
I have already update my SpeechBrain to the latest version, but I still encountered the same AttributeError. 
Is there other solutions ?

**Comment by eric-debug666** [comment]
Thanks for replying.
I finally solve problems by installing SpeechBrain through git, and updating pip install to 23.0.1 .

**Comment by AsuMagic** [comment]
Good to see it resolved, I'm assuming I can close the issue then.
