### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by psmoros** [speechbrain/speechbrain#1930]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nightfury99) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Adel-Moumen** [comment]
Hi @psmoros,

Thanks for opening this issue!

@TParcollet, @mravanelli, @pplantinga, could you please have a look at this? 

In the meantime, you can send me more informations at adel.moumen<at>univ-avignon.fr .

I will add the GitHub recommendation ASAP.

**Comment by TParcollet** [comment]
Hi, we would need to see more about this security issue first, but why not :-)

**Comment by psmoros** [comment]
Thanks for your fast response @Adel-Moumen ! Is this adel.moumen at univ-avignon.fr ?

**Comment by Adel-Moumen** [comment]
adel.moumen@univ-avignon.fr

**Comment by nightfury99** [comment]
Hi, any updates on this issue?

**Comment by Adel-Moumen** [comment]
Hi @nightfury99,

I'm waiting for further details :-) 

We are also working on this #1933 to add the SECURITY.md
