### ISSUE TITLE
[Docs]: `torch.distributed.launch` is deprecated, `torchrun` should be recommended

### ISSUE THREAD

**Issue by asumagic** [speechbrain/speechbrain#1937]
### Describe the bug

Many places in our documentation recommends to use `torch.distributed.launch`.

However, that option is being deprecated by upstream PyTorch: <https://pytorch.org/docs/stable/distributed.html#launch-utility>

The recommendation is to use `torchrun`, which is supposed to be functionally equivalent: <https://pytorch.org/docs/stable/elastic/run.html#launcher-api>

### Expected behaviour

SpeechBrain should recommend using `torchrun` in all the documentation - but we should check which version introduced it, and whether we still support versions that might not have it.  
Plus, we should check whether we might encounter any issues with that migration.

Quite a lot of the documentation in SB still recommends using the deprecated option, including the multigpu docs and some recipe READMEs.

### To Reproduce

Run any SB training job with DDP enabled (as documented in multigpu docs)

### Versions

At the time of writing, the `develop` tip `e353e95` is affected.

### Relevant log output

```shell
FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions
```

**Comment by Adel-Moumen** [comment]
Solved in #2158. Thanks @asumagic :)
