### ISSUE TITLE
[Feature Request]: process-kaldi-pitch-feats in kaldi

### ISSUE THREAD

**Issue by Pydataman** [speechbrain/speechbrain#1956]
### 🚀 The feature

Can you implement this function，process-kaldi-pitch-feats in kaldi

### Solution outline

no

### Additional context

no

**Comment by Adel-Moumen** [comment]
Hello,

Please add more context to your feature request such that we know why we should do it. 

Best

**Comment by Adel-Moumen** [comment]
Hello,

I'm closing this feature request due to a lack of activity from the author. Please reopen it and provide additional context for your feature request. Thank you!

Adel
