### ISSUE TITLE
[Bug]: CV multithread data preparation sometimes fails

### ISSUE THREAD

**Issue by TParcollet** [speechbrain/speechbrain#1958]
### Describe the bug

Sometimes, the data preparation of CommonVoice will stop in the middle and consider that everything is complete when it's not. In the screen for instance, only half of the data has been processed. This is happening when using DDP for me (dunno if it will happen without).
![image](https://user-images.githubusercontent.com/11910731/234359264-9b7df3cc-b8fa-42d1-be58-1f5b9e316cf7.png)

### Expected behaviour

Data preparation should create an entire csv file not half of it.

**Comment by AsuMagic** [comment]
I cannot reproduce the issue on my setup but I probably know why it happens: The code yields any jobs in the queue that have finished. But while as they are being yielded, these might have finished, so the queue may end up full depleted.

As a workaround until I make a PR, in `parallel.py`, you may swap out these two code blocks:

```python
            # try to enqueue as many jobs as there were just finished.
            # when the input is finished, the queue will not be refilled.
            for _ in range(to_queue_count):
                _enqueue_job()

            # as we must yield in order, try to deplete as much futures from the
            # start of the list as are currently available.
            while len(futures) != 0 and futures[0].done():
                yield from futures.popleft().result()
```

to

```python
            # as we must yield in order, try to deplete as much futures from the
            # start of the list as are currently available.
            while len(futures) != 0 and futures[0].done():
                yield from futures.popleft().result()

            # try to enqueue as many jobs as there were just finished.
            # when the input is finished, the queue will not be refilled.
            for _ in range(to_queue_count):
                _enqueue_job()
```

I'll refactor the logic a bit so that it is more robust and handles exceptions better as well.

**Comment by AsuMagic** [comment]
Actually, there might be more to it. I think I found a repro, I'll look into it this afternoon.
