### ISSUE TITLE
[Bug]: GPU OOM when start from checkpoints

### ISSUE THREAD

**Issue by My-captain** [speechbrain/speechbrain#1963]
### Describe the bug

Strictly speaking, this is not considered a GPU memory leak.

Details:

1. To my kownledge, SpeechBrain initializes the model from YAML file in the `load_hyperpyyaml`, and obviously the model parameters are randomly initialized at this time.
2. Then in the `Brain.__init__()` function, the randomly initialized model parameters will be sent to the target device, and the `fit()` function will be called.
3. However, if the program starts from a checkpoint, the `checkpoints.torch_recovery()` will send all the parameters in the checkpoint to the target device and load them into the model object.
4. At this point, **the optimizer still holds a reference to the model parameters that were randomly initialized in the first step**, so this part of the storage space will not be released. 
5. If the total size of the model parameters is exactly twice the size of the available memory, an OOM error will occur.

### Expected behaviour

I'm not sure if this can be considered a bug, but if SpeechBrain can ensure that the instantaneous storage space occupied during program startup does not exceed the actual model size, it would be very friendly to users with small VRAM.

To solve the problem simply and conveniently, I just sent the model to the CPU first and then loaded the checkpoint in `checkpoints.torch_recovery()`.

**Comment by Adel-Moumen** [comment]
Hey @Gastron could you please have a look? Thanks :)

**Comment by My-captain** [comment]
Thanks for your reply.
