### ISSUE TITLE
[Bug]: Not Found for url: https://huggingface.co/api/models/facebook/wav2vec2-large-lv60

### ISSUE THREAD

**Issue by jtrindade15** [speechbrain/speechbrain#1975]
### Describe the bug

When running the common voice pretrained model (found at: https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-en), I suddenly started getting the error in the title whilst trying to load the model as indicated:

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-en", savedir="pretrained_models/asr-wav2vec2-commonvoice-en")

**Full error:**

Exception has occurred: HfHubHTTPError
404 Client Error: Not Found for url: https://huggingface.co/api/models/facebook/wav2vec2-large-lv60 (Request ID: Root=1-645a5ad3-0d9e4b2c6cf0471a6aaeea6f)

Sorry, we can't find the page you are looking for.
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/facebook/wav2vec2-large-lv60

The above exception was the direct cause of the following exception:

  File "/home/jtrindade/Documents/kenansville_attack-master/kenan_attack.py", line 547, in <module>
    asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-en", savedir="pretrained_models/asr-wav2vec2-commonvoice-en")
huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/facebook/wav2vec2-large-lv60 (Request ID: Root=1-645a5ad3-0d9e4b2c6cf0471a6aaeea6f)

Sorry, we can't find the page you are looking for.

![image](https://github.com/speechbrain/speechbrain/assets/84677239/19281023-a9ec-4be9-8b52-ee918d70687b)

The model has been working since february, I haven't changed anything since I last used this model and there haven't occurred any recent updates to the models code, so I'm unsure if its a temporary error related to hugginface or if I am missing something.

### Expected behaviour

Expected behaviour would be for the ASR model to load seamlessly, which then could be used to transcribe audio files as seen below:

asr_model.transcribe_file(file_path)

This is all according to the instruction given in the hugginface page relative to this model.

**Comment by Adel-Moumen** [comment]
Hey @jtrindade15,

Could you please retry?

I think it was coming from HuggingFace and not from our side (see: https://twitter.com/julien_c/status/1656001632612622341?s=20).
