### ISSUE TITLE
[Feature Request]: More Guidance for Placeholders

### ISSUE THREAD

**Issue by flckv** [speechbrain/speechbrain#1985]
### 🚀 The feature

https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml

isn't this model training based on only audio? I am not sure why is there a csv file request specification. Can you clarify, please?

I am confused about the placeholders - the speechbrain wrapper requirements are not obvious. 

### Solution outline

I would like to pretrain wav2vec with librispeech audio only.

May you provide more guidance on what to put on placeholders after line 70?
https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml

for example, they do the same with wav2vec and librispeech and they give example values: https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-pretraining/README.md
or 
https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/config/pretraining/wav2vec2_base_librispeech.yaml

The possible range of values would be appreciated.

**Comment by Adel-Moumen** [comment]
Please have a look at https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing 

"The goal of data preparation is to create the data manifest files. These files tell SpeechBrain where to find the audio data and their corresponding transcriptions. They are text files written in the popular CSV and JSON formats." this is the main purpose of the csv files. They are generated automatically when running the recipe. You should only have to specify the data_folder path.
