### ISSUE TITLE
[Bug]: Pretrain wav2vec

### ISSUE THREAD

**Issue by flckv** [speechbrain/speechbrain#1989]
### Describe the bug

The documentation is confusing for pretraining wav2vec and none of the options work.

(1) In the readme the command suggested is: 
`python train_sb_wav2vec2.py hparams/wav2vec2_base.yaml`

however, when I run it 

(2) In the [training script ](https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py)the command suggested is:
_To run this recipe call python 

`train.py hparams/train_wav2vec.yaml --find_unused_parameters --max_grad_norm 0.0`

Authors
    * Rudolf Braun 2022
    * Guillermo Cámbara 2022
    * Titouan Parcollet 2022_

Problem: there is no "hparams/train_wav2vec.yaml" file under the directory: self-supervised-learning/wav2vec2/hparams

There is a train_sb_wav2vec2.py under self-supervised-learning/wav2vec2/ directory

### Expected behaviour

with the downloaded librispeech and after running the librispeech prep script I should be able to successfully start pertaining the wav2vec

**Comment by Adel-Moumen** [comment]
Hi,

this is a typo in the doc of the python file. Please try and use : python train_sb_wav2vec2.py hparams/wav2vec2_base.yaml

**Comment by Adel-Moumen** [comment]
Merged in #1993
