### ISSUE TITLE
[Bug]: Finetuning wav2vec on LibriSpeech dataset with recipe

### ISSUE THREAD

**Issue by Jasonlee1995** [speechbrain/speechbrain#1991]
### Describe the bug

<img width="700" alt="image" src="https://github.com/speechbrain/speechbrain/assets/49643709/51517350-c861-4e8b-b18c-2020a0e0e231">
<img width="500" alt="image" src="https://github.com/speechbrain/speechbrain/assets/49643709/dadd3f11-642e-4463-9783-82971939e092">

[error link](https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/CTC/train_with_wav2vec.py#L62)

<img width="500" alt="image" src="https://github.com/speechbrain/speechbrain/assets/49643709/ba1e98fd-0ba4-4b8a-b373-76928bf2c9d1">

[model forward link](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/lobes/models/huggingface_wav2vec.py#L298)

I followed the LibriSpeech training recipe [link](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/CTC) for reproduce.
(nothing changed)

But I stucked as above error and try to debug, but I cannot understand why error occured.

### Expected behaviour

Finetune well

### Versions

<img width="199" alt="image" src="https://github.com/speechbrain/speechbrain/assets/49643709/2560022d-5a65-41c2-ab35-14da5d38a131">

**Comment by Adel-Moumen** [comment]
Hello, 

could you please share your transformer version please? It might come from that. (Try to install the latest version of hugging face transformers)

**Comment by Jasonlee1995** [comment]
<img width="350" alt="image" src="https://github.com/speechbrain/speechbrain/assets/49643709/e4ea83d2-81b2-4b55-840b-83ff85afa14b">

I also tried library upgrade and rerun, but stucked again.

**Comment by Adel-Moumen** [comment]
Ok. I will have a look today. Thanks for raising this issue. :-)

**Comment by Adel-Moumen** [comment]
Hi @Jasonlee1995,

Unfortunately I'm not facing your issue... 

I have: 
transformers             4.29.2

And I git clone the develop branch of SpeechBrain:
speechbrain              0.5.14

Could you please bump your version of Speechbrain and tell me if the issue is still here please?https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Btw, I used this wav2vec model: speechbrain/ssl-wav2vec2-base-librispeech

Best.

**Comment by Jasonlee1995** [comment]
I don't have left gpus to test on for the develop brand of SpeechBrain, but I checked it works well by changing the codes below.

- Before (error)
``` python
feats = self.modules.wav2vec2(wavs, wav_lens)
```

- After (no error)
``` python
feats = self.modules.wav2vec2(wavs)
```
