### ISSUE TITLE
[Bug]: DDP Does Not Seem to Work When Resuming From Checkpoint

### ISSUE THREAD

**Issue by My-captain** [speechbrain/speechbrain#1999]
### Describe the bug

Thanks for your great work! Compared to other frameworks, SpeechBrain has enabled me to quickly get started with ASR-related experiments.
Recently, I encountered some issues with DDP when conducting experiments using SpeechBrain.

```python
def on_fit_start(self):
    """Gets called at the beginning of ``fit()``, on multiple processes
    if ``distributed_count > 0`` and backend is ddp.

    Default implementation compiles the jit modules, initializes
    optimizers, and loads the latest checkpoint to resume training.
    """
    # Run this *after* starting all processes since jit modules cannot be
    # pickled.
    self._compile_jit()

    # Wrap modules with parallel backend after jit
    self._wrap_distributed()

    # Initialize optimizers after parameters are configured
    self.init_optimizers()

    # Load latest checkpoint to resume training if interrupted
    if self.checkpointer is not None:
        self.checkpointer.recover_if_possible(device=torch.device(self.device))
```
1. I am using DDP for distributed training with 8 * V100 GPUs, and I found that the iteration speed is 8 times faster when training from a checkpoint compared to training from scratch.
2. Regarding the current workflow of SpeechBrain before `fit()` startup, performing `wrap_distributed` before `recover_checkpointer` during training causes the `modules` to not be wrapped by DDP when resuming the training from a checkpoint, while the Dataloader has already been wrapped by DistributedSampler. This results in the model using only 1/N of the dataset(for N is the count of GPUs).
3. From recent research, fine-tuning large models is a popular trend, and many people rely on DDP for accelerated training. If there are problems with DDP adaptation, a lot of computing power will be wasted, and users will need to redo their experiments.

I am considering modifying the flow of core.py on my own, but I don't have much experience with deep learning and may overlook other issues that need to be considered. I would greatly appreciate any help from anyone who can assist me.

Looking forward to your reply.
Best Wishes.

### Expected behaviour

DDP has good compatibility with the existing workflow.

**Comment by Gastron** [comment]
Recovering from a checkpoint in DDP should work. Do you have some logs or something, what happens when you use DDP and resume from a checkpoint?
