### ISSUE TITLE
[Bug]: Question about vocoder tts-hifigan-libritts-16kHz

### ISSUE THREAD

**Issue by vivian556123** [speechbrain/speechbrain#2012]
### Describe the bug

Hi, thanks for sharing this repo.

I am using this vocoder to reconstruct the melspectrogram. I have a wav of sample rate 16k, and the length of wav is 65280. I first extract the melspectrogram of hopsize=256 and windowsize=1024, and I get a melspec of dimension [80,245]. I turn it back to wav by using this vocoder, but the reconstructed wav has length 62720 (does not match the input)! The difference is always 2560

I checked the config of vocoder, including hopsize and window size, and they are the same as the mel extraction process. Although there is no significant difference when human listening, the objective evaluation, like stoi and snr and sdr are very very bad (stoi is only 0.15 and sisnr, sdr are negative! ). I think it is because the misalignment between input and the output, but how to fix this problem?
![image](https://github.com/speechbrain/speechbrain/assets/45330476/25ff14dc-bc49-4808-afdd-d07b196d482d)

### Expected behaviour

I want the input wav and the reconstructed wav to have the same shape. And the snr should be high

**Comment by wj-gxy** [comment]
Yes, I am the same way. By using sr=22050 and len=8192, all the parameters set in the paper resulted in mel sizes of 32, 80, and 32. Even with a vocoder, the same duration cannot be obtained.

**Comment by Adel-Moumen** [comment]
Hi @BenoitWang could you please have a look?

**Comment by vivian556123** [comment]
> 

Hi, I used exactly the same mel extractor, and all the parameters(hop size, win size) are the same. This problem still exits. It is strange that the difference between gt and reconstructed wav is 256*10 = 2560, instead of 256. I think the padding will not cause such a big mismatch?

**Comment by BenoitWang** [comment]
I ran the extraction code above and I got a mel-spec of dimension [80,256], do you still get [80,245] with the code above? I used `torch==1.13.1 torchaudio==0.13.1`
