### ISSUE TITLE
[Bug]: Wrong parameter's name in \speechbrain\utils\parameter_transfer.py caused loading wrong pretrained model file

### ISSUE THREAD

**Issue by netwsdk** [speechbrain/speechbrain#2026]
### Describe the bug

I tried Speech Recognition: Speech-to-text ([see this tutorial](https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing))

In the step3 : LM training
There is a error as below:
D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM>python train.py RNNLM.yaml
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/RNNLM/
speechbrain.pretrained.fetching - Destination 1000_unigram.model: local file in D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\..\Tokenizer\save\1000_unigram.model.
speechbrain.utils.parameter_transfer - Loading pretrained files for: tokenizer
speechbrain.utils.parameter_transfer - CLEMENT: loading: model_checkpoints\tokenizer.ckpt
speechbrain.core - Exception:
Traceback (most recent call last):
  File "D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\train.py", line 258, in <module>
    hparams["pretrainer"].load_collected(device=run_opts["device"])
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\parameter_transfer.py", line 316, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\parameter_transfer.py", line 333, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\checkpoints.py", line 202, in _load_spm
    obj.load(str(path))  # SentencePieceProcessor needs a string.
  File "C:\Users\netws\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Users\netws\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "model_checkpoints\tokenizer.ckpt": No such file or directory Error #2

It is a bug for there is a pretrained model file in RNNLM.yaml, which is "D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\..\Tokenizer\save\1000_unigram.model."

So I debug the code and figure out that "\speechbrain\utils\parameter_transfer.py" use a wrong parameter name in the function "load_collected".

### Expected behaviour

When do the step3 LM training, It ought to load the pretrained file "D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\..\Tokenizer\save\1000_unigram.model."

### To Reproduce

run "Speech Recognition: Speech-to-text ([see this tutorial]" on a local PC(win10).
(https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing))
In the step3 : LM training
python train.py RNNLM.yaml

### Versions

Just git clone the lastest code from github on June 8th.

### Relevant log output

```shell
D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM>python train.py RNNLM.yaml
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/RNNLM/
speechbrain.pretrained.fetching - Destination 1000_unigram.model: local file in D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\..\Tokenizer\save\1000_unigram.model.
speechbrain.utils.parameter_transfer - Loading pretrained files for: tokenizer
speechbrain.utils.parameter_transfer - CLEMENT: loading: model_checkpoints\tokenizer.ckpt
speechbrain.core - Exception:
Traceback (most recent call last):
  File "D:\AIGC\workspace\speechbrain\templates\speech_recognition\LM\train.py", line 258, in <module>
    hparams["pretrainer"].load_collected(device=run_opts["device"])
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\parameter_transfer.py", line 316, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\parameter_transfer.py", line 333, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "D:\AIGC\workspace\speechbrain\speechbrain\utils\checkpoints.py", line 202, in _load_spm
    obj.load(str(path))  # SentencePieceProcessor needs a string.
  File "C:\Users\netws\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Users\netws\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "model_checkpoints\tokenizer.ckpt": No such file or directory Error #2
```

### Additional context

I changed the code of "speechbrain\utils\parameter_transfer.py" to fix this bug.
Change "if name in self.is_local:“ to "if name in self.paths:"
Here is the my code:
def load_collected(self, device=None):
        """Loads the files that have been collected.

        Arguments
        ---------
        device : str
            Device on which to load, if you want to load to a specific device
            directly ( otherwise just leave it to None ).
        """
        logger.info(
            f"Loading pretrained files for: {', '.join(self.loadables)}"
        )
        paramfiles = {}
        for name in self.loadables:
            if not self.is_loadable(name):
                continue
            filename = name + PARAMFILE_EXT
            paramfiles[name] = self.collect_in / filename
            if name in self.paths:
            # if name in self.is_local: # Clement Debug: this is wrong parameter's name, caused load wrong model pretrained file!!!
                logger.info(
                    f"Redirecting (loading from local path): {paramfiles[name]} -> {self.paths[name]}"
                )
                paramfiles[name] = self.paths[name]
        self._call_load_hooks(paramfiles, device)

**Comment by Adel-Moumen** [comment]
Hey @netwsdk, 

Thanks for opening this issue. 

Could you please retry with the latest develop version of SpeechBrain ? We fixed a bug that could be similar to yours. 

Thanks. 

Adel

**Comment by netwsdk** [comment]
I tried again, it is fixed!
Thanks!
