### ISSUE TITLE
IndexError: Out of range:

### ISSUE THREAD

**Issue by zhengqing187** [speechbrain/speechbrain#2032]
### Describe the bug

```
Traceback (most recent call last):
  File "train_with_wav2vec2.py", line 374, in <module>
    valid_loader_kwargs=hparams["dataloader_opts"],
  File "/home/zhengbeida/anaconda3/envs/slurp/lib/python3.7/site-packages/speechbrain/core.py", line 1225, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/zhengbeida/anaconda3/envs/slurp/lib/python3.7/site-packages/speechbrain/core.py", line 1078, in _fit_train
    loss = self.fit_batch(batch)
  File "train_with_wav2vec2.py", line 143, in fit_batch
    loss = self.compute_objectives(predictions, batch, sb.Stage.TRAIN)
  File "train_with_wav2vec2.py", line 89, in compute_objectives
    for utt_seq in predicted_tokens
  File "train_with_wav2vec2.py", line 89, in <listcomp>
    for utt_seq in predicted_tokens
  File "/home/zhengbeida/anaconda3/envs/slurp/lib/python3.7/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/home/zhengbeida/anaconda3/envs/slurp/lib/python3.7/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/home/zhengbeida/anaconda3/envs/slurp/lib/python3.7/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
```

After running a few epochs, the problem suddenly appears and then disappears when running again. 35 epochs sometimes have this problem several times, will it have any effect on the final result?

### Expected behaviour

Have you encountered this problem? The experiment I am running is SLURP. how do I fix this?

### To Reproduce

I only modified the path to the dataset and the path to the saved file.

### Versions

```
SpeechBrain system description
==============================
Python version:
3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0]
==============================
Installed Python packages:
appdirs==1.4.4
attrs==23.1.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
distlib==0.3.6
entrypoints==0.3
filelock==3.12.0
flake8==3.7.9
fsspec==2023.1.0
huggingface-hub==0.15.1
HyperPyYAML==1.2.1
identify==2.5.24
idna==3.4
importlib-metadata==6.6.0
joblib==1.2.0
jsonlines==3.1.0
mccabe==0.6.1
more-itertools==9.1.0
nodeenv==1.7.0
numpy==1.21.6
packaging==23.1
pandas==1.3.5
pathspec==0.11.1
Pillow==9.5.0
platformdirs==3.5.1
pluggy==0.13.1
pre-commit==2.21.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
scipy==1.7.3
sentencepiece==0.1.99
six==1.16.0
speechbrain==0.5.14
tokenizers==0.13.3
toml==0.10.2
torch==1.9.0
torchaudio==0.9.0
torchvision==0.10.0
tqdm==4.65.0
transformers==4.29.2
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==2.0.2
virtualenv==20.23.0
wcwidth==0.2.6
yamllint==1.23.0
zipp==3.15.0
==============================
Could not get git revision==============================
CUDA version:
10.2
```

**Comment by Adel-Moumen** [comment]
Hello, 

Could you please share the size of your vocab / embedding of your decoder etc? I suspect that there is a mismatch between both. 

Best.

**Comment by zhengqing187** [comment]
# URL for the wav2vec2 model, you can change to benchmark diffrenet models
wav2vec2_hub: "facebook/hubert-base-ls960"

# Training parameters
number_of_epochs: 35
batch_size: 6
lr: 0.0003
lr_wav2vec2: 0.00001
# token_type: unigram # ["unigram", "bpe", "char"]
sorting: random
ckpt_interval_minutes: 15 # save checkpoint every N min

#freeze all wav2vec2
freeze_wav2vec2: False

#set to true to freeze the CONV part of the wav2vec2 model
freeze_wav2vec2_conv: True

# Model parameters
sample_rate: 16000
emb_size: 128
dec_neurons: 512
output_neurons: 58 # index(eos/bos) = 0
encoder_dim: 768

# Decoding parameters
bos_index: 0
eos_index: 0
min_decode_ratio: 0.0
max_decode_ratio: 10.0
slu_beam_size: 80
eos_threshold: 1.5
temperature: 1.25

dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Models
wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec2>
    save_path: !ref <save_folder>/wav2vec2_checkpoint

output_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: !ref <encoder_dim>
    input_size: !ref <emb_size>
    rnn_type: lstm
    attn_type: content
    hidden_size: !ref <dec_neurons>
    attn_dim: 512
    num_layers: 3
    scaling: 1.0
    dropout: 0.0

seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

modules:
    wav2vec2: !ref <wav2vec2>
    output_emb: !ref <output_emb>
    dec: !ref <dec>
    seq_lin: !ref <seq_lin>

model: !new:torch.nn.ModuleList
    - [!ref <output_emb>,
       !ref <dec>, !ref <seq_lin>]

tokenizer: !new:sentencepiece.SentencePieceProcessor

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>/SLURP_tokenizer
    loadables:
        tokenizer: !ref <tokenizer>
    paths:
        tokenizer: !ref <tokenizer_file>/tokenizer_58_unigram.model

beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <output_emb>
    decoder: !ref <dec>
    linear: !ref <seq_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <slu_beam_size>
    eos_threshold: !ref <eos_threshold>
    temperature: !ref <temperature>
    using_max_attn_shift: False
    max_attn_shift: 30
    coverage_penalty: 0.

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec2_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec2>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

lr_annealing_wav2vec2: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec2>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        scheduler: !ref <lr_annealing>
        lr_annealing_wav2vec2: !ref <lr_annealing_wav2vec2>
        counter: !ref <epoch_counter>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

seq_cost: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True




The content of yaml file I only modified the path of dataset and the path to save the model, the others were not modified, the problem sometimes appears suddenly after running several epochs, sometimes it is IndexError: Out of range: piece id is out of range.
To debug, wrap `fit()` with autograd's `detect_anomaly()`, e.g., the word list size is 128, and the decoding is done by the same method.
, the word list size is 128, and the input dimension of the decoder is 768 dimensions.

**Comment by zhengqing187** [comment]
Hello
Could the reason for this problem be due to the version?

**Comment by zhengqing187** [comment]
Hello
Sorry, my answer is wrong, vocab_size is 58, not 128.
The project I reproduced is SLURP, which is a sequence-to-sequence project. The model structure of this project consists of the following parts. (1) Extracting a 768-dimensional speech feature using HuBert. (2) Decoding using 3 layers of lstm+attention. Where the output of lstm is 512 dimensions and attention is used Q,K,V. Its output is 512 dimensions. (3) The output of (2) is passed through a linear layer, and the output of the linear layer is 58, which is vocab_size.(4) The loss function used is NLL loss.@Adel-Moumen

**Comment by zhengqing187** [comment]
hello
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/train_with_wav2vec2.py,https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
This is the SLURP link I am reproducing, I have changed the path to load the dataset, the path to save it and the batch size is set to 2. The reproduced device is 3090. thanks very much.

**Comment by zhengqing187** [comment]
Hello:
I checked the solution for https://github.com/speechbrain/speechbrain/pull/1186, https://github.com/speechbrain/speechbrain/pull/1183, but still the Loss is not finite and patience is exhausted, I tried to retrain a tokenizer_bpe51 but got RuntimeError: Internal: src/trainer_ interface.cc(581) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is Increase vocab size or decrease character_coverage with --character_coverage option. It indicates that vocab_size needs to be greater than or equal to 58. So, how do I solve this problem now?@ Adel-Moumen

**Comment by WangHelin1997** [comment]
Hi @Adel-Moumen, I also have this problem. Can someone take a look at this? Thanks.

**Comment by zhengqing187** [comment]
Hi @https://github.com/WangHelin1997,You can try to set output_neurons = 51, for the time being, I have successfully reproduced the lstm+content and lstm+keyvalue experiments without the above problem in between. But the reason for this mismatch in the original code is still unclear to me. You can consult the person in charge.@https://github.com/Adel-Moumen

**Comment by zhengqing187** [comment]
Hi ,@WangHelin1997,You can try to set output_neurons = 51, for the time being, I have successfully reproduced the lstm+content and lstm+keyvalue experiments without the above problem in between. But the reason for this mismatch in the original code is still unclear to me. You can consult the person in charge.@Adel-Moumen

**Comment by mhn226** [comment]
Hi @zhengqing187 , should we consider this done also?

**Comment by zhengqing187** [comment]
Hi @[mhn226](https://github.com/mhn226)
Yes, I have no more problems for now, thank you very much.
