### ISSUE TITLE
[Bug]: RuntimeError: Error(s) in loading state_dict for HuggingFaceWhisper

### ISSUE THREAD

**Issue by Marwan-Ghouma** [speechbrain/speechbrain#2034]
### Describe the bug

size mismatch for _mel_filters: copying a param with shape torch.Size([80, 201]) from the checkpoint, the shape in the current model is torch.Size([201, 80]).

when i transpose the mel_filters tensor on the checkpoint, the model loaded but when transcribing gives a matrix multiplication error :

File /opt/conda/lib/python3.10/site-packages/speechbrain/lobes/models/huggingface_whisper.py:247, in HuggingFaceWhisper._log_mel_spectrogram(self, audio)
244 magnitudes = stft[..., :-1].abs() ** 2
246 filters = self._mel_filters
--> 247 mel_spec = filters @ magnitudes

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3000x201 and 80x201)

I use torch.version '2.0.0+cu117'

It works when I reshape the feature_extractor.filter on speechbrain in /speechbrain/lobes/models/huggingface_whisper.py

but I don't know if this is a good way to fix it

### Expected behaviour

loading the whisper model and transcribe audio 

### To Reproduce

```python #
pip install speechbrain transformers

from speechbrain.pretrained import WhisperASR

asr_model = WhisperASR.from_hparams(source="speechbrain/asr-whisper-large-v2-commonvoice-ar", savedir="pretrained_models/asr-whisper-large-v2-commonvoice-ar")
asr_model.transcribe_file("speechbrain/asr-whisper-large-v2-commonvoice-ar/example-ar.mp3")
 ```

### Versions

torch.version '2.0.0+cu117'

### Relevant log output

```shell
size mismatch for _mel_filters: copying a param with shape torch.Size([80, 201]) from the checkpoint, the shape in the current model is torch.Size([201, 80]).
```

**Comment by Adel-Moumen** [comment]
Hello @Marwan-Ghouma,

Thanks for raising this issue. 

The problem is coming from the transformer toolkit, basically they release a new version that is changing Whisper. 

We are working on it! Could you please in the meantime downgrade your version of transformer please? 

Many thanks.

Best.

**Comment by Marwan-Ghouma** [comment]
Thanks, it works with transformers-4.26.0 !
