### ISSUE TITLE
Update Common Voice recipes

### ISSUE THREAD

**Issue by Adel-Moumen** [speechbrain/speechbrain#2039]

**Comment by Adel-Moumen** [comment]
@lucadellalib

**Comment by mravanelli** [comment]
@poonehmousavi

**Comment by mravanelli** [comment]
You should run the experiment starting from the latest dev branch. You can
start the experiments for all the languages except French. Salima should
update the French preprocessing soon.

**Comment by Adel-Moumen** [comment]
> You should run the experiment starting from the latest dev branch. 

Hey @mravanelli, what do you think about training smaller Whisper models for each languages? On the hub we have several Whisper large-v2 models, but they consumes a lot of vram and they are slow at inference time. I propose to train (and release on the HF hub) Whisper models such as the base (74M) or the small (244M) instead of the large-v2 (1550M). Furthermore, if we have time, it would be great to replicate a little bit what @bofenghuang did in his blog post (see: https://medium.com/@bofenghuang7/what-i-learned-from-whisper-fine-tuning-event-2a68dab1862) in terms of hyper parameters (I believe we should be able to improve the WER with this setting).

**Comment by mravanelli** [comment]
Yes,
we can release a fine-tuned Whisper for all the languages currently in
CommonVoice. Pooneh has already experience with that.

**Comment by poonehmousavi** [comment]
I will do that but currently, as @Adel-Moumen we have several Whisper large-v2 models, but they consume a lot of vram and they are slow at inference time. Should we train medium or base  Whisper models instead of the large one so it could be more applicable for the release on the HF hub?

**Comment by mravanelli** [comment]
Yes, small models are fine.
