### ISSUE TITLE
Annoying Warning ( CTCTextEncoder)

### ISSUE THREAD

**Issue by mravanelli** [speechbrain/speechbrain#2046]
### Describe the bug

When running recipes that involve CTC, we always output the following warning:
```

/scratch/ravanelm/speechbrain/speechbrain/dataio/encoder.py:722: UserWarning: CTCTextEncoder.expect_len was never called: assuming category count of 40 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
  warnings.warn(
```

This can be useful, but it is very annoying if it comes out every time. Aku, do you see a fix for that?

### Expected behaviour

-

### To Reproduce

-

### Versions

-

### Relevant log output

```shell
-
```

### Additional context

-

**Comment by Adel-Moumen** [comment]
@AsuMagic

**Comment by mravanelli** [comment]
@Gastron, any insight on that? It is pretty annoying as it appears every time we run a recipe with CTC.

**Comment by mravanelli** [comment]
Similarly, we often see this warning: "`UserWarning: CategoricalEncoder.expect_len was never called: assuming category count of 4 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.`". How can we avoid that to happen when running a recipe?

**Comment by mravanelli** [comment]
It looks like it is a change you made @AsuMagic . This causes many unnecessary warnings while running some recipes (e.g,, TIMIT)

**Comment by AsuMagic** [comment]
Yes, the change was intentional to prevent accidental mismatches. At the time of the PR I didn't update recipes (partly because IIRC recipe tests weren't that ready back then). Will need to look into it.

**Comment by AsuMagic** [comment]
I don't think I will have the time to update all recipes given the work time I have left (on top of existing PRs+streaming), so I spent some time thinking about how the warning should be improved instead. Right now, it looks like:

> CTCTextEncoder.expect_len was never called: assuming category count of 1000 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.

I had some ideas for shorter messages but discussing it with an (uninvolved) developer, it seems to me that the verbosity remains useful/necessary and that my attempts at shorter warnings were not better.

So, would just revising the tone of the first sentence and adding a notice in the warning that states "This may be normal, users can ignore this." suffice?

**Comment by Adel-Moumen** [comment]
any updates @mravanelli ?
