### ISSUE TITLE
[Bug]: Python version

### ISSUE THREAD

**Issue by WangHelin1997** [speechbrain/speechbrain#2063]
### Describe the bug

I was using `train_with_wav2vec2.py` but it came to a bug called `Segmentation fault      (core dumped)`.
I found that it was caused by `Python=3.7`.
If I change to new version of Python, it will be solved.

### Expected behaviour

Check for this.

**Comment by AsuMagic** [comment]
Difficult to say why that would be without being able to dig into the source of the segfault itself. Right now, I'm tempted to say it has more to do with a setup/package issue that you accidentally solved by recreating an environment with a newer Python version. Would need more testing to be able to tell.

I don't know if this warrants more investigation at the moment, but having this as an easily searchable issue should suffice in the mean time (especially as we may end up deprecating 3.7 in a not so distant future, AFAIK).

**Comment by pplantinga** [comment]
3.7 is EOL, let's mark this won't fix.
