### ISSUE TITLE
[Bug]: The pre-trained model is deployed to GPU but still processes input tensor on CPU?

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#2076]
### Describe the bug

Hi all! So I wanna ask a question about our lobe model hosted on hugging face. I am not sure if this is the right channel but since we don't have a Q&A channel I will post it here. Sorry for the noise.

I call this model in this way:
```
# load model
self.model = SpeakerRecognition.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb",
    savedir="pretrained_models/spkrec-ecapa-voxceleb",
)
self.device = "cuda" if torch.cuda.is_available() else "cpu"
self.model.to(self.device)
```
So the model is put onto GPU device. 

### Expected behaviour

However, I found that when processing the tensor, even though the original tensor is put onto CUDA, it still will be processed back to CPU and thus the error will look like:
```
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```
I then found in speechbrain/pretrained/interfaces.py , line 190, we have the default device setting up to CPU. 
```
run_opt_defaults = {
            "device": "cpu",
            "data_parallel_count": -1,
            "data_parallel_backend": False,
            "distributed_launch": False,
            "distributed_backend": "nccl",
            "jit_module_keys": None,
}
```
Is this option being changed with the model? If not, is there anyway to change it?

**Comment by ShamanthNyk** [comment]
Hello,

I am assuming you are encountering this issue during the inference. The default parameters that are on line 190 actually come into play when you call the from_hparams() method. (see line 187)
Try adding run_opts={"device":"cuda"}  to the from_hparams() method. This overrides the default setting.

**Comment by underdogliu** [comment]
@ShamanthNyk Thanks a lot and that solves my problem! I will close this issue.

**Comment by ShamanthNyk** [comment]
You're welcome!
