### ISSUE TITLE
ValueError: Loss is not finite and patience is exhausted.

### ISSUE THREAD

**Issue by leilei183** [speechbrain/speechbrain#2085]
### Describe the bug

Dear Project Maintainers:
       When I tried to use the article "A FINE-TUNED WAV2VEC 2.0/HUBERT BENCHMARK FOR SPEECH EMOTION RECOGNITION, SPEAKER VERIFICATION AND SPOKEN LANGUAGE UNDERSTANDING" in the This problem occurred when experimenting with the configuration of the SLURP project (gru+content). The problem appeared after running some epochs.
       I tried to change output_neurons = 51, because the vocab_size of tokenizer = 51, but still the above problem occurs.
       I tried to configure gru+keyvalue again and still have the above problem.
       Do you have any solution for this?

### Expected behaviour

Fixing the bug

### Versions

Python version:
3.7.12
[GCC 9.4.0]
appdirs==1.4.4
attrs==23.1.0
black==19.10b0
certifi==2023.5.7
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
distlib==0.3.6
entrypoints==0.3
filelock==3.12.0
flake8==3.7.9
fsspec==2023.1.0
huggingface-hub==0.14.1
HyperPyYAML==1.2.0
identify==2.5.24
idna==3.4
importlib-metadata==6.6.0
joblib==1.2.0
jsonlines==3.1.0
mccabe==0.6.1
more-itertools==9.1.0
nodeenv==1.7.0
numpy==1.21.6
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
packaging==23.1
pandas==1.3.5
pathspec==0.11.1
Pillow==9.5.0
platformdirs==3.5.1
pluggy==0.13.1
pre-commit==2.21.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.30.0
ruamel.yaml==0.17.26
ruamel.yaml.clib==0.2.7
scipy==1.7.3
sentencepiece==0.1.99
six==1.16.0
speechbrain==0.5.14
tokenizers==0.13.3
toml==0.10.2
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.1
tqdm==4.65.0
transformers==4.29.2
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==2.0.2
virtualenv==20.23.0
wcwidth==0.2.6
yamllint==1.23.0
zipp==3.15.0
CUDA version:
11.7

### Relevant log output

```shell
Traceback (most recent call last):
  File "train_with_wav2vec2.py", line 379, in <module>
    valid_loader_kwargs=hparams["dataloader_opts"],
  File "/anaconda3/envs/SLU/lib/python3.7/site-packages/speechbrain/core.py", line 1225, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/anaconda3/envs/SLU/lib/python3.7/site-packages/speechbrain/core.py", line 1078, in _fit_train
    loss = self.fit_batch(batch)
  File "train_with_wav2vec2.py", line 150, in fit_batch
    if self.check_gradients(loss):
  File "/anaconda3/envs/SLU/lib/python3.7/site-packages/speechbrain/core.py", line 1007, in check_gradients
    "Loss is not finite and patience is exhausted. "
ValueError: Loss is not finite and patience is exhausted. To debug, wrap `fit()` with autograd's `detect_anomaly()`, e.g.

with torch.autograd.detect_anomaly():
	brain.fit(...)
```

### Additional context

wav2vec2_hub: facebook/hubert-base-ls960

# Training parameters
number_of_epochs: 35
batch_size: 4
lr: 0.0003
lr_wav2vec2: 0.00001
# token_type: unigram # ["unigram", "bpe", "char"]
sorting: random
ckpt_interval_minutes: 15 # save checkpoint every N min

#freeze all wav2vec2
freeze_wav2vec2: false

#set to true to freeze the CONV part of the wav2vec2 model
freeze_wav2vec2_conv: true

# Model parameters
sample_rate: 16000
emb_size: 128
dec_neurons: 512
output_neurons: 51 # index(eos/bos) = 0
encoder_dim: 768

# Decoding parameters
bos_index: 0
eos_index: 0
min_decode_ratio: 0.0
max_decode_ratio: 10.0
slu_beam_size: 80
eos_threshold: 1.5
temperature: 1.25

dataloader_opts:
  batch_size: 4
  shuffle: true

epoch_counter: &id009 !new:speechbrain.utils.epoch_loop.EpochCounter

  limit: 35

# Models
wav2vec2: &id001 !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
  source: facebook/hubert-base-ls960
  output_norm: true
  freeze: false
  save_path: /grucontent/1986/save/wav2vec2_checkpoint

output_emb: &id002 !new:speechbrain.nnet.embedding.Embedding
  num_embeddings: 51
  embedding_dim: 128

dec: &id003 !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
  enc_dim: 768
  input_size: 128
  rnn_type: gru
  attn_type: content
  hidden_size: 512
  attn_dim: 512
  num_layers: 3
  scaling: 1.0
  dropout: 0.0

seq_lin: &id004 !new:speechbrain.nnet.linear.Linear

  input_size: 512
  n_neurons: 51

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  sample_rate: 16000
  speeds: [95, 100, 105]

modules:
  wav2vec2: *id001
  output_emb: *id002
  dec: *id003
  seq_lin: *id004
model: &id006 !new:torch.nn.ModuleList
- [*id002, *id003, *id004]
tokenizer: &id005 !new:sentencepiece.SentencePieceProcessor

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: /grucontent/save/SLURP_tokenizer
  loadables:
    tokenizer: *id005
  paths:
    tokenizer: speechbrain/SLU-direct-SLURP-hubert-enc/tokenizer_58_unigram.model

beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
  embedding: *id002
  decoder: *id003
  linear: *id004
  bos_index: 0
  eos_index: 0
  min_decode_ratio: 0.0
  max_decode_ratio: 10.0
  beam_size: 80
  eos_threshold: 1.5
  temperature: 1.25
  using_max_attn_shift: false
  max_attn_shift: 30
  coverage_penalty: 0.

opt_class: !name:torch.optim.Adam
  lr: 0.0003

wav2vec2_opt_class: !name:torch.optim.Adam
  lr: 0.00001

lr_annealing: &id007 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0003
  improvement_threshold: 0.0025
  annealing_factor: 0.8
  patient: 0

lr_annealing_wav2vec2: &id008 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.00001
  improvement_threshold: 0.0025
  annealing_factor: 0.9

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: /grucontent/save
  recoverables:
    model: *id006
    wav2vec2: *id001
    scheduler: *id007
    lr_annealing_wav2vec2: *id008
    counter: *id009
log_softmax: !new:speechbrain.nnet.activations.Softmax
  apply_log: true

seq_cost: !name:speechbrain.nnet.losses.nll_loss
  label_smoothing: 0.1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: /grucontent/train_log.txt

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
  split_tokens: true

**Comment by BenoitWang** [comment]
Hi @leilei183, I could remember that I encountered this too but it didn't occur each time. So for now if you are still getting this, I would suggest reducing the learning rate to 1e-4 and see what happens.

**Comment by Adel-Moumen** [comment]
Hey, 

Thanks for opening this issue. 

There's an ongoing PR on these NaN issues in #2010. I will work on this next week. 

In the meantime, could you please give me the exact YAML that you used? A link to our YAML recipes would be great. Thanks.

Best, 
Ade;

**Comment by leilei183** [comment]
Hi@ Adel-Moumen ,Here's a link to the experiment I reproduced, https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by leilei183** [comment]
Hi@https://github.com/Adel-Moumen
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by leilei183** [comment]
Hi@Adel-Moumen
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by leilei183** [comment]
Hi@Adel-Moumen
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by leilei183** [comment]
Hi@Adel-Moumen
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by leilei183** [comment]
Hi @Adel-Moumen
https://github.com/speechbrain/speechbrain/blob/develop/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml,
I experimented with the following configuration: attn_type: content, rnn_type: gru

**Comment by Adel-Moumen** [comment]
Could you please check that `output_neurons: 58 # index(eos/bos) = 0` is equal to the size of your vocabulary please?

**Comment by leilei183** [comment]
Hi @Adel-Moumen
The vocabulary size is 51, I tried to put output_neurons: 51, but it still sometimes shows ValueError: Loss is not finite and patience is exhaust.

**Comment by Adel-Moumen** [comment]
Are you using automatic mixed precision ?

**Comment by leilei183** [comment]
I didn't pay attention to this one

**Comment by leilei183** [comment]
Yes, I checked the code and used mixed precision in the code.

**Comment by leilei183** [comment]
bfloat16

**Comment by leilei183** [comment]
hi@BenoitWang 
I'm inquiring about the tokenizer.ckpt you trained, what are the numbers for bos,eos,pad in it? Can you share your trained vocab_file with me please?

**Comment by leilei183** [comment]
hi@BenoitWang
I'm inquiring about the tokenizer.ckpt you trained, what are the numbers for bos,eos,pad in it? Can you share your trained vocab_file with me pleas

**Comment by leilei183** [comment]
hi@BenoitWang
I'm inquiring about the tokenizer.ckpt you trained, what are the numbers for bos,eos,pad in it? Can you share your trained vocab_file with me please?

**Comment by leilei183** [comment]
hi@https://github.com/BenoitWang
I'm inquiring about the tokenizer.ckpt you trained, what are the numbers for bos,eos,pad in it? Can you share your trained vocab_file with me please?

**Comment by leilei183** [comment]
hi @ [BenoitWang](https://github.com/BenoitWang)
I'm inquiring about the tokenizer.ckpt you trained, what are the numbers for bos,eos,pad in it? Can you share your trained vocab_file with me please?

**Comment by BenoitWang** [comment]
Hi @leilei183 , when I did my experiments I directly loaded the pretrained tokenizer which was the same as in hparams.yaml. But you can find all the information for the tokenizer training [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/SLURP/Tokenizer). bos,eos,pad should all be 0.
Are you getting the error with hubert base or large?  It's likely to be a convergence issue at the model level.

**Comment by leilei183** [comment]
For the time being, this problem only occurs with gru+keyvalue, using the hubert base.

**Comment by Adel-Moumen** [comment]
Any news @leilei183 ? Thanks :)

**Comment by leilei183** [comment]
Hi@[Adel-Moumen](https://github.com/Adel-Moumen),I'm inquiring if your seq2seq.py is encoded in UTF-8?
thanks

**Comment by leilei183** [comment]
Hi,@[BenoitWang](https://github.com/BenoitWang)
I am trying to reproduce your experiment using HUBERT-Large, is there any change in the epoch of HUBERT training in the Large version? Can you share the hyperparameter details of your experiment at that time?

**Comment by BenoitWang** [comment]
Hi @leilei183 sorry for the late response. There is no difference in my hparams between base and large models. Did you manage to reproduce the reported results?

**Comment by leilei183** [comment]
Hi@[BenoitWang](https://github.com/BenoitWang)
The hubert-base and wav2vec-base results are basically the same as in your paper, but the hubert-large results don't converge, and the link to the hubert-large model I used is as follows https://huggingface.co/facebook/hubert-large- ls960-ft, the configuration used is lstm+content.

**Comment by BenoitWang** [comment]
yes the non-convergence happened several times to me too. You can run the same experiment several times to see if it is always diverging... And maybe try the non-asr fine-tuned version **facebook/hubert-large-ll60k**.
