### ISSUE TITLE
[Bug]: ValueError: Need hparams['tokenizer']

### ISSUE THREAD

**Issue by Reginald-Gillespie** [speechbrain/speechbrain#2097]
### Describe the bug

The bug occurs when running this example: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.pretrained.interfaces.html#speechbrain.pretrained.interfaces.EncoderDecoderASR

I get a "ValueError: Need hparams['tokenizer']".

On Windows.

### Expected behaviour

Run without issue considering it is a basic example.

### Versions

Tried speechbrain-0.5.15 (pip) and speechbrain-0.5.14 (git).

### Relevant log output

```shell
...
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "c:\Users\Me\Documents\Project\sb.py", line 7, in <module>
    asr_model = EncoderDecoderASR.from_hparams(
  File "c:\Users\Me\Documents\Project\speechbrain\speechbrain\pretrained\interfaces.py", line 509, in from_hparams
    return cls(hparams["modules"], hparams, **kwargs)
  File "c:\Users\Me\Documents\Project\speechbrain\speechbrain\pretrained\interfaces.py", line 650, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\Me\Documents\Project\speechbrain\speechbrain\pretrained\interfaces.py", line 239, in __init__
    raise ValueError(f"Need hparams['{hp}']")
ValueError: Need hparams['tokenizer']
```

**Comment by Adel-Moumen** [comment]
Hello @Reginald-Gillespie, 

Could you please share the exact code that you used ? 

I'm unable to reproduce your issue. See the following google colab: https://colab.research.google.com/drive/1xYRK4DiwnoTM0hciKhRSb-13R4WQghRl?usp=sharing

**Comment by Reginald-Gillespie** [comment]
Interesting, your code worked for me. Here's my code (directly copied from that link):
```python
from speechbrain.speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(
    source="speechbrain/asr-crdnn-rnnlm-librispeech",
    savedir="/"
)
asr_model.transcribe_file("tests/samples/single-mic/example2.flac")
```

**Comment by Reginald-Gillespie** [comment]
Oh my save dir seems to be throwing it off?

**Comment by Reginald-Gillespie** [comment]
For some reason, my setting "savedir" to "/" makes it not work. I thought that would be where the models and all would be saved, but it's not, or at least doesn't work with just a "/", or something like that... so it's not an error with the code, just how I was using it.
