### ISSUE TITLE
[Bug]: Issue JIT Pretrainer model

### ISSUE THREAD

**Issue by Zeiny96** [speechbrain/speechbrain#2109]
### Describe the bug

Can't transform the ECAPA-TDNN speaker-recognition model into torch script
I keep receiving various issues whenever I try to solve one I face another is this even supported or not in this model?

### Expected behaviour

The expected behaviour was to be able to export the model with no issues

### To Reproduce

```py
from speechbrain.pretrained import SpeakerRecognition
model = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="pretrained_models/spkrec-ecapa-voxceleb")
model_jit = torch.jit.script(model)
```

**Comment by Adel-Moumen** [comment]
Hello @Zeiny96,

Thanks for opening this issue. 

This is not the way to go with SpeechBrain for compiling/jitting a model. You should add a dict with the key `jit` or `compile` with a boolean `True` and give it to your class (see: https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py#L200).

In practice it means doing:
```python
run_opt_defaults = {
        "jit": True
    }

model = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="pretrained_models/spkrec-ecapa-voxceleb", run_opts=run_opt_defaults)
``` 

Note: if you are using the dev branch, please see this PR #2110. I found a small issue that I fixed. 

Thanks again for opening this issue! :)
