### ISSUE TITLE
KeyError: 'split_ratio'

### ISSUE THREAD

**Issue by kevin00616** [speechbrain/speechbrain#2114]
### Describe the bug

Hi,I'm working with the Speaker Recognition which model is ECAPA-TDNN,
but when I stared training , I got some error.
Please help me to solve this problem.
My English is not good, so please forgive some of my weird words.

### Expected behaviour

The training process is done and I got the new model weight without error.

### To Reproduce

I try to use : 

python train_speaker_embeddings.py hparams/train_x_vectors.yaml

and i got this problem:

Traceback (most recent call last):
  File "train_speaker_embeddings.py", line 226, in <module>
    "split_ratio": hparams["split_ratio"],
KeyError: 'split_ratio'

**Comment by Adel-Moumen** [comment]
Hey, thanks for opening the issue. 

Could you please give me the recipe that you are using (e.g. AMI, VoxCeleb, etc...) ?

**Comment by kevin00616** [comment]
I'm using VoxCeleb2 dataset now.
And I follow this step to prepare the data set.
(https://github.com/speechbrain/speechbrain/tree/develop/recipes/VoxCeleb/SpeakerRec)

**Comment by kevin00616** [comment]
Finally I solved the problem,I found split_ratio in train_x_vectors.yaml,i set it and it work.
But I got the new quetion,I think maybe this quetion is about dataset's setting,
but I don't know what's wrong with my dataset.
You can refer to my attachment.
![Screenshot from 2023-08-10 13-37-25](https://github.com/speechbrain/speechbrain/assets/43717959/c174867a-f78f-4142-9887-71cacbaa87de)

**Comment by Adel-Moumen** [comment]
Hey @mravanelli, could you please have a look ?

**Comment by kevin00616** [comment]
I think that I don't have the file train.csv, or it doesn't affect.
If this affects the result , can you help me make the .csv file ?

**Comment by Adel-Moumen** [comment]
Could you please elaborate more? Thanks.

**Comment by kevin00616** [comment]
Finally,I used the author's csv file to make modifications, and finally successfully solved the problem.
You only need to modify the file path in the csv file to your own file path.

**Comment by Adel-Moumen** [comment]
Yes, you have to change the csv file to your own file path. If you want to better understand how SpeechBrain work I invite you to have a look at our tutorials. Furthermore, if this is issue is solved please close it. Thanks! :)
