### ISSUE TITLE
[Bug]: Incompatible with huggingface PEFT: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by caidongqi** [speechbrain/speechbrain#2121]
### Describe the bug

I want to use LoRa tuning to fine-tune Whisper, but after I installed peft (parameter-efficient finetuning), it comes to a `segmentation fault` for each speechbrain process (even I didn't import it).

I uninstalled peft, and the code runs normally again.

I have no idea whether this bug derives from Speechbrain or peft, is there anyone meets the same bug?

### Expected behaviour

I expected I could import `speechbrain` and `peft` simultaneously.

### To Reproduce

```
import speechbrain as sb
from peft import LoraConfig, get_peft_model
```

### Versions

speechbrain version is 0.5.14
peft version: I tried 0.2.0, 0.4.0, and both of them do not work.

### Relevant log output

```shell
Segmentation fault (core dumped)
```

**Comment by Adel-Moumen** [comment]
Hello @caidongqi, is the issue still up? I believe this is coming from `peft` as everything is working on my side.

**Comment by caidongqi** [comment]
Hello, I tried to install them both but it still fails. I guess it is related to my python environment. I will reinstall it later.

By the way, I have manually realized lora in the root code of whisper, which is the father class of speechbrain's WhisperLayer. Anyone interested in it or encountered the same question could refer to [lora implementation](https://zhuanlan.zhihu.com/p/618894919).
