### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride 

### ISSUE THREAD

**Issue by JordanFan860406** [speechbrain/speechbrain#2190]
### Describe the bug

When I try to train my own corpus using train.py from recipes, get  following error:
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### Expected behaviour

Normal training

**Comment by TParcollet** [comment]
Hi, this description is unfortunately insufficient for us to help.
