### ISSUE TITLE
 How to specify gpu to run？

### ISSUE THREAD

**Issue by wntg** [speechbrain/speechbrain#2202]
### Describe the bug

when I run：
python -m torch.distributed.launch --nproc_per_node=5 train.py hparams/train.yaml --data_folder=dataset/aishell1 --distributed_launch --distributed_backend='nccl'
This program was interrupted halfway through. And only return nccl timeout.

### Expected behaviour

Can you tell me how to slove this problem?

**Comment by Adel-Moumen** [comment]
Are you using the latest version of SpeechBrain? We recently merged a fix #2191 that should resolves communication issues when using `ckpt_interval_minutes`.

**Comment by wntg** [comment]
@Adel-Moumen Thank you ！My question is sloved and I will close this issue
