### ISSUE TITLE
Pytorch 2.1, Requirements.txt and "RuntimeError: Couldn't find appropriate backend to handle uri".

### ISSUE THREAD

**Issue by jonah-ramponi** [speechbrain/speechbrain#2225]
### Describe the bug

Unless I am missing something, the requirements.txt file simply specifies

"torch>=1.9.0
torchaudio>=1.9.0"

However the majority of the tests fail using pytorch 2.1 due to "RuntimeError: Couldn't find appropriate backend to handle uri".

I am not sure why you recommend in the readme to use pytorch 1.13, suggest in the readme that it might work for pytorch 2.0, but then specify the requirements in this way. I think the requirements.txt or readme should be updated. 

After following the installiation steps, I had to run pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1

### Expected behaviour

I expected the installation to work, to get it ti work I had to downgrade the pytorch version.

**Comment by jonah-ramponi** [comment]
Hey,

Interesting. I'm using Linux, and the main version. Downgrading pytorch to 1.13 worked.  Before, 17 of the tests failed due to "RuntimeError: Couldn't find appropriate backend to handle uri".  Perhaps there was something up with my pytorch install! I suspect that is the case. Thanks anyways, my bad.

**Comment by mravanelli** [comment]
I cannot replicate this on my side. Can you replicate it?

**Comment by TParcollet** [comment]
Yes, the only solution was to downgrade torch and torchaudio to 2.0 ... Hopefully it will be fixed in a upcoming release but in the meantime I suggest that we freeze the torch version ...

**Comment by mravanelli** [comment]
I suggest doing an investigation as soon as possible to understand the
cause of it. Unfortunately, I cannot help as on my side every works fine.

**Comment by TParcollet** [comment]
Ok, so according to the following screen from the torchaudio 2.1.0 release, it looks like it's again a backend issue. 
![image](https://github.com/speechbrain/speechbrain/assets/11910731/bf828941-706b-4a5a-9098-148720ff48fb)

**Comment by TParcollet** [comment]
@jonah-ramponi could you please try changing "soundfile" to ffmpeg after updating it and letting us know if it solved your issue? https://github.com/speechbrain/speechbrain/blob/bd27e99119edfe6b4f530be16d46cce28af260b3/speechbrain/utils/torch_audio_backend.py#L19

**Comment by TParcollet** [comment]
@mravanelli @Adel-Moumen  and @asumagic pinging on this issue again because we might want to change the default backend to ffmpeg ...

**Comment by TParcollet** [comment]
@lucadellalib @asumagic @pplantinga  This is the issue to try and fix the backend problem.

**Comment by Adel-Moumen** [comment]
One note: our CommonVoice recipe doesn't work anymore due to this problem. In our data_prep file, we are doing 
```
if torchaudio.get_audio_backend() != "sox_io": 
           logger.warning("This recipe needs the sox-io backend of torchaudio")
            logger.warning("The torchaudio backend is changed to sox_io")
            torchaudio.set_audio_backend("sox_io")
```
But now, `torchaudio.get_audio_backend()` is a no-op function. 

We really need to fix it asap 

CC: @asumagic :eyes:

**Comment by asumagic** [comment]
The summary of current torchaudio issues we are encountering, as far as I can tell, is summed up to this:

1. torchaudio is deprecating & removing the concept of global audio backends; those must be specified at the `.info`/`.read` calls, which explains the CommonVoice breakage.
2. torchaudio no longer permits calling `.info`/`.read` for mp3 files using the SoX backend; ffmpeg seems like it is mandatory for mp3
3. even if it weren't, torchaudio has ceased shipping SoX inside of the torchaudio package, which explains that some users can no longer decode anything
4. ffmpeg was also never shipped pre-built by torchaudio

torchaudio and some other libraries, such as librosa, expect ffmpeg to be installed system-wide or through Conda.  
I'm on the fence as to whether this is a reasonable expectation, but practically speaking, I can imagine some users being justifiably annoyed by the install process when Conda is not necessarily a reasonable option.

[PyAV](https://github.com/PyAV-Org/PyAV) which was mentioned in the core meeting ships pre-built ffmpeg, which might be suitable. I haven't tried it, but I don't think torchaudio would be able to pick those ffmpeg `.so` at all... Would need to investigate.  
If we depend on PyAV, I think it should be optional.

I guess the questions are:

1. Can we make torchaudio work reliably out-of-the-box with pip only, without expecting a system-wide ffmpeg install - e.g. by leveraging PyAV
2. If we cannot, what are we using instead (maybe a multi-backend approach like lhotse as found out by Adel?)

**Comment by pplantinga** [comment]
What if we do away with torchaudio altogether (for loading audio at least) and just load audio with PyAV? Then it should work on all systems with just pip install. The install of PyAV is fast and painless in my experience.

See this note in faster whisper:

https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/audio.py#L1

**Comment by asumagic** [comment]
> What if we do away with torchaudio altogether (for loading audio at least) and just load audio with PyAV? Then it should work on all systems with just pip install. The install of PyAV is fast and painless in my experience.
> 
> See this note in faster whisper:
> 
> https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/audio.py#L1

After some more discussion that has been a tempting option indeed. It seems rather well adopted too. We could also build a thin abstraction on top so that it becomes less of a headache in the future.

As for torchaudio, we realized that even when Conda is available to the user, the install process remains a little finicky as any given torchaudio version can only support a specific ffmpeg version or range of versions. On certain setups, that might make the install process annoying and rather painful to debug when things go wrong...

**Comment by TParcollet** [comment]
If someone can open a PR with that change, I am happy to test it and see.

**Comment by Adel-Moumen** [comment]
Closing this issue since #2398 has been merged in develop branch.
