### ISSUE TITLE
[Feature Request]: Add checkpoint for HIFIGAN discriminator

### ISSUE THREAD

**Issue by nguyentr17** [speechbrain/speechbrain#2249]
### 🚀 The feature

Can you upload the checkpoint for HIFIGAN discriminator as well?

### Solution outline

 I would like to use it to finetune and output of discriminator as features in my model.

**Comment by BenoitWang** [comment]
Hi @nguyentr17, you can find all you need through the training log Dropbox link in the [readme](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LJSpeech/TTS#hifigan-vocoder).

**Comment by nguyentr17** [comment]
Thanks, can you upload the checkpoint for 16kHZ model as well?

**Comment by BenoitWang** [comment]
The 16k model is trained with the LibriTTS recipe instead of LibriSpeech, so you can find it [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriTTS/vocoder#hifi-gan-vocoder).

**Comment by nguyentr17** [comment]
Got it, thank you!
