### ISSUE TITLE
Checkpoint not being fully removed

### ISSUE THREAD

**Issue by whettenr** [speechbrain/speechbrain#2250]
### Describe the bug

Randomly get this error
`OSError: [Errno 39] Directory not empty: 'location/to/CKPT'
`
and again when I look at the CKPT directory the optimizer.ckpt is still in there

### Expected behaviour

I expect the CKPT to be entirely removed.

### Environment Details

- Using DDP
- Happen on the SpeechBrain development branch an 1 other branch

### Additional Context

I think this is just an issue with DDP that rarely happens. I think sometimes when running on DDP the program tries to remove the CKPT directory before it is has removed all the files inside of it. 

I'm not too familiar with speech brain and DDP but maybe there could be a simple fix to wait or check if the CKPT folder is empty.

**Comment by Adel-Moumen** [comment]
Hello @pplantinga, could you please have a look? Thanks...

**Comment by pplantinga** [comment]
The directory is removed all at once with `shutil.rmtree` so at first I couldn't think of what the issue could be. But I guess if any files get written by another process into this folder while it's being deleted, that would cause it to fail. For example, if process 2 saves `optimizer.ckpt` into a checkpoint while process 1 is deleting the same checkpoint, then it would fail.

**Comment by whettenr** [comment]
@Adel-Moumen  @pplantinga, 

I think that is the issue with one process deleting and another process creating, but I don't understand why anything should be being created. 

The checkpoint was from 10 epochs ago and so I believe the optimizer should have already been created. So I don't know why anything new should be being created in this folder.

Had it happen to me again btw this morning.

**Comment by whettenr** [comment]
@Adel-Moumen Yes I will test it out and get back to you! Thanks everybody for taking the time to work on this!

**Comment by asumagic** [comment]
Note, which Adel told me to report here: based on a recent-ish `unstable-0.6`, without #2267, I've encountered an issue with `save_checkpoint` failing at the end of a training epoch.

```
  File "/home/sdelang/sb/speechbrain/core.py", line 1420, in fit
    asr_brain.fit(
  File "/home/sdelang/sb/speechbrain/core.py", line 1420, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/sdelang/sb/speechbrain/core.py", line 1267, in _fit_train
    self._save_intra_epoch_ckpt()
  File "/home/sdelang/sb/speechbrain/core.py", line 1440, in _save_intra_epoch_ckpt
    self.checkpointer.save_and_keep_only(
  File "/home/sdelang/sb/speechbrain/utils/checkpoints.py", line 679, in save_and_keep_only
    self.save_checkpoint(
  File "/home/sdelang/sb/speechbrain/utils/checkpoints.py", line 592, in save_checkpoint
    savepath = ckpt_dir / objfname
               ~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'bool' and 'str'
```

Currently retrying with #2267 merged into my branch.

**Comment by TParcollet** [comment]
@whettenr could you please try #2268 and let us know if it solved the issue?

**Comment by TParcollet** [comment]
@asumagic could you try as well ?

**Comment by whettenr** [comment]
@TParcollet @Adel-Moumen,  Tried #2267. Had no issues (went 160K steps then i stopped it).

**Comment by TParcollet** [comment]
#2267 is not a fix, it's a revert. Please try this one instead.

**Comment by asumagic** [comment]
> @asumagic could you try as well ?

Will check along with the conformer-transducer fp16 fix you suggested when I have access to some compute again (so probably tomorrow).

**Comment by whettenr** [comment]
issue with #2268 

```
  File "/users/rwhetten/speechbrain/speechbrain/utils/distributed.py", line 101, in main_proc_wrapped_func
    return result
           ^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
    return result
           ^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
    main_process_only(func)(*args, **kwargs)
  File "/users/rwhetten/speechbrain/speechbrain/utils/distributed.py", line 101, in main_proc_wrapped_func
    return result
```

I think this function is trying to return a variable that is doesnt have
```
    def main_proc_wrapped_func(*args, **kwargs):
        """This decorated function runs only if this is the main process."""
        os.environ[MAIN_PROC_ENV] = "1"
        if if_main_process():
            result = function(*args, **kwargs)
        os.environ[MAIN_PROC_ENV] = "0"
        return result
```

**Comment by asumagic** [comment]
> issue with #2268
> 
> ```
>   File "/users/rwhetten/speechbrain/speechbrain/utils/distributed.py", line 101, in main_proc_wrapped_func
>     return result
>            ^^^^^^
> UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
>     return result
>            ^^^^^^
> UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
>     main_process_only(func)(*args, **kwargs)
>   File "/users/rwhetten/speechbrain/speechbrain/utils/distributed.py", line 101, in main_proc_wrapped_func
>     return result
> ```
> 
> I think this function is trying to return a variable that is doesnt have
> 
> ```
>     def main_proc_wrapped_func(*args, **kwargs):
>         """This decorated function runs only if this is the main process."""
>         os.environ[MAIN_PROC_ENV] = "1"
>         if if_main_process():
>             result = function(*args, **kwargs)
>         os.environ[MAIN_PROC_ENV] = "0"
>         return result
> ```

try adding `else: result = None` after the if_main_process branch. It solved the error for me, but I have not gone past an epoch yet.

**Comment by TParcollet** [comment]
Ok @asumagic and @whettenr it's a typo issue from @pplantinga he can fix it easily.
