### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by kevin00616** [speechbrain/speechbrain#2260]
### Describe the bug

I am using my data +voxceleb1 data set for training, but the following problems arise.
Please help me solve the problem.

### Expected behaviour

Training can proceed normally.

### Relevant Log Output

```shell
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 32767/32768 [4:45:35<00:00,  1.03it/s, train_loss=7.94]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train_speaker_embeddings.py", line 257, in <module>
    valid_loader_kwargs=hparams["dataloader_options"],
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1385, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1225, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1098, in fit_batch
    (loss / self.grad_accumulation_factor).backward()
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([186, 3072, 1, 301], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(3072, 3072, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    memory_format = Contiguous
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f93e01216a0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 186, 3072, 1, 301, 
    strideA = 924672, 301, 301, 1, 
output: TensorDescriptor 0x7f93e3c198b0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 186, 3072, 1, 301, 
    strideA = 924672, 301, 301, 1, 
weight: FilterDescriptor 0x7f93e3c0b580
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 3072, 3072, 1, 1, 
Pointer addresses: 
    input: 0x7f9532000000
    output: 0x7f94c4000000
    weight: 0x7f94ed016000

[W CUDAGuardImpl.h:113] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 2354568) of binary: /home/kalvin00616/anaconda3/envs/speechbrain/bin/python
Traceback (most recent call last):
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
```

**Comment by underdogliu** [comment]
Hi @kevin00616 ! I think I used to meet this error before as well. 

This is not a very easy bug to fix. But as an initial attempt, could you tell me the hardware configuration of your experiment? Like, the type of GPU you were using (if any)?

Also, you may try reducing the batch size and see how it works.

**Comment by asumagic** [comment]
@kevin00616 Does the code snippet provided in the error reproduce the error for you? This seems like a bug that should be reported to PyTorch, but more info is probably needed.

**Comment by asumagic** [comment]
Also, it seems like you have been having a lot of other strange CUDA behavior. I am wondering if it could be driver or hardware related at this point. Do other workloads exhibit such behavior?

**Comment by kevin00616** [comment]
@underdogliu 
My Environment Details
GPU：Tesla V100 *1
SpeechBrain：0.5.14
python：3.7.16
pytorch：1.12.1
Cuda：11.4

As for the batch size part, since I can’t use a computer at the moment, I will try it tomorrow.

**Comment by kevin00616** [comment]
@asumagic 
Since I'm using a shared server, there may be people using it at the same time, but I'm sure the GPU usage isn't much when I'm training, but when I'm training the GPU usage reaches 100%, but the GPU's memory The body is not fully occupied, only 2/3 is occupied.

**Comment by kevin00616** [comment]
And I have another question. How can I specify a specific GPU for training? I currently have four GPUs and I want to use the second and third for training.
Now I use: python -m torch.distributed.launch --nproc_per_node=2 train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml --distributed_launch
But that cant not use No.2 and No.3 GPU to train, just can use No.1 and No.2 GPU.
Because sometimes No.1 GPU need to share with others,so thats why I want to specify a specific GPUs for training.

**Comment by kevin00616** [comment]
@underdogliu I try reducing the batch size,the GPU usage sometimes reaches 100%, but the memory consumption decreases to 1/3.

**Comment by underdogliu** [comment]
> How can I specify a specific GPU for training? I currently have four GPUs and I want to use the second and third for training.

You can add `CUDA_VISIBLE_DEVICES=2,3` at the beginning of your runner command, to specify the GPU you wanna use.

**Comment by kevin00616** [comment]
Finally, I was able to train. I modified torch.backends.cudnn.benchmark = True to False in train_speaker_embeddings.py, and then reduced the batch size. 
Although it slowed down a bit, I could train successfully.

**Comment by asumagic** [comment]
Great, I'll close the issue in this case. I don't think there's much we can fix on our end to prevent this from happening.
