### ISSUE TITLE
[Feature Request]: STT Example?

### ISSUE THREAD

**Issue by chrisspen** [speechbrain/speechbrain#2288]
### 🚀 The feature

The limited documentation implies this project can perform speech-to-text conversion. However, there appears to be zero documentation on how to do this, and the tutorials.md in the docs folder is essentially empty.

### Solution outline

Please provide a simple example for how to take an audio file and feed it into Speechbrain to convert it to text.

**Comment by asumagic** [comment]
The term used in SpeechBrain for speech-to-text is "automatic speech recognition" (or ASR). You can search all of the published SpeechBrain ASR models on HuggingFace doing a search like this: https://huggingface.co/speechbrain?search_models=asr

Trained models on HF should have an example snippet in their README.

As for `tutorials.md`, it links to the official website which contains the tutorials in a drop-down menu at the top right. I agree it's not too clear, as there currently isn't a main tutorials page linking to the others.
