### ISSUE TITLE
No module named 'speechbrain.inference'

### ISSUE THREAD

**Issue by chrisspen** [speechbrain/speechbrain#2325]
### Describe the bug

I'm attempting to run the trivial Python example at https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-14-en

I've created my Python virtual environment and install dependencies as described with:

    pip install speechbrain transformers

However, attempting the initial import of:

    from speechbrain.inference.ASR import EncoderASR

throws the exception:

   ModuleNotFoundError: No module named 'speechbrain.inference'

Do you know why this module is missing and where I might find it?

### Expected behaviour

No import error.

**Comment by mravanelli** [comment]
Hi Chris,
it looks like this recipe is already updated to SpeechBrain 1.0 (we will
switch all the repositories soon).
To make it work, please install speechbrain in this way:

# Clone SpeechBrain repository (development branch)
!git clone https://github.com/speechbrain/speechbrain/
%cd /content/speechbrain/

# Switch to the unstable-v0.6 branch (SpeechBrain 1.0)
!git checkout unstable-v0.6

# Install required dependencies
!pip install -r requirements.txt

# Install SpeechBrain in editable mode
!pip install -e .

Please, let me know if this way it works

Best,

Mirco

**Comment by chrisspen** [comment]
Thank you for the clarification. Following those steps allowed me to access the model.
