### ISSUE TITLE
Language codes not following ISO standards in lang-id-voxlingua107-ecapa

### ISSUE THREAD

**Issue by FredHaa** [speechbrain/speechbrain#2396]
### Describe the bug

In the tokenizer, Hebrew is given the language code 'iw' and Javanese is given 'jw'. These language codes are incorrect according to the [ISO standard](https://www.loc.gov/standards/iso639-2/php/code_changes.php)

'iw' has been obsoleted and changed to 'he' and 'jw' was an error from the first version of the ISO639 standard, and has latter been corrected to 'jv'.

### Expected behaviour

That the correct language codes for Hebrew and Javanese were returned.

**Comment by asumagic** [comment]
Seems like the problem originates from the [VoxLingua107](https://bark.phon.ioc.ee/voxlingua107/) dataset itself, though it can be corrected in the `label_encoder.txt` file used at inference.

Considering changing this on existing models could break existing code, adding a notice in the relevant documentations would make sense.

**Comment by asumagic** [comment]
Created PR for `speechbrain/lang-id-voxlingua107-ecapa`: https://huggingface.co/speechbrain/lang-id-voxlingua107-ecapa/discussions/7

Will also create a PR in the recipe documentation in the main repo and link it to close this issue.
