### ISSUE TITLE
🐞 | Import error in speechbrain.pretrained

### ISSUE THREAD

**Issue by AbhinavSingh-21f1002369** [speechbrain/speechbrain#2436]
### Describe the bug

Hello guys, 

I wanted to import `EndToEndSLU` from `speechbrain.pretrained`, but it seems there is an error. Anyone who did resolve it earlier?

`from speechbrain.pretrained import EndToEndSLU` produces error

### Expected behaviour

It should have imported easiily.

### To Reproduce

Steps to reproduce : https://colab.research.google.com/drive/1XnCba8gDTN2n2Yknn7fjx3zsCI72NG0V?usp=sharing

###  Output

<img width="407" alt="image" src="https://github.com/speechbrain/speechbrain/assets/84432889/98eeff1f-d1a3-4679-ab0c-e212c3c1ca5b">
<img width="798" alt="image" src="https://github.com/speechbrain/speechbrain/assets/84432889/036a7b62-afaa-4707-8eb1-8f7243410ea7">

**Comment by Adel-Moumen** [comment]
Hello, 

SpeechBrain 1.0 is out and we moved our interfaces in the folder `inference`. Please see for instance: https://huggingface.co/speechbrain/slu-timers-and-such-direct-librispeech-asr

``` 
from speechbrain.inference.SLU import EndToEndSLU
slu = EndToEndSLU.from_hparams("speechbrain/slu-timers-and-such-direct-librispeech-asr")
slu.decode_file("speechbrain/slu-timers-and-such-direct-librispeech-asr/math.wav")
```

**Comment by AbhinavSingh-21f1002369** [comment]
The docs were not updated, was confused there.
Thank you so much.

**Comment by mravanelli** [comment]
Please, update SpeechBrain to the latest version (SpeechBrain 1.0) that we
just released
