### ISSUE TITLE
Not Able to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings in Google Colab.

### ISSUE THREAD

**Issue by itsdivgithub** [speechbrain/speechbrain#2438]
### Describe the bug

I have installed speechbrain module 1.0.0 latest version and wants to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings in Google Colab but it's throwing error that speechbrain must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings.

![d3cf9ce1-66d3-4b8a-ad36-2905f963bd43](https://github.com/speechbrain/speechbrain/assets/92361650/572825dd-5302-43e9-9fc7-dc65c097d071)

### Expected behaviour

After speechbrain installation I was expecting to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings.

**Comment by Adel-Moumen** [comment]
Hello @itsdivgithub, could you please provide a working reproductible example with google colab ? Thanks.

**Comment by itsdivgithub** [comment]
![ac52a03b-7c94-4803-9edf-651a01f13a25](https://github.com/speechbrain/speechbrain/assets/92361650/a4deaada-68b6-4264-9afe-44f5cf5157ac)
