### ISSUE TITLE
Circular import in ESC-50 classification recipe

### ISSUE THREAD

**Issue by lucadellalib** [speechbrain/speechbrain#2501]
### Describe the bug

Since the `isort` refactoring ESC-50 classification recipes do not run.

### Expected behaviour

Classification recipes working.

### To Reproduce

`python train_classifier.py hparams/cnn14_classifier.yaml --data_folder data`
`> ImportError: cannot import name 'length_to_mask' from partially initialized module 'speechbrain.dataio.dataio' (most likely due to a circular import)`

**Comment by mravanelli** [comment]
This is connected to #2500. Solving that is quite urgent. I'm wondering why all our tests did not detect this issue before merging that PR.
