### ISSUE TITLE
not able to import 'HuggingFaceWhisper' from speechbrain.lobes.models.huggingface_whisper

### ISSUE THREAD

**Issue by aquorio15** [speechbrain/speechbrain#2522]
### Describe the bug

I am trying to extract whisper features from pretrained whisper model available on hugging face using "SpeechBrain". 

### Expected behaviour

To extract the features I am following this discussion [https://github.com/openai/whisper/discussions/1246](url). But I am not able to import HuggingFaceWhisper even after properly installing speechbrain.

### Environment Details

from speechbrain.lobes.models.huggingface_whisper import HuggingFaceWhisper
import speechbrain as sb

### Relevant Log Output

```shell
ModuleNotFoundError: No module named 'speechbrain.lobes.models.huggingface_whisper'
```

**Comment by Adel-Moumen** [comment]
Hi, 

The path to whisper is: `from speechbrain.lobes.models.huggingface_transformers.whisper import Whisper`

**Comment by aquorio15** [comment]
Hi,
Thanks for the quick reply. I want to import this module [https://speechbrain.readthedocs.io/en/stable/API/speechbrain.lobes.models.huggingface_whisper.html](url)

**Comment by Adel-Moumen** [comment]
Could you please share with me the speechbrain version that you are using? I think you are not using the latest speechbrain hence why you are struggling to import the whisper module.

**Comment by aquorio15** [comment]
I install speechbrain by using the following command which is available on the official website
```
git clone https://github.com/speechbrain/speechbrain.git
cd speechbrain
pip install -r requirements.txt
pip install --editable .
```
I don't know how to check the version. Can you tell me what is the argument for that. This is my first time using the toolkit

**Comment by Adel-Moumen** [comment]
This is the correct way of downloading speechbrain. I think the issue is that you are not looking at the latest documentation. Please have a look here: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.lobes.models.huggingface_transformers.whisper.html#module-speechbrain.lobes.models.huggingface_transformers.whisper also make sure to have a look at our beginner tutorials hosted on our website.

**Comment by aquorio15** [comment]
Just now did a fresh install from the link above. Speechbrain is installed as I am able to import the speechbrain module but I am not able to import 'huggingface_whisper' module.

**Comment by Adel-Moumen** [comment]
> Just now did a fresh install from the link above. Speechbrain is installed as I am able to import the speechbrain module but I am not able to import 'huggingface_whisper' module.

Please have a look at this notebook that I did for you: https://colab.research.google.com/drive/1O9tigK_0Qv3JOlf-e9_j2pYilkztQm2_?usp=sharing

You'll see how to import this module.
