### ISSUE TITLE
A lot of softlinks have been created when doing emotion classificatin

### ISSUE THREAD

**Issue by underdogliu** [speechbrain/speechbrain#2626]
### Describe the bug

I am doing emotion classification on waveforms using the speechbrain IEMOCAP hugging face interface. The code was executed perfectly. But meanwhile it creates a lot fo softlinks from my current directory to the original wav file paths. I wonder if this is a bug.

### Expected behaviour

Below is the code block. Simply initiate the class and perform classify_emotion would work, but with a softlink to the input wav file.

### To Reproduce

```python
import torch
from speechbrain.inference.interfaces import foreign_class


class EmotionClassifier(object):
    def __init__(self):
        self.classifier = foreign_class(
            source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP",
            pymodule_file="custom_interface.py",
            classname="CustomEncoderWav2vec2Classifier",
        )
        self.classifier.eval()
        device = "cuda" if torch.cuda.is_available() else "cpu"
        self.classifier = self.classifier.to(device)

    def classify_emotion(self, audio_path):
        # Load the audio file
        out_prob, score, index, text_lab = self.classifier.classify_file(audio_path)
        emotion = text_lab[0]
        return emotion
```

### Environment Details

speechbrain@develop branch. Seems this toolkit only works for this version of speechbrain

**Comment by seastar105** [comment]
+1
