### ISSUE TITLE
How do you add a yaml file?  

### ISSUE THREAD

**Issue by StevePGLS** [speechbrain/speechbrain#2651]
### Describe the bug

It seems like the documentation hangs us out to dry.   I am trying to use your ASR but I get error messages that I need a tokenizer.

Why doesn't your documentation offer clear instructions on how to do this?

### Expected behaviour

I expect to see clear instructions.

### To Reproduce

from speechbrain.inference.ASR import EncoderDecoderASR
tmpdir = getfixture("tmpdir")
asr_model = EncoderDecoderASR.from_hparams(
    source="speechbrain/asr-crdnn-rnnlm-librispeech",
    savedir=tmpdir,
)  
asr_model.transcribe_file("tests/samples/single-mic/example2.flac")  
"MY FATHER HAS REVEALED THE CULPRIT'S NAME"

### Environment Details

Version 1.0

### Relevant Log Output

```shell
Error
Traceback (most recent call last):
  File "C:\workspace\SLIDE\test_slide.py", line 53, in setUp
    self.identifier = LanguageIdentifier()
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\SLIDE\slide.py", line 15, in __init__
    self.asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="tmp")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SteveBraich\AppData\Local\Programs\Python\Python312\Lib\site-packages\speechbrain\inference\interfaces.py", line 497, in from_hparams
    return cls(hparams["modules"], hparams, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SteveBraich\AppData\Local\Programs\Python\Python312\Lib\site-packages\speechbrain\inference\ASR.py", line 55, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\SteveBraich\AppData\Local\Programs\Python\Python312\Lib\site-packages\speechbrain\inference\interfaces.py", line 240, in __init__
    raise ValueError(f"Need hparams['{hp}']")
ValueError: Need hparams['tokenizer']
```

### Additional Context

Language identification using SpeechBrain already works.

**Comment by StevePGLS** [comment]
Dood.  Like so do I go over to HuggingFace and copy the hyperparams.yaml file for the specific model and just what?  Put it in the same directory as the python script?  Can someone point me to an actual functioning example?

**Comment by TParcollet** [comment]
Hi, I am not sure to understand your error or problem. If it's a problem with the above code snippet, it works for me. If it's a problem with how to make your own model work with the inference pipeline, please have a look at [our tutorial: "Inferring on your own SpeechBrain models"](https://speechbrain.github.io/tutorial_advanced.html). If this does not help, please describe a bit more what you are trying to achieve and we'll help.
