### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Uglychild8936** [speechbrain/speechbrain#2652]
### Describe the bug

When training a transformer model using the Aishell-1 dataset, I encounter the error "ZeroDivisionError: division by zero." It seems that this issue arises from setting the target sequences to a uniform length. How can I resolve this problem? I would appreciate your advice.

![fb78c01a-51ec-4e83-a3cf-6803d6c10ecc](https://github.com/user-attachments/assets/b177b6ae-83a8-433c-b580-6a799c7fae94)

### Expected behaviour

Hope it can run normally

**Comment by ZCzzzzzz** [comment]
hi,I have the same problem,do you know how to solve it?

**Comment by Uglychild8936** [comment]
This is my problem. At first, I didn't understand the code and commented out the code for downloading tokenizer, which resulted in the program running without a character conversion dictionary. The following code has been commented out, which is the code in train.py.
![Uploading bc452e68-b18d-45d0-a495-2285144b00b1.png…]()

**Comment by Uglychild8936** [comment]
![bc452e68-b18d-45d0-a495-2285144b00b1](https://github.com/user-attachments/assets/b0a17f8c-3059-4dc2-ac27-6d472d755e30)

**Comment by ZCzzzzzz** [comment]
I know that this should be to download pretrain and tokenizer, because I want to change the model weight, so I commented out this part of the code and replaced it with "model = EncoderDecoderASR.from_hparams(source="/workspace/speechbrain/recipes/AISHELL-1/ASR/transformer/asr_ model/asr-transformer-aishell", savedir="/workspace/speechbrain/recipes/AISHELL-1/ASR/transformer/asr_model/asr-transformer-aishell")", but I don't know if this is the right thing to do

**Comment by Uglychild8936** [comment]
I think this part is not about downloading pre trained models, but about downloading tokenizers. Training models must have tokenizers, and the model needs to find the corresponding labels for characters based on this. If you can't download it, you can also train one yourself. I remember the official website tutorial has instructions about tokenizers. The content of tokenizer is similar to the following image.
![Uploading QQ20240904-142809.png…]()

**Comment by Uglychild8936** [comment]
![QQ20240904-142809](https://github.com/user-attachments/assets/379cb8e4-89a0-4195-817d-51734571fadf)

**Comment by Uglychild8936** [comment]
You can also train yourself according to this program.
![QQ20240904-143354](https://github.com/user-attachments/assets/1b80f7c5-06af-420a-b0eb-67aa8e447b5c)
