### ISSUE TITLE
Is there a reference to the noise file used in the Voxlingua107 train_ecapa receipe?

### ISSUE THREAD

**Issue by ajesujoba** [speechbrain/speechbrain#2668]
### Describe the bug

Hi, I would like to correctly reference the NOISE dataset, used in the [VoxLingual LID](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxLingua107/lang_id/hparams/train_ecapa.yaml#L21C1-L21C18) recipe. What is the name of this dataset? And does it have a reference paper?

### Expected behaviour

NA

**Comment by asumagic** [comment]
Hello, this refers to the `pointsource_noises` directory of this dataset: https://www.openslr.org/28/
