### ISSUE TITLE
how to load everything from local path?

### ISSUE THREAD

**Issue by littlebowlnju** [speechbrain/speechbrain#2699]
### Describe the bug

I have pre-downloaded the model I need from huggingface to a local path, and using following code to load the model:
```
verifier = SpeakerRecognition.from_hparams(source=args.model_path, savedir=args.model_path, run_opts={"device": device})
score, prediction = verifier.verify_files(path_x=audio_path, path_y=args.ref_audio_file, savedir="<audio_local_savedir>")
```

where `source`, `savedir`, `path_x` and `path_y` are all local paths. Due to network reason, I cannot access huggingface in the server where i run the code, thus I am always getting error like this:
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /speechbrain/spkrec-ecapa-voxceleb/resolve/main/label_encoder.txt (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
```

Also, I want to keep `path_x` and `path_y` in different directory. However, it will always need a `savedir` and only one `savedir` to load audio from local path , forcing me to put two audio in the same directory and provide the directory to `savedir`, which i believe is not very reasonable.

Is there any other parameters that I can set to solve this problem? Or maybe I just have to work on my network to use this model😭

### Expected behaviour

directly load models and audios from the **absolute local path** I provide without trying to download model files from remote.

**Comment by asumagic** [comment]
This probably has to do with the `pretrained_path` in [`speechbrain/spkrec-ecapa-voxceleb/hyperparams.yaml`](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb/blob/main/hyperparams.yaml) being specified as a HF path (see also #1253).

I just tested this and passing something like `overrides={"pretrained_path": args.model_path}` to `from_hparams` seems to avoid any HF connection for me.

**Comment by littlebowlnju** [comment]
You're correct. This solves my problem. Thanks!!
