### ISSUE TITLE
Fetch Semantics

### ISSUE THREAD

**Issue by pplantinga** [speechbrain/speechbrain#2711]
### Describe the bug

The recent changes to `fetch` have changed the defaults that some templates (at least) depend on, see #2701. In that issue, some general changes to the default were discussed, this issue should track those changes.

### Expected behaviour

* Code that explicitly sets the fetch savedir behave the same (default to SYMLINK or perhaps an environment variable).
* Code can now explicitly opt in to any of the new strategy options.
* Code that does not set savedir are now assumed to not rely on where the files are saved (default and enforce NO_LINK).
* Examples and uses in the codebase edited to not specify savedir.
* Ensure that at least one message sums up what any fetch operation has resulted into, at INFO level.
* Detect and warn for leftover (old) pretrainer cache directories.

**Comment by asumagic** [comment]
Also should look into resolving #1253 although that one might just be a misconfigured hparams?
