### ISSUE TITLE
Drastically different embeddings for sampling rate 16k - recorded at 16k vs recorded at 44.1k and down sampled to 16k

### ISSUE THREAD

**Issue by utility-aagrawal** [speechbrain/speechbrain#2720]
### Describe the bug

Can someone please look at this question and provide their feedback? Thanks!

https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb/discussions/15

### Expected behaviour

I was expecting these two scenarios to produce similar embeddings

**Comment by TParcollet** [comment]
Hi, well, downsampling != native recording depending and it may vary quite a lot depending on how you downsample. The model is trained with native 16khz, so the feature extractor might not like the downsampling. You may want to finetune a bit before.

**Comment by utility-aagrawal** [comment]
Thanks @TParcollet !!
