### ISSUE TITLE
on_fit_batch_start() method not called in the beginning of the fit_batch() method 

### ISSUE THREAD

**Issue by tiatariene** [speechbrain/speechbrain#2721]
### Describe the bug

Hello ! 

I would first like to thank you for the useful tools that Speechbrain provides us !

I noticed that the method on_fit_batch_start() is never called anywhere in the Brain class.

### Expected behaviour

Shouldn't we call the self.on_fit_batch_start() method on the fit_batch() method ?

Somewhere around this line of code : https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/core.py#L1218

Thank you very much :)

**Comment by Adel-Moumen** [comment]
You are correct! @tiatariene I will fix this ASAP. Thanks a lot :)

**Comment by tiatariene** [comment]
Nice ! Many thanks
