### ISSUE TITLE
`test_sign_flip` does sometimes fail

### ISSUE THREAD

**Issue by asumagic** [speechbrain/speechbrain#2740]
### Describe the bug

Observed on CI earlier; turns out:

```
    trials = 1000
    for _ in range(trials):
        flipped_sig = flip_sign(signal)
        if torch.all(flipped_sig == -signal):
            flips += 1
    test_prob = flips / trials
    # these values are 5 stds in each direction,
    # making a false negative extremely unlikely
    assert 0.421 < test_prob < 0.579
```

This has failed in at least one CI run. Need to double-check if this might be due to a logic error, otherwise just increase trials or tolerance.

Not critical for v1.0.2

### Expected behaviour

Tests shouldn't randomly fail.

**Comment by gfdb** [comment]
@asumagic do you have a link to the failing CI by chance? I'd like to take a look and fix this.

**Comment by asumagic** [comment]
Apparently, rerunning CI (as I did) makes the log go away...
