### ISSUE TITLE
PyPI installation fails with a conda environment on Windows OS

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#512]
Hi!
I've tried following [recommended pypi installation](http://www.darnault-parcollet.fr/Parcollet/hiddennoshare/speechbrain.github.io/documentation/installation.html) but it seems that there are some conflicts dependencies. 

Steps to reproduce the error ( Use Windows OS without WSL support):
1) `conda create -n "speechbrain_env" Python=3.8`
2) `conda activate speechbrain_env`
3) `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple BeechSprain` 

The following error I get is:
``` bash
(speechbrain_env) C:\Users\kacpe\Desktop\Github>pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple BeechSprain
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting BeechSprain
  Downloading https://test-files.pythonhosted.org/packages/98/6c/f3b5ea8582e75a9097f9d2aab47bb380a337acf3874ad87d208b01dc9cae/BeechSprain-0.5.3-py3-none-any.whl (324 kB)
     |████████████████████████████████| 324 kB 3.3 MB/s
  Downloading https://test-files.pythonhosted.org/packages/b9/7f/a2506025df280b1cf9ed4032bfbd1afbbd1555ce919061ee157889d467c6/BeechSprain-0.5.2-py3-none-any.whl (244 kB)
     |████████████████████████████████| 244 kB 1.7 MB/s
  Downloading https://test-files.pythonhosted.org/packages/28/aa/a6802f8f2d39199f43fe220833a0dd5a12ee9aa9f34f60b6c90178bbc57f/BeechSprain-0.5.1-py3-none-any.whl (244 kB)
     |████████████████████████████████| 244 kB 2.2 MB/s
ERROR: Cannot install beechsprain==0.5.1, beechsprain==0.5.2 and beechsprain==0.5.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    beechsprain 0.5.3 depends on torchaudio
    beechsprain 0.5.2 depends on torchaudio
    beechsprain 0.5.1 depends on torchaudio

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by tankchenggeng** [comment]
You downloaded BeechSprain but not SpeechBrain，Why?

**Comment by Gastron** [comment]
> You downloaded BeechSprain but not SpeechBrain，Why?

BeechSprain was used for an early "stealth release" alpha version before the full public release.

**Comment by Gastron** [comment]
I happened to have a WSL2 Ubuntu 20.04 on Windows 10 here, and I was able to reproduce this MP3 file info issue @kelseyicotton. I didn't use conda.

The error actually comes from the torchaudio side. I tried both the speechbrain code and direct calls to torchaudio.info() (which is used by the speechbrain code in question) and it fails. The info reading fails for both the MP3 created by speechbrain in this test, but also for a different ("normal") MP3 I had on my computer. If you don't need MP3 reading, then all should be fine anyway, but if you need it, you can go search for answers or report the issue on torchaudio.

**Comment by mravanelli** [comment]
I had the same problem on a linux machine. You need to install a new
version of ffmpeg. This should solve the issue.

See https://github.com/pytorch/audio/issues/2363

**Comment by kelseyicotton** [comment]
Thanks @Gastron for checking this out! This helps a lot 🙌 

> I happened to have a WSL2 Ubuntu 20.04 on Windows 10 here, and I was able to reproduce this MP3 file info issue @kelseyicotton. I didn't use conda.
> 
> The error actually comes from the torchaudio side. I tried both the speechbrain code and direct calls to torchaudio.info() (which is used by the speechbrain code in question) and it fails. The info reading fails for both the MP3 created by speechbrain in this test, but also for a different ("normal") MP3 I had on my computer. If you don't need MP3 reading, then all should be fine anyway, but if you need it, you can go search for answers or report the issue on torchaudio.

**Comment by asumagic** [comment]
This is not related to the issue you replied to. If you don't need to use the k2 functionality from SpeechBrain it doesn't matter. Otherwise you need to follow the link in the error to install it. You can also look in ways to tell pytest to exclude specific files from testing. I will lock the issue to avoid other participants from being notified further.
