### ISSUE TITLE
Support of Conformer transducer

### ISSUE THREAD

**Issue by Jxu-Thu** [speechbrain/speechbrain#558]
Thanks for your great codes!
The SOTA of the ASR model is Conformer proposed by Google. In the raw paper, the conformer is a transducer-based model (a conformer encoder + lstm decoder, named transducer model). I find that many open-source tools actually implement an attention-based model ( conformer encoder + transformer/lstm attention decoder) rather than transducer.

For purpose of research, we hope to propose a new paradigm based on the SOTA methods to make our findings significant and convincing.  Can you provide the transducer-based model with a conformer encoder on LibrSpeech (a well-known benchmark)?  Ideally, reach the score reported in the conformer paper. [https://arxiv.org/abs/2005.08100]

Many thanks for your great codes again!

**Comment by mravanelli** [comment]
Hi,
SpeechBrain already supports Conformers and Transducers. We are currently doing some experiments with Conformers within a traditional seq2seq pipeline (@JianyuanZhong). We expect an improvement with that. The next step could be to combine Conformer with Transducer. What do you think @aheba? In general, replicating the best results from other papers is not an easy job though, especially if the code is not released and you don't have the same amount of gpu of google. For this reason, I think the help of the community could be really precious!

**Comment by mravanelli** [comment]
I suggest continuing the discussion about new features in the discourse channel! 
https://speechbrain.discourse.group/
