### ISSUE TITLE
Support of transformer models

### ISSUE THREAD

**Issue by flozi00** [speechbrain/speechbrain#559]
I saw there is already an open PR for wav2vec 1, based on fairseq. https://github.com/speechbrain/speechbrain/pull/545

What do you think about adding wav2vec 2 based on the huggingface implementation, because fairseq is not compatible to windows yet ?
Furthermore there is an open PR of speech to text transformer at huggingface too.

**Comment by TParcollet** [comment]
Hey Hi,

PR #545 will just provide a easy way to combine pre-trained wav2vec1 and wav2vec2 (with fairseq) models with SpeechBrain. From a medium-term perspective, we would like to develop wav2vec2 directly within SpeechBrain. However, and as we already integrated HuggingFace for other purposes, we would love to have someone trying to nicely integrate their models (maybe not transformer as we already have ours) but at least wav2vecX !

**Comment by mravanelli** [comment]
Yes, I confirm it we are working on both wav2vect and PASE. Maybe the best place to continue this discussion is Discourse channel, right @TParcollet ?

**Comment by mravanelli** [comment]
I suggest continuing the discussion on the discourse channel!
