### ISSUE TITLE
Looking for x-vector tutorial

### ISSUE THREAD

**Issue by babindemers** [speechbrain/speechbrain#563]
Hi, is there a tutorial on how to use x-vectors for speaker recognition?

Congrats on your first release by the way :)

**Comment by TParcollet** [comment]
Hi ! We do not have a tutorial specifically for X-vectors. To learn about them within SpeechBrain you can: 

1. Look at the simplest template we have for them (maybe not SOTA): https://github.com/speechbrain/speechbrain/tree/develop/templates/speaker_id
2. Look at the VoxCeleb recipe (SOTA but also harder)

**Comment by nauman-daw** [comment]
Hi @babindemers ,

Apart from what @TParcollet suggested, you may also find the following basic example useful.

https://github.com/speechbrain/speechbrain/blob/develop/tests/integration/neural_networks/speaker_id/example_xvector_experiment.py

**Comment by mravanelli** [comment]
Yes, this template is actually based on xvectors (I will write a tutorial
on that soon). Note that in SpeechBrain, we now have much better embeddings
for the ECAPA-TDNN model. You might wanna take a look into that as well:
https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb
These embeddings are trained with this recipe:
https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml

**Comment by babindemers** [comment]
Thanks a lot for the links. I also found your tutorial on how to use pre-trained models on your [website](https://speechbrain.github.io/tutorial_advanced.html), which was useful.
