### ISSUE TITLE
Error importing EncoderDecoderASR

### ISSUE THREAD

**Issue by aicentral** [speechbrain/speechbrain#567]
Code creating the error:
`from speechbrain.pretrained import EncoderDecoderASR`

Error reported:
`Exception has occurred: ModuleNotFoundError No module named 'ruamel' File "C:\Users\asnad\code\sandbox\speechbrain\speechbrain\core.py", line 31, in <module> from hyperpyyaml import resolve_references File "C:\Users\asnad\code\sandbox\speechbrain\speechbrain\__init__.py", line 4, in <module> from .core import Stage, Brain, create_experiment_directory, parse_arguments File "C:\Users\asnad\code\sandbox\try_speech.py", line 1, in <module> from speechbrain.pretrained import EncoderDecoderASR`

Installation:
I tried both pip install speechbrain and installation from github. I get the same error in both cases
the pytest throws 261 errors all of them are No module named 'ruamel'

Environment:
```
Windows 10
conda 4.9.2
pip 20.2.4
python 3.8.5
```

Notes:
While searching online I found some other packages having the same issue and most of them contribute the error to incompatibility between ruamel.yaml and conda. Some of them offered different pip-install-based solutions and workarounds but none of them worked.

**Comment by TParcollet** [comment]
Hi ! Very bad news, but we are not windows compatible. As a matter of fact I believe that even torch.audio that we use isn't windows compatible :(

**Comment by mravanelli** [comment]
Even though we do not currently support windows, some of my students are
working with Windows without issues. They only had to switch from sox-io
backend to the soundfile one. Here it looks like a module is missing. Maybe
some windows users can help with that!

**Comment by TParcollet** [comment]
Ah so maybe I'm wrong :P

**Comment by gauravgund** [comment]
I am getting the following error while import EncodeDecoderASR in google colaboratory:

ModuleNotFoundError: No module named 'speechbrain.pretrained'

**Comment by sweetcocoa** [comment]
Have you tried below?

> pip install git+https://github.com/speechbrain/HyperPyYAML

I am not sure what causes ruamel import error, but above one works for me.  *(I am using ubuntu docker, py38+)*

I suspect pypi resolves different version of ruamel from this repo....

**Comment by gauravgund** [comment]
Hi,

I restarted the runtime and it worked. Another question is ‘will it work
for longer audio files’? My colab environment got crashed due to unknown
reasons while trying pretrained models on longer audio files. Regards

**Comment by TParcollet** [comment]
So, it depends on the model and how it has been trained. We will try to release in the next few weeks models that are compatible with very long sentences. However, in practice, it is always better to properly segment your speech in multiple files and then feed them into the ASR system. For now, for example, the CommonVoice French model does not deal well with 20s+ sentences.
