### ISSUE TITLE
How to train the model using multiple GPUs?

### ISSUE THREAD

**Issue by husencd** [speechbrain/speechbrain#570]
How to train the model using multiple GPUs?

**Comment by tulasiram58827** [comment]
@husencd I think this [Notebook](https://colab.research.google.com/drive/13pBUacPiotw1IvyffvGZ-HrtBr9T6l15?usp=sharing) can help you.

**Comment by TParcollet** [comment]
Second solution via the documentation: https://speechbrain.readthedocs.io/en/latest/multigpu.html
