### ISSUE TITLE
SpectralNorm for Complex Convolutions

### ISSUE THREAD

**Issue by vkothapally** [speechbrain/speechbrain#571]
Hello, thanks for putting a great repo. I was curious to know if spectral norm or weight norm can be used for the complex layers in the current version. If not, do you have plans on implementing?

**Comment by TParcollet** [comment]
Hey, yes of course. So, as long as something is natively implemented in PyTorch you can easily use it. 

If you take a look in the hidden test-integration dir:[here](https://speechbrain.readthedocs.io/en/latest/multigpu.html), you'll see that we use a ComplexNorm after few layers. However, you can simply use torch spectral_norm instead. Or you can build your own torch.nn.Module and use it within SpeechBrain :)
