### ISSUE TITLE
Option to use mic input instead of reading from file?

### ISSUE THREAD

**Issue by richieyoum** [speechbrain/speechbrain#572]
Would it be possible to efficiently transcribe stream of inputs from mic directly rather than from a saved .wav file to be normalized?

One obvious way would be to chunk the stream and save the input and processing them sequentially, but seems terribly inefficient and unsuitable for real time use.

Any help/tip would be appreciated!

**Comment by TParcollet** [comment]
Currently no. Online ASR is on the very short-term to do list. It is possible that, at some point, we will make an official call to the community to start working on this. 

Your proposed solution could work, of course, but it might definitely not be real time. You can lower the latency by using very simple models though.

**Comment by balkce** [comment]
This is definitely something that interests me, and not only ASR, but source localization, separation, speaker identification, etc. Please let me know when you make that official call, since I can definitely help out on this end.
