### ISSUE TITLE
is mobile target in roadmap

### ISSUE THREAD

**Issue by kezakool** [speechbrain/speechbrain#573]
Hi,

thank you for all your work, this is great! :) 
i was asking myself if mobile compatibility for iOS and Android was in the roadmap?

thx

**Comment by mravanelli** [comment]
I think one solution for that could be to use the Just-in-time (JIT)
compiler of pytorch to export a model in c++. SpeechBrain supports it. With
that, you should be able to export it to all the devices you want, right?
Maybe in the future we can do a tutorial on that.

**Comment by stefan-falk** [comment]
@mravanelli is there anything out there yet? I'd like to run a SpeechBrain model on iOS and Android devices as well. Is it possible at this point and can I find a guide somewhere for this particular topic?

**Comment by zohaibmushwani** [comment]
> Just-in-time (JIT) compiler of pytorch to export a model in c++. SpeechBrain supports it.

Hi ,SIr please update me if there is any update about tutorial..?
it will be highly apprecaited.
thank you

**Comment by csukuangfj** [comment]
> @mravanelli is there anything out there yet? I'd like to run a SpeechBrain model on iOS and Android devices as well. Is it possible at this point and can I find a guide somewhere for this particular topic?

@stefan-falk 
You may find the following sub-project of next-gen Kaldi helpful
https://github.com/k2-fsa/sherpa-ncnn

It supports Android, iOS, Raspberry pi, etc. I

t also has detailed documentation for building and deploying, though it does not support models from Speechbrain. 

Help in adding support for SpeechBrain is highly appreciated.
