### ISSUE TITLE
How to use GPU during inference?

### ISSUE THREAD

**Issue by alpoktem** [speechbrain/speechbrain#574]
The example code for inference doesn't seem to be using GPU. How can I do so?

I've tried this but getting a `CUDNN_STATUS_NOT_INITIALIZED` error:

````
run_opts = {"device": "cuda","data_parallel_count": -1,"data_parallel_backend": False,"distributed_launch": False,"distributed_backend": "nccl","jit_module_keys": None}

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="pretrained_model", run_opts=run_opts)
```

**Comment by Gastron** [comment]
Using the `device` option in `run_opts` is the intended way. The error message you posted suggests a problem with the  cuDNN installation (or some other issue with the GPU drivers or e.g. cuda-cudnn version mismatch). 

Does `torch.cuda.is_available()` return `True` for you? Could you check cuDNN and Cuda versions and GPU?

**Comment by mschonwe** [comment]
Searching for how to specify _"the `device` option in `run_opts`"_

for example, can this be a command line flag `--device cuda`?
or does it need to be json on the command line:
`python3 example_asr_ctc_experiment.py hyperparams.yaml 'run_opts = {"device": "cuda:0"}'`

I've tried both of these and neither seems to work. 

(torch.cuda.is_available() does return True for me)

**Comment by mravanelli** [comment]
python example_asr_ctc_experiment.py hyperparams.yaml --device='cuda:0'.
Isn't that working? It works on my end.

**Comment by mschonwe** [comment]
The training _runs_ fine, but while monitoring via nvidia-smi on a loop, the GPU is idle with no running processes attached to it.

There is no logging to the screen or anywhere else that gives clues to what device(s) are being used.   I've tried adding `--debug --log_config mylog` to the command line those also seem to have no effect.

**Comment by pplantinga** [comment]
The integration tests do not read command line parameters, because they are mostly just designed for checking to make sure that our neural networks can overfit properly. If you're looking for an example file to run, the best place to find this is in `templates` where we have well-documented examples of ASR, enhancement, and speaker ID.

**Comment by alpoktem** [comment]
`torch.cuda.is_available()` returns `True`. I have a stable cuDNN and Cuda installation since I use them in other torch based code.

**Comment by mschonwe** [comment]
Sorry @alpoktem that I derailed your question.  I got the _training_ to use the GPU (via templates/recipes), but now I'm hitting the issue that you were actually asking about **GPU during _inference_**.  

Seeing `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same` when running with `asr_model.device = 'cuda:0'` 

Using the example pre-trained model `asr_model = TransformerASR.from_hparams(source="speechbrain/asr-transformer-transformerlm-librispeech", savedir="pretrained_models/asr-transformer-transformerlm-librispeech"`

Can the pre-trained models only run on CPU?

**Comment by pplantinga** [comment]
@mschonwe You will need to pass the device to `run_opts` if you want to run on GPU. The `run_opts` can be just a manually-coded dictionary like {"device": "cuda"} or can parsed from the command line with `sb.parse_arguments(sys.argv[1:])`

@alpoktem what is the size of your GPU? If you're familiar with torch and haven't had problems in the past with cuda/cudnn than I'm a little stumped.

**Comment by mschonwe** [comment]
Here is the 'hello world' gpu inference script I'm using, with an empty param_file.yaml
```
import sys
import speechbrain as sb
from speechbrain.pretrained import TransformerASR
sb.parse_arguments(sys.argv[1:])
run_opts = {"device" : "cuda"}
asr_model = TransformerASR.from_hparams(source="speechbrain/asr-transformer-transformerlm-librispeech",savedir="pretrained_models/asr-transformer-transformerlm-librispeech")
result = asr_model.transcribe_file("speechbrain/asr-transformer-transformerlm-librispeech/example.wav")
print(result)
```
`python3 gputest.py param_file.yaml --device='cuda'`

As best I can tell, the processing is happening on CPU only.

**Comment by pplantinga** [comment]
Try:
```python
asr_model = TransformerASR.from_hparams(
  source="speechbrain/asr-transformer-transformerlm-librispeech",
  savedir="pretrained_models/asr-transformer-transformerlm-librispeech",
  run_opts={"device": "cuda"},
}
```

**Comment by mschonwe** [comment]
That works! :)

Sorry for the noob question.  But I figure I might not be the only one.

btw, in your example the closing "}" s.b. a ")"

**Comment by alpoktem** [comment]
I was wrong trusting `torch.cuda.is_available()` saying everything is fine. I had upgraded to PyTorch 1.8 as required by speechbrain and it broke my other GPU training setups too. I was getting this error:
```
`RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

Reverting back into torch 1.7.1 fixed it for me. I am now able to run both my and @mschonwe's code using GPU. Thanks for the guidance @pplantinga.
