### ISSUE TITLE
AMI Diarization

### ISSUE THREAD

**Issue by vrinda14** [speechbrain/speechbrain#578]
It's mentioned in the experiments.py to run the file using :
python experiment.py hyperparams.yaml
 This raises an error as :
File "experiment.py", line 389, in <module>
    with open(params_file) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'hyperparams.yaml'

How to use speaker diarization . Pls guide

**Comment by TParcollet** [comment]
hyperparameter filenames vary according to the recipes. You will find the files in the folder hparams of each recipe.

**Comment by vrinda14** [comment]
Thanks for the response !!  I tried running both the files in hparams ,  still getting an error

File "experiment.py", line 229, in diarize_dataset
    concate_rttm_file = out_rttm_dir + "/sys_output.rttm"
UnboundLocalError: local variable 'out_rttm_dir' referenced before assignment

**Comment by nauman-daw** [comment]
Hi, 

`out_rttm_dir` is already assigned at line 201. 
https://github.com/speechbrain/speechbrain/blob/30e466393a1730f138909d3ae696d5acfb48a09f/recipes/AMI/Diarization/experiment.py#L201

Did you set the paths according to your directory structure in yaml files? After setting the paths you can use it as: 
`python experiment.py hparams/ecapa_tdnn.yaml`

**Comment by vrinda14** [comment]
Thank you for the response . Should i download from this link https://groups.inf.ed.ac.uk/ami/download/
Also, are you refering to these paths in yaml files ,
data_folder: /network/datasets/ami/amicorpus
manual_annot_folder: /miniscratch/nauman/ami_public_manual
output_folder: results/ami/sd_ecapa_tdnn/
save_folder: !ref <output_folder>/save
device: 'cuda:0'

Very new to this. Kindly help.

**Comment by nauman-daw** [comment]
Sure. We would like to help you get started.

Yes, you have to download the dataset before you can run the recipe and also update the paths in the yaml file accordingly.

I would suggest you to go through the basic tutorial on SpeechBrain (https://speechbrain.github.io/tutorial_basics.html). This is a nice tutorial to easily get started. Alongside, you can also refer to the documentation.

Also, please feel free to put questions on discourse (https://speechbrain.discourse.group) where we may have more general discussions on general topics.

**Comment by vrinda14** [comment]
Thanks a lot for the response! Will post questions if any on discourse. 
Thanks for the help.

**Comment by TianlongKong** [comment]
> Thank you for the response . Should i download from this link https://groups.inf.ed.ac.uk/ami/download/ Also, are you refering to these paths in yaml files , data_folder: /network/datasets/ami/amicorpus manual_annot_folder: /miniscratch/nauman/ami_public_manual output_folder: results/ami/sd_ecapa_tdnn/ save_folder: !ref <output_folder>/save device: 'cuda:0'
> 
> Very new to this. Kindly help.

Hello, when i want to download at https://groups.inf.ed.ac.uk/ami/download/, I don't know how to download those as data, can you give some introduction?

![image](https://user-images.githubusercontent.com/65606373/149091764-ae1501c4-f10b-484b-8349-15b38309cb40.png)

![image](https://user-images.githubusercontent.com/65606373/149091841-cf746f45-2523-4881-9f53-fc89162bee06.png)

Thanks a lot!

**Comment by TianlongKong** [comment]
> > Thank you for the response . Should i download from this link https://groups.inf.ed.ac.uk/ami/download/ Also, are you refering to these paths in yaml files , data_folder: /network/datasets/ami/amicorpus manual_annot_folder: /miniscratch/nauman/ami_public_manual output_folder: results/ami/sd_ecapa_tdnn/ save_folder: !ref <output_folder>/save device: 'cuda:0'
> > Very new to this. Kindly help.
> 
> Hello, when i want to download at https://groups.inf.ed.ac.uk/ami/download/, I don't know how to download those as data, can you give some introduction?
> 
> ![image](https://user-images.githubusercontent.com/65606373/149091764-ae1501c4-f10b-484b-8349-15b38309cb40.png)
> 
> ![image](https://user-images.githubusercontent.com/65606373/149091841-cf746f45-2523-4881-9f53-fc89162bee06.png)
> 
> Thanks a lot!

Which should I choose to download?
