### ISSUE TITLE
how to inference in .py  not shell

### ISSUE THREAD

**Issue by wac81** [speechbrain/speechbrain#585]
how to inference in .py  not shell

**Comment by TParcollet** [comment]
Hey, it depends on what you would like to do (exactly). If it's from hugging face, you can just copy and past the "commands" otherwise, you might want to describe a bit more what you would like to do so we can help

**Comment by wac81** [comment]
i want inference from wav file or stream, what can i do ?

**Comment by mravanelli** [comment]
From wav file inference, you can basically take a look here:
https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech

As you know, we have special classes designed to do inference on different
models.
