### ISSUE TITLE
Request: Add edge based KWS to  the framework

### ISSUE THREAD

**Issue by StuartIanNaylor** [speechbrain/speechbrain#592]
It would be great to also have satellite KWS added to the project as with pytorch & pytorch audio it seems to enforce some vendor considerations.

I would be really interested in a common MFCC method for Brain and Edge or maybe 'Shelf' is a better description for simple devices that connect to a brain to create solutions.
Having a MFCC source reduces Brain process but also makes an extremely low bandwidth audio representative stream.

I have been playing with the Google KWS from there research repo and the quantised TFL models can run on a little as 20% of a single core of a Pi3 which gives a lot of headroom for some interesting implementations.
I have my convenience repo https://github.com/StuartIanNaylor/google-kws which is all google work with just some quick scripts to test inference.

It would be really great to have, something similar, Brain addons as my current interest with the above is to  use simple multi-mic unidirectional distributed mics and use KW hit to position the near/far stream and maybe try blind source separation as a relatively low load feed to the brain.

But also in network mic situations MFCC as a stream is also another consideration but having identical processing is essential, but my tests the methods of torchaudio seem strangely locked to intel_mkl (maybe that has changed?)

The dataset set side of Google-kws could do with some work but the models for TFL are extremely lite and not saying use it but as an example its exactly what I would envisage if I was to look at distributed edge devices to connect to a brain.
The google methods use 2 MFCC methods a DCT method that should run with any inference engine and then there TF FFT based one.

**Comment by TParcollet** [comment]
Maybe you could put this on our Discourse and try to foster some discussion from there. I am not super familiar with this topic though.
