### ISSUE TITLE
"sox_io" is set as the default torchaudio backend in stoi_loss.py and dataio.py

### ISSUE THREAD

**Issue by UrosOgrizovic** [speechbrain/speechbrain#593]
Right now, if running on Windows, it's necessary to manually change from `torchaudio.set_audio_backend("sox_io")` to `torchaudio.set_audio_backend("soundfile")` in two files: `stoi_loss.py` and `dataio.py`. It seems reasonable to me that a check should be written, determining whether the system is "soundfile"- or "sox_io"-compatible.

`python` version: 3.8.3
`torchaudio` version: 0.8.0
`speechbrain` version: 0.5.4

**Comment by mravanelli** [comment]
Hi,
there is an ongoing PR for fixing that. Could you please try it?
https://github.com/speechbrain/speechbrain/pull/560
