### ISSUE TITLE
interfaces.py separate_file() not working properly?

### ISSUE THREAD

**Issue by UrosOgrizovic** [speechbrain/speechbrain#594]
Specs: Windows Version	10.0.19042 Build 19042, Python 3.8.3

I'm following the Source Separation tutorial that can be accessed from [this page](https://speechbrain.github.io/tutorial_processing.html).

Since the audio I have is already mixed, I tried to use `model.separate_file()`, based off the HuggingFace speechbrain/sepformer-wsj02mix [code](https://huggingface.co/speechbrain/sepformer-wsj02mix). There are two issues with that:

1. CPU, RAM and disk usage on my PC shoot up into the high nineties, causing the computer to freeze.
2. After the computer unfreezes (presumably, after the calculations are finished), an error is thrown:
```
Traceback (most recent call last):
  ...
    est_sources = model.separate_file(path='data/test/audio/speech.wav')
  File "C:\...\venv\lib\site-packages\speechbrain\pretrained\interfaces.py", line 710, in separate_file
    est_sources = self.separate_batch(batch)
  File "C:\...\venv\lib\site-packages\speechbrain\pretrained\interfaces.py", line 669, in separate_batch
    est_mask = self.modules.masknet(mix_w)
  File "C:\...\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\...\venv\lib\site-packages\speechbrain\lobes\models\dual_path.py", line 1124, in forward
    x = self.dual_mdl[i](x)
  File "C:\...\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\...\venv\lib\site-packages\speechbrain\lobes\models\dual_path.py", line 975, in forward
    inter = self.inter_mdl(inter)
  File "C:\...\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\...\venv\lib\site-packages\speechbrain\lobes\models\dual_path.py", line 597, in forward
    return self.mdl(x + pos_enc)[0]
RuntimeError: The size of tensor a (2830) must match the size of tensor b (2500) at non-singleton dimension 1
```

My guess is that the data that `separate_file()` passes to `separate_batch()` is incorrect:
```
source, fl = split_path(path)
path = fetch(fl, source=source, savedir=savedir)
batch, _ = torchaudio.load(path)
est_sources = self.separate_batch(batch)
```

Does resampling the data have something to do with it?

If, instead of using `separate_file()`, I write:
```
mix, fs = torchaudio.load('data/test/audio/speech.wav')
resampler = torchaudio.transforms.Resample(fs, 8000)
mix = resampler(mix)
est_sources = model.separate_batch(mix)
```

as suggested in the aforementioned tutorial, the computer doesn't freeze and `est_sources` is a `torch.Tensor` with `torch.Size([1, 471272, 2])`, which looks like expected behavior to me.

**Comment by mravanelli** [comment]
I didn't see this issue when I tried it few days ago. @ycemsubakan could you please take a look?

**Comment by ycemsubakan** [comment]
It seems this is related to the maximum length parameter inside the positional encodings. Those are currently set to 2500 maximum sequence length. If you downsample your signal to 8k, and then use the `separate_file()` function, it should work also, as it seems like after downsampling the sequence that is entered in the transformer is shorter than 2500.

**Comment by UrosOgrizovic** [comment]
It does work, but since `separate_file()` requires a path argument, I had to load the data, downsample it, save it to a file, and then pass the path to that file into `separate_file()`. To me, this seems unnecessary. Wouldn't it be better if the required downsampling was performed in the `separate_file()` method?

**Comment by ycemsubakan** [comment]
Yes, this is a good suggestion actually. We will add this to the code. Thank you @UrosOgrizovic !

**Comment by ycemsubakan** [comment]
The suggested fix has been implemented in #608 .

**Comment by rogermiranda1000** [comment]
Was this fixed? I'm having the same problem (using the latest version, `v0.5.13`).


```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Import all libraries
import speechbrain as sb
from speechbrain.dataio.dataio import read_audio, write_audio
import soundfile as sf # save librosa output
from speechbrain.pretrained import SepformerSeparation as separator # pretrained model by SpeechBrain
import os

MODEL_SAMPLE_RATE = 8000

if __name__ == '__main__':
    # Get audio
    print(f"[v] Getting file...")
    file_name = "../tmp_Vocals.wav"
    signal = read_audio(file_name).squeeze() # returns a `torch.Tensor`

    # separate
    print(f"[v] Separating speakers...")
    model = separator.from_hparams(source="speechbrain/sepformer-wsj02mix", savedir='pretrained_models/sepformer-wsj02mix')
    tmp_file_name = "tmp.wav"
    est_sources = model.separate_file(path=file_name, savedir=tmp_file_name) # ERROR HERE
```

Logs:
```
[v] Getting file...
[v] Separating speakers...
Resampling the audio from 44100 Hz to 8000 Hz
Traceback (most recent call last):
  File "init.py", line 24, in <module>
    est_sources = model.separate_file(path=file_name, savedir=tmp_file_name)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 2033, in separate_file
    est_sources = self.separate_batch(batch)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 1976, in separate_batch
    est_mask = self.mods.masknet(mix_w)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/speechbrain/lobes/models/dual_path.py", line 1021, in forward
    x = self.dual_mdl[i](x)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/speechbrain/lobes/models/dual_path.py", line 872, in forward
    inter = self.inter_mdl(inter)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rogermiranda1000/miniconda3/lib/python3.10/site-packages/speechbrain/lobes/models/dual_path.py", line 597, in forward
    return self.mdl(x + pos_enc)[0]
RuntimeError: The size of tensor a (4924) must match the size of tensor b (2500) at non-singleton dimension 1
```

**Comment by pamann** [comment]
I am also still having this problem in `v0.5.13 `

**Comment by rogermiranda1000** [comment]
@mravanelli @ycemsubakan maybe the ticket needs to be re-opened?

**Comment by rogermiranda1000** [comment]
> I am also still having this problem in `v0.5.13 `
> 
> I tried using the code suggested by @UrosOgrizovic, using `separate_batch` instead of `separate_file`. Still getting the same issue though, only occurs with some audio files.

Same about the `separate_batch`. I also tried with `v0.5.7` and I got the same results.

**Comment by pamann** [comment]
Ah okay, it seems like this is also related to the `max_length` parameter. Splitting one of the files that failed into smaller chunks and running them individually fixes the problem. Is there a reason why that parameter isn't overridable?

**Comment by yc-li20** [comment]
still having the problem

**Comment by rogermiranda1000** [comment]
> @rogermiranda1000 Hi Roger, did you find a solution to this?

I actually don't remember. I've seen this error multiple times, and usually it was one of those 3 things:
1. The audio is stereo (multiple channels); it has to have one channel
2. The audio needs to be downsampled (I see in this issue that I tried `MODEL_SAMPLE_RATE = 8000`)
3. The audio is too long

You can try if any of those solves the issue, and if it does please state it here ( don't be like me XD ). Hope it helps!

**Comment by ycemsubakan** [comment]
Thanks for your reply @rogermiranda1000 
@yc-li20 , please check what's happening here:

https://github.com/speechbrain/speechbrain/blob/f285f19e50567d5ba25f06c83c9bd9a31742b386/speechbrain/pretrained/interfaces.py#L2223

the file is automatically converted to mono, and it automatically down/re-samples the input audio to the model sampling frequency. 

I think in your case it's due to the signal being long. And that's due to the positional embeddings. Can you try feeding a shorter audio?

**Comment by yc-li20** [comment]
> > @rogermiranda1000 Hi Roger, did you find a solution to this?
> 
> I actually don't remember. I've seen this error multiple times, and usually it was one of those 3 things:
> 
> 1. The audio is stereo (multiple channels); it has to have one channel
> 2. The audio needs to be downsampled (I see in this issue that I tried `MODEL_SAMPLE_RATE = 8000`)
> 3. The audio is too long
> 
> You can try if any of those solves the issue, and if it does please state it here ( don't be like me XD ). Hope it helps!

Thank you so much for your kind response, Roger! Wish you happy holidays!

**Comment by yc-li20** [comment]
> Thanks for your reply @rogermiranda1000 @yc-li20 , please check what's happening here:
> 
> https://github.com/speechbrain/speechbrain/blob/f285f19e50567d5ba25f06c83c9bd9a31742b386/speechbrain/pretrained/interfaces.py#L2223
> 
> the file is automatically converted to mono, and it automatically down/re-samples the input audio to the model sampling frequency.
> 
> I think in your case it's due to the signal being long. And that's due to the positional embeddings. Can you try feeding a shorter audio?

Thank you for your prompt answer, Cem! @ycemsubakan  I noticed this problem and am wondering if it is proper to simply chop the audio and then concatenate.

**Comment by ycemsubakan** [comment]
Yes, I think you can process the long chunks and concatenate. In the
transition you might have artifacts, but you can definitely try.

Best,
Cem

**Comment by yc-li20** [comment]
> Yes, I think you can process the long chunks and concatenate. In the transition you might have artifacts, but you can definitely try. Best, Cem Le ven. 15 déc. 2023, à 18 h 52, YC ***@***.***> a écrit :
> […](#)

Thank you, Cem! I am in the process of this. Hope it works well.
Happy early holidays!
