### ISSUE TITLE
how to inference in local model?

### ISSUE THREAD

**Issue by dayu1979** [speechbrain/speechbrain#598]
i train one model
# Encoder: CRDNN model
# Decoder: GRU + beamsearch + RNNLM
but i dont know how to test on wavs

**Comment by mravanelli** [comment]
You might wanna take a look into the classes we designed for inference:
https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py
In particular, you might take a look into the EncoderDecoderASR one, which
is the one we use to do inference on the released models on HuggingFace (
https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech).
