### ISSUE TITLE
md-eval.pl perl script for diarization evaluation is failing in pip package

### ISSUE THREAD

**Issue by Joepetey** [speechbrain/speechbrain#600]
`Traceback (most recent call last):
  File "experiment.py", line 444, in <module>
    best_nn = dev_nn_tuner(full_csv, "dev")
  File "experiment.py", line 299, in dev_nn_tuner
    [MS, FA, SER, DER_] = DER(
  File "/home/michael/anaconda3/lib/python3.8/site-packages/speechbrain/utils/DER.py", line 103, in DER
    stdout = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/home/michael/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/michael/anaconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/michael/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/michael/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: '/home/michael/anaconda3/lib/python3.8/site-packages/speechbrain/utils              /../../tools/der_eval/md-eval.pl'`

Got that error when running the AMI diarization experiment.py file. Looked in the directoy and couldn't find a tools folder.

Edit: Forgive me, but I can't figure out how to format the traceback correctly.
![image](https://user-images.githubusercontent.com/28886640/112080888-1d02b900-8b59-11eb-8ee4-4a75d3323424.png)

**Comment by mravanelli** [comment]
@nauman-daw could you please double check this with the latest version of speechbrain?

**Comment by TParcollet** [comment]
@mravanelli isn't the problem that tools aren't installed with the package SpeechBrain :o

**Comment by nauman-daw** [comment]
Hi,
Have you done pip install or cloned the git repo?

**Comment by Joepetey** [comment]
I pip installed the package.

**Comment by nauman-daw** [comment]
Just discussed with our team. Looks like there is some issue with having perl script (md-eval.pl) installed in pip package. We plan to fix this in coming future. Meanwhile, please free to clone git repo. It should work fine.

**Comment by EklavyaFCB** [comment]
I had the same issue. Pip install gives the same error, but via git clone works for now.

**Comment by AMITKESARI2000** [comment]
Any update on this ?
Still getting same error for `speechbrain==0.5.12` pip installation
