### ISSUE TITLE
About conformer cache mechanism

### ISSUE THREAD

**Issue by Speakin-sy** [speechbrain/speechbrain#601]
Hi,
I find that the conformer encoder does not support cache mechanism for inference. 
I think it's helpful, so I just want to give a suggestion here. : )
Regards

**Comment by mravanelli** [comment]
@JianyuanZhong, any insight on that?

**Comment by JianyuanZhong** [comment]
Hi @Speakin-sy, thank you for raising this issue!

As far as I understand, the cache mechanism for the transformer/conformer is to cache to input feature for t -1 steps and only compute feature for the t step when being used for auto-regressive inference.

TBH, I don't know how much time it can save, but it will take some space to store caches for each layer. For example, the most time-consuming parts of ASR beam-search IMO are the CTC-prefix-scorer and index-slicing. But we basically have to store features from 18 transformer layers (AM + LM) with caches.

I think we hope to decode our ASR models with a single GPU to speed up the decoding at the current stage. However, I am not sure if we can do that with the cache mechanism.

We also have predefined interfaces for decoding with transformers if your question is related to inference without such a cache mechanism.

Let me know if you still would like to see this feature!

**Comment by Speakin-sy** [comment]
Hi @JianyuanZhong , thank you for your reply~

I agree that CTC and auto-regression decoding calculation are more time consuming. And cache mechanism can only reduce the time that the data pass through transformer/conformer structures. Maybe it can be added in the future~

Regards
