### ISSUE TITLE
Can't use an existing RIRS_NOISES dir

### ISSUE THREAD

**Issue by RuABraun** [speechbrain/speechbrain#602]
I'm trying to run the librispeech transformer recipe. I want to use an existing RIRS_NOISES folder instead of downloading a new one.

Unless I've done something wrong, it seems like regardless of whether one sets the path to an existing dir or not the dataset is downloaded again. [See if statement here](https://github.com/speechbrain/speechbrain/blob/e2ad28433291f1c2fbddb7a896b07d5ccb972a92/speechbrain/lobes/augment.py#L453), it downloads in both cases.

So I think that if statement needs to be fixed.

On the side:
I think it's a pretty common scenario to have a dedicated disk (as part of a cluster) where raw data is saved. To avoid someone accidentally deleting something those dirs are set to Read-Only. So I think it makes sense that scripts should be able to use existing data directories that are RO. Just a thought. (Even if I change the if statement above, I still get an error because the script creates new files in the passed directory.)

**Comment by mravanelli** [comment]
Thank you  @RuABraun. I think this should be fixed. Could you please @pplantinga take a look into that?
Let me take this opportunity to remark the workflow that we suggest (at least when possible):

**Comment by RuABraun** [comment]
I didn't think of the slowdown, you're right thank you for elaborating.
