### ISSUE TITLE
How can SpeechBrain's ASR support different languages?

### ISSUE THREAD

**Issue by leijue222** [speechbrain/speechbrain#604]
Hi, it's a nice project! But I have some questions that I need help with.
Which languages does the ASR currently provided by SpeechBrain support?
[Official pre-trained models](https://huggingface.co/speechbrain) seems only support English and Italian.

### Test examples
The multilingual audio(Zh&En) can only recognize English
![微信截图_20210325103952](https://user-images.githubusercontent.com/30276789/112410642-7be15180-8d56-11eb-8a23-3848527dba8f.png)
I hope that both Chinese and English can be correctly recognized. 
How can I use SpeechBrain to achieve this goal?

**Comment by mravanelli** [comment]
The model that you are using is trained for English. You can easily train models in different languages (see for instance our recipes on CommonVoice)
