### ISSUE TITLE
the result in single machine with single gpu and single machine with two gpu is very different

### ISSUE THREAD

**Issue by wwbnjsace** [speechbrain/speechbrain#605]
i use speechbrain to train mini_librespeech. i train it in single machine with single gpu and single machine with two gpus.after tringing ,the wer is very different, in single machine with single gpu,the wer is %WER 35.76 [ 18802 / 52576, 16605 ins, 327 del, 1870 sub ],howerer in single machine with two gpu,the wer is %WER 77.34 [ 40661 / 52576, 38646 ins, 178 del, 1837 sub ].

the single machine with two gpu is:
PyTorch version: 1.7.1
CUDA used to build PyTorch: 10.2
OS: Ubuntu 18.04.4 LTS (x86_64)
Python version: 3.8 (64-bit runtime)
CUDA runtime version: 9.1.85
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
Nvidia driver version: 440.100
and the pypameter is: number_of_epochs: 15 ;batch_size: 4;lr: 1.0
the command is python3 train.py train.yaml --data_parallel_backend=True --data_parallel_count=2

the single machine with single gpu is:
PyTorch version: 1.7.1
CUDA used to build PyTorch: 10.2
OS: Ubuntu 16.04.7 LTS (x86_64)
Python version: 3.8 (64-bit runtime)
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 450.80.02
and the pypameter is: number_of_epochs: 15 ;batch_size: 4;lr: 1.0
the command is python train.py train.yaml

in the end ,the wer result is very different
why?

**Comment by mravanelli** [comment]
@aheba

**Comment by aheba** [comment]
hello @wwbnjsace, could you please share the `mini_librispeech` recipe with us (Github link)? I can take a deeper look

**Comment by TParcollet** [comment]
@aheba any update ?

**Comment by aheba** [comment]
@wwbnjsace could you share with us the code + results please ? 
We can reopen this issue when having more information.
