### ISSUE TITLE
Extract hidden states of PyTorch module

### ISSUE THREAD

**Issue by gretatuckute** [speechbrain/speechbrain#606]
Hi,
First of all, thank you for this brilliant framework.

Is it possible to extract model representations of the pre-trained models for a given input. Say I load: 

```
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech",
											 savedir="pretrained_models/asr-crdnn-rnnlm-librispeech")
asr_model.transcribe_file('speechbrain/asr-crdnn-rnnlm-librispeech/example.wav')
asr_model.modules
```

Under asr_model.modules I am able to see the PyTorch modules, but I am not able to see the hidden states (similar to Huggingface model(output_hidden_states=True). Is this currently possible in Speechbrain?

Thank you,
Greta

**Comment by TParcollet** [comment]
Hi and sorry for the late reply,

So, directly from the current implementation of EncoderDecoderASR, it isn't possible. However, it can easily be done (if you did not install speechbrain with pip install as you will need the source of EncoderDecoderASR). What do you call "hidden_states". RNN states ? Because our CRDNN is CNN->RNN-> DNN so RNN states aren't the last linear transformation of the encoder.

**Comment by TParcollet** [comment]
Hi @gretatuckute, what is the status of your issue ? :-D

**Comment by gretatuckute** [comment]
Hi, thank you very much for following up, and apologies for the delay. By hidden states I mean the weights/states of the modules of CRDNN, so those of the CNN and the RNN (or, just the RNN), similar to how the flag "output_hidden_states=True" in the Huggingface Transformers framework outputs states from the neural networks in the encoders/decoders in the transformer blocks. So, you pass an input through the model, and output the hidden states of how the input is represented in the model. So, would that be possible to extract from the source code of the pretrained models in EncoderDecoderASR? 
Again, thank you!

**Comment by TParcollet** [comment]
Oof, I just realized that I completely missed this issue. I suppose that your problem is now solved @gretatuckute ?
