### ISSUE TITLE
inference with the ASR model in AISHELL-1 dataset

### ISSUE THREAD

**Issue by gotogotogo** [speechbrain/speechbrain#607]
I trained the recipe ASR model with /speechbrain/recipes/AISHELL-1/ASR/train.py  in AISHELL-1, and inference with the following code:
<pre>from speechbrain.pretrained import EncoderDecoderASR    
asr_model = EncoderDecoderASR.from_hparams(source="/home/linhj/speechbrain/recipes/AISHELL-1/ASR/results/base/1/", savedir="pretrained_models/asr")  
result = asr_model.transcribe_file('/home/linhj/myaudio/myaudio.wav')  
print('result: ', result)</pre>
but I gained following ValueError:

>  File "/home/linhj/speechbrain/speechbrain/pretrained/interfaces.py", line 270, in __init__    
        super().__init__(*args, **kwargs)   
File "/home/linhj/speechbrain/speechbrain/pretrained/interfaces.py", line 91, in __init__    
        raise ValueError(f"Need modules['{mod}']") 
ValueError: Need modules['compute_features'] 

could you please teach me how to solve this error .
Thank you very much !

**Comment by mravanelli** [comment]
@lorenlugosch, did you try in the past to use an AISHELL model with our EncoderDecoderASR?

**Comment by lorenlugosch** [comment]
I have not. The AISHELL recipe is basically identical to the LibriSpeech seq2seq model (but with no external LM), so it should work just fine.

@Gastron or @pplantinga might be able to help.

**Comment by mravanelli** [comment]
Now this is supported: https://huggingface.co/speechbrain/asr-transformer-aishell
