### ISSUE TITLE
unsupervised learning / PASE

### ISSUE THREAD

**Issue by tensorfoo** [speechbrain/speechbrain#610]
hi, I have come across the existing pykaldi implementation but I am curious about PASE implemented in speechbrain. Would @mravanelli kindly give his thoughts on what sort of work that would take and how things would be best done in speechbrain. In case someone was looking to help the project out, what would be a rough guide in how to go about it. Many thanks to the entire speechbrain team.

**Comment by TParcollet** [comment]
From what I am aware of, we currently have 3 different PASE implementation within private forks of SpeechBrain. Two are from @salah-zaiem and @aheba but I don't know about the third one. Maybe we can hope to see one of them pushed after Interspeech ? @salah-zaiem do you think you could take few days after IS to properly push your PASE ?

**Comment by TParcollet** [comment]
On the contrary, we are lacking peoples working on wav2vec2 (if interested :-p)

**Comment by mravanelli** [comment]
Yes, I confirm that self-supervised learning with PASE and wav2vect is something are working on. Any help on that part from the community is really welcome!

**Comment by TParcollet** [comment]
@tensorfoo note that we currently have a PR to support wav2vec2 pretrained models from fairseq (you just need to specify the url of the model). It isn't merged yet, but works.
