### ISSUE TITLE
Testing speed slow compared to dev during training

### ISSUE THREAD

**Issue by BuaaAlban** [speechbrain/speechbrain#611]
I have using the code in [transformer asr on librispeech](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/ASR/transformer)

I tested performance by commenting out Training parts in the train.py, I found that testing is really slow compared to that of testing on dev clean during the end of an training epoch(approximately 1min vs 200 min ) even if I set the  **test_beam_size: 1**  instead of **66**.  

Do you have any ideas? Thanks
here is the scripts and configs  I am using. 
[eval_and_yaml.zip](https://github.com/speechbrain/speechbrain/files/6220316/eval_and_yaml.zip)

**Comment by JianyuanZhong** [comment]
Thank you for raising this issue. For saving speech, we ONLY perform decoding for dev every 10 epoch. For the rest of the epochs, we report the accuracy of the one-step-forward prediction. This is the reason why you see such a speed difference.

Also, it's worth noting that we perform decoding on dev without LM with **valid_beam_size: 10**. This makes the decoding for the dev stage faster than that of the test stage (~60 min vs 180 min on V100 GPU).

I hope this can solve your concerns!

**Comment by BuaaAlban** [comment]
> Thank you for raising this issue. For saving speech, we ONLY perform decoding for dev every 10 epoch. For the rest of the epochs, we report the accuracy of the one-step-forward prediction. This is the reason why you see such a speed difference.
> 
> Also, it's worth noting that we perform decoding on dev without LM with **valid_beam_size: 10**. This makes the decoding for the dev stage faster than that of the test stage (~60 min vs 180 min on V100 GPU).
> 
> I hope this can solve your concerns!

Thanks for your reply, now I get to know why there is a speed difference, but I wonder what is the one-step -forward prediction(what's the difference between it and greedy decode, it's faster than GD)? whould you please give me some reference?

**Comment by mravanelli** [comment]
@JianyuanZhong, could you please provide some clarification on the difference between decoding and one-step-forward prediction as requested by @BuaaAlban?

**Comment by TParcollet** [comment]
I believe that it is GD (we do not use Beam Search for the ACC computation). But it's like, on-the-fly GD as we do it while training.
