### ISSUE TITLE
bug in recipe WSJ0Mix when training with dynamic mixing in multi-thread dataloader mode

### ISSUE THREAD

**Issue by hongwenxie** [speechbrain/speechbrain#614]
The decorated local function audio_pipeline() in dynamic_mix_data_prep() can not be serialized by python, an "can not pickle local object *<local>.audio_pipeline*"  occurs

**Comment by TParcollet** [comment]
@pplantinga

**Comment by pplantinga** [comment]
I think @ycemsubakan was the author of this.

**Comment by ycemsubakan** [comment]
Thanks for sharing this error. I will look into this.

**Comment by ycemsubakan** [comment]
@hongwenxie Do you run the script `recipes/WSJ0Mix/meta/preprocess_dynamic_mixing.py` to preprocess your wsj0 folder as described in the README?

**Comment by karims** [comment]
This happens to me on Mac, but not on Ubuntu/CentOS. Are you running on Mac, @hongwenxie  ? If it so, let me know, i will tell you the fix.

**Comment by mravanelli** [comment]
Can we find a fix that makes the code working on both linux and Mac?

**Comment by karims** [comment]
The fix I have isn't code change, but in settings of `dataloader`. I made `num_workers = 0` :

```
# Dataloader options
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 0
```

It is a problem with multiprocessing library on mac where the default way of starting new process is `spawn`, but in Linux it is `fork` where the state is shared.

It is very slow with this setting, but helps if one is working locally and not running on large data.

However, it could be another reason as well. Just want to confirm from @hongwenxie if it is a Mac issue.

**Comment by mravanelli** [comment]
Cem, is there a huge difference in computing time if we set num_workers=0?
As an alternative, we can add a comment like "set it to 0" on a mac
machine.

**Comment by ycemsubakan** [comment]
I tried with `num_workers=0` on the Mila compute cluster, and the estimated time difference seems to be around 10 minutes for one epoch on WSJ0-2Mix. I added a note for MacOS users on the pull request #623 .

**Comment by hongwenxie** [comment]
> This happens to me on Mac, but not on Ubuntu/CentOS. Are you running on Mac, @hongwenxie ? If it so, let me know, i will tell you the fix.

Yes, I run it on Mac. Num_workers=0 is Ok, but when num_workers>0 an error occurs
