### ISSUE TITLE
about name "sb"

### ISSUE THREAD

**Issue by koala7580** [speechbrain/speechbrain#619]
没有人来吐槽一下吗？这个“sb”在中文里是个不咋雅观的词。建议修改下简称。。。
Is there no one to complain about it? This "sb" is an unsightly word in Chinese. It is recommended to modify the abbreviation below. . .

**Comment by TParcollet** [comment]
AH. 

We did not know that indeed despite having Chinese researchers in the team. We can discuss this internally. @mravanelli

**Comment by zzFon** [comment]
indeed. sb means fool in Chinese (abbr. for Sha Bi). but that's fine, i think, it is not that rude actually. 
it brings me fun during the coding time aha :)

**Comment by TParcollet** [comment]
According to internal discussions, we do not feel like this something that should be tackled right now. Indeed, it's a very specific issue, and in the context of speechbrain, it is pretty clear that "sb" means SpeechBrain. 

Thank you so much for reporting this "funny" issue.
