### ISSUE TITLE
Relative position embedding in the Conformer

### ISSUE THREAD

**Issue by joyolee** [speechbrain/speechbrain#620]
Hi,
As I see in the Conformer implementation of speechbrain, the encoder uses vanilla multi-head attention from the PyTorch(https://github.com/speechbrain/speechbrain/blob/92ab7c0e13935891256ffb6abfe8a8bd3075c292/speechbrain/lobes/models/transformer/conformer.py#L130-L132). While in the original paper and implementation in ESPnet, the  MHA with **relative positional embedding** is used. I would ask if it will be fixed in the future or there is no difference in performance in your experience?

Best regards

**Comment by mravanelli** [comment]
We are comparing the standard MHA and the one with relative positional embeddings. For now, we have better results with the standard MHA.  The relative positional embedding one tends to overfit too much and we have to figure out if there is an issue somewhere. We are running some experiments to figure out what is going on. If you would like to help us with that, you are welcome! @JianyuanZhong @popcornell

**Comment by mravanelli** [comment]
@joyolee, feel free to help with the conformer. We are currently working on that, but the performance is not as good as it should be.

**Comment by TParcollet** [comment]
Being dealed with in #535.
