### ISSUE TITLE
Speechbrain: Transcription using Fine-tuned model

### ISSUE THREAD

**Issue by gauravgund** [speechbrain/speechbrain#627]
Hi @mravanelli ,

I have fine-tuned a model with custom dataset but could not find any code as to how to transcribe the audio files with the fine-tuned model of class "brain.fit()". Could you provide example code for the same?

**Comment by TParcollet** [comment]
Right, it highly depends on your model. In fact, you have to remember that your system is nothing more that a complex PyTorch model, hence you can simply "infer" on it. 

An example class of "how SpeechBrain uses pretrained encoder-decoder ASR models" is: https://github.com/speechbrain/speechbrain/blob/672685431515c1f2b499291a6ead99893979b59b/speechbrain/pretrained/interfaces.py#L353 

An example on how to call it:
https://huggingface.co/speechbrain/asr-crdnn-transformerlm-librispeech

If your model is identical to what we have on our recipes for LibriSpeech or CommonVoice for example, then you can even simply use this class.

**Comment by gauravgund** [comment]
Sure, let me try! I will get back
to you in case of queries!
