### ISSUE TITLE
how to add pitch features to the FBANK/MFCC features

### ISSUE THREAD

**Issue by ASR2020Guru** [speechbrain/speechbrain#631]
Hi @mravanelli 

Thanks for this killing toolkit👍.

I have noticed that the feature extraction process is on the GPU and count as the first layer to the network.

I would like to know how to add pitch features to the FBANK/MFCC features?
 
Thanks

**Comment by TParcollet** [comment]
Hey, I guess you would have to derive your own lobes from the existing MFCC / FBANKs as we don't have any implementation for that. But note that if you can come up with a solution to do it in PyTorch / Python, then it's a matter of 10 minutes to implement it by deriving our class :D

**Comment by mravanelli** [comment]
I think they have pitch in torchaudio, right? If so, we can simply import it in speechbrain.

**Comment by mravanelli** [comment]
@ASR2020Guru, I think we should create a lobe for adding pitch features and maybe adding an option to MFCCs and FBANKS lobes to concatenate pitch if required. Feel free to ask for a PR with that change if you have a little bit of time to work on that.
