### ISSUE TITLE
Inference from checkpoints ?

### ISSUE THREAD

**Issue by flozi00** [speechbrain/speechbrain#635]
I am training on a large dataset, each epoch takes some days and I choosed 5 epochs to train.
Now I wanted to test the model in real cases, it is still training but every hour an checkpoint is being saved.
I tried to load the checkpoint as shown in the tutorials or model cards on modelhub, but the asr.ckpt can't be found and loaded, 

![image](https://user-images.githubusercontent.com/47894090/114271048-d1348880-9a0f-11eb-8725-7cfeb49d049e.png)

That's what my checkpoints looks like, very different to the samples on modelhub.
How to convert the checkpoint into an valid model that can be loaded ?

**Comment by grgaDo** [comment]
How did you solve this problem?

I can't find `lm.ckpt`, `asr.ckpt` and `tokenizer.cpkt` (a file that should be generated after training the **LM**).

@flozi00
