### ISSUE TITLE
speech brain by c# programing 

### ISSUE THREAD

**Issue by doctorwho-123** [speechbrain/speechbrain#637]
Hello
Please develop this brain speech in C # so that it receives the sound live through the microphone and eventually converts it into text?

**Comment by flozi00** [comment]
https://github.com/speechbrain/speechbrain/issues/617#issuecomment-812361601

Maybe this helps ?

**Comment by doctorwho-123** [comment]
@flozi00 thank you . Unfortunately, this does not help me. I am looking for someone like this that I can add to Visal staduio through  nuget pagage . 

https://www.nuget.org/packages/Vosk/

**Comment by mravanelli** [comment]
SpeechBrain is implemented with pytorch and python. The models can be exported in c++ using torch.script and jit. We have no plans for c#.

**Comment by AleiChan** [comment]
> SpeechBrain is implemented with pytorch and python. The models can be exported in c++ using torch.script and jit. We have no plans for c#.

Hi, how to export the model using torch.jit.script , please?
