### ISSUE TITLE
speech brain in Distributed control system c# or c 

### ISSUE THREAD

**Issue by doctorwho-123** [speechbrain/speechbrain#638]
Please train speech brain  in Persian and English languge  for specialized words in Distributed control system
  so that it can recognize words in this field.

**Comment by TParcollet** [comment]
Hi, I am not sure to understand what you would like to see here.

**Comment by doctorwho-123** [comment]
@TParcollet I mean, speehbrain for the most specialized words in the field of oil and gas, especially industrial systems  " Distributed control system "  deltav and .... using the deep learning.

**Comment by mravanelli** [comment]
The current version of the toolkit already allows users to train a system with this and other features. This is not something the  development team is gong to do though because we have to focus on core functionalities and not on specific topics like that.
