### ISSUE TITLE
Does speech brain work offline?

### ISSUE THREAD

**Issue by doctorwho-123** [speechbrain/speechbrain#639]
Does speech brain work offline? Unfortunately, there are no speech recognition systems that work offline yet?

**Comment by flozi00** [comment]
If all ressources are lokal everything works fine without ethernet in my environment.
After saving the trained model the predictions works locally

**Comment by doctorwho-123** [comment]
@flozi00  
thank you . The problem I have is how to use this model in the visual environment of C # studio. The program I am writing is based on C # language, but the model that is the most popular is Python language. Please advise me how to use this in C # environment.

**Comment by TParcollet** [comment]
Well, I guess you would need a middleware or something to work with multiple languages. Potentially, there are also some tools that can "recompile" the code w.r.t your target language, see: https://ironpython.net But I am not experienced enough to say: This will work with SpeechBrain 100%.

**Comment by flozi00** [comment]
What about ONNX ? https://github.com/onnx/tutorials/blob/master/tutorials/ExportModelFromPyTorchForWinML.md

**Comment by doctorwho-123** [comment]
@flozi00  @TParcollet  Please put speech brain  separately for C # so that we do not use other languages ​​like ironpython , onnx or ....
