### ISSUE TITLE
Using MetricGAN+ for Speech Enhancement Inference

### ISSUE THREAD

**Issue by 8W9aG** [speechbrain/speechbrain#641]
I am wondering how to use MetricGAN+ to perform speech enhancement on some audio files I have. I looked at the HuggingFace speechbrain page but couldn't see a model that corresponded to MetricGAN+, and I have [this](https://colab.research.google.com/drive/18RyiuKupAhwWX7fh3LCatwQGU5eIS3TR?usp=sharing) tutorial on Colab regarding speech enhancement however it seems like that is more about creating a speech enhancement model from scratch and not just inference (but perhaps I am wrong there).

Could anyone assist me in understanding how to perform an inference task for speech enhancement?

**Comment by mravanelli** [comment]
Hi, this is not ready but we plan to make available on HuggingFace with the inference function as soon as we can. For now, you can take a look into the existing inference function for [SpectralMaskEnhancement](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py#L915). @pplantinga do you think we can reuse that for MetricGan+?

**Comment by pplantinga** [comment]
MetricGAN is on HuggingFace now at https://huggingface.co/speechbrain/metricgan-plus-voicebank
