### ISSUE TITLE
ECAPA_TDNN data pipeline bug

### ISSUE THREAD

**Issue by forwiat** [speechbrain/speechbrain#644]
hello @mravanelli , thank you so much for the great work you shared.
I found that 'start' and 'stop' were all in 'train.csv' after preparing voxceleb. But when training, the default 'random_chunk' in hparams didn't use 'start' and 'stop' but random start, which means that a random segment in one wav may be used in several times for training in one batch? 
as code in line 154~157 in 'train_speaker_embeddings.py'.
```
if hparams["random_chunk"]:
    duration_sample = int(duration * hparams["sample_rate"])
    start = random.randint(0, max(duration_sample - snt_len_sample - 1, 0))
    stop = start + snt_len_sample
```
best wishes

**Comment by mravanelli** [comment]
Hi, this is actually done on purpose. This way every time we sample something we have a chunk that is slightly different (we will never sample exactly the same chunk of signal and, on average, we can expect to cover all of it).
