### ISSUE TITLE
Custom Language Model and transcription 

### ISSUE THREAD

**Issue by gauravgund** [speechbrain/speechbrain#645]
Hi  @TParcollet ,

I have successfully fine-tuned SpeechBrain Librispeech recipe along with the transcription. Now, I want to train my custom language model and use it for Transcription. How can this be achieved in speechbrain, I could not find any codes on this?

Regards

**Comment by TParcollet** [comment]
Hey, isn't: https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/LM helping ?

Regards.

**Comment by gauravgund** [comment]
Fine tuning a KenLM model, I meant to be used for decoding.

Regrads

**Comment by TParcollet** [comment]
Oof, we do not provide an integration of KenLM yet ... Would love to see someone doing it though :p

**Comment by TParcollet** [comment]
But you can train your LM with SpeechBrain !

**Comment by gauravgund** [comment]
So, how to account for words in case of domain-specific cases?

Regards

**Comment by TParcollet** [comment]
Well, you can train your own LM within Speechbrain.

**Comment by gauravgund** [comment]
And how to use it for decoding using beam-search, I can’t find a code for
that?

**Comment by TParcollet** [comment]
The LibriSpeech recipe does it. BPE1000 is with a RNNLM and BPE5000 is with a TransformerLM

**Comment by TParcollet** [comment]
Be carefull to train your LM with the same tokenizer than the acoustic model.

**Comment by gauravgund** [comment]
Yes! So, will it just be like training LM model and pasting it in the
pretrained-directory and using the usual transcribe_file?

Regards

**Comment by Gastron** [comment]
We could also take a note to properly connect the N-gram LM interface with the S2SBeamSearch. Thus also supporting KenLM (not the most efficient approach, but probably fine). Todo.

**Comment by TParcollet** [comment]
As long as the beam_search in the YAML point towards the beamsearch with LM and your LM, yes it should do.

**Comment by gauravgund** [comment]
Also, regarding saving the brain.fit model, usual way of pickling it will
work to be used to save and load model for future use.

**Comment by TParcollet** [comment]
If your LM is on the checkpointer, then it will be saved (and can be used in the pretrainer).

**Comment by mravanelli** [comment]
Hi @gauravgund, I think the ASR tutorial that we recently wrote can be helpful:
https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing
It covers the LM part as well and how to combine it within the speech recognizer.

**Comment by 30stomercury** [comment]
@gauravgund we implement a N-gram LM interface for beamsearch in this PR #751, please refer to `speechbrain/decoders/scorer.py`. We will release a new version based on that PR.

**Comment by csetanmayjain** [comment]
Hi,
Any update on the kenlm integration with speechbrain?
Can we use kenlm in speechbrain while decoding?
