### ISSUE TITLE
Training dies with NaNs

### ISSUE THREAD

**Issue by mschonwe** [speechbrain/speechbrain#649]
Training runs for ~12,000 steps on LibriSpeech conformer recipe with internal dataset, then dies with NaN error

```
speechbrain.core - Loss is nan.
speechbrain.core - Parameter is not finite: Parameter containing:
tensor([[[[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]]],
...etc
```

I've restarted training with the `gradient_clipping: 5.0` to `gradient_clipping: 3.0` and still get the crash.

I'm assuming there is a bad utt, but wondering if there is any guidance on isolating/working around the cause?

**Comment by TParcollet** [comment]
Well, the only solution here is to print when the loss is not finite :/

**Comment by mschonwe** [comment]
Thanks.  Of course, it won't fail while being watched ;).

Added some debugging, and restricted batch size to 1 to isolate the bad utt, and it moved on with training w/o going off the NaN rails.  Will keep training, and will do more print/debugging if it blows up again.
