### ISSUE TITLE
Better documentation/tutorial for setting device (and run_opts in general)

### ISSUE THREAD

**Issue by rbracco** [speechbrain/speechbrain#652]
It took me a while to get the "pretraining.ipynb"/fine-tune tutorial working on a colab GPU. It would be great if the docs and tutorial would be updated to show how to set the device for single GPU. I am happy to update and PR if desired, please let me know.

Here's what worked for me
```
brain = EncDecFineTune(modules, hparams=hparams, opt_class=lambda x: torch.optim.SGD(x, 1e-5), run_opts={'device':"cuda:0"})
```
I just added `run_opts={'device':"cuda:0"}`. 

Note that you must include the device number, setting device="cuda" as suggested in #574 causes the following error:
```
--> 473             torch.cuda.set_device(int(self.device[-1]))
    474 
    475         # Put modules on the right device, accessible with dot notation

ValueError: invalid literal for int() with base 10: 'a'
```

**Comment by TParcollet** [comment]
Right, the thing is that in practice, you just have to set the device: variable in the YAML, but in Colab, we do not have access to a YAML file. What do you suggest to add in the documentation ?

**Comment by rbracco** [comment]
Thanks for the quick reply. The tutorials are great. They are very high quality with nice examples. In the hyperpyyaml tutorial I didn't see anything about cpu/gpu/device, and I'm also not finding the device variable used in the ASR recipes/templates, I did however find comments saying that "Objects in 'modules' dict will have their parameters moved to the correct device". 

My suggestion would be that if the device is meant to be controlled by the yaml config, to include a brief section in that tutorial on setting the device. If the finetuning tutorial uses a non-standard method for setting the device (either by using the CPU or by using `run_opts`), I'd make a note of that and say for more see the yaml tutorial. 

For finetuning it would be really awesome to see a more complex end-to-end example, like taking a pretrained model in English and fine-tuning it in another language (I've worked with NVidia's NeMo library a lot and this is a really common use case for them). This is something I'm happy to try to contribute as well if there's interest, although I would likely need some guidance. Cheers.

**Comment by TParcollet** [comment]
@pplantinga Do you think the hyperpyaml tutorial would be a nice place for documenting the device arg of the brain class ? Or maybe better on the brain class tutorial ?

@rbracco We would love to have a tutorial showing this. We have a tutorial on E2E ASR coming very soon. But I belive that what you describe could be a complex example on the currently existing pretaining tutorial ?

**Comment by rbracco** [comment]
@TParcollet, awesome, I'm looking forward to it. That could absolutely be a complex example that fits in the existing pretraining tutorial, basically replacing the current section which uses a toy example. It would be very useful to see transfer learning, also with some change in the architecture, like swapping out the decoder. It'd also be great to see a simpler model used as I was only able to get a BS of 2 on a single GPU with 10GB and many of the people doing transfer learning to lower resource languages are constrained by compute. I'd be happy to help with this. Thanks again for your work.

**Comment by TParcollet** [comment]
Hey @rbracco, in the current state of the project, helping mostly mean doing it :-P We can provide all the help you might need to try to achieve this though. I suppose that a good way to start would be: 1. Do a simple recipe where you apply transfer learning; 2. Propose a Colab Tutorial out of it. 3. In the long-term, see if you are able to reach some SOTA on a well-known dataset and then push an official recipe for it. 

" It'd also be great to see a simpler model used as I was only able to get a BS of 2 on a single GPU with 10GB" -> This is true. If you look at our PR, we currently have one of Dynamic Batching. This will allow for a precise setup of the batching strategy so it fits any GPU memory (of course, it might become slower due to smaller batches). 

Thanks for your interest.

**Comment by rbracco** [comment]
Thank you @TParcollet, I will see if I am able to implement some transfer learning in speechbrain and report back. I would like to use a much simpler model than the current default CRDNN + RNNLM + BPE, both so that it requires less compute, and so that it is easier to alter for less experienced ASR practitioners (like myself). 

I think among the current libraries (SpeechBrain, NeMo, Kaldi, ESPNet) there is still a missing slice for people who want to make models that sacrifice some accuracy to achieve reduced complexity, ease of training, and faster inference. NeMo fits that quite well and makes transfer learning very easy, but it is a bit of a headache to deviate from their standard recipe and alter models. My experience with SpeechBrain has been that the low/mid level API is great and it is easier to swap pieces in and out, but it's harder to do basic ASR transfer learning (take a simple pretrained encoder/decoder model that is part of the library, and replace the decoder with your new vocab, freeze the stem/body, fit, unfreeze and fit more). Please let me know if I've overlooked any models that are simpler but I've only seen really large models like the CRDNN and Wav2vec, but I haven't spent a ton of time in the library yet. 

Thanks again, closing the issue for now but I'll open a new tutorial issue/PR if I make progress or get stuck. Cheers.

**Comment by TParcollet** [comment]
Hey, doing transfer learning with SpeechBrain won't be hard at all (conceptually speaking), however, you are right when saying that we don't have "low-resources" models. I guess you could develop some quite nicely. For instance, you could remove the CNN front-end before RNN models. You could also remove the CTC+Att decoding and start with CTC only (making both the VRAM and decoding time lower, this will be at the cost of performance). I would love to see one of the NeMo model implemented in SpeechBrain also (Quartznet or jasper).

**Comment by mattiasu96** [comment]
Maybe out of context question, but does Speechbrain support the M1 GPU? (mps backend) Using something like` run_opts={'device':"mps"}`

**Comment by pplantinga** [comment]
This should work straight out of the box, the device is forwarded to PyTorch. However, I'm not sure if its been tested and if you are able to do so, this would be nice to verify.

**Comment by mattiasu96** [comment]
> However, I'm not sure if its been tested and if you are able to do so, this would be nice to verify.
Yes I've been testing it now but it doesn't look like working 🤔 I posted a question here: https://github.com/speechbrain/speechbrain/discussions/1791

Is there anything else I can do to help?

**Comment by mattiasu96** [comment]
It is most likely a pytorch bug that has been reported here: https://github.com/pytorch/pytorch/issues/82296
