### ISSUE TITLE
how to use my trained model 

### ISSUE THREAD

**Issue by dugudongfangshuo** [speechbrain/speechbrain#653]

**Comment by dugudongfangshuo** [comment]
use
model_dict=torch.load(PATH)
can load model  but  data which will input model need deal to fit model format，that  is not very convenient ,beacause this need redo dataio_prep. there is any method can input data directly?

**Comment by TParcollet** [comment]
Hi, so it actually depends. What do you want to do exactly? If it simply is loading the model to do something else, then torch.load() on anything saved with the checkpointer will work. If it's something more complex (fine-tuning, inference within SpeechBrain or whatever) then we should discuss it a bit here :)

**Comment by dugudongfangshuo** [comment]
ok thank you
