### ISSUE TITLE
ECAPA-TDNN pretrained model 

### ISSUE THREAD

**Issue by chw18019** [speechbrain/speechbrain#656]
I have problem using the preprinted model for speaker verification after the latest update. It worked on Colab last couple weeks, but now it shows “cannot import nam EncoderClassifier from ‘speechbrain.pretrained’ (/user/local/lib/python3.7/dist-packages/speechbrain/pretrained/__init__.py).” Thinking maybe the pretrained class should also import the EncoderClassifier library. Please let me know if it’s my own issue.... or any possible solutions. Thanks!

**Comment by TParcollet** [comment]
@mravanelli Isn't connected to your PR ?

**Comment by mravanelli** [comment]
That's a very recent update. Could you please install speechbrain again? It
should work.

**Comment by chw18019** [comment]
It works now. Thanks for checking. 👍🏻
