### ISSUE TITLE
VAD for e2e diarization

### ISSUE THREAD

**Issue by Felflare** [speechbrain/speechbrain#657]
Thank you for maintaining and working on this library.

Hi, I am looking for documentation or perhaps pointers/suggestions for performing end-to-end diarization.

The current AMI diarization recipe utilizes labeled data to perform utterance splits. (as I understand it)
How would one approach an unlabeled AMI dataset to perform diarization?

**Comment by mravanelli** [comment]
Good question!
I have some of my students working on VAD. After having a reliable VAD we
can provide a recipe for AMI without using the provided segmentation.
As for E2E diarization, this is an extremely interesting research topic.
Over the last months, we tried some approaches, but the performance wasn't
good at all. This is an exellent topic for a collaboration with any
contributors interested in that!

Best,

Mirco

**Comment by Felflare** [comment]
Thank you for your input @mravanelli,

Can you point me to an approach that you think is worthwhile to try to further e2e diarization?
I am thinking a simple approach is segmenting on silences, but there maybe be a better approach to this which I'm unaware of which would address overlapping speech and sudden speaker change.

**Comment by mravanelli** [comment]
There was a growing interest in the literature on this topic in the last year but I'm not aware of a solution really working much better than standard non end2end with a reasonable amount of data (but I might be wrong here). If someone from the community would like to suggest something, this is really and interesting topic for a collaboration. The E2E neural speaker diarization is something that looks pretty reasonable to me: https://arxiv.org/pdf/1909.06247.pdf
