### ISSUE TITLE
Word-level timestamps

### ISSUE THREAD

**Issue by pKrysenko** [speechbrain/speechbrain#658]
Good day!
Many thanks for your project!
I have started to look into tutorials, code, but can't find possibility of returning timestamps per words. It's essential feature for me and just interesting about your plans on this feature?

**Comment by mravanelli** [comment]
With E2E attention-based systems the alignment between the input sequence and the output is learned through an soft (not hard) attention mechanism. This makes it hard finding the final alignment. With our CTC system, instead, this might be possible to retrieve (even though we never done that so far). You have to take a look into the best predictions at each time step (before removing the blank token) and process the output tokens by replacing 'blank' with the next valid token. I think we do something similar in our [[MM-DNN alignment recipe](https://github.com/speechbrain/speechbrain/tree/develop/recipes/TIMIT/Alignment). Not sure it that works well though. Any insight @lorenlugosch?

**Comment by lorenlugosch** [comment]
See: https://speechbrain.discourse.group/t/getting-time-alignment/181/3?u=lugosch

**Comment by pKrysenko** [comment]
Many thanks for answer!
