### ISSUE TITLE
Multiple GPU Separator does not work!

### ISSUE THREAD

**Issue by 91205074** [speechbrain/speechbrain#659]
Hi,

I have used multiple gpu for Librispeech ASR and it worked properly, and I did the same things to use multiple gpu for Dual-path RNN separator but it seems it uses only one GPU, it is needed to mentioned I increased the batch size, so my batch size is not one. I am wondering what is the issue that the model uses only one gpu?

**Comment by aheba** [comment]
@91205074 , @ycemsubakan , I can help on that part, could you share with me which the repos we are talking about ?

**Comment by ycemsubakan** [comment]
Hi @aheba , we are talking about the WSJ0Mix recipe. Thanks for your help!

**Comment by aheba** [comment]
okay, Let me take a deeper look

**Comment by ycemsubakan** [comment]
Hi @91205074 , @aheba  and I had a chance to look into this. On the `develop` branch, I am able to run dual-path separator.. can you try the following command:

```
 python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/dprnn.yaml --data_folder /putin_yourdatapath --distributed_launch --distributed_backend='nccl'
```

**Comment by 91205074** [comment]
Hi, I used the command, and now it worked.
thank you so much for your help.

**Comment by ycemsubakan** [comment]
You are welcome @91205074 . I am closing the issue.
