### ISSUE TITLE
Wrong Test dataset on VoxCeleb1 (?) 

### ISSUE THREAD

**Issue by Fhrozen** [speechbrain/speechbrain#664]
Just to confirm:

https://github.com/speechbrain/speechbrain/blob/44ce741de00d56082749600b287df9378d75e27c/recipes/VoxCeleb/SpeakerRec/speaker_verification_plda.py#L175-L178

on L175, `test_data` is loaded from the corresponding CSV, but on L178, it is overwritten with the filtered `enrol_data.`
Should it not be: `test_data = test_data .filtered_sorted(sort_key="duration")` ??

The EER does not change, but I am wondering about the notation.

**Comment by mravanelli** [comment]
Right, this had no impact of the performance but it is something definitely to fix. I actually already fixed in the development branch. Thanks noticing it!
