### ISSUE TITLE
Test for windows and download files

### ISSUE THREAD

**Issue by Simploid** [speechbrain/speechbrain#680]
Hi,
I'm testing just few lines to test the example on windows and i'm facing a simple problem:
Just by doing :
`asr_model = EncoderDecoderASR.from_hparams(source="D:/Mes Fichiers/Info/python/Voxtel/asr-crdnn-rnnlm-librispeech", savedir="pretrained_models/asr-crdnn-rnnlm-librispeech")`
it goes for the error : 
`UnpicklingError:`` invalid load key, 'v'.`
That's a problem with torch.load and precisely with pickle for loading asr.ckpt
I checked and the only reason should be that the file is corrupted. 
I have download all the files with git (Ming64) then how can i change that?

Thanks for responding and your help :)

**Comment by mravanelli** [comment]
Hi @Simploid, I never tried this on a windows machine (on linux it works fine). Is there someone from the community that can take a look into that?

**Comment by Simploid** [comment]
@mravanelli, i tried on a linux machine and it works fine on the librispeech model but not on the commum voice model.
i got the same error `UnpicklingError:`` invalid load key, 'v'.`
Can you help me again please?

**Comment by mravanelli** [comment]
I'm not able to replicate the issue. Anyone is observing the same issue?

**Comment by TParcollet** [comment]
@Simploid did you find an answer? We do not have any core developer on Windows unfortunately :(

**Comment by Simploid** [comment]
@TParcollet no, i change my windows to linux. There is too much problem on that os.
