### ISSUE TITLE
VoxCeleb Empty dev.csv and train.csv

### ISSUE THREAD

**Issue by RuslanSel** [speechbrain/speechbrain#684]
Hi!
I tried to run speaker_verification_cosine.py and got an error.
Traceback (most recent call last):
  File "speaker_verification_cosine.py", line 255, in <module>
    train_dataloader, enrol_dataloader, test_dataloader = dataio_prep(params)
  File "speaker_verification_cosine.py", line 161, in dataio_prep
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/ubuntu/speechbrain/speechbrain/dataio/dataset.py", line 365, in from_csv
    return cls(data, dynamic_items, output_keys)
  File "/home/ubuntu/speechbrain/speechbrain/dataio/dataset.py", line 151, in __init__
    static_keys = list(self.data[self.data_ids[0]].keys())
IndexError: list index out of range
There are empty dev.csv and train.csv in save directory.
By the way in voxceleb_prepare.py DEV_WAV initialized but not used.

Thanks in advance.

**Comment by mravanelli** [comment]
Hi @RuslanSel,
this can happen if the data folder is not set correctly or some data are missing.
The csv files are prepared by this function; https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/voxceleb_prepare.py#L37
You can take a look here to figure out what is happening. You can also follow the instructions that we reported here:
https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/README.md.
Are you using voxceleb1, voxceleb2, or both?

**Comment by RuslanSel** [comment]
Thanks for quick reply!
I'm using voxceleb1.
voxceleb_source: voxceleb1 with meta and wav folders.

**Comment by mravanelli** [comment]
Do you have both dev and test data unzip?
I think the easiest way to debug is to go here:
https://github.com/speechbrain/speechbrain/blob/48536546bd47549d98149d9e30853ec3806fc9fe/recipes/VoxCeleb/voxceleb_prepare.py#L270
and prints some variables such as (path, data_folder, audio_files_dict
(after the for loop)). Based on that you can see if these variables match
with the existing paths or not.

**Comment by JiusiZheng** [comment]
I also faced this problem. I found the reason is that I just used test fold(contain metadata and wav) so the training list is blank.
