### ISSUE TITLE
Roadmap priorities

### ISSUE THREAD

**Issue by francisr** [speechbrain/speechbrain#702]
Hi,  

The roadmap is interesting, however looks more like a wish list rather than a roadmap.  
Are you planning to add priorities for each item so that the community can have a sense of what would be the most important things to contribute to?

**Comment by TParcollet** [comment]
Hi @francisr maybe we should make it clearer, but the idea is the following: All added items are top priorities except for the "others" section.

**Comment by mravanelli** [comment]
Right. Said that, we need help from the community to implement all these
things soon. Any help is welcome!
