### ISSUE TITLE
Language Identification using Audio data

### ISSUE THREAD

**Issue by parthplc** [speechbrain/speechbrain#705]
Hey Guys,
I am working on the problem of identifying Language based on the audio clip. I tried the technique of creating a Mel spectrogram and training a CNN classifier but the results were pretty bad. Any pretrained models that can convert audio to embeddings that can be used for classification? 
Also if you can suggest some other way to do this
Thankyou in advance

**Comment by mravanelli** [comment]
We have very good results with the xvector and ECAPA networks (see our
tutorial on speech classification). My student will push the language-id
recipe in the next weeks.

**Comment by parthplc** [comment]
> We have very good results with the xvector and ECAPA networks (see our tutorial on speech classification). My student will push the language-id recipe in the next weeks.
Thankyou @mravanelli. So does this classification work for all languages or have any limitation?

**Comment by parthplc** [comment]
> We have very good results with the xvector and ECAPA networks (see our tutorial on speech classification). My student will push the language-id recipe in the next weeks.
Thankyou @mravanelli. So does this classification work for all languages or have any limitation?

**Comment by androidshu** [comment]
I also encountered the same problem, did you solve it?
