### ISSUE TITLE
 [LibriSpeech recipe]: Typo in Conformer config file

### ISSUE THREAD

**Issue by JuanPZuluaga** [speechbrain/speechbrain#707]
Hi Guys, 

Thanks for the great work in Speechbrain. I think there is a 'typo' in the hparam file in the LibriSpeech recipe for Transformer model in the Conformer config file. 

Specifically in: 
`line 158: optimizer: !name:torch.optim.Adam
`
The train.py in `https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/transformer/train.py` is looking for `hparams["Adam"]` instead of `hparams["optimizer"]`

regards,
Juan

**Comment by TParcollet** [comment]
Hi Juan, 

Thanks. The conformer recipe (and model) is about to get revised. See: https://github.com/speechbrain/speechbrain/pull/535
