### ISSUE TITLE
TransformerASR, same dataset, different file order, different result

### ISSUE THREAD

**Issue by sunwell1994** [speechbrain/speechbrain#724]
I use glob.glob() to get the audio file list, then I evaluate speech one by one. However, I find the WER of default order and sorted order by wav length are different. I thought different speeches are independent of each other.  They should get small WER. But the result is different a lot(5.80 vs 5.93). Is there any state that remained due to the previous sentence in TransformerASR? Thanks.

**Comment by TParcollet** [comment]
So, this is due to batched decoding. If you want to remove this variability, you should decode with a batch of one (unless you already do that, then there is something weird)

**Comment by sunwell1994** [comment]
> So, this is due to batched decoding. If you want to remove this variability, you should decode with a batch of one (unless you already do that, then there is something weird)

I transcribe speeches one by one. Is there any dependency or cache between continuous transcription?

**Comment by TParcollet** [comment]
Interesting ... Could you share your code ?

**Comment by TParcollet** [comment]
@sunwell1994 any update to share?

**Comment by sunwell1994** [comment]
> @sunwell1994 any update to share?

Hi, I did not invest in the problem. I just fix the order of evaluation. I am sorry that the whole code is distributed in a private project thus I cannot share it currently. Thanks!
