### ISSUE TITLE
Generate CSV files for TIMIT 

### ISSUE THREAD

**Issue by jlian2** [speechbrain/speechbrain#730]
In recipes/TIMIT/Alignment/train.pi
![image](https://user-images.githubusercontent.com/61141271/117068176-c7850480-acdf-11eb-83f5-1bb718e8b7fb.png)
How are csv files generated actually? It turns out they are not generated and error then appears:
![image](https://user-images.githubusercontent.com/61141271/117068269-ebe0e100-acdf-11eb-89aa-264cb32c0606.png)

**Comment by mravanelli** [comment]
Thank you for pointing it out. This is solved in the current development branch.
