### ISSUE TITLE
Pytorch Version Issue(Torchaudio)

### ISSUE THREAD

**Issue by jlian2** [speechbrain/speechbrain#732]
My previous pytorch version is just 1.8.1 (the same as speechbrain's default version). Since my NVIDIA driver is old, then I just switched to pytorch 1.5.1. Then this error appears:
![image](https://user-images.githubusercontent.com/61141271/117081430-b85c8180-acf4-11eb-92df-f0ce89121339.png)

So I was wondering is ">=1.8" required for pytorch?

**Comment by TParcollet** [comment]
oof. 1.5.1 is pretty old and torchaudio is pretty new. I am afraid that you can't get below 1.7.

**Comment by TParcollet** [comment]
Did you try with a higher pytorch version ? Maybe 1.7 ?
