### ISSUE TITLE
ImportError when load 'asr-transformer-transformerlm-librispeech' pre-trained model

### ISSUE THREAD

**Issue by GatoY** [speechbrain/speechbrain#733]
### Code snippet
```from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-transformer-transformerlm-librispeech", savedir="pretrained_models/asr-transformer-transformerlm-librispeech")
```

### Error Message:
```ImportError: There is no such class as speechbrain.lobes.models.transformer.TransformerASR.EncoderWrapper```

**Comment by mravanelli** [comment]
Could you please update speechbrain to the latest version?

**Comment by GatoY** [comment]
Thank

> Could you please update speechbrain to the latest version?
> […](#)

Thanks for the quick response. It fixed my issue. 
Just want to point it out that currently I can't use `pip install --upgrade ` to get the newest version. I'm sure that'll come through!
Cheers!
