### ISSUE TITLE
How do I add a special symbol for unknown labels?

### ISSUE THREAD

**Issue by teinhonglo** [speechbrain/speechbrain#736]
How do I add a special symbol for unknown labels?
I prepare my dataset based on timit recipe, but I encountered this error.
KeyError: 'Cannot encode unknown label [b]. You have not called add_unk() to add a special unk-label for unknown labels.'

Thanks.

**Comment by TParcollet** [comment]
Hi ! If you are not using SentencePiece (BPE, unigram), then you can use the function add_unk().

For instance, you can see that the label_encoder in the limit recipe is an instance of `class CTCTextEncoder(TextEncoder):`

And in the class `TextEncoder`, you can see that there is an `add_unk` function that will automatically add the unknown label ! So simply call this function on the label_encoder :-)
