### ISSUE TITLE
Set of Questions  about MetricGAN+ recipe

### ISSUE THREAD

**Issue by kadir-gunel** [speechbrain/speechbrain#737]
Hello,

Trying to learn the framework, in order to do that I am trying to train an enhancement model with MetricGan+. There are series of problems, that I am facing right now about it. 
1. For training, inside the YAML file, it is written that there are only 2 metrics are supported : PESQ and STOI. When I choose STOI the model starts training just fine. But when I set PESQ as metric I get the exception below saying that : 
```python 
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 579, in <module>
    se_brain.fit(
  File "/home/kg/pyvenv/speechBrain/lib/python3.9/site-packages/speechbrain/core.py", line 989, in fit
    self.on_stage_start(Stage.TRAIN, epoch)
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 337, in on_stage_start
    raise NotImplementedError(
NotImplementedError: Right now we only support 'pesq' and 'stoi'
```
The error rises from line 337 from train.py which points to : 

```python 
 if stage == sb.Stage.TRAIN:
            if self.hparams.target_metric == "pesq":
                self.target_metric = MetricStats(metric=pesq_eval, n_jobs=5)
            elif self.hparams.target_metric == "stoi":
                self.target_metric = MetricStats(metric=stoi_loss)
            else:
                raise NotImplementedError(
                    "Right now we only support 'pesq' and 'stoi'"
                )
```
For me it is strange because when I debug the ``` train.py ``` I can get inside the first ``` if ``` statement. The only difference between STOI and PESQ is that STOI is described as a loss function where PESQ is just a evaluation function.  So does this mean PESQ is not described as a differentiable function ? Hence the exception is thrown ?

2. Aside from setting target_metric as PESQ, when I set it to STOI , with default parameters of the train.yaml, after 380 epochs in training, I start to get Nan values which later causes training to stop; (probably gradients approached to 0 ?) .  My question is are those parameters inside the train.yaml are randomly given ? Or are they the exact parameters of the original paper ? 

Best Regards

p.s. I am training with VoiceBank dataset. All samples are downsampled from 48kHz to 16kHz.

**Comment by pplantinga** [comment]
The recipe works for me as-is with `pesq` as the metric. The parameters are set up to work with `pesq` so I'm not sure if they work well with `stoi` as the metric. I did have some problems getting `NaN` with `pesq` but they were resolved by reducing the learning rate, perhaps this can help with `stoi` too.

**Comment by kadir-gunel** [comment]
@pplantinga  Thank you for the information. I managed to solve the  ```pesq``` issue, now it works as expected. 

I have 3 more question :)  

1. When I try to change the ```train_N_batch: 1``` to another value (like 8) I get an error saying that : 
```python
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: /run/media/kg/disk3/KG/arge-data/cleaned/MetricGAN+/1600123
speechbrain.core - 1.9M trainable parameters in MetricGanBrain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
Discriminator training by current data...
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 576, in <module>
    se_brain.fit(
  File "/home/kg/pyvenv/speechBrain/lib/python3.9/site-packages/speechbrain/core.py", line 989, in fit
    self.on_stage_start(Stage.TRAIN, epoch)
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 344, in on_stage_start
    self.train_discriminator()
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 357, in train_discriminator
    self.fit(
  File "/home/kg/pyvenv/speechBrain/lib/python3.9/site-packages/speechbrain/core.py", line 1013, in fit
    loss = self.fit_batch(batch)
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 286, in fit_batch
    loss = self.compute_objectives(
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 106, in compute_objectives
    self.write_wavs(batch.id, ids, predict_wav, target_score, lens)
  File "/run/media/kg/workenv/github/speechbrain/recipes/Voicebank/enhance/MetricGAN/train.py", line 267, in write_wavs
    score = float(score[i][0])
TypeError: 'float' object is not subscriptable
```
A possible error about slicing ?
2. What is the meaning of ```number_of_samples: 100``` ? What is its usage ? I cannot increase the batch size but I can increase this value(from 100 to 1000), still the allocated memory in GPU stays the same; no big changes. 
3. Since I want to test my own testing files on the trained model. Is it possible to bypass the annotation files of testing ? Because I have no annotations. I just want the cleaned .wav files.  


B.R.

**Comment by pplantinga** [comment]
1. I guess there's potentially some code that depends on a batch size of 1. Feel free to track it down and add a PR for that :) 
2. The `number_of_samples` refers to number of utterances used for training each epoch. These are randomly sampled.
3. The most straightforward way to use your own files for testing is to use the `Pretrained` interface via Huggingface. Check out https://huggingface.co/speechbrain/metricgan-plus-voicebank

**Comment by kadir-gunel** [comment]
Thank you.
