### ISSUE TITLE
Was each batchsize samples added the same reverbration noise?

### ISSUE THREAD

**Issue by Alva-2020** [speechbrain/speechbrain#752]
Thanks for your sharing. When I read the code in [speechbrain/processing/signal_processing.py], I found the inputs  of [def reverberate(waveforms, rir_waveform, rescale_amp="avg")]  are waveforms with size [B,T,C] and rir_waveform [1,T,C], and I read the code behind, I wonder if each batchsize samples with the same reverbration noise? It isn't each sample added different reverbration noise???

**Comment by mravanelli** [comment]
As far as I remember we decided to opt for that for making everything much faster. Is that true @pplantinga?

**Comment by Alva-2020** [comment]
OK, I see. Thank you very much.
