### ISSUE TITLE
Only able to separate 1 minute long audio

### ISSUE THREAD

**Issue by therc01** [speechbrain/speechbrain#758]
Hi, when im trying to separate a two minute long audio using your library, i am only getting one minute long audio clip as output. 
`
model = separator.from_hparams(source="speechbrain/sepformer-wsj03mix", savedir='/content/')
`
Can i get more length of audio as output or not?

**Comment by TParcollet** [comment]
@ycemsubakan

**Comment by ycemsubakan** [comment]
Are you getting out of memory error? Also, are you trying to run on the gpu?

**Comment by xxoospring** [comment]
> Are you getting out of memory error? Also, are you trying to run on the gpu?

my memory explode when I inferene on a 209s audio clip on cpu

**Comment by mravanelli** [comment]
I think the code is designed for short clips (e.g, 10-20 seconds).

**Comment by ycemsubakan** [comment]
Sorry I have been neglecting this. This might be because of the limit on the length of the positional encodings in the self attention layers. I will need to look into this. I will do this very soon.

**Comment by PoLabs** [comment]
I am also confused on this. Trying to decode a 1min audio file only renders half the text. Surely the model is meant for more than 20 seconds otherwise what is the point...

**Comment by ycemsubakan** [comment]
@PoLabs  What do you mean by half the text? Do you mean half the recording?

**Comment by PoLabs** [comment]
That's correct. Only half the recording was transcribed. Total length is about 1min, longer recordings don't seem to work well. Other models like wave2vec2 are transcribing the full audio file but with worse performance.

**Comment by ycemsubakan** [comment]
@PoLabs Right, but this issue is about the source-separation models.

**Comment by ycemsubakan** [comment]
Hi @therc01 , I have just tried `sepformer-wsj02mix` and `sepformer-wsj03mix` and it is able to separate two minute long files, without clipping. Are you trying this using the latest `develop` branch?

**Comment by spullara** [comment]
Do I need to reinitialize the model or something between transcribing files? Though I am splitting them into chunks it gets worse as it transcribes later chunks using the same model.

**Comment by ycemsubakan** [comment]
No, it should work normally.. it's been a whole since I looked into this but if I remember correctly I was able to separate a two minute long file on the cpu.
