### ISSUE TITLE
Converting embedding back to audio

### ISSUE THREAD

**Issue by therc01** [speechbrain/speechbrain#759]
Hi, i'm trying to use speaker diarization. I got embedding matrix but how do i convert it back to words according to speakers.

`verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="./pretrained_ecapa")
signal, fs = torchaudio.load('/content/shorter_audio.wav')
embedding = verification.encode_batch(signal)`

Here's the code. 
shape of embedding is `torch.Size([2, 1, 192])`

**Comment by nauman-daw** [comment]
Hi @therc01 ,
Thanks for trying out SpeechBrain. Do you mean to convert embeddings to audio or words (text)? 
If it's the later case then you can easily use the diarized output (see generated RTTM files) and process the audio chunks using any ASR recipes. And then maybe you can concatenate ASR outputs to have transcription (with speaker annotations) for the whole recording. Currently, AFAIK we do not have support for converting speaker embeddings directly to audio.

**Comment by nauman-daw** [comment]
Kindly let me know if this query is answered. I can then close this issue.

**Comment by therc01** [comment]
can you share a demo code how to get transcriptions with speaker annotations. Thanks

**Comment by nauman-daw** [comment]
Currently, we do not have the full code for ASR+Dairization. 

I can mention how this can be done with the current version of SpeechBrain. Please note that the following approach is not the best way to deal with this problem. There may be difficulties with overlapping speakers, incorrect speaker boundaries, etc.

**Diarization of long recording:**
Once you diarize the recording using [Diarizarion recipe](https://github.com/speechbrain/speechbrain/tree/develop/recipes/AMI/Diarization), you should get RTTM files like this one: [RTTM examples](https://github.com/speechbrain/speechbrain/blob/develop/samples/rttm_samples/ref_rttm/ES2014c.rttm)

**ASR on diarized chunks:**
After getting the RTTM file, write the data_preparation.py script for ASR task using this RTTM. You may also have to split longer speaker chunks into smaller ones while preparing data. Please see the ASR recipes [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/TIMIT/ASR).

**Comment by nauman-daw** [comment]
I assume this is solved. I will close this issue for now.
