### ISSUE TITLE
How to compute EER from scores.txt

### ISSUE THREAD

**Issue by RuslanSel** [speechbrain/speechbrain#762]
I've run speaker_verification_cosine.py and got Command terminated by signal 9 after writing scores.txt.
How can I compute EER from scores.txt?

Thanks in advance.

**Comment by mravanelli** [comment]
I think the best thing is trying to run the script again. If you are using
a HPC cluster, make sure to request enough RAM in the computation node.

**Comment by RuslanSel** [comment]
Thanks for quick reply.

How much is "enough RAM" for VoxCeleb speaker verification scripts?
