### ISSUE TITLE
Add batch file processing for pretrained Interface? 

### ISSUE THREAD

**Issue by sharockys** [speechbrain/speechbrain#768]
Hello,

I was trying to use pretrained ASR models. and I would like to know if it is interested if I make a PR of the code for batch processing files in the pretrained interfaces?

Sincerely,
S

**Comment by TParcollet** [comment]
Hey @sharockys what do you mean by batch processing? Allowing for batch inference is the pretrained inferface? I think this could be interesting, but one core concept would be to not enforce it. Basically, the code should work as it is AND allow for batch decoding. (No refactoring on the existing models). @Gastron what do you think?

**Comment by sharockys** [comment]
> Hey @sharockys what do you mean by batch processing? Allowing for batch inference is the pretrained inferface? I think this could be interesting, but one core concept would be to not enforce it. Basically, the code should work as it is AND allow for batch decoding. (No refactoring on the existing models). @Gastron what do you think?

Hello. Thank you for the prompt response. 
What I mean is just to allow process multiple audio files with precomputed length, as the below code snippet does.
```python 
    def transcribe_batch_files(self, paths, audio_lens):
        """Transcribes the given audiofiles into a list of sequence of words.

        Arguments
        ----------
        paths : list
            List of paths to audio files which to transcribe.

        audio_lens: list
            List of length of audios.

        Returns
        -------
        list
            The list of transcriptions for audiofiles produced by this ASR system.
        """
        waveforms = [self.load_audio(path).unsqueeze(0) for path in paths]
        batch = batch_pad_right(waveforms)
        max_len = max(audio_lens)
        rel_length = torch.tensor([l / max_len for l in audio_lens])
        predicted_words, predicted_tokens = self.transcribe_batch(
            batch, rel_length
        )
        return predicted_words[0]
```
Maybe compute the lengths of audios on-the-fly is interested, too. 

What do you think?

**Comment by Gastron** [comment]
I think we should have a clear usecase in mind. Are you already using this for something, @sharockys ?

**Comment by sharockys** [comment]
> I think we should have a clear usecase in mind. Are you already using this for something, @sharockys ?

For example, if we want to transcribe a long audio, we could use VAD to cut the audio into smaller pieces, and then feed the pieces into the transcriber. I did this personally.

**Comment by Gastron** [comment]
Sounds to me that in that case, ideally, the cuts could remain in memory, no saving to disk needed. I feel that it is a good point that this can be done, particularly with getting the lengths on the fly. However I feel that this could be best left to be implemented on a case-by-case basis for now, depending on the users' particular needs.

**Comment by sharockys** [comment]
> Sounds to me that in that case, ideally, the cuts could remain in memory, no saving to disk needed. I feel that it is a good point that this can be done, particularly with getting the lengths on the fly. However I feel that this could be best left to be implemented on a case-by-case basis for now, depending on the users' particular needs.

I am agreed with the on-the-fly part. 
For the use case, I am less sure. 
It seems contradictory to me that we have api for batch wavs processing https://github.com/speechbrain/speechbrain/blob/97e027ce5234e49e3f4969b218f0e12ee104f2cc/speechbrain/pretrained/interfaces.py#L434 and the transcription of file is only for a single file, and we made it up to fake that they are wavs batch. 
At the same time, the case-by-case implementation is reasonable. I will make a gist code snippet instead of PR. 

Thank you very much.

**Comment by Gastron** [comment]
Thank you, a gist would be perfect in my opinion!
