### ISSUE TITLE
Operate directly on embeddings rather than signals or wav files?

### ISSUE THREAD

**Issue by merkoski** [speechbrain/speechbrain#772]
First of all, I really like the speechbrain system and I am thrilled you released it!

In my use case, I would like to be able to run speechbrain.pretrained.interfaces.SpeakerRecognition directly on an embeddings returned by speechbrain.pretrained.interfaces.EncoderClassifier. However, SpeakerRecognition only has interfaces for a signal or a wav file. Would it be possible to add support for passing in embeddings directly?

I ask because I would like to use SpeakerRecognition to compare a voice signal (call this the "source") thousands of times to other voice signals via SpeakerRecognition.verify_batch, but each time I run SpeakerRecognition.verify_batch it is performing the expensive operation to take the signal from "the source" to an embedding behind the scenes, which uses a lot of CPU time and takes a lot of time to process data. This repetitive operations happens over and over, and I would like to bypass this.

Ideally I would like to be able to precompute the embeddings and run SpeakerRecognition.verify_batch on embeddings; that way I can cache the embeddings for "the source" in my case to drastically speed up computations.

Would this be possible?

**Comment by TParcollet** [comment]
Hi and thanks for using SB! We won't be able to provide you with a solution directly but you can implement it! 
Basically, you can simply create a function in the speechbrain.pretrained.interfaces.SpeakerRecognition class that calls encode_batch and saves it to a file :) Then you can have another function that opens the corresponding file and uses it.

**Comment by merkoski** [comment]
Fantastic thank you @TParcollet ... with your pointers I used encode_batch directly and reimplemented the cosine similarity function ... it works 100,000 times faster! Much appreciated!
