### ISSUE TITLE
how to use gpu to predict speaker similar

### ISSUE THREAD

**Issue by guowhite** [speechbrain/speechbrain#777]
i was use
 "
from speechbrain.pretrained import SpeakerRecognition
verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", 
score, prediction = verification.verify_batch(signal1, signal2)
"
to predcit similar. but it is could not use gpu that so slow. how can i use gpu to predict it

**Comment by TParcollet** [comment]
simply give run_opts={"device":"cuda"} as an argument. See https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py

**Comment by naba89** [comment]
Hi,

Running the following with run_opts to use gpu: 
```python
verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb",
                                               savedir="pretrained_models/spkrec-ecapa-voxceleb",
                                               run_opts={"device":"cuda:0"})
score, prediction = verification.verify_files(ef, tf)
```

But getting error:
```
Traceback (most recent call last):
  File "evaluate_cosine_similarity.py", line 26, in <module>
    score, prediction = verification.verify_files(ef, tf)
  File "/masked_path/speechbrain/pretrained/interfaces.py", line 696, in verify_files
    score, decision = self.verify_batch(batch_x, batch_y)
  File "/masked_path/speechbrain/pretrained/interfaces.py", line 670, in verify_batch
    emb1 = self.encode_batch(wavs1, wav1_lens, normalize=True)
  File "/masked_path/speechbrain/pretrained/interfaces.py", line 560, in encode_batch
    embeddings = self.hparams.mean_var_norm_emb(
  File "/masked_path/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/masked_path/speechbrain/processing/features.py", line 1085, in forward
    self.glob_mean = (
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
Is there anything I am missing?

**Comment by naba89** [comment]
Here you go (works fine on cpu albeit slow):

```python
import glob
import time
from pathlib import Path
import pandas as pd

from speechbrain.pretrained import SpeakerRecognition

enrolment_dir = 'dataset/test_data/final_test/'
test_dir = 'outputs/final_test/'

enrolment_files = glob.glob(enrolment_dir + '**/*.wav', recursive=True)
test_files = glob.glob(test_dir + '**/*.wav', recursive=True)

verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb",
                                               savedir="pretrained_models/spkrec-ecapa-voxceleb",
                                               run_opts={"device":"cuda:0"})

cosine_scores = {}
for i, ef in enumerate(enrolment_files):
    fname = Path(ef).stem
    tf_for_ef = [x for x in test_files if fname in x]
    print(ef)
    for j, tf in enumerate(tf_for_ef):
        # print('\t', tf)
        st = time.time()
        score, prediction = verification.verify_files(ef, tf)
        Path(Path(tf).name).unlink(missing_ok=True)
        cosine_scores[tf] = score.item()
        print('\t', i, j, tf, '\t', '{:.2f}'.format(time.time()-st), '\t', '{:.5f}'.format(cosine_scores[tf]))
    Path(Path(ef).name).unlink(missing_ok=True)


df = pd.DataFrame(list(cosine_scores.items()), columns=['fnames', 'cosine_scores'])
df.to_csv('cosine_scores.csv', index=False)
```

Also, I had to explicitly unlink the symlinks, as it doesn't remove by default and clutters up my workspace with thousands of symlinks.

**Comment by TParcollet** [comment]
HUm @Gastron any idea why this would not set all tensors to GPU? I don't see any errors

**Comment by naba89** [comment]
Any updates on this?

**Comment by BarathiGanesh-HB** [comment]
I have faced a similar issue. After certain debugging, the following changes worked for me. The problem is with the "speechbrain/processing/features.py" file at line numbers 1085 and 1089. The self.glob_mean and self.glob_std are not mapped to the cuda device (i.e x.device at line 1008). After including the following, it works perfectly.

`self.glob_mean = self.glob_mean.to(x.device)`  # at line 1084 and
`self.glob_std = self.glob_std.to(x.device`) # at line 1088

Attached screenshots FYR.
**Before**
<img width="710" alt="before" src="https://user-images.githubusercontent.com/17673823/120534626-afe48d00-c3ff-11eb-9046-81fb7b0d4806.png">
**After**
<img width="710" alt="after" src="https://user-images.githubusercontent.com/17673823/120534611-ab1fd900-c3ff-11eb-8a9b-079969b0d3ea.png">

**Comment by BarathiGanesh-HB** [comment]
> I have faced a similar issue. After certain debugging, the following changes worked for me. The problem is with the "speechbrain/processing/features.py" file at line numbers 1085 and 1089. The self.glob_mean and self.glob_std are not mapped to the cuda device (i.e x.device at line 1008). After including the following, it works perfectly.
> 
> `self.glob_mean = self.glob_mean.to(x.device)` # at line 1084 and
> `self.glob_std = self.glob_std.to(x.device`) # at line 1088
> 
> Attached screenshots FYR.
> **Before**
> <img alt="before" width="710" src="https://user-images.githubusercontent.com/17673823/120534626-afe48d00-c3ff-11eb-9046-81fb7b0d4806.png">
> **After**
> <img alt="after" width="710" src="https://user-images.githubusercontent.com/17673823/120534611-ab1fd900-c3ff-11eb-8a9b-079969b0d3ea.png">

@TParcollet @naba89 @guowhite @Gastron

**Comment by TParcollet** [comment]
@mravanelli This is the issue you mentioned last time?

**Comment by mravanelli** [comment]
Yes,
the gpu issue is fixed when using the latest version of the development
branch. It will be on the main branch once we release a new version (i.e,
probably within few days).
