### ISSUE TITLE
"EnvCorrupt" is not usable outside the training stage

### ISSUE THREAD

**Issue by baptistepouthier** [speechbrain/speechbrain#780]
Hello,

Is the following condition necessary? 

https://github.com/speechbrain/speechbrain/blob/97e027ce5234e49e3f4969b218f0e12ee104f2cc/speechbrain/lobes/augment.py#L419

It does not allow the use of data augmentation during the test phase. You may want to test your model in noisy conditions.
IMHO, the "if stage == sb.Stage.TRAIN:" condition in the brain class could suffice.

What do you think?

**Comment by TParcollet** [comment]
Hey, as stated you can easily apply env_corr at test time by removing the if statement in the compute_forward. However, this is not something we want to put in any recipe as models are compared with the clean version of each dataset usually.

**Comment by mravanelli** [comment]
It looks to me that we can even remove that check in the lobe and only keep the check in the recipes. This way we allow using the augmentation even in test modality. Any though @pplantinga?

**Comment by pplantinga** [comment]
Sure, I guess I can see a use for that.
