### ISSUE TITLE
Training ASR model with larger batch size couldn't accelerate

### ISSUE THREAD

**Issue by YujunZhong** [speechbrain/speechbrain#784]
Hello, 
I was trying to train Transformer model in AISHELL, everything works fine with the default setting. But when I **changed the batch size** from 8 to 16, the time spent on each iteration became about twice(sometimes even more) compare to previous, which means **it didn't shorten the training time**. I tried to changed the batch size to 32 and it had the same problem. 
I was thinking maybe the cause was in the dataloader, then I check the code and it looks like the only step compute in CPU is audio loading. So I printed the time cost in this step, but it doesn't seem to be the problem.
Any idea about this issue?

`Recipe: speechbrain/recipes/AISHELL-1/ASR/transformer`
`Python: 3.8.0`
`torch: 1.7.1+cu101`
`torchaudio: 0.7.2`

**Comment by TParcollet** [comment]
Hi,

We will need a bit more of context. Are you using 1 or many GPUs? Do you mean that increasing the batch_size also increased the training time? If so, this could be due to a slow read access where the data are stored. This typically happens when the data are accessed through the NFS. If this is the case, increasing the num_workers on the dataloader will solve the issue.

**Comment by YujunZhong** [comment]
> Hi,
> 
> We will need a bit more of context. Are you using 1 or many GPUs? Do you mean that increasing the batch_size also increased the training time? If so, this could be due to a slow read access where the data are stored. This typically happens when the data are accessed through the NFS. If this is the case, increasing the num_workers on the dataloader will solve the issue.

I did the experiment separately with 1 GPU and multi-GPU training using DDP, both methods ran into the same problem. Like you said, when I increased the batch_size, the training time was also increased. 
So I increased the num_workers on the dataloader as you suggest, and the training speed has been significantly improved, everything seems to be fine by now. 

Thank you for your great work and helpful reply!
