### ISSUE TITLE
Training AMI diarization model oncustom dataset

### ISSUE THREAD

**Issue by Wulin824** [speechbrain/speechbrain#786]
Hello, I am training a own dataset without overlapping. I have prepared rttm files of train, dev, test and csv myself. Because there is no speaker overlapping part in my dataset, I have not generated rttm and csv files of subsegment (does this have any impact? or whether there is something wrong with the data information I provided?）.Then I trained, but I reported the following mistakes. I hope you can give me an answer. Thank you.
![csv](https://user-images.githubusercontent.com/56509789/119589934-6811a480-be06-11eb-939c-374b897fce0b.png)
![csvinfo](https://user-images.githubusercontent.com/56509789/119590137-c63e8780-be06-11eb-8d59-2a52009e120d.png)
![rttm](https://user-images.githubusercontent.com/56509789/119590200-e2dabf80-be06-11eb-93ca-3b07d18672ba.png)
![报错](https://user-images.githubusercontent.com/56509789/119590236-f0904500-be06-11eb-8fe3-cf50cb0012e7.png)

**Comment by nauman-daw** [comment]
Looks like the problem is in the embedding extraction stage. Can you please check if your embeddings are generated properly?

**Comment by nauman-daw** [comment]
Is there any update on this issue?

**Comment by Wulin824** [comment]
I have solved it, please close it, thank you!
