### ISSUE TITLE
Performance of pretrained speechbrain/spkrec-xvect-voxceleb on VoxCeleb

### ISSUE THREAD

**Issue by hbredin** [speechbrain/speechbrain#789]
[speechbrain/spkrec-xvect-voxceleb](https://huggingface.co/speechbrain/spkrec-xvect-voxceleb) says EER=0.69% on VoxCeleb 1.

This number looks suspiciously similar to that of [speechbrain/spkrec-ecapa-voxceleb](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb) (also EER=0.69%). 

Probably a bad copy-n-paste?

**Comment by mravanelli** [comment]
Hi Hervé!
Yes, that's a typo. The EER performance for xvector is 3.2%. Let me fix it.

Thank you for noticing!

Best,

Mirco

**Comment by mravanelli** [comment]
Fixed, thank you!

**Comment by hbredin** [comment]
Thanks Mirco!
