### ISSUE TITLE
Recipe/VoxCeleb: missing "mean_var_norm_emb.ckpt"

### ISSUE THREAD

**Issue by yfliao** [speechbrain/speechbrain#792]
Dear All,

I tried to run "python train_speaker_embeddings.py hparams/train_ecapa_tdnn_big.yaml" after finish the training process. But I can't find the "mean_var_norm_emb.ckpt" file. How to generate this file?

Best Regards,
yuanfu

![image](https://user-images.githubusercontent.com/6238892/120056553-9940dd80-c06f-11eb-9b1e-5e29c8f7603c.png)

**Comment by mravanelli** [comment]
Hi, the normalization of the embeddings is done here: https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/speaker_verification_cosine.py. We basically save the normalization vector from here (it is not needed for computing the embeddings). However, I plan to refactor the code and store the normalization part as well.

**Comment by goexle** [comment]
@mravanelli I had the same question, thanks for answering it.
I  called
`params["mean_var_norm_emb"]._save(params["save_folder"]+"mean_var_norm_emb.ckpt")`
at the end of the speaker_verification_cosine.py script.    
Is that correct or am I missing something?

**Comment by mravanelli** [comment]
Yes,
that's what I basically did (I used torch.save but it is the same). In the
next refactor of the ECAPA-TDNN network I plan to add it when training the
embeddings to avoid this annoying extra step.

**Comment by goexle** [comment]
thank you :)
