### ISSUE TITLE
question about the transducer loss

### ISSUE THREAD

**Issue by songtaoshi** [speechbrain/speechbrain#796]
Hi, It's so useful to a transducer loss. 
But I have a question about that what is the value if we have trained a good model.  
The situation I met now is that the loss is 0.56 but the Chinese CER is 0.65 and the reduction mode is "mean".    
@maelp @shawntan @breandan @jimregan @vaenyr

**Comment by mravanelli** [comment]
@aheba

**Comment by jinggaizi** [comment]
i have used the transducer loss and found that the loss average by frames ,so it's very low. Maybe it's this reason

**Comment by mravanelli** [comment]
@aheba could you please clarify this point?

**Comment by Gastron** [comment]
Closing after lack of activity. My understanding of the question is understanding what is a good transducer loss value to aim for. It can apparently reach very low values. My suggestion is to monitor the validation CER, as you have done.
