### ISSUE TITLE
[Documentation] Explanation on sequence length units is inconsistent

### ISSUE THREAD

**Issue by Fhrozen** [speechbrain/speechbrain#797]
This issue does not generate any error, but maybe confusion about the use:

https://github.com/speechbrain/speechbrain/blob/97e027ce5234e49e3f4969b218f0e12ee104f2cc/recipes/VoxCeleb/voxceleb_prepare.py#L69-L70

It says that `Segment duration of a chunk in milliseconds`, But the seq_len is multiplied by `100`

https://github.com/speechbrain/speechbrain/blob/97e027ce5234e49e3f4969b218f0e12ee104f2cc/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py#L225

Should not be `1000` to get in milliseconds?

Ofc, because the duration is multiply by `100` does not generate error: 
https://github.com/speechbrain/speechbrain/blob/97e027ce5234e49e3f4969b218f0e12ee104f2cc/recipes/VoxCeleb/voxceleb_prepare.py#L314

Maybe the explanation could be changed to `chunk in tens of milliseconds`?

**Comment by mravanelli** [comment]
Right, that could be misleading. I think the best approach here is to leave it in seconds, right? Let me fix that.

**Comment by mravanelli** [comment]
fixed, thank you!
