### ISSUE TITLE
oct2py.utils.Oct2PyError: Value "activlev" does not exist in Octave workspace

### ISSUE THREAD

**Issue by r-katti** [speechbrain/speechbrain#805]
Hello,

I tried running the ```prepare_data.py``` script given in ```speechbrain/recipes/WSJ0Mix/separation```. I get the following error when I try running the script.

```Traceback (most recent call last):
  File "/scratch/rohith/other_repos/speechbrain/recipes/WSJ0Mix/separation/prepare_data.py", line 523, in <module>
    get_wsj_files(wsj0root, output_dir)
  File "/scratch/rohith/other_repos/speechbrain/recipes/WSJ0Mix/separation/prepare_data.py", line 426, in get_wsj_files
    out = octave.activlev(s1_8k, fs_read, "n")
  File "/scratch/rohith/virtualenvs/speechbrain_env/lib/python3.9/site-packages/oct2py/core.py", line 729, in __getattr__
    exist = self._exist(name)
  File "/scratch/rohith/virtualenvs/speechbrain_env/lib/python3.9/site-packages/oct2py/core.py", line 686, in _exist
    raise Oct2PyError(msg % name)
oct2py.utils.Oct2PyError: Value "activlev" does not exist in Octave workspace
```

The ```octave``` installation works fine on the terminal. ```oct2py``` is also installed and imported in the code correctly.
I have installed all the packages specified in the ```requirements.txt``` and ```extra-dependencies.txt```. I'm working on Ubuntu ```18.04.5``` and Python ```3.9.5```.

Am I missing something? I couldn't really find any supporting documentation on the Octave website related to the ```activlev``` function. Any help would be appreciated.

Thanks!

**Comment by mravanelli** [comment]
@ycemsubakan any idea?

**Comment by ycemsubakan** [comment]
Right, to be honest, I think you would be better off using the original Matlab generation scripts. You can also try the WHAM/WHAMR python scripts.  http://wham.whisper.ai/ 

We will be removing these scripts as the octave part does not work well.

I am closing the issue.

**Comment by danpovey** [comment]
Remember that matlab is quite expensive, people outside an institution generally won't have it and many institutions don't have it.

**Comment by ycemsubakan** [comment]
Yes, the current code on the main branch requires some work and verification, and that's why it wasn't recommended on the readme files. We just removed the dataset preparation code for WSJ0Mix on the going source separation PR. In the meantime the script on http://wham.whisper.ai/ seems to work fine, and it's python. I haven't verified if the resulting clean dataset with the wham script is exactly the same as the original matlab script, but it can be used for experimentation. Maybe someone who verified this can add a comment here.

**Comment by mravanelli** [comment]
Hi Dan,
thank you very much for your comments!
I think the speech separation community should now consider alternatives to
standard WSJ0-based tasks. Creating the data requires having Matlab and the
WSJ corpus (both licensed) for no reason. A valuable alternative is
LibriMix.  I think the best approach nowadays is to create the mixtures on
the fly with dynamic batching and test the performance on a common (fixed)
test set.
