### ISSUE TITLE
AMI/Diarization

### ISSUE THREAD

**Issue by Tushar-Melmalgi** [speechbrain/speechbrain#809]
I tried to run pre trained model for Diarization
![image](https://user-images.githubusercontent.com/57182984/121202413-e6545900-c892-11eb-827a-c56eb7d35e0f.png)

And these are the tracebacks errors I get in google colab. Can anyone help resolve the issues

**Comment by mravanelli** [comment]
Any idea @nauman-daw?

**Comment by nauman-daw** [comment]
Hi @Tushar-Melmalgi ,
This looks like you happening in data_prep stage. Maybe didn't your manual_annot folder is not set properly. Could you please check it once? You can refer to the hprams.yaml file.
