### ISSUE TITLE
"Killed" when running model.separate_file()

### ISSUE THREAD

**Issue by denisvee** [speechbrain/speechbrain#810]
Hi there, I am trying to run the sepformer on a local file but can't seem to trace down the "Killed" response I am getting.

Code (the sample from https://huggingface.co/speechbrain/sepformer-wsj02mix):

```python
from speechbrain.pretrained import SepformerSeparation as separator
import torchaudio

model = separator.from_hparams(source="speechbrain/sepformer-wsj02mix", savedir='pretrained_models/sepformer-wsj02mix')

# for custom file, change path
est_sources = model.separate_file(path='test.wav') 

torchaudio.save("source1hat.wav", est_sources[:, :, 0].detach().cpu(), 44100)
torchaudio.save("source2hat.wav", est_sources[:, :, 1].detach().cpu(), 44100)
```

Output:
Hangs and then "Killed" stdout.

Env:
I am running on WSL2 and `test.wav` here is a 3 minute audio file @ 44100Hz. The resampling op seems to also fail from 44100 -> 8000. When changing the hyperparams.yaml sample_rate to 44100 I get "Killed" eventually.

Appreciate any guidance on this and let me know if you need additional context, thanks!

**Comment by TParcollet** [comment]
Usually, when a Kill arises, it is on the system side i.e. you exceed the allocated resources. Are you sure that the node that you are in as enough resources ? (RAM, CPU, GPU eventually)

**Comment by denisvee** [comment]
Ah yeah that's it. Switching to inference w/ cuda solves this problem for me thanks!
