### ISSUE TITLE
Any plan for lfmmi training

### ISSUE THREAD

**Issue by jasonyong** [speechbrain/speechbrain#811]
Hi, thanks for your work! Is there any play for supporting lfmmi training? When speechbrain starts, I have seen 'lfmmi train' in the introduction. So it is canceled now?

**Comment by TParcollet** [comment]
Hi Jason,

Yes it's on the roadmap (see our discourse). However, we would like to wait for K2 before going on our own way. Indeed, we believe that K2 might do an amazing job at this, and we would just need to integrate it.

**Comment by danpovey** [comment]
FYI, The place we are drafting the recipe-level stuff is snowfallhttps://github.com/k2-fsa/snowfall

Right now the LF-MMI code doesn't work great if the number of units is very large (thousands), for memory consumption reasons,but we are working on some changes to make it work for those types of units.  (2 changes: a change in the CTC topology, and a change in the topology of the LF-MMI denominator graph P to be sparse, not full).

**Comment by TParcollet** [comment]
Hi @danpovey, thanks for the pointer.

I wonder if it wouldn't be worth having a chat with someone from the K2 team at some point to see if there is any space for a better collaboration / integration.

**Comment by danpovey** [comment]
Sure, you can email me at dpovey@gmail.com
