### ISSUE TITLE
Running inference on windows returning errors

### ISSUE THREAD

**Issue by abhikvarma** [speechbrain/speechbrain#815]
on executing the following line:

`asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="asr/pretrained_models/asr-crdnn-rnnlm-librispeech", run_opts={"device":"cuda"})
`

I face this error:
 
![image](https://user-images.githubusercontent.com/43804297/121530051-a324f200-ca1a-11eb-9084-e80946917783.png)

From what I can figure out, load_hyperpyyaml (and yaml.load) are returning strings instead of dictionaries when running inference on windows.

Is there a workaround to this?

**Comment by mravanelli** [comment]
Unfortunately, I don't have windows and I cannot replicate the issue. Is there someone from the community that can try inference on windows and provide some fixes?

**Comment by Gastron** [comment]
Closing for now, since there was on new activity - reopen if there are follow-ups.
