### ISSUE TITLE
kernel_size not used in ECAPA_TDNN?

### ISSUE THREAD

**Issue by ZimingY** [speechbrain/speechbrain#817]
Hi, In ecapa_tdnn, it includes several SERes2NetBlock 
https://github.com/speechbrain/speechbrain/blob/60f34b1b38e99b8a2bdc8b00d7aa9678d43de390/speechbrain/lobes/models/ECAPA_TDNN.py#L409
and it passes the kernel_side defined in yaml file to them.
https://github.com/speechbrain/speechbrain/blob/60f34b1b38e99b8a2bdc8b00d7aa9678d43de390/speechbrain/lobes/models/ECAPA_TDNN.py#L414
But in the class https://github.com/speechbrain/speechbrain/blob/60f34b1b38e99b8a2bdc8b00d7aa9678d43de390/speechbrain/lobes/models/ECAPA_TDNN.py#L267
These kernel size are all hard-coded as 1 (I think it makes sense since we will do _x+residual_ in the end)
https://github.com/speechbrain/speechbrain/blob/60f34b1b38e99b8a2bdc8b00d7aa9678d43de390/speechbrain/lobes/models/ECAPA_TDNN.py#L308
But then what is the point defining/passing them at the beginning?

**Comment by mravanelli** [comment]
Thank you for noticing. The kernel size=3 is not anymore hard coded within the residual block.
