### ISSUE TITLE
streaming inference in ASR

### ISSUE THREAD

**Issue by MahdiEsrafili** [speechbrain/speechbrain#818]
Hello. I want to use speechbrain ASR as a streaming service to create transcript for streaming voice in real time. I couldn't find anything about streaming in documentation. Is it available to do this? if so, what hardware resources (GPU/CPU) is needed?
thanks

**Comment by mravanelli** [comment]
Hi! The current version of SpeechBrain does not support streaming. This is a feature that we plan to add in the future.

**Comment by MahdiEsrafili** [comment]
> Hi! The current version of SpeechBrain does not support streaming. This is a feature that we plan to add in the future.

Thanks

**Comment by himanshucodz55** [comment]
Hi, Thanks for grate work team!
I'm training e2e ASR model with Transducer using Librispeech Recipe and also looking for streaming support. but i didn’t  find anything related to that. Could you please update streaming support.
Thanks.

**Comment by imEckenrode** [comment]
Any progress? Pushing this a year later

**Comment by Adel-Moumen** [comment]
Hello, 

Yes! We are currently actively working on it! 

We have pretty good results so far. Will keep you updated when something is ready ;)
