### ISSUE TITLE
Issues with speaker_verification_cosine.py and prepare_voxceleb.py

### ISSUE THREAD

**Issue by MingjieChen** [speechbrain/speechbrain#828]
Hello there, 

Found some issues when playing with speaker verification recipes:

1.  I found Line 241 in speaker_verification_cosine.py is trying to pass a 'rand_seed' argument to function prepare_voxceleb(), however there is no 'rand_seed' defined in function prepare_voxceleb().
2.  Again Line 241 in speaker_verification_cosine.py set seg_dur=300, which I think dismatch the commit that change from ms to sec.
3.  As I understand, if the score norm is used, voxceleb1 training data will be used. But I am not sure why training wav files are not copied into data_folder.

Btw, according to the 1st point, which is an obvious python syntax error, I just want to make sure is this recipe really working or it is still under development?

Thanks

**Comment by TParcollet** [comment]
Hi the recipe should work. Few changes were made recently, maybe it's something we forgot to check. @nauman-daw could you have a look please?

**Comment by mravanelli** [comment]
Yes, the recipe is working. The only thing to fix is to update the cosine
distance script to the new data preparation. I will do it soon!

**Comment by mravanelli** [comment]
This is fixed in the current development branch. Feel free to double check!
