### ISSUE TITLE
CRDNN: Cannot do pooling across the time dimension

### ISSUE THREAD

**Issue by RuABraun** [speechbrain/speechbrain#829]
Hi,
I'm trying to use the CRDNN, I've got 3 CNN blocks and want to do pooling across the time dim. I set `inter_layer_pooling_size: [3, 3, 3]`, and then noticed that by default the pooling is actually done over the input channel dimension. If I changed the hardcoded axis I got `Given input size: (512x1x2). Calculated output size: (512x1x0). Output size is too small`

I get the same error if I use `using_2d_pooling: True` (without any changes to the code from me).

It seems to be happening when the hyperparams file is loaded and dummy inputs are input into the model. It's weird because after the CNN part I *am* pooling across the time dim (`time_pooling: True`) but that alone does not lead to any issues.

I'm guessing for someone who knows SB there is an obvious fix which is why I haven't provided much info, would be happy to provide more if necessary.

PS [this](https://github.com/speechbrain/speechbrain/blob/f62eba9314d1254905818114f7febd174b82826e/speechbrain/nnet/CNN.py#L476) is a typo right?

**Comment by RuABraun** [comment]
I got around it by reducing the effective amount of reduction across the time domain.

**Comment by TParcollet** [comment]
Hi, 

COuld you please provide the full error stack trace? I'll have a look into this. Yes it's a typo :p

**Comment by mravanelli** [comment]
I think the issue happens when the input is short and, given the pooling applied in each layer, you end up with no time steps left. I think this is expected. However, as mentioned by @TParcollet, if you can share a code snippet it would be easier for us to take a look at that.

**Comment by RuABraun** [comment]
I figured it out it's because I was doing so much pooling the default dummy dimension of [64](https://github.com/speechbrain/speechbrain/blob/96077e9a1afff89d3f5ff47cab4bca0202770e4f/speechbrain/nnet/containers.py#L72) wasn't enough. I was expecting something like this but didn't understand why the model was being run during the loading of the yaml file. The reason is (for any future reader) because when appending layers with `Sequential` the model is run to figure out what the current output shape of the model is (and what therefore the current input shape for the just added layer is).

**Comment by TParcollet** [comment]
How much pooling did you do ? Maybe this is something we want to allow by increasing the dummy input.

**Comment by RuABraun** [comment]
A ton (going from ~100 timesteps to 1), not sure if it's actually a good idea yet :smile: so dunno if it makes sense to allow for it (but at the same I guess it wouldn't cost much to increase it to 128)
