### ISSUE TITLE
Feature : Running Training on AWS SageMaker

### ISSUE THREAD

**Issue by ayush9096** [speechbrain/speechbrain#833]
Feature request for support of easy integration for running the training and inference of SpeechBrain Models on AWS SageMaker.

**Comment by TParcollet** [comment]
Hi @ayush9096, we are not familiar with AWS SageMaker. Could you be more precise and what would be needed?

**Comment by rudsamn** [comment]
Hi @TParcollet, I was trying to automate running the speechbrain enhancement model on sagemaker but I cannot convert the model into a callable instance object. Can you help with this?
