### ISSUE TITLE
Can the Speech Brain be used for harmonic band expansion for human voice or speech synthesis?

### ISSUE THREAD

**Issue by huskyachao** [speechbrain/speechbrain#839]
For example, the input audio signal only contains the fundamental frequency of the human voice (which is hard for a listener to understand), is the speech Brain can recover a more intelligible voice that contains more high-frequency components?

**Comment by mravanelli** [comment]
Hi @huskyachao, 
we never addressed this task so far. However, the toolkit is flexible enough to allow you at least trying to train such a system (if you have a dataset for that).
