### ISSUE TITLE
How can I see the pretrained model parameters in the speechbrain.pretrained ?

### ISSUE THREAD

**Issue by huskyachao** [speechbrain/speechbrain#848]
For example, how can I see the network layers of the following model (i.e., enhancer)?
``` python
import torchaudio
from speechbrain.pretrained import SpectralMaskEnhancement
enhancer = SpectralMaskEnhancement.from_hparams(
    ...     source="speechbrain/mtl-mimic-voicebank",
    ...     savedir=tmpdir,
    ... )
```

**Comment by TParcollet** [comment]
Hi @huskyachao, I propose you to have a look at the SpectralMaskEnhancement code. But basically, all parameters can be accessed with the self.modules variable. (just print enhancer.modules and you'll see your different Torch modules with standard access to parameters etc)
