### ISSUE TITLE
speechbrain.processing.speech_augmentation.AddNoise Error: raise ValueError(f"Duplicate id: {data_id}")

### ISSUE THREAD

**Issue by ZeHuangFang** [speechbrain/speechbrain#854]
Hi guys,
    I have got a error when I used **speechbrain.processing.speech_augmentation.AddNoise**, error information like as this:

 File "../utils.py", line 134, in forward
    waveforms = self.noisifier(waveforms, lengths)
  File "../anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../anaconda3/lib/python3.8/site-packages/speechbrain/processing/speech_augmentation.py", line 146, in forward
    noise_waveform, noise_length = self._load_noise(
  File "../anaconda3/lib/python3.8/site-packages/speechbrain/processing/speech_augmentation.py", line 176, in _load_noise
    dataset = ExtendedCSVDataset(
  File "../anaconda3/lib/python3.8/site-packages/speechbrain/dataio/legacy.py", line 89, in __init__
    data, di_to_add, data_names = load_sb_extended_csv(
  File "../anaconda3/lib/python3.8/site-packages/speechbrain/dataio/legacy.py", line 178, in load_sb_extended_csv
    raise ValueError(f"Duplicate id: {data_id}")
ValueError: Duplicate id: 1

    And my noise.csv file is:
  ID, duration, wav, wav_format, wav_opts
  1, 60.0, DATASET/noise/wav/long_wav_000000.wav, wav,
  2, 60.0, DATASET/noise/wav/long_wav_000001.wav, wav,
  3, 60.0, DATASET/noise/wav/long_wav_000002.wav, wav,
  4, 60.0,DATASET/noise/wav/long_wav_000003.wav, wav,
  5, 60.0, DATASET/noise/wav/long_wav_000004.wav, wav,
  6, 60.0, DATASET/noise/wav/long_wav_000005.wav, wav,
  7, 60.0,DATASET/noise/wav/long_wav_000006.wav, wav,
  8, 60.0, DATASET/noise/wav/long_wav_000007.wav, wav,
  9, 60.0, DATASET/noise/wav/long_wav_000008.wav, wav,
...
  I can't find anything error in codes, could you tell me what happen in it?

**Comment by mravanelli** [comment]
It looks like there is an issue with the id (that should be unique). @pplantinga do you see any issue with that?

**Comment by pplantinga** [comment]
I tested the portion of this file copied here and found no issues. Please check your ID column to make sure there are no repeated entries.

**Comment by ZeHuangFang** [comment]
Thanks for your reply! I resolved this problem by add my noise-set, so is there something limit of noise-set size?

**Comment by pplantinga** [comment]
There's no limit on size.
