### ISSUE TITLE
recipes/VoxCeleb/SpeakerRec - missing yaml files

### ISSUE THREAD

**Issue by akaver** [speechbrain/speechbrain#863]
Hi,

Working on data augmentation experiments for speaker verification and would like to test my ideas on speechbrain.
Currently recipes/VoxCeleb/SpeakerRec/hparams contains:
train_ecapa_tdnn.yaml
train_x_vectors.yaml
verification_ecapa.yaml
verification_plda_xvector.yaml

But the README.md also refers to
train_ecapa_tdnn_big.yaml
verification_ecapa_tdnn.yaml
train_xvector_voxceleb2.yaml

Would it be possible to also somehow access these missing yaml files?

regards,
akaver

**Comment by mravanelli** [comment]
Thank you for noticing! It was just the README outdated (I fixed it).  We only release the yaml files that correspond to the best systems. In general, we are trying to minimize the number of yaml file released for each recipe to make maintainability easier.
