### ISSUE TITLE
Does the recipe for TIMIT using wav2vec2 pretrained model only works with Wav2Vec 2.0 Large (LV-60)? 

### ISSUE THREAD

**Issue by hxixium** [speechbrain/speechbrain#865]
Hi,

I'm trying to train on TIMIT use the recipe from _recipes/TIMIT/ASR/seq2seq/train_with_wav2vec2.py_ and I'm using a Fairseq pretrained model. It works perfectly when using the default setting of _recipes/TIMIT/ASR/seq2seq/hparams/train_with_wav2vec2.yaml_, but when I changed the default pretraining model from [Wav2Vec 2.0 Large (LV-60)](https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt) to [Wav2Vec 2.0 Large](https://dl.fbaipublicfiles.com/fairseq/wav2vec/libri960_big.pt) (or [Wav2Vec 2.0 Base](https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt)), it seems the model won't converge and I got a very high PER on TIMIT. Any idea why this happens? 

Thanks a lot!

**Comment by mravanelli** [comment]
We didn't try all the variations on TIMIT. It looks like Wav2Vec 2.0 Large (LV-60)  is using 60k hours of unlabeled data from LibriVox, while Wav2Vec 2.0 Large and  Wav2Vec 2.0 Base are only using the 960 hours of LibriSpeech. This looks like a big difference in terms of data. Maybe trying to tweak a bit the hyperparameters might help anyway having a better performance anyway.

**Comment by hxixium** [comment]
Thanks!
