### ISSUE TITLE
custom training on speaker identification 

### ISSUE THREAD

**Issue by rohaantahir** [speechbrain/speechbrain#866]
Hi! I am trying to do training on my custom dataset of about 500 speakers for speaker identification. I am following the code available inside templated/speaker_id. but when I am trying to train the the model I am getting the following error :

    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Rohan Tahir\Anaconda3\envs\py38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\Rohan Tahir\Anaconda3\envs\py38\lib\site-packages\speechbrain\dataio\batch.py", line 125, in __init__
    padded = PaddedData(*padding_func(values, **padding_kwargs))
  File "C:\Users\Rohan Tahir\Anaconda3\envs\py38\lib\site-packages\speechbrain\utils\data_utils.py", line 405, in batch_pad_right
    raise EnvironmentError(
OSError: Tensors should have same dimensions except for last one

Kindly see it and guide me from where I can change the tensor or should I make smaller clips of sound files as in LibriSpeech ?

**Comment by mravanelli** [comment]
Hi,
it looks like this is just a dimensionality mismatch. Make sure, for instance, the batches (that I guess contain the input waveforms) respect the batch formalism:  [batch, time].
If you are able to run the example in the template, you can do some prints of the shapes there to figure out what is the expected dimensionality.

**Comment by rohaantahir** [comment]
Thanks for the reply. Yes, it was the mismatch of the number of channels. the LibriSpeech has one channel while my dataset was of having 2 channels. I split the wav files and it solved my problem.
