### ISSUE TITLE
Can't train a model with multi NVIDIA RTX 3090 GPUs.

### ISSUE THREAD

**Issue by Xinghui-Wu** [speechbrain/speechbrain#868]
OS: Ubuntu 20.04
Python: I tested both 3.7 and 3.8
SpeechBrain: I tested 0.5.8 and 0.5.9
PyTorch: 1.7.0 for SpeechBrain 0.5.8 and 1.9.0 for SpeechBrain 0.5.9, both complied on CUDA 11.1
Recipe: speechbrain/recipes/LibriSpeech/ASR/transformer

command: python train.py hparams/transformer.yaml --data_folder xxx --data_parallel_backend

I have 8 3090 GPUs on my server. But when I watched nvidia-smi, there was only one GPU process running on one GPU, the rest of the 7 GPUs were idle. So how can I fix this problem? Thank you.

**Comment by Xinghui-Wu** [comment]
Btw, I have tested the example code in https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#sphx-glr-beginner-blitz-data-parallel-tutorial-py and that could work in all 8 GPUs, which indicates that the PyTorch has no problem in training a model with multi 3090 cards.

Furthermore, I have analyzed the code of SpeechBrain in https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/core.py#L1128, and didn't find any coding problem.

**Comment by jamfly** [comment]
Hi,
I encountered the same issue before, the following command fix my problem
```CUDA_VISIBLE_DEVICES=0,2 python train.py hparams/train.yaml --data_parallel_backend```

**Comment by Xinghui-Wu** [comment]
> Hi,
> I encountered the same issue before, the following command fix my problem
> `CUDA_VISIBLE_DEVICES=0,2 python train.py hparams/train.yaml --data_parallel_backend`

Hi, I tried this just now but it seemed that still only one GPU was used.

**Comment by jamfly** [comment]
or can you use DDP instead

```python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/train.yaml --distributed_launch --distributed_backend='nccl' --find_unused_parameters```

**Comment by Xinghui-Wu** [comment]
> or can you use DDP instead
> 
> `python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/train.yaml --distributed_launch --distributed_backend='nccl' --find_unused_parameters`

And here I got this error:

subprocess.CalledProcessError: Command '['python', '-u', 'train.py', '--local_rank=1', 'hparams/transformer.yaml', '--distributed_launch', '--distributed_backend=nccl']' returned non-zero exit status 1.

**Comment by jamfly** [comment]
Could you scroll up a little bit, or could you copy the full error message, otherwise, it is a bit hard to trace the issue.

**Comment by Xinghui-Wu** [comment]
> Could you scroll up a little bit, or could you copy the full error message, otherwise, it is a bit hard to trace the issue.

Here is the error message:

Traceback (most recent call last):
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/wuxh/speechbrain/SpeechBrain/bin/python', '-u', 'train.py', '--local_rank=1', 'hparams/transformer.yaml', '--distributed_launch']' returned non-zero exit status 1.

**Comment by Xinghui-Wu** [comment]
> Could you scroll up a little bit, or could you copy the full error message, otherwise, it is a bit hard to trace the issue.

Here is the error message:

Traceback (most recent call last):
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/data/wuxh/speechbrain/SpeechBrain/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/wuxh/speechbrain/SpeechBrain/bin/python', '-u', 'train.py', '--local_rank=1', 'hparams/transformer.yaml', '--distributed_launch']' returned non-zero exit status 1.

**Comment by jamfly** [comment]
it seems like that you miss `--find_unused_parameters` in the end of command, but, I don't know if it is the reason.

**Comment by Xinghui-Wu** [comment]
> it seems like that you miss `--find_unused_parameters` in the end of command, but, I don't know if it is the reason.

I guess no.
When watching nvidia-smi, is it supposed that all the specified GPUs have memory allocated at the very beginning, or just GPU 0 runs first for a while and later other GPUs begin to work?

When I just saw the message "going into epoch 1" and the progress bar, only GPU 0 was working and I just killed the process. Should I wait for a moment?

**Comment by Xinghui-Wu** [comment]
I also tried to train the model on another server equipped with 2 TITAN V GPUs and I got the same issue that only one GPU was working.

**Comment by TParcollet** [comment]
Let me try to replicate this issue.

**Comment by TParcollet** [comment]
Right, I can't replicate, I tried on two 3090 and it worked 
![Capture d’écran 2021-07-05 à 21 53 16](https://user-images.githubusercontent.com/11910731/124513715-b6d63500-dddb-11eb-8674-02fd7c72c6dc.png)

with
`python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='gloo'`

Here is my env.log
![Capture d’écran 2021-07-05 à 21 57 56](https://user-images.githubusercontent.com/11910731/124513902-1af8f900-dddc-11eb-9041-6cc319d494fa.png)

Do you use conda ?

**Comment by TParcollet** [comment]
(Note CUDA 11.3 is the OS default, but I use 11.1)

**Comment by TParcollet** [comment]
All GPUs should start directly.

**Comment by TParcollet** [comment]
Maybe you could check the log.log to see if there is any weird log about DDP ?

**Comment by Xinghui-Wu** [comment]
> Right, I can't replicate, I tried on two 3090 and it worked
> 
> ![Capture d’écran 2021-07-05 à 21 52 52](https://user-images.githubusercontent.com/11910731/124513934-2cda9c00-dddc-11eb-9ca5-7761b9b6f3b6.png)
> 
> with
> `python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='gloo'`
> 
> Here is my env.log
> ![Capture d’écran 2021-07-05 à 21 57 56](https://user-images.githubusercontent.com/11910731/124513902-1af8f900-dddc-11eb-9041-6cc319d494fa.png)
> 
> Do you use conda ?

Yes, I use conda to create a virtual environment. But when activated, I use pip to install the PyTorch and SpeechBrain, following the official documents. The used commands are as follows, and I tried various versions of PyTorch (1.7.0, 1.8.1 and 1.9.0 with CUDA 11.1) and peechBrain.

`pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html`
`pip install speechbrain`

**Comment by TParcollet** [comment]
Could you try to install it with conda? 
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

I don't really understand what is happening ... Could you check the log.log file as well? Last check -> Could you try to use DDP without SpeechBrain ? With a simple example given by PyTorch? I suspect that it is a system wide issue and not SpeechBrain one.

**Comment by jamfly** [comment]
Hi @Xinghui-Wu ,
I tested on two 3090ti GPUs, I firstly install torch1.8 via conda, and then install speechbrain directly via source code.
It works perfectly without any problem.

**Comment by lhanzl** [comment]
I also have a GPU training problem.
My GPU and cuda versions are as follows:
A100-PCIE-40GB+cuda11.0, it seems that only torch with +cuxx.x can be installed on this GPU, so the version I installed is as follows:
torch 1.7.1+cu110 pypi_0 pypi
torchaudio 0.7.2 pypi_0 pypi
torchvision 0.8.2+cu110 pypi_0 pypi
But the following error occurred when I was training:
```
Traceback (most recent call last):                                                                                                       [0/77]
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 458, in forward
    x = layer(x, lengths=lengths)
  File "/dir/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'lengths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 303, in <module>
    lid_brain.fit(
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/core.py", line 1022, in fit
    loss = self.fit_batch(batch)
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/core.py", line 848, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "train.py", line 77, in compute_forward
    embeddings = self.modules.embedding_model(feats)
  File "/dir/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 460, in forward
    x = layer(x)
  File "/dir/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 72, in forward
    return self.norm(self.activation(self.conv(x)))
  File "/dir/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/nnet/CNN.py", line 394, in forward
    x = self._manage_padding(
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/nnet/CNN.py", line 443, in _manage_padding
    padding = get_padding_elem(L_in, stride, kernel_size, dilation)
  File "/dir/anaconda3/lib/python3.8/site-packages/speechbrain/nnet/CNN.py", line 1055, in get_padding_elem
    half_padding = torch.div(tot_padding, 2, rounding_mode="floor")
TypeError: div() got an unexpected keyword argument 'rounding_mode'
```
Can anyone tell me the reason, thank you very much.

**Comment by TParcollet** [comment]
@lhanzl I can tell you, because we still did not updated the requirements because of this change. We will drop the support for torch 1.7.1 since 1.9 came out. Please update to >1.8

**Comment by PabloPeso** [comment]
Hi,

I have the same problem when trying to run with the DataParallel (DP) approach, i.e. `CUDA_VISIBLE_DEVICES=0,1 python train.py hparams/conformer_small.yaml --data_parallel_backend`, it just runs on one GPU instead of using the 2 GPU available. However it works fine when I use the  DistributedDataParallel (DDP) approach, i.e. `python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/conformer_small.yaml --distributed_launch --distributed_backend='nccl' --find_unused_parameters`.

 I am using the following:

- Recipe: speechbrain/recipes/LibriSpeech/ASR/transformer
- CUDA Version: 11.2 
- Python: 3.8
- Speechbrain: 0.5.9
- Torch: 1.8.1

I am interested in parallelising with DataParallel (DP), is this option still available for training?

Thanks for your help.

**Comment by PabloPeso** [comment]
Is this DP issue only running on a single GPU related to this comment https://github.com/speechbrain/speechbrain/pull/713#issuecomment-862385401?

**Comment by Xinghui-Wu** [comment]
@TParcollet @jamfly Thanks for your help. I turned to use conda to install torch in my virtual environment instead of pip. And now I can run the training script on multi GPUs with the DDP mode.

However, I still encountered the same problem as @PabloPeso , that only one single GPU worked with the DP approach.

**Comment by mravanelli** [comment]
This looks solved for the tranformer recipe, right @TParcollet and @popcornell? Not sure we already merged the needed changes though.

**Comment by TParcollet** [comment]
The PR could have solved the problem, but we don't know. Because we never have been able to replicate ...

**Comment by PabloPeso** [comment]
@TParcollet I can test the PR if you want and let you know the result, would that help?

**Comment by TParcollet** [comment]
It would be great, thanks!

**Comment by PabloPeso** [comment]
Answer in https://github.com/speechbrain/speechbrain/issues/899#issuecomment-898484357 since all the train logs are in that issue
