### ISSUE TITLE
Redundancy of the equal sign in  `--<boolean-argument>=True` in the tutorials.

### ISSUE THREAD

**Issue by geoph9** [speechbrain/speechbrain#870]
Hi,

This is a very minor issue, but I wanted to point it out just for the sake of clarity. In the `MultiGPU.ipynb` tutorial, the given examples give boolean options/actions in the form of `--distributed_launch=True`. But, `argparse` doesn't really need the `=True` part and throws an error otherwise. I am not sure if this is also the case for other tutorials.

**Comment by TParcollet** [comment]
Has been changed ! Thanks
