### ISSUE TITLE
Likely memory leaks with huge datasets in Dataset class

### ISSUE THREAD

**Issue by vadimkantorov** [speechbrain/speechbrain#872]
As far as I can see, the dataset in SpeechBrain is a list holding dicts with file paths.

With current state of affairs in PyTorch (maybe DataPipes will fix this?), this is the road to DataLoader leaking memory: https://github.com/pytorch/pytorch/issues/13246

I experienced this myself in a similar set-up (dozen thousand hours datasets, some string meta information)

The solution is to use hacks such as dicts of managed lists or packing strings into tensors (my solution): https://gist.github.com/vadimkantorov/86c3a46bf25bed3ad45d043ae86fff57

**Comment by TParcollet** [comment]
@Gastron is WebDataset fixing this? I guess so ?

**Comment by Gastron** [comment]
Oof, complicated stuff! Thank you for raising this issue. As I understand it, bypassing this problem requires specific data types (ones that avoid copy-on-write behaviour), so in the general case this requires some effort from the user?

I believe WebDataset data loading (which is our current go-to for huge datasets) does not suffer from this, and hopefully once the PyTorch data loading updates are ready, this is also taken care of.

So for now, I think it's good that we have this issue in our issue history for reference if people run into this, and the recommended solution should be to either switch to WebDataset or then use solutions such as the one in @vadimkantorov 's gist. Does that sound good?

**Comment by Gastron** [comment]
Closing for now, see above comment.

**Comment by vadimkantorov** [comment]
In general case it requires some effort from the Dataset subclass author to replace list-of-dicts containers with other data structures. But it's possible and stays under the hood from the end-user standpoint.
