### ISSUE TITLE
Language id performance

### ISSUE THREAD

**Issue by lhanzl** [speechbrain/speechbrain#874]
Language id performance
I used the following script to test the performance of the released language model, and got the correct rate of 82.29%, which could not reach 85% (In https://huggingface.co/speechbrain/lang-id-commonlanguage_ecapa)
```
import torchaudio
from speechbrain.pretrained import EncoderClassifier
from itertools import islice
import csv
import sys

model = "speechbrain/lang-id-commonlanguage_ecapa"
test = sys.argv[1] # test.csv, generate by common_language_prepare.py
classifier = EncoderClassifier.from_hparams(source=model, savedir="pretrained_models/lang-id-commonlanguage_ecapa")

all_count = 0.0
correct = 0.0
error = 0.0
with open(test) as f:
  reader = csv.reader(f)
  for row in islice(reader, 1, None):
    all_count += 1
    wav = row[1]
    result = row[4]
    out_prob, score, index, text_lab = classifier.classify_file(wav)
    if text_lab[0] == result:
      correct += 1
    else:
      error += 1

print(all_count, correct, error, correct/all_count)
print("All {}, Correct {}, Error {}, ACC {:.2%}".format(all_count, correct, error, correct/all_count))
```
Is something wrong? Thank you

**Comment by mravanelli** [comment]
Hi, you can find the training logs and the test performance here:
`https://drive.google.com/drive/folders/1C6FSy-FcGYyd-ggaSIANcTMHGCNF4aUE?usp=sharing`
Let me try to replicate the issue. It might be that I uploaded the last model and not the best one. Let me dive into it as soon as I can.

**Comment by lhanzl** [comment]
Hi, I have another question. I ran this recipe on different machines and got different Loss. One is normal and the other is problematic. The error message is as follows:

```
Epoch: 1, lr: 1.00e-04 - train loss: 9.05 - valid loss: 6.65, valid error: 4.91e-01
Epoch: 2, lr: 9.69e-05 - train loss: 7.14 - valid loss: 4.70, valid error: 3.24e-01
Epoch: 3, lr: 9.38e-05 - train loss: 6.19 - valid loss: 3.88, valid error: 2.56e-01
Epoch: 4, lr: 9.07e-05 - train loss: 5.58 - valid loss: 3.43, valid error: 2.26e-01
Epoch: 5, lr: 8.76e-05 - train loss: 5.11 - valid loss: 3.06, valid error: 2.06e-01
Epoch: 6, lr: 8.45e-05 - train loss: 4.79 - valid loss: 2.96, valid error: 1.97e-01
Epoch: 7, lr: 8.14e-05 - train loss: 4.50 - valid loss: 2.73, valid error: 1.79e-01
Epoch: 8, lr: 7.83e-05 - train loss: 4.24 - valid loss: 2.78, valid error: 1.81e-01
Epoch: 9, lr: 7.52e-05 - train loss: 4.05 - valid loss: 2.54, valid error: 1.67e-01
Epoch: 10, lr: 7.21e-05 - train loss: 3.92 - valid loss: 2.54, valid error: 1.68e-01
Epoch: 11, lr: 6.90e-05 - train loss: 3.76 - valid loss: 2.50, valid error: 1.68e-01
Epoch: 12, lr: 6.59e-05 - train loss: 3.60 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 13, lr: 6.28e-05 - train loss: 3.45 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 14, lr: 5.97e-05 - train loss: 3.38 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 15, lr: 5.66e-05 - train loss: 3.21 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 16, lr: 5.34e-05 - train loss: 3.13 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 17, lr: 5.03e-05 - train loss: 2.99 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 18, lr: 4.72e-05 - train loss: 2.94 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 19, lr: 4.41e-05 - train loss: 2.87 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 20, lr: 4.10e-05 - train loss: 2.83 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 21, lr: 3.79e-05 - train loss: 2.71 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 22, lr: 3.48e-05 - train loss: 2.68 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 23, lr: 3.17e-05 - train loss: 2.58 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 24, lr: 2.86e-05 - train loss: 2.54 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 25, lr: 2.55e-05 - train loss: 2.50 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 26, lr: 2.24e-05 - train loss: 2.43 - valid loss: 0.00e+00, valid error: 9.72e-01
```

2021-07-13 22:33:42,831 - speechbrain.utils.epoch_loop - INFO - Going into epoch 27
2021-07-13 22:34:22,692 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "train_debug.py", line 304, in <module>
    lid_brain.fit(
  File "/dir/envs/sb/lib/python3.8/site-packages/speechbrain-0.5.9-py3.8.egg/speechbrain/core.py", line 1033, in fit
    loss = self.fit_batch(batch)
  File "/dir/envs/sb/lib/python3.8/site-packages/speechbrain-0.5.9-py3.8.egg/speechbrain/core.py", line 855, in fit_batch
    loss.backward()
  File "/dir/envs/sb/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/dir/envs/sb/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output.

Is it related to my training environment?

**Comment by mravanelli** [comment]
Yes, I also noticed that the language id recipe sometimes runs into numerical issues. I think one should  try to play with gradient clipping to fix it. Let me know if that helps.

**Comment by lhanzl** [comment]
Thanks for your reply @mravanelli 
My goal is to use ECAPA_TDNN for speech classification tasks, such as gender id, language id, etc.
Let me talk about the problem I encountered in detail. First, I used batch=2 on the GPU of GeForce RTX 2080 11019MiB, and this recipe can be reproduced, but the accuracy rate can only reach 79.51%. The training loss seems to be normal. 
When I switched to A100-PCIE-40GB GPU and used batch=4, when I reproduced this recipe, I found the above-mentioned Loss nan problem.
I think speechbrain and ECAPA_TDNN is a SOTA system. I hope to use speechbrain for my gender id task. Do you have any suggestions? use the IEMOCAP recipe or wait for you to fix the problem.
Thank you very much.

**Comment by mravanelli** [comment]
As for the numerical instability issue with batch=4, my suggestion is to
re-run the experiment with a different seed (see hyperameter file). Another
solution would be to add gradient clipping (just add gradient_clipping: 5.0
in the hparams file). Let me know if that solves the problem (you might
wanna play a bit with the gradient clipping threshold to find a proper
value for it).  You can definitely try ECAPA for audio classification
problems (where you are already using it for speaker-id, music-id, etc)
without issues.

**Comment by lhanzl** [comment]
Thank you very much for your answers.
I tried the two suggestions you made:
My training environment is A100-PCIE-40GB+cuda11.0+torch1.8.1+cu111
First, modify the seed to 2000, and the trained Loss is as follows:
```
Epoch: 1, lr: 1.00e-04 - train loss: 9.13 - valid loss: 6.71, valid error: 4.97e-01
Epoch: 2, lr: 9.69e-05 - train loss: 7.20 - valid loss: 4.79, valid error: 3.26e-01
Epoch: 3, lr: 9.38e-05 - train loss: 6.23 - valid loss: 3.93, valid error: 2.61e-01
Epoch: 4, lr: 9.07e-05 - train loss: 5.61 - valid loss: 3.41, valid error: 2.23e-01
Epoch: 5, lr: 8.76e-05 - train loss: 5.14 - valid loss: 3.06, valid error: 2.04e-01
Epoch: 6, lr: 8.45e-05 - train loss: 4.80 - valid loss: 2.91, valid error: 1.91e-01
Epoch: 7, lr: 8.14e-05 - train loss: 4.54 - valid loss: 2.77, valid error: 1.80e-01
Epoch: 8, lr: 7.83e-05 - train loss: 4.27 - valid loss: 2.74, valid error: 1.81e-01
Epoch: 9, lr: 7.52e-05 - train loss: 4.10 - valid loss: 2.51, valid error: 1.64e-01
Epoch: 10, lr: 7.21e-05 - train loss: 3.91 - valid loss: 2.62, valid error: 1.73e-01
Epoch: 11, lr: 6.90e-05 - train loss: 3.77 - valid loss: 2.45, valid error: 1.64e-01
Epoch: 12, lr: 6.59e-05 - train loss: 3.61 - valid loss: 2.45, valid error: 1.65e-01
Epoch: 13, lr: 6.28e-05 - train loss: 3.49 - valid loss: 2.48, valid error: 1.65e-01
Epoch: 14, lr: 5.97e-05 - train loss: 3.41 - valid loss: 2.38, valid error: 1.58e-01
Epoch: 15, lr: 5.66e-05 - train loss: 3.23 - valid loss: 2.29, valid error: 1.56e-01
Epoch: 16, lr: 5.34e-05 - train loss: 3.16 - valid loss: 2.35, valid error: 1.59e-01
Epoch: 17, lr: 5.03e-05 - train loss: 3.05 - valid loss: 2.26, valid error: 1.49e-01
Epoch: 18, lr: 4.72e-05 - train loss: 2.96 - valid loss: 2.35, valid error: 1.56e-01
Epoch: 19, lr: 4.41e-05 - train loss: 2.89 - valid loss: 2.32, valid error: 1.57e-01
Epoch: 20, lr: 4.10e-05 - train loss: 2.87 - valid loss: 2.23, valid error: 1.49e-01
Epoch: 21, lr: 3.79e-05 - train loss: 2.73 - valid loss: 2.20, valid error: 1.49e-01
Epoch: 22, lr: 3.48e-05 - train loss: 2.71 - valid loss: 2.24, valid error: 1.49e-01
Epoch: 23, lr: 3.17e-05 - train loss: 2.60 - valid loss: 2.19, valid error: 1.46e-01
Epoch: 24, lr: 2.86e-05 - train loss: 2.57 - valid loss: 2.24, valid error: 1.55e-01
Epoch: 25, lr: 2.55e-05 - train loss: 2.53 - valid loss: 2.12, valid error: 1.42e-01
Epoch: 26, lr: 2.24e-05 - train loss: 2.44 - valid loss: 2.29, valid error: 1.51e-01
Epoch: 27, lr: 1.93e-05 - train loss: 2.41 - valid loss: 2.14, valid error: 1.46e-01
Epoch: 28, lr: 1.62e-05 - train loss: 2.42 - valid loss: 2.15, valid error: 1.46e-01
Epoch: 29, lr: 1.31e-05 - train loss: 2.37 - valid loss: 2.17, valid error: 1.48e-01
Epoch: 30, lr: 1.00e-05 - train loss: 2.30 - valid loss: 2.13, valid error: 1.42e-01
Epoch loaded: 30 - test loss: 2.15, test error: 1.45e-01
```
It looks normal.
Second, modify gradient_clipping: 5, and the trained Loss is as follows:
```
Epoch: 1, lr: 1.00e-04 - train loss: 9.06 - valid loss: 6.55, valid error: 4.84e-01
Epoch: 2, lr: 9.69e-05 - train loss: 7.17 - valid loss: 4.78, valid error: 3.33e-01
Epoch: 3, lr: 9.38e-05 - train loss: 6.21 - valid loss: 3.96, valid error: 2.65e-01
Epoch: 4, lr: 9.07e-05 - train loss: 5.59 - valid loss: 3.42, valid error: 2.27e-01
Epoch: 5, lr: 8.76e-05 - train loss: 5.13 - valid loss: 3.05, valid error: 2.05e-01
Epoch: 6, lr: 8.45e-05 - train loss: 4.81 - valid loss: 2.94, valid error: 1.98e-01
Epoch: 7, lr: 8.14e-05 - train loss: 4.52 - valid loss: 2.72, valid error: 1.77e-01
Epoch: 8, lr: 7.83e-05 - train loss: 4.26 - valid loss: 2.72, valid error: 1.80e-01
Epoch: 9, lr: 7.52e-05 - train loss: 4.07 - valid loss: 2.57, valid error: 1.72e-01
Epoch: 10, lr: 7.21e-05 - train loss: 3.93 - valid loss: 2.53, valid error: 1.68e-01
Epoch: 11, lr: 6.90e-05 - train loss: 3.77 - valid loss: 2.50, valid error: 1.67e-01
Epoch: 12, lr: 6.59e-05 - train loss: 3.62 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 13, lr: 6.28e-05 - train loss: 3.47 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 14, lr: 5.97e-05 - train loss: 3.41 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 15, lr: 5.66e-05 - train loss: 3.24 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 16, lr: 5.34e-05 - train loss: 3.15 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 17, lr: 5.03e-05 - train loss: 3.05 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 18, lr: 4.72e-05 - train loss: 2.97 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 19, lr: 4.41e-05 - train loss: 2.89 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 20, lr: 4.10e-05 - train loss: 2.86 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 21, lr: 3.79e-05 - train loss: 2.73 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 22, lr: 3.48e-05 - train loss: 2.69 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 23, lr: 3.17e-05 - train loss: 2.60 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 24, lr: 2.86e-05 - train loss: 2.57 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 25, lr: 2.55e-05 - train loss: 2.54 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 26, lr: 2.24e-05 - train loss: 2.46 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 27, lr: 1.93e-05 - train loss: 2.41 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 28, lr: 1.62e-05 - train loss: 2.44 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 29, lr: 1.31e-05 - train loss: 2.36 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch: 30, lr: 1.00e-05 - train loss: 2.31 - valid loss: 0.00e+00, valid error: 9.72e-01
Epoch loaded: 11 - test loss: 2.62, test error: 1.76e-01
```
There is still the problem of nan.
Finally, the correct rate comparison between the model I trained and the model published on Huggingface (https://huggingface.co/speechbrain/lang-id-commonlanguage_ecapa)
|model|Total sentences|Correct Num| Error Num|ACC|
|----|----|----|----|----|
|huggingface |5963.0| 4907.0|1056.0| 82.29%|
|seed2000 |5963.0|4886.0|1077.0|81.94%|

In this regard, I would like to ask you a few questions.
1. What is the role of seed and why it can solve the nan problem
2. Why is the accuracy rate of the model I trained is lower than that of the huggingface model
3. The Release model can achieve 85% accuracy. If I want to achieve this performance, are there any hyperparameters that need to be tuning? Looking forward to your reply.

**Comment by mravanelli** [comment]
1- seed changes the initialization of the network as well (i.e.,the set of initial parameters are different). This recipe suffers from some numerical instabilities and we might need to investigate the cause of that. However, changing seed can be a temporary workaround.
2- The accuracy changes a bit every time you train a new model (new model = different initialization, dropout masks, and all the other random operations)

**Comment by lhanzl** [comment]
Thanks for the reply.

**Comment by asr-lord** [comment]
After 5 epochs of the training of my own model, following https://github.com/speechbrain/speechbrain/tree/develop/recipes/VoxCeleb/SpeakerRec, I get the NaN error. 

Is it fixed @mravanelli ? Or do I need to change the seed and add gradient_clipping: 5.0 in the hparams file?

**Comment by mravanelli** [comment]
Which model are you training? and on which data? Yes, try to see if
reducing gradient_clipping is enough. According to my experience, sometimes
there are some sentences in the datasets that systematically cause
NaN issues. If this is the case, try to print the sentence ids (ids
variable) and remove the critical sentences.

**Comment by asr-lord** [comment]
> Which model are you training? and on which data? Yes, try to see if reducing gradient_clipping is enough. According to my experience, sometimes there are some sentences in the datasets that systematically cause NaN issues. If this is the case, try to print the sentence ids (ids variable) and remove the critical sentences.

I'm traning ECAPA-TDNN embedding model with voxceleb1+2+own data.

**Comment by lhanzl** [comment]
The phenomenon is the same as when I trained CommonLanguage. Actually, I printed out the voice id and listened to it. There is indeed no problem with these voices that report nan errors.

**Comment by asr-lord** [comment]
> The phenomenon is the same as when I trained CommonLanguage. Actually, I printed out the voice id and listened to it. There is indeed no problem with these voices that report nan errors.

So there is no answer for this phenomenon?
