### ISSUE TITLE
Wrong model link for CTC training on commonvoice Italy

### ISSUE THREAD

**Issue by mrtunguyen** [speechbrain/speechbrain#876]
Hello, 

Could you please fix the model link for CTC training on commonvoice Italy? The link you provided seems not the good one. 
https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/CTC 

Thanks.

**Comment by mravanelli** [comment]
Hi, 
thank you for noticing. I cannot find the CTC wav2vect model for Italian in the project google drive and I cannot find it anymore in my local folders. I thus started a new training and the model will be available in few days.

**Comment by mrtunguyen** [comment]
thank you!

**Comment by mravanelli** [comment]
This is fixed now. Thank you!
