### ISSUE TITLE
cannot extract "rir noises" zip file for speaker_ id template

### ISSUE THREAD

**Issue by rajwanraz** [speechbrain/speechbrain#878]
I tried to run speaker_id template (with python train.py train.yaml) the script downloaded rirs_noises.zip, but while extracting the file raised the following error: "ReadError: ./data\rirs_noises.zip is not a zip file".
how to solve that? i think its path related

**Comment by mravanelli** [comment]
Are you using windows or linux?

**Comment by rajwanraz** [comment]
Using windows

**Comment by mravanelli** [comment]
Ok, we don't really support that. In the specific example, it looks like
the path where the rirs_noises dataset is stored gets messed up.

**Comment by rajwanraz** [comment]
do you mean that "speechbrain" doesn't support windows? should i run it on linux?
the script downloaded the zip file to a certain location.
and when it tries to extract, it looks for the zip file in a different directory.

**Comment by mravanelli** [comment]
We only have linux machines on our side and we cannot reproduce your error. If it is just a path issue, however, it should be easy to identify and fix. Please. keep us updated!
