### ISSUE TITLE
Speechbrain to get Number of occurrences of specific sounds

### ISSUE THREAD

**Issue by ZeroTiem** [speechbrain/speechbrain#880]
Hello, I’m a beginner developer. Can I use Speechbrain to get Number of occurrences of specific sounds
I use urbansound8k_ecapa and hope to get the number of gunshots. What examples can I refer to?

**Comment by mravanelli** [comment]
Hi @ZeroTiem, we don't have such a system, but you can try to train it if you have proper data for that. The urban sound recipe only tells you which of the 10 sounds is present in the clip. Note that we are also setting up a recipe for Domestic Sound Event Detection- DCASE (see https://github.com/speechbrain/speechbrain/pull/861) where the output is a binary matrix (noise_type, time) that tells you which noises are active for each time step. On the top of this output format, one can try to count the number of times each noise source is active.
