### ISSUE TITLE
Speaker recognition

### ISSUE THREAD

**Issue by Humayan-Kabir** [speechbrain/speechbrain#885]
hello, i am new in asr, if want to do speaker recognition, identification and diarization on Bengali language dataset, then what i need to do. If anyone gives little bit of light in this regard, it would be really helpful. thanks in advance.

**Comment by mravanelli** [comment]
For the speaker  recognition/classification part your can take a look at our tutorials (e.g, [speech classification from scratch](https://speechbrain.github.io/tutorial_classification.html)). For the diarization part, instead, you can take a look at our diarization recipe on [AMI](https://github.com/speechbrain/speechbrain/tree/develop/recipes/AMI/Diarization).

**Comment by Humayan-Kabir** [comment]
Thanks for your reply, Basically what I want to do is to find out speaker diversity of two corpora for comparing robustness. What can i do to serve my purpose using speech brain? is it possible to train a speaker adaptive model?

**Comment by mravanelli** [comment]
Not sure to understand here. My understanding is that you have two speech corpora and figure out which speakers are different?
