### ISSUE TITLE
SpeakerIDfromScratch EncoderClassifier.from_hparams(...) 

### ISSUE THREAD

**Issue by Humayan-Kabir** [speechbrain/speechbrain#890]
classifier = EncoderClassifier.from_hparams(source="~/best_model/", hparams_file='hyperparams.yaml', savedir="~/best_model/")
  File "/speechbrain/pretrained/interfaces.py", line 235, in from_hparams
    with open(hparams_local_path) as fin:
OSError: [Errno 40] Too many levels of symbolic links: 'hyperparams.yaml

**Comment by TParcollet** [comment]
Hi, I am not sure to understand properly the problem here.
