### ISSUE TITLE
How to do inference in diarization 

### ISSUE THREAD

**Issue by rohaantahir** [speechbrain/speechbrain#892]
Hi, I have been working on speech brain I successfully trained speaker verification and identification on my custom dataset. Now I want to do inference on diarization on input audio file. Can you please tell me the way how to do it to simply input the audio file and outputs the diarizations like speaker 1 speaks between what time and so on. Kindly guide me. 
thanks.

**Comment by mravanelli** [comment]
We still don't have an easy inference function for diarization. The reason is that we are working on a VAD that will be part of the full system. Once ready, we can add an inference function that performs VAD + embedding computation + clustering. Any comment on that @nauman-daw?

**Comment by nauman-daw** [comment]
Yes, this should be possible once VAD is ready. However, if you have Speech/Non-Speech boundaries (i.e. VAD info) available with you, you could probably follow the current AMI diarization recipe which assumes VAD details to be taken from groundtruth. Please note that you have to write data_prepare for your custom data accordingly.

**Comment by rohaantahir** [comment]
Till when we can get an easy inference of any kind of speaker diarization using speechbrain. Like we have for speaker verification? Could you please tell

**Comment by EmreOzkose** [comment]
Hi all, is there any progress for this issue?

**Comment by EmreOzkose** [comment]
@rohaantahir how did you use a custom set? Did you organize folder structure like AMI?
