### ISSUE TITLE
ModuleNotFoundError: No module named ‘parse_data’ 

### ISSUE THREAD

**Issue by qingtian1771** [speechbrain/speechbrain#894]
When I tried the tutorials dataioBasics.ipynb and pretraining.ipynb, I met the same problem, it can not find the module “parse_data”, and I can not use pip to install it, because pip also can not find it.
the code is here:

```
from parse_data import parse_to_json
parse_to_json("./LibriSpeech/dev-clean-2")
```

How to resolve? please help!
Thanks!

**Comment by TParcollet** [comment]
Hi, could you please tell us what is your python version?

**Comment by stephengineer** [comment]
I have same issue, I am using python 3.7
`pip install parse_data` does not work.

**Comment by mravanelli** [comment]
Hi, it works in Colab. The `parse_data`  is a local library downloaded in the first steps on the tutorial. We don't put it in the main toolkit because it is a function very specific for this tutorial.

**Comment by Gastron** [comment]
Closing, as the question was answered.
