### ISSUE TITLE
Questions about AttentionalRNNDecoder when running inference on ASR models.

### ISSUE THREAD

**Issue by Kuray107** [speechbrain/speechbrain#896]
I have a question about the forward function of speechbrain.nnet.RNN.AttentionalRNNDecoder: https://github.com/speechbrain/speechbrain/blob/4d7a971f98058ceb7192fcb29d4268b3aa12b1ce/speechbrain/nnet/RNN.py#L945-L950

To my understanding, the for loop here goes through every timestep of ground truth labels and feeds it as input to the RNN decoder (i.e. teacher forcing,) which is very normal for training. However, it seems that we shouldn't use the same method to compute forward when we do inference because we have no information about the ground truth of input waveforms. I am therefore a little confused and would like to ask whether the RNN decoder will perform differently in the evaluation stage.

**Comment by TParcollet** [comment]
Hey! You are totally right. At inference time, this code isn't used. Instead, at inference, the AttentionalRNN module is connected to a searcher (BeamSearch or greedy). In this searcher, things are done differently! (https://github.com/speechbrain/speechbrain/blob/4d7a971f98058ceb7192fcb29d4268b3aa12b1ce/speechbrain/decoders/seq2seq.py#L623)

**Comment by Kuray107** [comment]
Got it. Thanks for your clear explanation.
