### ISSUE TITLE
doctest fails: There is no such class as "..EnhanceResnet"

### ISSUE THREAD

**Issue by goexle** [speechbrain/speechbrain#897]
The doctest for speechbrain.pretrained.interfaces.SpectralMaskEnhancement is broken.

I run the command `pytest --doctest-modules speechbrain`. It fails with the error message:
"ImportError: There is no such class as speechbrain.lobes.models.EnhanceResnet.EnhanceResnet"

This is most likely due to a new [commit](https://huggingface.co/speechbrain/mtl-mimic-voicebank/commit/7e4f17f9504e5d8f26eda48d2545059025414016) at huggingfaces.
In [this line](https://huggingface.co/speechbrain/mtl-mimic-voicebank/blob/main/hyperparams.yaml#L10), it tries to call speechbrain.lobes.models.EnhanceResnet.EnhanceResnet. But this class does not exist in the speechbrain repository

**Comment by TParcollet** [comment]
@pplantinga can you confirm that this issue is solved?

**Comment by goexle** [comment]
Solved with [commit](https://huggingface.co/speechbrain/mtl-mimic-voicebank/commit/2a2af5c27919464e0c83b71790908f8ae0890928)
