### ISSUE TITLE
Audio Clustering

### ISSUE THREAD

**Issue by rohaantahir** [speechbrain/speechbrain#900]
Hi! Is there any solution provided by speechbrain to do clustering of similar kind of audio with number N from the dataset.?? Kindly tell me Thanks

**Comment by mravanelli** [comment]
Dear @rohaantahir,
I'm not sure to understand your request. What do you mean with " similar kind of audio with number N"?

**Comment by rohaantahir** [comment]
I want to clustering on the basis of input audio file. E.g to extract N (input number of similar speaker to extract) similar speaker labels from dataset. Hope so I made it clear to you.

**Comment by nauman-daw** [comment]
If I get it correctly, you want to perform clustering on a large number of audio clips (a dataset) and form N such clusters such that each cluster has all the audio clips belonging to a single speaker?

Currently, we do not have clustering recipes (maybe this should be somewhat aligned with diarization recipe). However, you can take a look at the spectral clustering present in SpeechBrain (https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/processing/diarization.py) and use it accordingly. In one of my ongoing PRs (#642), I am also trying to push a few other clustering approaches (but in the context of diarization). Have a look at #642. This PR is currently under review so it may change a bit in the future.
