### ISSUE TITLE
Data augmentation at 8kHz

### ISSUE THREAD

**Issue by fosimoes** [speechbrain/speechbrain#901]
I intend to train a speaker recognition model with 8kHz data, but it looks like the data augmentation implementation is somewhat restricted to work with the original RIRS noise sampling rate, which is 16kHz. More specifically, the EnvCorrupt class does not allow specifying the sampling rate.
I considered using the "rir_scale_factor" param to resample the reverb impulse response, but I suppose the resulting response might be affected by aliasing. With regard to noise addition, I didn't find a way to work with a different sampling rate.
At last, I observed that the TimeDomainSpecAugment class does not expose some parameters such as drop_freq_low, drop_freq_high, drop_width, which need to be set in accordance with the target sampling rate. 
Please let me know if I am missing something.

**Comment by mravanelli** [comment]
Good point. I think we should try to integrate here our resampler to resample the noise to the target sampling rate. What do you think @pplantinga?

**Comment by mravanelli** [comment]
That's a valid point. We should address it in the new version (@pplantinga @aheba)

**Comment by fosimoes** [comment]
have there been any developments regarding this issue?
