### ISSUE TITLE
ASR training using facebook/wav2vec2-base model

### ISSUE THREAD

**Issue by Reuben-Lim** [speechbrain/speechbrain#904]
Hi. I'm unable to run the train_with_wav2vec.py script when selecting facebook/wav2vec2-base in train_en_with_wav2vec.yaml. Is this model supported by speechbrain? I got the following error:

![image](https://user-images.githubusercontent.com/86700213/127613002-5450e1e9-4f96-4512-9f97-b5bbe5ebf61c.png)

Any help would be much appreciated. Thank you.

**Comment by TParcollet** [comment]
Hi, all wa2vec2 models are supported. It is mot likely that you did not change properly the input size of the model that follows the wav2vec2 (base models have a reduced output dim).

**Comment by Reuben-Lim** [comment]
Hi @TParcollet. Thank you for your help. So, I changed the train_en_with_wav2vec.yaml by replacing the value 1024 to 768 in the following lines for the facebook/wav2vec2-base model:
![image](https://user-images.githubusercontent.com/86700213/127733126-8706dc14-f4bb-4e98-8824-323d1b095701.png)
Not sure if that's entirely correct, but it seems to be finetuning with the error decreasing over time now.
Thanks
