### ISSUE TITLE
Training on long utterances

### ISSUE THREAD

**Issue by emirdemirel** [speechbrain/speechbrain#909]
Hi,

I am working on the task of speech recognition from sung utterances and the training data I have been using consists of utterances of 3-4 min length and the text is the full lyrics of songs. I was previously using Kaldi for this task where we could input data with segments annotations that enables training on shorter utterances. Is there such feature in SpeechBrain where we can specify beginning and ending timestamps of line-level utterances within long (few min) audio files? If not, would it cause a major problem to train an end-to-end system on these full-length long utterances? 

Thanks in advance

**Comment by mravanelli** [comment]
Hi Emir,
for a transformer-based model, 3-4 minutes could be too much. For an
RNN-based model it could potentially be feasible (as far as I know with the
current models with tried sentences up to 1 minutes). Note that we are
working on a Voice Activity Detection (VAD) system as well that should be
able to split a long recording into smaller chunks. The VAD will be ready
once we finalize all the tests.

**Comment by emirdemirel** [comment]
Hi Marco,

Thanks a lot for the rapid reply and your team's work on VAD.

Is the VAD system you mentioned operates on signals with no (or minimal) background noise? In other words, is this going to be based something like energy based activity detection?

The reason why I am asking this is that I am planning on training an acoustic model on polyphonic music data, where the singing voice is accompanied by music instruments. An energy-based VAD, or a supervised VAD trained on monophonic signals wouldn't work where there is musical accompaniment. However a recipe where we could train a VAD based on annotations would be really helpful for this ASR task.

Another solution would be generating training data samples where utterance boundaries are annotated within long utterances.

For the notice, my current solution to this problem would be splitting long audio recordings based on annotations and training the acoustic model on these newly generated audio files.

Regards

**Comment by mravanelli** [comment]
We are working on a neural network-based VAD that should work in noisy
conditions as well. I've been working on this recipe for a while and it
will be released once everything is ready.

**Comment by emirdemirel** [comment]
Great news! Looking forward to it. Thanks for the response
