### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by jamfly** [speechbrain/speechbrain#912]
### Issue
Hi there, I run my experiment in Linux with 64 core CPUs, and set worker numbers to 32. During the training, I encounter the following issue. It works perfectly when I set worker numbers to 8.

### How to reproduce 
set num_workers = 32

### Error
```
...
File "/home/jamfly/miniconda3/envs/sb/lib/python3.8/multiprocessing/reduction.py", line 189,
in recv_handle
return recvfds(s, 1)[0]
File "/home/jamfly/miniconda3/envs/sb/lib/python3.8/multiprocessing/reduction.py", line 164,
in recvfds
raise RuntimeError('received %d items of ancdata' %
```

**Comment by TParcollet** [comment]
Hi @jamfly could you please give us more context on what is this experiment about? Where does this error happen in the different steps ?

**Comment by jamfly** [comment]
Hi @TParcollet,

Sorry for the lack of context, it happened during the training step of ST recipe, but, I think it will also happen on every recipe that uses dataloader. (The num_workers is set to dataloader)

But after days of googling, it is the issue coming from [pytorch](https://github.com/pytorch/pytorch/issues/973). I will close this issue, sorry for bothering you.
