### ISSUE TITLE
Code for voxceleb_prepare.py

### ISSUE THREAD

**Issue by TaoRuijie** [speechbrain/speechbrain#913]
Thanks for your great work! That is amazing.

In voxceleb_prepare.py, prepare_voxceleb function. You provide the example:

from recipes.VoxCeleb.voxceleb1_prepare import prepare_voxceleb
data_folder = 'data/VoxCeleb1/'
save_folder = 'VoxData/'
splits = ['train', 'dev']
split_ratio = [90, 10]
prepare_voxceleb(data_folder, save_folder, splits, split_ratio)

I think it ought to be updated like:

from recipes.VoxCeleb.**voxceleb_prepare** import prepare_voxceleb
data_folder = 'data/VoxCeleb1/'
save_folder = 'VoxData/'
**verification_pairs_file = '.....'**
splits = ['train', 'dev']
split_ratio = [90, 10]
prepare_voxceleb(data_folder, save_folder, **verification_pairs_file**, splits, split_ratio)

**Comment by TaoRuijie** [comment]
I guess it ought to be the test pair in Vox1: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt

**Comment by dragen1860** [comment]
Yes it is. Thanks very much.

**Comment by dragen1860** [comment]
@TaoRuijie May I add you via wechat? we can keep in touch on voice recognition related research. Here is my wechat:  dragen1860
