### ISSUE TITLE
Loading final checkpoint fails due to CUDA out of memory

### ISSUE THREAD

**Issue by aviadb** [speechbrain/speechbrain#918]
Hello,
I managed to train the speech_recognition ASR template.
The batch size is 8
and the number of epochs is 15.

The training session completed,
however, when loading the final checkpoint, I get 
and exception of "CUDA out of memory"

Do I have to retrain again with a smaller batch size?
Is my trained model broken and unusable? 

What other options are available if I want to avoid re-training?

**Comment by TParcollet** [comment]
Hi, solely loading shouldn't cause CUDA OOM. Could you please post a screen shot of the full error + logs before it happens ?

**Comment by aviadb** [comment]
> ../data/rirs_noises.zip exists. Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/CRDNN_BPE_960h_LM/2602
mini_librispeech_prepare - Preparation completed in previous run, skipping.
speechbrain.pretrained.fetching - Fetch lm.ckpt: Using existing file/symlink in results/CRDNN_BPE_960h_LM/2602/save/lm.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in results/CRDNN_BPE_960h_LM/2602/save/tokenizer.ckpt.
speechbrain.pretrained.fetching - Fetch asr.ckpt: Using existing file/symlink in results/CRDNN_BPE_960h_LM/2602/save/model.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer, model
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 173.0M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from results/CRDNN_BPE_960h_LM/2602/save/CKPT+2021-08-04+20-34-40+00
speechbrain.utils.checkpoints - Loading a checkpoint from results/CRDNN_BPE_960h_LM/2602/save/CKPT+2021-08-04+16-37-53+00
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 471, in <module>
    test_stats = asr_brain.evaluate(
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/core.py", line 1185, in evaluate
    loss = self.evaluate_batch(batch, stage=Stage.TEST)
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/core.py", line 928, in evaluate_batch
    out = self.compute_forward(batch, stage=stage)
  File "train.py", line 106, in compute_forward
    predictions["tokens"], _ = self.hparams.test_search(
  File "/home-net/home-1/abenhai2@jhu.edu/work/aviad_conda_envs/sb_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/decoders/seq2seq.py", line 628, in forward
    log_probs, memory, attn = self.forward_step(
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/decoders/seq2seq.py", line 943, in forward_step
    dec_out, hs, c, w = self.dec.forward_step(
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/nnet/RNN.py", line 908, in forward_step
    c, w = self.attn(enc_states, enc_len, cell_out)
  File "/home-net/home-1/abenhai2@jhu.edu/work/aviad_conda_envs/sb_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home-net/home-1/abenhai2@jhu.edu/code/speechbrain/speechbrain/nnet/attention.py", line 219, in forward
    torch.tanh(self.precomputed_enc_h + dec_h + attn_conv)
RuntimeError: CUDA out of memory. Tried to allocate 1.93 GiB (GPU 0; 11.17 GiB total capacity; 6.44 GiB already allocated; 1.71 GiB free; 8.97 GiB reserved in total by PyTorch)

**Comment by TParcollet** [comment]
Ok, so, the test_search is usually more intensive in terms of computation and memory because we do the full beam search with a big beam (have a look at the yaml file). You can either 1. reduce the test batch size; 2. if it's already set to 1 then reduce slightly the beam size.

**Comment by aviadb** [comment]
@TParcollet 
Thank you,
decreasing the test batch size solved the problem.

Is there a way to quantify the impact of batch size over accuracy results?
For lower batch sizes will I get higher WERs?

**Comment by Gastron** [comment]
The test time batch size doesn't affect the WER (or if it does, something is going wrong). 

Beam size will affect WER, and empirically you may even find an (at least locally) optimal beam. That is, a wider beam doesn't always result in better WER.

**Comment by aviadb** [comment]
Thank you @Gastron ,
Is there a convenient way (rule of thumb?) of calculating or estimating the optimal beam size?
Or is it subject to change based on the nature of the test / training data?

**Comment by Gastron** [comment]
Unfortunately it just depends on the particular experiment. You should just try a couple of values on the validation data and see what works. Still, the rule of thumb is more in the direction that wider beam gives better WER - but I've personally found that the very wide beam used in the SpeechBrain LibriSpeech recipes doesn't always work well on other data.

Closing this issue it seems to have been solved.

**Comment by danpovey** [comment]
With conformers, the way the batching is done in test time might make some difference (although hopefully not very much), because the conv_module has conv1d's with quite large receptive fields (31 frames, which comes to over a second if you have done 4x subsampling), and at the edge of the batch it would be seeing zeros, while if it's in a padding segment it would see whatever the output of the previous layer was, which might not be zero.
That is: if there are more frames of padding than the model has seen in train time, it might potentially cause a mismatch.
