### ISSUE TITLE
Development of new models

### ISSUE THREAD

**Issue by Mlallena** [speechbrain/speechbrain#919]
OK, I'm continuing my work with a language identifier that works with only 3 languages, but right now it's getting stuck in a rut - on epoch 3, trying to obtain results with audios of different languages (Catalan, English, Spanish) returns that it is English for most audios, with only a few of them being reported as Catalan or Spanish. Plus, checking the network output shows that most answers have all values very similar, either all >0.9 or <-0.9. 

I'm guessing it's just a matter of patience and waiting for the training to end, but just for the sake of making sure I'm doing it right - how many audios do you consider would be required to ensure a decently trained network with only three languages (I am currently using 7500 for training and 2500 each for dev and testing, per language)?

EDIT: I have also noticed an issue with torchaudio. Sometimes, when it extracts the number of frames to calculate the time, it returns instead the cap for int32 (2^31-1), which might be one of the reasons previous calculations were so messed. I managed to fix this by using pydub, which returned the correct audio duration.

**Comment by mravanelli** [comment]
Hi, is the dataset balanced?

**Comment by Mlallena** [comment]
Well, _I_ think it ought to be. There's exactly the same number of audio files for each language (7500 for training, 2500 for dev, 2500 for testing) and the audios have the same average duration (they are from CommonVoice). Right now, I'm waiting for the training to end before I go and check.

One doubt I now remember I wanted to ask: I'm guessing it is necessary to have the normalizer.ckpt file, given that the LID recipes I've checked (lang_id_commonlanguage_ecapa and TalTechNLP's voxlingua-107-epaca-tdnn) have this. I've done this by copying the normalizer_input.ckpt file that is created in the CKPT folder for the epoch. Is this the correct action?

**Comment by mravanelli** [comment]
Yes, that is correct. Is the original model (the one we released for many
languages) working well with your data?

**Comment by Mlallena** [comment]
It is. Well, when I just ask for the language, it usually returns some weird results, but when I just compare the three languages I want, it is quite accurate (I don't have an actual number because I want to wait until I have my actual model before I make in-depth comparisons).

OK, glad I didn't make a mistake with normalizer.ckpt.

**Comment by mravanelli** [comment]
It should work with 3 languages as well then. Rather than training from
scratch, my suggestion is to fine-tune the existing model. This will likely
lead to a better performance.

**Comment by Mlallena** [comment]
Well, I am using the model from spkrec-ecapa-voxceleb as the initial embedding model (the one suggested in the present hyperparameter.yaml file), but perhaps using the already existing LID models might work. I'll test that. Thanks for the suggestion.

**Comment by Mlallena** [comment]
When I try to do this by changing embedding_model_path so it points to either of the existing models, I get this error:
```
/home/ubuntu/audiosSpeechbrain/rirs_noises.zip exists. Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/20200823
common_language_prepare - results/20200823/save/train.csv already exists, skipping data preparation!
common_language_prepare - results/20200823/save/dev.csv already exists, skipping data preparation!
common_language_prepare - results/20200823/save/test.csv already exists, skipping data preparation!
speechbrain.dataio.encoder - Load called, but CategoricalEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
speechbrain.pretrained.fetching - Fetch embedding_model.ckpt: Using existing file/symlink in results/20200823/save/embedding_model.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: embedding_model
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    hparams["pretrainer"].load_collected(device=torch.device('cpu'))
  File "/home/ubuntu/gitfolder/speechbrain/speechbrain/utils/parameter_transfer.py", line 203, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "/home/ubuntu/gitfolder/speechbrain/speechbrain/utils/parameter_transfer.py", line 218, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "/home/ubuntu/gitfolder/speechbrain/speechbrain/utils/checkpoints.py", line 143, in torch_parameter_transfer
    torch.load(path, map_location=device), strict=False
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
The only solution for this error that I have found is to use the command `git lfs pull` (or `git-lfs pull`, I've seen it both ways), but there is no reaction from the system, not even a warning to indicate that it isn't working at all.

I'm supposing I must make a reference to the embedding model path in a different way, or perhaps modify the hyperparameters file, but I'm not certain about the method.

This is the hyperparameters file I'm using:
```
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 20170812
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
# Dataset will be downloaded to the `data_folder`
data_folder: /home/ubuntu/audiosSpeechbrain
output_folder: !ref results/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
device: 'cuda:0'
skip_prep: False

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

# Feature parameters btw: 40 - 80
n_mels: 80

# Training Parameters
sample_rate: 8000
number_of_epochs: 30
batch_size: 4
n_languages: 3
emb_dim: 192 # dimensionality of the embeddings

# Dataloaders
train_dataloader_options:
    batch_size: !ref <batch_size>
    drop_last: True
    shuffle: True

test_dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: True

# Added noise and reverb come from OpenRIR dataset, automatically
# downloaded and prepared with this Environmental Corruption class.
env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <data_folder>
    openrir_max_noise_len: 3.0  # seconds
    babble_prob: 0.0
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

# Adds speech change + time and frequency dropouts (time-domain implementation)
# A small speed change help to improve the performance of speaker-id as well.
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

# Feature extraction
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

# Mean and std normalization of the input features
mean_var_norm_input: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

# To design a custom model, either just edit the simple CustomModel
# class that's listed here, or replace this `!new` call with a line
# pointing to a different file you've defined.

# Embedding Model
embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: !ref <emb_dim>

# Classifier baseed on cosine distance
classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: !ref <emb_dim>
    out_neurons: !ref <n_languages>

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class.
modules:
    compute_features: !ref <compute_features>
    env_corrupt: !ref <env_corrupt>
    augmentation: !ref <augmentation>
    embedding_model: !ref <embedding_model>
    mean_var_norm_input: !ref <mean_var_norm_input>
    classifier: !ref <classifier>

# Additive Angular Margin
compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
    loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
        margin: 0.2
        scale: 30

# Learning rates
lr: 0.0001
lr_final: 0.00001


# This optimizer will be constructed by the Brain class after all parameters
# are moved to the correct device. Then it will be added to the checkpointer.
opt_class: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0.000002

# Linear lr decay
lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        normalizer_input: !ref <mean_var_norm_input>
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        counter: !ref <epoch_counter>

# Load pretrained embedding module
# Note: in this case, we pre-train with the ECAPA-TDNN model trained on voxceleb
# for speaker-id (this leads to a performance improvement).
#embedding_model_path: /home/ubuntu/speechbrain/recipes/lang-id-commonlanguage_ecapa/embedding_model.ckpt
pretrained_path: speechbrain/lang-id-commonlanguage_ecapa

# Pretrained ECAPA embeddings from SpeakerID on VoxCeleb
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrained_path>/embedding_model.ckpt
```
Any suggestions about this? You have probably found this problem already, so hopefully you will have an answer for me.

Thanks in advance for any solution you may provide (or just for making the effort).

**Comment by Mlallena** [comment]
Nevermind, I have managed to make is start running - it was just a problem with the hyperparams.yaml file.

**Comment by Mlallena** [comment]
No use - it keeps returning mostly English. I'm quite stumped at why this is happening, because it makes little sense, as far as I can tell. And I have tried with different models and the same dataset. Could the problem be there?

**Comment by mravanelli** [comment]
What I would do here is to take the ECAPA encoder only for pre-training. Then you can a linear layer on top of it with just your targeted languages.  You might have to run some experiments to find a proper value for the learning rate. Please, let me know if that helps.

**Comment by Gastron** [comment]
@Mlallena did you get this to work? It seems that this issue has touched on many things, but the last point is about how to do pretraining. This sounds like a case where you need to implement the model yourself (as it would be a new architecture) and to also implement the pretraining loading code (as you're taking just a part of an existing model). I refer you to these [PyTorch docs](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

I suggest we close this issue and continue with specific topics on e.g. [the discourse page](https://speechbrain.discourse.group/)

**Comment by Mlallena** [comment]
No, I was unable to get it to work. That was why I made that last comment. I guess I'll have to try implementing a new model, based on the same architecture the pretrained model uses.

Unless anyone has to say anything, we can just close the issue.
