### ISSUE TITLE
Out of memory for lang_id recipe

### ISSUE THREAD

**Issue by Jamiroquai88** [speechbrain/speechbrain#925]
Hi, I am trying to train my own ECAPA-TDNN model on VoxLingua107 dataset. Frequently, I run into CUDA out of memory issues
```
RuntimeError: CUDA error: out of memory
```

I am using 8x A100 40GB for the training, with batch size set to 8. Do you have an idea where these out-of-memory issues are coming from? At first, I blamed audio data, but all audio recordings are under 20 seconds. I am trying to train only on audios under 10 seconds, and I want to see if the problem persists.

I used to run into same issues with V100 16GB, even when training on the single GPU.

Thanks.

**Comment by TParcollet** [comment]
Hi, if you use DDP, the batch_size is replicated on each GPU so you'll get a batch size of 8x8. Hence, increasing the number of GPUs with DDP without decreasing the BS does not solve the problem. You can have a look at the CommonVoice ASR recipe to see how to filter audio files per length. Please track the avoid_if_longer_than parameter in the YAML and .py file (just few lines to modify).

**Comment by Jamiroquai88** [comment]
Thanks, I'll try that. I am actually using DataParallel from torch.
I was able to finish 2 epochs with audios < 10 seconds.

**Comment by mravanelli** [comment]
Well, that's definitely too much. Are you able to train the model on CommonLanguage using a single GPU? We here don't have very long recodings (e.g, 5 seconds).

**Comment by Jamiroquai88** [comment]
I was able to start the training on CommonLanguage, but then I went straight to VoxLingua107. I was able to train a model on utterances shorter than 15 seconds without any issue (batch size = 64). I am gonna close this one, thank you for your help.
