### ISSUE TITLE
recipes/*/ASR/transformer/train.py -> compute_forward -> hparams.Transformer shuod be modules.Transformer

### ISSUE THREAD

**Issue by bookong22** [speechbrain/speechbrain#930]
I have checked recipes CommonVoice and LibriSpeech ASR/transformer/train.py
def compute_forward(self, batch, stage):
self.hparams.CNN   self.hparams.Transformer  self.hparams.ctc_lin  self.hparams.seq_lin
should be
self.modules.CNN   self.modules.Transformer  self.modules.ctc_lin  self.modules.seq_lin

If not, Something wrong will happend when we use DP or DDP.

**Comment by TParcollet** [comment]
Hey, yes we noticed this issue. We will merge the corresponding PR soon.

**Comment by bookong22** [comment]
> Hey, yes we noticed this issue. We will merge the corresponding PR soon.

OK, Thank you!
