### ISSUE TITLE
How to use recipes/VoxCeleb/SpeakerRec/ for custom verification training

### ISSUE THREAD

**Issue by rohaantahir** [speechbrain/speechbrain#932]
I am trying to reciprocate this recipe to my custom dataset. But facing some errors because I don't have meta files for my custom dataset while running this command "python train_speaker_embeddings.py hparams/train_x_vectors.yaml" .  I want to know how could I use this recipe to train the model for verification. I once used your template for speaker recognition available in colab https://colab.research.google.com/drive/1UwisnAjr8nQF3UnrkIJ4abBMAWzVwBMh?usp=sharing I want to confirm that should I use its method or its specific YML file of data preparation for this particular recipe? Kindly help me in this regard. Thanks

**Comment by mravanelli** [comment]
Hi @rohaantahir,
the data preparation step is always dataset dependent. You should create your prepare_dataset function such that the preparation script provides the data manifest files (i.e., csv/json) with the expected fields. You can run the voxceleb recipe and figure out what information is needed. Once you have the correct data preparation, the training script should run. You might want then to tune a bit the hyperparameters in the YAML file based on your data (if you don't see a good performance with the default parameters).

**Comment by rohaantahir** [comment]
Thankyou so much resolved the issue by making directory structure similar to Voxceleb1 structure.

**Comment by rohaantahir** [comment]
This issue is resolved
