### ISSUE TITLE
how to find the path speechbrain.utils.parameter_transfer.Pretrainer on Github?

### ISSUE THREAD

**Issue by ZEngXCiao** [speechbrain/speechbrain#935]
I find that speaker_verification_plda.py download pretrained model from this path defined in the speaker_verification_plda.yaml file.
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer.
But I can not find this function Pretrainer in the path, so I want to know where it is.
Thank you much!

**Comment by csukuangfj** [comment]
speechbrain.utils.parameter_transfer.Pretrainer -> speechbrain/utils/parameter_transfer

https://github.com/speechbrain/speechbrain/blob/725b37219b2776329039dfa9e1118f881f853fb9/speechbrain/utils/parameter_transfer.py#L23

**Comment by ZEngXCiao** [comment]
Oh, I am stupid.  It's so obvious!  Thank u
