### ISSUE TITLE
Problem about Speaker Verification test batch size

### ISSUE THREAD

**Issue by MLrookie** [speechbrain/speechbrain#945]
I was using the speaker recognition scripts in the directory _“speechbrain/recpies/VoxCeleb/SpeakRec”_. I have trained the ECAPA-TDNN speakerRec model and try to test the performance of the model.

However, I surprisingly found that when i changed the batch size in yaml file, i got different scores of the same pair enrol.wav and test.wav in text.txt. What 's more, when i set only one pair in the test.txt, i always got the **“-1.0”** score using CosineSimilarity function.

**Why did the scores of the same pair change with different batch size? It seems that the same audio file can get different embedding in speakerRec model, is it reasonable?**

Wish for your result! i can’t thanks anymore!

**Comment by 30stomercury** [comment]
Might relate to the `InputNormalization` (#933).

**Comment by mravanelli** [comment]
There are some small sources of variabilities that happen when working with
batches. For instance,  the convolutions, pooling, STFT introduce a tail
effect when zero-padding is used. Moreover, some operations (e.g, torch.mm)
are not fully deterministic and might provide slightly different results
depending on the length of the padding.  We are investigating and fixing
some of these issues in #933.

>

**Comment by MLrookie** [comment]
> There are some small sources of variabilities that happen when working with batches. For instance, the convolutions, pooling, STFT introduce a tail effect when zero-padding is used. Moreover, some operations (e.g, torch.mm) are not fully deterministic and might provide slightly different results depending on the length of the padding. We are investigating and fixing some of these issues in #933.
> […](#)

Thank you so much.  I want to get the stable output of a certain audio file. It means that i should replace the problem blocks with the fixed one in #933, right?  For example,  should i replace the 

> Might relate to the `InputNormalization` (#933).



> There are some small sources of variabilities that happen when working with batches. For instance, the convolutions, pooling, STFT introduce a tail effect when zero-padding is used. Moreover, some operations (e.g, torch.mm) are not fully deterministic and might provide slightly different results depending on the length of the padding. We are investigating and fixing some of these issues in #933.
> […](#)

Thank you so much.  I want to get the stable output of a certain audio file. It means that i should replace the problem blocks with the fixed one in #933, right?  For example,  should i replace the `InputNormalization` and `Fbank` if the model structure is as below:

_compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False_

**Comment by 30stomercury** [comment]
Hi, yes please replace them with fixed ones. However, embedding_model could be batch dependent as well, since it involves cnn components. While the effect should be small, we would like to solve it by applying masking after each conv layer.

**Comment by 30stomercury** [comment]
Hi, yes please replace them with fixed ones. However, embedding_model could be batch dependent as well, since it involves cnn components. While the effect should be small, we would like to solve it by applying masking after each conv layer.
