### ISSUE TITLE
If only one file was pushed into batch, there is a error occured in speaker_verification_plda!

### ISSUE THREAD

**Issue by ZEngXCiao** [speechbrain/speechbrain#946]
![Snipaste_2021-08-21_00-11-19](https://user-images.githubusercontent.com/38159923/130263066-028cb698-efcd-431c-9306-1db3ab4520c2.png)
![Snipaste_2021-08-21_00-12-01](https://user-images.githubusercontent.com/38159923/130263076-838861bf-bddc-487c-b5ce-6b5393ee7393.png)

I use my own datasets and find that when it is the final epoch in training enrol_obj, the last file did not send into the audio_pipeline() instead output directly.

the original data size is [n x 859 x 13], the correct size returned after feeding into xvector network is [n x 512].

![Snipaste_2021-08-21_00-16-34](https://user-images.githubusercontent.com/38159923/130263663-717c3f12-586c-4783-a60f-e0e46661f0b8.png)

**Comment by TParcollet** [comment]
Hi, I am not sure to understand properly. When you say one file, you mean -> When batch_size = 1 there is a bug at the end of the training ?

**Comment by ZEngXCiao** [comment]
Yes, you got it right. There is a bug when the batch_size = 1

**Comment by ZEngXCiao** [comment]
Sorry, It's not much a bug. I fixed it, just get rid of the squeeze of compute_embeddings(wavs, lens).squeeze()
