### ISSUE TITLE
RuntimeError: Backend "soundfile" is not one of available backends: [].

### ISSUE THREAD

**Issue by yinxx** [speechbrain/speechbrain#948]
import speechbrain as sb
E:\python\python37\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\python\python37\lib\site-packages\speechbrain\__init__.py", line 4, in <module>
    from .core import Stage, Brain, create_experiment_directory, parse_arguments
  File "E:\python\python37\lib\site-packages\speechbrain\core.py", line 32, in <module>
    from speechbrain.utils.distributed import run_on_main
  File "E:\python\python37\lib\site-packages\speechbrain\utils\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "E:\python\python37\lib\site-packages\speechbrain\utils\Accuracy.py", line 7, in <module>
    from speechbrain.dataio.dataio import length_to_mask
  File "E:\python\python37\lib\site-packages\speechbrain\dataio\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "E:\python\python37\lib\site-packages\speechbrain\dataio\dataio.py", line 26, in <module>
    torchaudio.set_audio_backend(torchaudio_backend)
  File "E:\python\python37\lib\site-packages\torchaudio\backend\utils.py", line 44, in set_audio_backend
    f'Backend "{backend}" is not one of '
RuntimeError: Backend "soundfile" is not one of available backends: [].

**Comment by anaNASHAAT** [comment]
@TParcollet I'm windows and same issue

**Comment by Abanobbb** [comment]
Hi, I'm on windows and this worked for me :

`pip install soundfile

import torchaudio
torchaudio.set_audio_backend("soundfile")`

> import speechbrain as sb
> E:\python\python37\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
> warnings.warn('No audio backend is available.')
> Traceback (most recent call last):
> File "", line 1, in
> File "E:\python\python37\lib\site-packages\speechbrain__init__.py", line 4, in
> from .core import Stage, Brain, create_experiment_directory, parse_arguments
> File "E:\python\python37\lib\site-packages\speechbrain\core.py", line 32, in
> from speechbrain.utils.distributed import run_on_main
> File "E:\python\python37\lib\site-packages\speechbrain\utils__init__.py", line 11, in
> from . import * # noqa
> File "E:\python\python37\lib\site-packages\speechbrain\utils\Accuracy.py", line 7, in
> from speechbrain.dataio.dataio import length_to_mask
> File "E:\python\python37\lib\site-packages\speechbrain\dataio__init__.py", line 11, in
> from . import * # noqa
> File "E:\python\python37\lib\site-packages\speechbrain\dataio\dataio.py", line 26, in
> torchaudio.set_audio_backend(torchaudio_backend)
> File "E:\python\python37\lib\site-packages\torchaudio\backend\utils.py", line 44, in set_audio_backend
> f'Backend "{backend}" is not one of '
> RuntimeError: Backend "soundfile" is not one of available backends: [].

**Comment by TParcollet** [comment]
Hi, we don't have anyone from the team on Windows :/ Hopefully answer from the community will be given

**Comment by Adel-Moumen** [comment]
Hi,

Got the same error and solved it by doing `pip install soundfile` as mentioned previously. 

I'm closing this issue as the problem seem's to be solved. Please feel free to reopen if needed. :)
