### ISSUE TITLE
Brain object has no attribute named optimizer ?

### ISSUE THREAD

**Issue by Enescigdem** [speechbrain/speechbrain#952]
I conduct audio classification experiments.
I got the error below:
_
Traceback (most recent call last):
  File "train.py", line 441, in <module>
    test_stats = lang_id_brain.evaluate(
  File "speechbrain/speechbrain/core.py", line 1185, in evaluate
    loss = self.evaluate_batch(batch, stage=Stage.TEST)
  File "/speechbrain/speechbrain/core.py", line 929, in evaluate_batch
    loss = self.compute_objectives(out, batch, stage=stage)
  File "train.py", line 104, in compute_objectives
    self.hparams.lr_annealing.on_batch_end(self.optimizer)
AttributeError: 'LangIDBrain' object has no attribute 'optimizer'
_
And i printed the attributes of the brain object and saw there is no optimizer attribute.
What should i do ?

**Comment by Enescigdem** [comment]
yes it does contain optimiser and problem  appears after training stage.

**Comment by TParcollet** [comment]
Hi, sorry for the late reply ... Is it solved ?
