### ISSUE TITLE
I keep getting UserWarning: torchaudio C++ extension is not available.

### ISSUE THREAD

**Issue by firefox1221** [speechbrain/speechbrain#956]
I'm trying to lunch the code 

```
from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="pretrained_models/asr-crdnn-rnnlm-librispeech")
asr_model.transcribe_file('speechbrain/asr-crdnn-rnnlm-librispeech/example.wav')

```

but whenever I do that I get the error 

```
UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
Traceback (most recent call last):....
```

![image](https://user-images.githubusercontent.com/75361725/130915395-4e9e528b-24b3-4d48-82af-d9b98d5b2fe8.png)

**Comment by BrownsugarZeer** [comment]
The real problem is you need to run with admin privilege.
Take a look at the closed [issue](https://github.com/speechbrain/speechbrain/issues//893)

**Comment by Gastron** [comment]
Thanks @BrownsugarZeer, as you said, this is the same issue. Unfortunately currently our solution is just using the heightened privileges. Closing.
