### ISSUE TITLE
python3.9 install takes HOURS

### ISSUE THREAD

**Issue by turian** [speechbrain/speechbrain#959]
pip3 install on python3.9 takes HOURS. There are many packages that should have pinned version numbers, but since they don't, pip3 backtracks endlessly trying a variety of versions to satisfy dependencies.

This is causing problems for our packages that use speechbrain, because our python 3.9 CI jobs now never can install speechbrain in a reasonable amount of time.

I submit this PR that allow you to include python 3.7 and 3.9 in your CI matrix:

https://github.com/speechbrain/speechbrain/pull/958

If you won't support Python 3.9, I suggest removing it from your allow python versions in setup.py

**Comment by mravanelli** [comment]
I'm using python 3.9 and on my side. On my side, I didn't notice any speed problem when installing spechbrain under python 3.9. Not sure what is happening in your case. It looks like there is something to understand better.

**Comment by turian** [comment]
I'll close for now and reopen if it occurs. For now we have decided not to support 3.9
