### ISSUE TITLE
Different result with same data in train_speaker_embeddings.py

### ISSUE THREAD

**Issue by zengxinch** [speechbrain/speechbrain#964]
When I train a model (the 23 epoch), the feats are the same in fit_batch() and evaluate_batch(), but the results are different! 
the embeddings in evaluate_batch progress is totally wrong. 

![image](https://user-images.githubusercontent.com/38159923/131320557-8ebef3c0-ae46-40d3-873d-393a0b4d608e.png)

![image](https://user-images.githubusercontent.com/38159923/131320483-bd080e54-e1e7-4a5b-b224-38e94d971239.png)

and I found that the classifier prediction results are pointing to the same people!
![image](https://user-images.githubusercontent.com/38159923/131320847-3b8fd83c-9443-4043-ba74-d58d9d644169.png)

I don't know why, and I find that the self.modules.embedding_model is the same in two progress (fit_batch() and evaluate_batch()), only norm.running_var has a little bit differences.

**Comment by ZEngXCiao** [comment]
the same feats but different embeddings!  Need for helps, Please.

**Comment by ZEngXCiao** [comment]
the same feats but different embeddings!  Need for helps, Please.

**Comment by ZEngXCiao** [comment]
![image](https://user-images.githubusercontent.com/38159923/131429496-010d0f6a-5632-4ffc-b30c-80e409bf32a4.png)
t'he
the valid loss is much larger than train loss.

**Comment by 30stomercury** [comment]
Hi, did you use the same batch size? the differences in norm is fixed here #933.

**Comment by Adel-Moumen** [comment]
Hello,

Is there any news about this issue, please? Thanks. :)

**Comment by Adel-Moumen** [comment]
Hello,

There is no more activity on this issue, and therefore, I am closing it. 

Open a new issue if needed. Thanks! :-)
