### ISSUE TITLE
ImportError: There is no such class as templates.speech_recognition.LM.custom_model.CustomModel

### ISSUE THREAD

**Issue by haopeining** [speechbrain/speechbrain#965]
Hi,this error is came from "Training a Speech Recognizer"'s part2:
> cd ../LM
python train.py RNNLM.yaml
I don't know why this error happen,because "templates.speech_recognition.LM.custom_model.CustomModel"  really exist in my local program,and nothing changed after i download this great program.
![screenshot_5](https://user-images.githubusercontent.com/50979817/131322340-c4f9999d-8204-4cd9-9fd8-f1ee07eb59c0.png)
Thank you!

**Comment by TParcollet** [comment]
Hi, did you install with pip install or via Git ?

**Comment by haopeining** [comment]
Hi,yes.Yestoday i uesd python version 3.7,so I try python3.8 today,and install with pip and git.This error also happened.
> 
![screenshot_6](https://user-images.githubusercontent.com/50979817/131622120-abc997c8-24ba-40fb-ab90-6d9d7cf42c3d.png)

---
Hi,this mistake is path problem,my interpreter find "site-packages" directly,and  don't fine.After I put the floder of "templates" to "site-packages",interpreter can find,maybe i need to set a path for loacl program,Thank you for your help.
