### ISSUE TITLE
 handle varied length data in a batch (ECAPA-TDNN)

### ISSUE THREAD

**Issue by joaquinCaceres** [speechbrain/speechbrain#968]
Hi!
Currently, I am extracting the embeddings from the ECAPA-TDNN with this code:

classifier = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", run_opts={"device":"cuda"})
signal, fs = x torchaudio.load("00055.wav")
embeddings = classifier.encode_batch(signal, normalize=False)

Signal is a tensor whose shape is torch.Size([1, 64512]). If all the audios had the same length, an input tensor could be constructed whose shape would be torch.Size([X, 64512]) (where x would be the number of audios). Is it possible send to the model a tensor that contains audios of different lengths?

Thanks!

**Comment by mravanelli** [comment]
Hi,
sure. You have to perform zero padding and then use wav_len to exclude the
zero-padded elements from the computation. You can find some details on
wav_len in the corresponding docstring:
https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py#L313
