### ISSUE TITLE
Speech separation: The sisnr calculated by one GPU and multiple GPUs is inconsistent

### ISSUE THREAD

**Issue by srdfjy** [speechbrain/speechbrain#971]
Same environment and configuration，run default recipe

Single GPU
__main__-Mean SISNR is 13.686118245124817

Four GPUs in a single machine
__main__-Mean SISNR is 6.234192698448896

**Comment by mravanelli** [comment]
Are you using the pre-trained models and doing inference only on multiple GPUs or you are doing training from scratch over multiple gpu?

**Comment by srdfjy** [comment]
Hi @mravanelli ,Both scenes are trained from scratch.
num_workers are different, the rest are the same.

**Comment by mravanelli** [comment]
Which dataset are you using?  Are you using  DP or DDP for multi-gpu training? Note that the effective batch size is different in the two cases. Any insight @ycemsubakan and @popcornell?

**Comment by ycemsubakan** [comment]
I will need to look into this. I am confident that the results should be correct with single gpu, however I am not sure what is happening. Can you just try to see if you get the same result with same number of workers?

**Comment by srdfjy** [comment]
hi @mravanelli @ycemsubakan Self-built data set, using DDP, the same data, model (sepformer) and batchsize.

**Comment by mravanelli** [comment]
If you use DDP with N GPUs, the effective batch size is N * batch_size. The
effective batch size might have a strong impact when training this model
apparently. What happens if you train the multi-gpu model a bit more?

**Comment by srdfjy** [comment]
If a single machine has 4 GPUs, the batchsize is set to 4?

**Comment by mravanelli** [comment]
With DDP yes. Usually there is a difference due to that in the performance
(you use batch size=1 in one case abd batch size=4 with multiple gpus).
Normally is not that huge though.

**Comment by srdfjy** [comment]
thanks @mravanelli @ycemsubakan

**Comment by caixy97** [comment]
Hi srdfjy, I encountered the same problem. Could you please tell me how you solved it?

**Comment by ycemsubakan** [comment]
Hi @caixy97 , please take a look at these issues:

#659 #1082

**Comment by caixy97** [comment]
Hi @ycemsubakan , thanks very much for your quick reply. 
I‘ve looked into these issues #659 #1082 , but they didn't solve my problem. I am training a sepformer on a slurm cluster. Single GPU works fine, **si-snr=16**. Multiple GPUs get much worse results: **si-snr=7**.
I've checked the load of all GPUs and input data of each gpu. All looks good but result is bad. 
#1314 describes my previous problem and some attempts.  My current code skips line 222-230 in *recipes/LibriMix/separation/dynamic_mixing.py*.
I would like to know how to set the hyperparameters to train the sepformer quickly and get right result.
Thank you very much!

**Comment by ycemsubakan** [comment]
You should be able to get the same results with multiple gpus, without changing the hyperparameters. 
1. Are you using DDP? With DP the performance is not as good. With DDP my experience was things were fine. 
2. Did you verify that both GPUs are using their memories? Please check https://github.com/speechbrain/speechbrain/issues/1082.

**Comment by poor1017** [comment]
@caixy97 My situation is similar to yours, but my train_log.txt looks good, while I do a test with trained model, the result is bad. Have you solved your issue?

**Comment by ycemsubakan** [comment]
@poor1017 , do you train with multiple GPUs?

**Comment by poor1017** [comment]
@ycemsubakan Yes, I train my model with DDP (4 GPUs). Errr.... I have found the reason: When I save the model, I forgot to add `.module`, it seems that DDP will encapsulate the model with `.module`.

**Comment by ycemsubakan** [comment]
@poor1017 . Great.. Thanks for your followup!
