### ISSUE TITLE
Error on 'pretrained_models\\lang-id-commonlanguage_ecapa\\hyperparams.yaml'

### ISSUE THREAD

**Issue by alexsomoza** [speechbrain/speechbrain#976]
When running

classifier = EncoderClassifier.from_hparams(source="speechbrain/lang-id-commonlanguage_ecapa", savedir="pretrained_models/lang-id-commonlanguage_ecapa")

I get

OSError: [WinError 1] Función incorrecta: 'C:\\Users\\asomoza\\.cache\\huggingface\\hub\\f1cb07494c3cf72d67202c925b11c8745b0cf964f3c0f1c969dd7f15fe3a69e5.6a5b020bdb255f49924cb6bf2d6be48181713f684c54ed6e64b01f203ca5292b' -> 'pretrained_models\\lang-id-commonlanguage_ecapa\\hyperparams.yaml'

**Comment by mravanelli** [comment]
This looks like an error with windows, which we don't really support for now. It looks like a path problem though so someone using windows in the community might help here.

**Comment by Gastron** [comment]
Also possibly relevant, see issue #893.

**Comment by Gastron** [comment]
Closing since there was no more activity here. Reopen if there's more to discuss.
