### ISSUE TITLE
Finetuning speechbrain/asr-wav2vec2-commonvoice-en with custom data

### ISSUE THREAD

**Issue by Reuben-Lim** [speechbrain/speechbrain#981]
Hi, I was wondering if there's a way to finetune the pretrained speechbrain/asr-wav2vec2-commonvoice-en model. 
I don't want to train it from scratch with the common voice dataset, but just to adapt it for few of my own data.
I don't see how I can finetune it with the train_with_wav2vec2.py script (from https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec.py) as I don't have the checkpoint files.
Would it be possible to get the best checkpoint files for the above model?

**Comment by mravanelli** [comment]
Here @TParcollet might have some insights....

**Comment by TParcollet** [comment]
You can find them on the README: https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/seq2seq (the link of the checkpoints towards google drive.)

**Comment by Reuben-Lim** [comment]
Hi @TParcollet, thank you so much for your quick reply. Didn't realize the checkpoints are linked there. 

For others, here's the link: https://drive.google.com/drive/folders/1FpTLWfAikEsKUOc7mpPG5k11t4hxtYRk.
