### ISSUE TITLE
Information about extracting speaker signature value or speaker embedding

### ISSUE THREAD

**Issue by rohaantahir** [speechbrain/speechbrain#983]
HI thanks for the wonderful toolkit. I am working on it and trying to dig down the code for speaker id classification. I had a confusion that in code speechbrain/templates/speaker_id/speechbrain/pretrained/interfaces.py line number 646 there is a code 
"out_prob = self.modules.classifier(wavs).squeeze(1)"
I want to confirm what does this self.modules.classifier reffers to. I mean from where the function classifier is being called I want to see the internal code of classifier. Could you please help me out. Is it calling internally from classifer.ckpt ?? or some internal python function

**Comment by mravanelli** [comment]
Maybe you can take a look [here](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb) to figure out how the interface work. For instance, look at these two lines:

```
from speechbrain.pretrained import EncoderClassifier
classifier = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb")
```
In the second like we basically read the hyperparameter file that you find [here](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb/blob/main/hyperparams.yaml#L48). As you can see this hyperparameter file has a pretrainer object that pretrain  the classifier with the file "classifier.ckpt" found in the repository.
