### ISSUE TITLE
Sepformer LibriMix training OOM

### ISSUE THREAD

**Issue by rohitpaturi** [speechbrain/speechbrain#985]
Hi, I am trying to run SepFormer training on LibriMix (Libri2Mix) but the script errors out even when batch size is 1 (which is the default) with both DP and DDP. Here is the recipe I am following: https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriMix/separation
I am using a machine with 8 NVIDIA V100 GPUs with a memory of 16160MiB each. Any pointers to solve this issue?

**Comment by ycemsubakan** [comment]
Hi, are you limiting the length of the training signals? I would suggest using 4 seconds.

**Comment by rohitpaturi** [comment]
Thanks for the pointer. Yeah, limiting training length to 4 seconds works for a batch size of 1 but throws OOM for batch size above 2. What were the parameters used for training the model with wsj or LibriMix?

**Comment by ycemsubakan** [comment]
The hparam files were what we used for training. I am surprised that you get OOM error. We however used a 32 gb or 48 gbgpu for with the default hparam. Though, I was able to train the model on smaller gpus (including 16gb ones if I remember correctly) Can you continue to reduce the training signal length? 

Also, are you training with 8k or 16k sampling frequency?

**Comment by rohitpaturi** [comment]
Okay, so the batch size was 1 for training the model (default hparam file parameter). In that case, I am able to train with signal length limited to 4sec (limit_training_signal_len: True, training_signal_len: 32000). 
I am using 8k sampling frequency. The default training params uses only 1 gpu and I still get OOM with 1 gpu when the signal length is not limited.

**Comment by ycemsubakan** [comment]
Sounds right.. If you do not limit the training signal length, then the long sequences will get you out of memory. In librimix there is longer sequences. 

In my experience, limiting the length does not reduce the performance significantly. In WSJ0-2Mix, even without dynamic mixing, I get 21.7 dB SI-SNR on test set, with 4 second long training signals.

**Comment by rohitpaturi** [comment]
Okay, thanks. Will train with signal limiting to 4seconds and a batch size of 1.
