### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by srdfjy** [speechbrain/speechbrain#988]
Run the default sepformer recipe, stand-alone 4 gpu cards, batch_size is 2, the following error occurred

--------------------------------------------------------------------

2021/09/14 10:46:23     separator.fit(
2021/09/14 10:46:23   File "train.py", line 620, in <module>
2021/09/14 10:46:23     avg_valid_loss = self.update_average(
2021/09/14 10:46:23  99%|█████████▊| 4035/4091 [16:06<00:13,  4.05it/s, train_loss=-1.32]Traceback (most recent call last):
2021/09/14 10:46:23   File "/speechbrain/speechbrain/core.py", line 1068, in fit
2021/09/14 10:46:23   File "/speechbrain/speechbrain/core.py", line 1213, in update_average
2021/09/14 10:46:23 RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by YUCHEN005** [comment]
Hello, I met this same issue, how do you solve it? Thank you.

**Comment by srdfjy** [comment]
I didn't solve it.

**Comment by poor1017** [comment]
Hi, I met the same issue, can you reopen this issue?
