### ISSUE TITLE
Transfer learning spkrec-ecapa-TDNN with new data?

### ISSUE THREAD

**Issue by asr-lord** [speechbrain/speechbrain#989]
Is there a way to do transfer learning with [pre-trained spkrec-ecapa-TDNN](https://github.com/speechbrain/speechbrain/tree/develop/recipes/VoxCeleb/SpeakerRec) model with new data?

**Comment by Gastron** [comment]
There is this [tutorial](https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing#scrollTo=OyjEzG-6zIFT), is that helpful?

**Comment by Gastron** [comment]
Appears tutorial was helpful
