### ISSUE TITLE
Mismatched device on Speed Perturb

### ISSUE THREAD

**Issue by Fhrozen** [speechbrain/speechbrain#993]
I am trying to build my Frankenstein mixing ESPnet and Speechbrain. However, I found an issue trying the augmentations on the data_parallel routine from CustomTraining of ESPnet.

Using two GPUs, when I forward the feats using `speechbrain.lobes.augment.TimeDomainSpecAugment`, I have an error of GPU mismatch cuda:0 and cuda:1. 
The problem seems to be this line:
https://github.com/speechbrain/speechbrain/blob/29b3b7418c113615c40a78f67aef313d28f525ff/speechbrain/processing/speech_augmentation.py#L612

instead, if I replace with:
```
weights = self.weights.to(waveforms.device)
```
and use `weights` along the `_perform_resample`, I can avoid the error.
Not sure if there is any solution or any similar issues related to this.

**Comment by mravanelli** [comment]
@aheba @TParcollet, are you able to replicate this issue?

**Comment by Adel-Moumen** [comment]
Hello @Fhrozen, 

Sorry for the delay. Is the issue still up? Could you provide a working example? 

Thanks. 
Adel

**Comment by Adel-Moumen** [comment]
Hi @mravanelli, with the new refactored augmentation interface, is this issue fixed ?

**Comment by asumagic** [comment]
I'm gathering this code is using DataParallel, which seems to be directly causing this. Since we [strongly recommend against using it nowadays, in favor of DDP,](https://speechbrain.readthedocs.io/en/latest/multigpu.html) I am tentatively closing this as wontfix.
