### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

### ISSUE THREAD

**Issue by Jeremiah0425** [speechbrain/speechbrain#994]
I try to train the model on my dataset，There is an error in this code snippet.

 sb.create_experiment_directory(
        experiment_directory=hparams["output_folder"],
        hyperparams_to_save=hparams_file,
        overrides=overrides,
    )

**Comment by Gastron** [comment]
Is your data in UTF-8 or some other encoding? Have you found the text that results in this error?

**Comment by Jeremiah0425** [comment]
> Is your data in UTF-8 or some other encoding? Have you found the file that results in this error?


Thank you for your prompt response, but I think it is not the reason for the dataset.Is it the reason I run the script?

![1631846326](https://user-images.githubusercontent.com/51948524/133715499-7a2bb7db-cc77-42da-bc28-a4b36cb023b9.jpg)

**Comment by Gastron** [comment]
Oh that is interesting, thanks for the wider context, I will fix this.

**Comment by Jeremiah0425** [comment]
> 哦，这很有趣，感谢更广泛的背景，我会解决这个问题。

Ok thanks.I am using the Chinese dataset。http://166.111.134.19:7777/data/thchs30/README.html

**Comment by Gastron** [comment]
Hey @Jeremiah0425 a fix got merged to the develop branch, but would be nice if you can verify if it worked?
